### ISSUE TITLE
Feature Request: Schedules

### ISSUE THREAD

**Issue by etaylor77** [humhub/humhub#1073]
I am loving what everyone is doing with this project. I have been digging around and have yet to see a way to do a staff schedule. 

Any thoughts? Maybe I just overlooked it.

**Comment by WASasquatch** [comment]
What you are asking for is very much a custom modification. HumHub is since evolved from a work-source website and into a Social Network Framework, which completely omits staff scheduling / management as all users are just users besides admins. 

I would look into the following modules.

https://github.com/humhub/humhub-modules-tasks
https://github.com/humhub/humhub-modules-calendar
