### ISSUE TITLE
Search for new Spaces Users is not working

### ISSUE THREAD

**Issue by bbfdesign** [humhub/humhub#1082]
Hi,
I've added a new space, go to Members and enter a Name of a valid User. But nothing happend - I couldn't find a User to add ...

**Comment by dakur** [comment]
That's because it is not form for adding users, but for searching in current members of the space. Try to read the description around the form first before reporting a bug:
"In the area below, you see all **active** members of this space. You can edit their privileges or remove it from this space."
The functionality you search for is the big blue button in right top part of the space page called "Invite":
![humhub-invite](https://cloud.githubusercontent.com/assets/9862581/8127783/b1e60d00-10f9-11e5-98a4-33faff05d12b.png)
