### ISSUE TITLE
Very slow loading pages across the board

### ISSUE THREAD

**Issue by jonnypixel** [humhub/humhub#1098]
Hi i have a VPS with pretty good specs,

using php 5.4 i think it is

But for some reason its just loading really slowly - takes ages to load a space or pretty much do anything.

Any help would be appreciated, i have tried changing heaps of different settings and re-installing but not much luck.

**Comment by dakur** [comment]
Hi, your description is too general, it can be cause by many factors. Try to install it on localhost. Does it work normally? Do other websites (excepts HumHub, if there are some?) work correctly on your VPS? Is there big traffic? Do you have caching enabled? Etc... Try to investigate yourself first.
(Btw this is not really support forum, it's bug tracking and feature suggesting system.)

**Comment by jonnypixel** [comment]
I have installed on localhost mamp, it works slightly faster. THe firbug console shows that a lot of teh js files take quite a while to load. On my VPS they take much longer - sometimes 20-40seconds before it loads properly.

Is there a forum?

I found the software and i like it but it can be painfully slow, others on here have said teh same thing without much luck in resolving, is it possible that it is slow?

Anyway if tehre is a forum then i will use it and ask my questions there, please link me.

Sincerely
John

sidenote: I have joomla admins running on my vps, i have wordpress admins, i have other software and all of them load pages faster than humhub.

**Comment by WASasquatch** [comment]
A VPS is not to be used with HumHub and this really needs to be put in it's
requirements. It has way to many calls to run smoothly on any VPS which
will inherently have up to 100 other clients off the same CPU, RAM, and
Bandwidth.

On Fri, Jun 19, 2015 at 1:24 AM, jonnypixel <notifications@github.com>
wrote:

> I have installed on localhost mamp, it works slightly faster. THe firbug
> console shows that a lot of teh js files take quite a while to load. On my
> VPS they take much longer - sometimes 20-40seconds before it loads properly.
>
> Is there a forum?
>
> I found the software and i like it but it can be painfully slow, others on
> here have said teh same thing without much luck in resolving, is it
> possible that it is slow?
>
> Anyway if tehre is a forum then i will use it and ask my questions there,
> please link me.
>
> Sincerely
> John
>
> sidenote: I have joomla admins running on my vps, i have wordpress admins,
> i have other software and all of them load pages faster than humhub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1098#issuecomment-113429152>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by jonnypixel** [comment]
I had a feeling you would say that, i still think its worth checking my concerns as my VPS has plenty of ram and performs very well with lots of other apps on my server with no issues. The only issue has been humhub which could just be 'slow?'. I only have 30 accounts of which only a dozen are database driven so its not that.

All im saying is that it is slow. I'll un-install and go and lease a $200 a month dedicated server just so i can test it there, is that what youre saying? 

Is it installed on a dedicated server on your website? 

All the best mate, im surprised you're not willing to look into the possibility that it it is laggy, from slow page loads for data to slow loading alerts and more, i think the software needs optimizing mate.

Regards
John

**Comment by WASasquatch** [comment]
Like I said, HumHub makes tons of connections to itself and remote servers. It will be slow on a VPS. You RAM is shared between up to 100+ other clients. So it's impossible to gauge speed in any case as it's intermittent to begin with.

**Comment by WASasquatch** [comment]
Also yes, I use a dedicated server, and even there HumHun can slow down with 16GB RAM and a dedicated 8 core CPU and 1gigabit line

**Comment by hhirsch** [comment]
Well you can't counter bad coding with bigger hardware see #1107 

The machine specs are only to blame in part.

**Comment by hhirsch** [comment]
Fixing #1108 might help improve the speed, too.

**Comment by WASasquatch** [comment]
1107 is for effect. Buy if the code is at the end of the page you'll get a
non-functioning site before the code runs. Best to have no site in that
case while JS loads. You'll get more reports of "errors" regarding the
broken functionality while Javascript loads instead of the user
automatically assuming it's loading and not broken.

HumHub is not written for HHVM, and is silly to use. Even a couple
milisecond delays can have significant impact on HHVM. You must have 100%
dedicated and top of the line equipment, and most especially not beta
software that hasn't had performance overhauls.

On Mon, Jun 29, 2015 at 9:05 AM, hhirsch <notifications@github.com> wrote:

> Fixing #1108 <https://github.com/humhub/humhub/issues/1108> might help
> improve the speed, too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1098#issuecomment-116743564>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by WASasquatch** [comment]
1107 is for effect. If the code is at the end of the page you'll get a
non-functioning site before the code runs. Best to have no site in that
case while JS loads. You'll get more reports of "errors" regarding the
broken functionality while Javascript loads instead of the user
automatically assuming it's loading and not broken. Facebook uses the same method, and runs it's content so the content and their feeds aren't broken while the page loads.

HumHub is not written for HHVM, and is silly to use. Even a couple
milisecond delays can have significant impact on HHVM. You must have 100%
dedicated and top of the line equipment, and most especially not beta
software that hasn't had performance overhauls. You can crash HHVM with a simple `for()` loop test and some arbitrary code. It's definitely meant for sound and tested applications.

**Comment by hhirsch** [comment]
Well unless you do your styling with js you don't need it at this time of the loading process. And I just checked with the humhub 'Try it out now' service. Even with a few miliseconds faster than my installations the effect is still noticeable and anoying. The extreme case that you described that when the js is included last and the user tries to use the gui that does not react yet is just a sympton of the server beeing way underpowered. It also tells something about the software desing where the gui depends a lot on js to provide even basic functionality like links.

The HHVM issue I can reproduce. Sometimes the performance is better than apache and 10 tests later there is a peak in load times.

@WASasquatch are you speaking for the developers of humhub? There are a lot of better things to do than argue on the internet and it is open source so it is my responsibility to fix anything that I want fixed.
