### ISSUE TITLE
Question: How to integrate this beautiful app with other websites 

### ISSUE THREAD

**Issue by mjskraju** [humhub/humhub#1125]
Hi,
This might be a stupid or noob question for a developer's community such as this, but after few hours of internet search I couldn't find an answer to it, so hear I'm asking it, bear with me please. I liked the concept & design of this app, but is this limited to be a standalone app(use it entirely) and (or) to websites developed using Yii framework only. Or is there any way to integrate it with websites developed in other frameworks like codeigniter, cakephp & laravel etc or even a custom PHP frameworks. If there is indeed a way doing so, then any one(who knows it) can let people like me know how to do it.

Thanks.

**Comment by SrPatinhas** [comment]
I would like to know what @luke- have to say to this? i would like to see this compatible with others Frameworks

**Comment by WASasquatch** [comment]
Nothing can be compatible with something else unless it is built that way.
That means HumHub would need to robustly grow in size (by 100 fold) to
store enough alternative methods to communicate with whatever framework is
used. And a custom one would mean HumHub developers would not know it, nor
how to make it compatible. That's why HumHub is a framework itself, to
build your own custom system.

On Wed, Sep 9, 2015 at 2:13 AM, SrPatinhas <notifications@github.com> wrote:

> I would like to know what @luke- <https://github.com/luke-> have to say
> to this? i would like to see this compatible with others Frameworks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humhub/humhub/issues/1125#issuecomment-138849174>.
>



-- 
Sincerely,
*Jordan S. C. Thompson *
*Web Development & Design Coordinator*

**Comment by luke-** [comment]
At the moment it's designed as standalone app.

Maybe we can add some features like Facebook Social Plugins or some sort of Json/REST APIs in future to allow other Applications to integrate HumHub.

**Comment by elbakly** [comment]
Do you intent or even willing to have a version of humhub for laravel, If you are will for so we can just tweet that and check the way contribution can make your life easier
