### ISSUE TITLE
max upload size ignored

### ISSUE THREAD

**Issue by pashadee** [humhub/humhub#1207]
I have set max upload size to 20M and post size to 50M on apache2. I can confirm that it's reporting correctly by phpinfo() however when I try to upload a 4.9MB jpg I get error: File is too big, it's size can not exceed 3,145,728 bytes. I can not figure out where this number is coming from, I have also set the option under humhub administration to 20MB.

I am using beta version.

**Comment by luke-** [comment]
Did you also changed the value at   HumHub -> Administration -> Files?

**Comment by pashadee** [comment]
Yes I did, changed that to 20MB as well.

**Comment by petersmithca** [comment]
If your server uses mod_fcgid, you may also need the FcgidMaxRequestLen directive in your apache configuration file for your site. See here for more: https://www.howtoforge.com/apache2-mod_fcgid-http-request-length-exceeds-maxrequestlen - if thats not it I'm stumped

**Comment by pashadee** [comment]
I'm using ispconfig3 version of apache2 / mysql etc. I looked in to the link you provided and upped the limit for fcgid as well but exact same error. Stumps me too.. I thought maybe it was internally part of humhub config somewhere.

**Comment by petersmithca** [comment]
Yeah I'm not sure, I had the same issue on Ispconfig3 with a wordpress site, and changing that in sites conf file (you also have to reload apache) worked for me. I'm running my humhub on ubuntu 14.04 without any tools, just installed lamp stack and created a site. No issues here, just uploaded a 6 meg file to test

**Comment by pashadee** [comment]
I did that too with no changes, will keep digging.

**Comment by armouredking** [comment]
Out of curiousity, where were you trying this? I was originally going to post here to confirm this bug, but I've since seen that it only seems to apply to profiles. For example, my avatar and profile page cover photo have to be less than the 3,145,728 bytes or I get the error message you state. However, throughout the rest of the site ( such as attaching images to my profile stream messages ) I'm able to upload anything up to my current set limit ( 16MB ).

It could be a hardlimit just set on the avatars / profile covers to keep them from getting out of hand. Would be nice if we could adjust it ourselves though, if that is the case.

**Comment by diegochentw** [comment]
after doing Administrator setting, also edit UploadProfileImage.php
array('image', 'file', 'extensions' => 'jpg, png, jpeg, tiff', 'maxSize' => 3 * 1024 * 1024),
change the maxSize you want ex:20 , maybe it can work
