### ISSUE TITLE
Wrong URL in users invite

### ISSUE THREAD

**Issue by dvas13** [humhub/humhub#1316]
Hello,

I just can't fix the URL which is in the user invites. Humhub is installed on my NAS and email invite keep sending a sign up link with a local IP in the URL... Found no entrey in database as humhum can be reach via à subdomain on my NAS...

**Comment by luke-** [comment]
Did you try to set:
Administration -> Basic -> Base Url?

**Comment by dvas13** [comment]
Absolutely ! Actually, I have to be connected outside my local network to get invites sent with the right URL...

**Comment by cboulanger** [comment]
Same here. Invitation mail contains link to http://10.10.10.123 instead of real https link set in Administration > Settings > Emails > Server Settings. The Humhub installation (v1.1) is on a VM inside a private network proxied by an Apache Server on a public IP.

**Comment by haqa** [comment]
I don't believe this issue should have been closed as it is still using the `HTTP_HOST` instead of the configured `Base URL` - If you're not going to use it, why put it in the settings page? This is an issue for me as my proxy isn't easy to configure to send on the original `Host` header.

Please can someone take a look into this as otherwise the system is awesome, but this is making it hard for me to go live.

**Comment by haqa** [comment]
Reopened: https://github.com/humhub/humhub/issues/3510
