### ISSUE TITLE
Database Design: is User-Follower Table efficiently?

### ISSUE THREAD

**Issue by gharach** [humhub/humhub#1348]
in table user-follow we should add a record for  every user follow space or another user, a single user can just follow thousand users so in this case we have a 1000 records for just one user in user-follow table it seams this table will cause low speed in the featured. isn't it?

**Comment by gharach** [comment]
@luke- could  anybody help?

**Comment by feldrim** [comment]
I understand the question but do you have a solutioun?

**Comment by gharach** [comment]
Yes i have, we can store on user-follow just like this :
 id | object-model |  object-ids    | user-id ,  ... 
#   |   ...../User      |{1,25,6,7...n}|  integer
instead of object-id use object-ids that are series of ids(serialize data like json , ..) that user-id followed 
is it good ?

**Comment by feldrim** [comment]
I agree with your opinion altough it requires a little bir more. I want to give an example, which is a bit different than Humhub. Because Humhub doesn't require friend requests like Facebook but the example does.

http://www.codedodle.com/2014/12/social-network-friends-database.html

In the article on the link above, the developer used 4 different filed like user_one_id, user_two_id, status, action_user_id. Because the relationship is not symmetdical, one user may send a request, the other one may haven't accepted it yet so the action_user_id field is "pending" or it may be accepted, declined or blocked.

This design requires user_one_id as the primary key. It's possible to get a friend list easily by this design. And it is limited by four fields. It's simple and lightweight. It has some problems too, but it is ok.

I give this example not to criticise your idea but to give you new approaches about "relationship" databases. There may be some duplicate informations etc. If you think that your code is well optimized, why dont you write it down and let us see your whole idea of database architecture. So maybe, it might spark upgrade to the database. I'm not qualified enough to to that but you or someone else might give it a try.

**Comment by gharach** [comment]
good point, i am trying to use humhub for MY CUSTOM social network , i know there are several database architectures for this problem and i wanna decide to find the best one for my medium size social network web applicatin ,but  i just interested to know  why humhub developers choose this architecture.

**Comment by feldrim** [comment]
I see. I think you can ask it on communiy.humhub.com too. You can get better answers. But I'm pretty sure it's not a big deal to have a million rows (or records) if you have a stable and fast database.

**Comment by gharach** [comment]
ok, thank u.

**Comment by luke-** [comment]
@gharach I think the table is efficient, the database builds an index. In my opinion serialized data isn't the best approach for relational databases.
