### ISSUE TITLE
Admin profile requirement modal - why ???

### ISSUE THREAD

**Issue by frey1esm** [humhub/humhub#1388]
Just updated to to v1 beta 2.    Now I get the Admin profile modal requiring every field to be filled out. 

Except you can't fill it out and dismiss the modal. Ever.

The Birthday field auto formats the birthdate field to an invalid date format. Therefore the modal won't close when you click "Save and close".

Why did you do this???

Why is this popup here in the first place?  Why are all the fields required? Why can't you just close the popup without filling out everything?  Now the entire app is locked onto that popup screen with no chance of using the app.

I went and manually populated the fields in the database, including the birthday.   But the popup still won't go away because of the birthday reformat.

In addition, the modal says, "You are the first user here" which is definitely NOT the case. I have many users.

**Comment by luke-** [comment]
Is fixed in upcoming beta.3
The modal should only displayed for user with id 1  - the first time.

**Comment by luke-** [comment]
Normally there is no field required - maybe you defined all fields as mandatory in your installation.

**Comment by frey1esm** [comment]
Is there a temporary quick fix to unlock this? Database setting to removed "required" settings?

**Comment by luke-** [comment]
add entry to user_setting table

user_id = 1
module_id = tour
name = welcome
value = 1

and flush cache

**Comment by frey1esm** [comment]
Perfect.    Thank you @luke-  !!!

**Comment by DiscordiaChaos** [comment]
I'm running into the same issue in 1.6.1, how can I make it go away? I don't see a user_setting table in my database.

**Comment by luke-** [comment]
@DiscordiaChaos Can you please provide a screenshot?

**Comment by DiscordiaChaos** [comment]
Sure, here is what it looks like. It appears when I go to the Dashboard, and clicking the "Save and close" button does nothing. I have to manually type in the URL of the admin panel to do anything. 

![image](https://user-images.githubusercontent.com/6591554/89342913-74f3ba80-d671-11ea-9a52-7fdc66ef104a.png)

**Comment by DiscordiaChaos** [comment]
Okay, so I toggled off the setting I highlighted and that made it go away. The only thing is that now new users aren't being given the tour, which works correctly for them with no issue. When I toggle it back on, it's back and stuck on top of everything.

I keep trying to find anything like described [here](https://github.com/humhub/humhub/issues/1388#issuecomment-167650719) says, but I can't seem to. Is the completed state saved in another table now? This issue is the only thing keeping me from opening up my site to new users, as they can use it just fine and I cannot.

![image](https://user-images.githubusercontent.com/6591554/90856178-5ff47800-e34f-11ea-918d-e07b71ec2bc3.png)
