### ISSUE TITLE
How to change banner size and profile image size please guide me

### ISSUE THREAD

**Issue by saurabhchris1** [humhub/humhub#1426]
How to change banner size and profile image size please guide me

**Comment by VasileGabriel** [comment]
In protected/humhub/libs edit ProfileImage.php and ProfileBannerImage.php. The views might need some adjusting after you do this.

**Comment by saurabhchris1** [comment]
can you guide me throughly step by step i tried to change height but nothing has happened

**Comment by VasileGabriel** [comment]
@saurabhchris1 email me and I will guide you.

**Comment by andipalmer** [comment]
I would also love to know how to do this please @VasileGabriel That would be great!

**Comment by saurabhchris1** [comment]
In protected/humhub/libs edit ProfileImage.php and ProfileBannerImage.php. The views might need some adjusting after you do this.

here we need to change height and and also we have to change height in 
protected/humhub/modules/user/widgets/views/profileheader.php here default height is 192px

**Comment by sukita2534** [comment]
how to edit  ProfileImage.php and ProfileBannerImage.php

**Comment by WebCrew** [comment]
Best way to do it is to copy the default HumHub Design in HumHub/themes folder and then rename the copied folder and give it a name You like. Now upload the folder again to HumHub/themes, go to Your admin backend and activate Your own new design. Now You are able to do changes in the css file of Your own theme. You have to edit the file called "theme.css", there You can handle the size You want for the profile image and the banner. 

For the profile banner warch out for:
.panel-profile .panel-profile-header .img-profile-header-background 

For the profile avatar image watch out for:
.panel-profile .panel-profile-header .img-profile-header-background

**Comment by lisandi** [comment]
@luke- it says closed as completed on Jan 17, 2019 but where can I change the header image height without editing the core files and the CSS files? I don't see that this is completed as it seems still not to be possible at all without modifications of core files.

**Comment by luke-** [comment]
@lisandi It is currently not possible to change the size. However, we are planning a more flexible approach here in the future...

**Comment by lisandi** [comment]
Already if you would set up the size in core from 192 to something bigger or same then 552 would help because then the images already could be resizied either to fit in a 192 frame or in a much bigger one. The CSS part can always be implemented easily in the CSS of the Theme but the resize frame is the actual problem. It is really not a big change as only that number in the ProfileBannerImage.php has to be much bigger so that this frame can then be matching much bigger sizes and it would still be able to resize the image to 192 height. The width already is designed to be flexible in CSS.

Here is what we changed:
protected/humhub/libs/ProfileBannerImage.php

```
<?php

/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2017 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

namespace humhub\libs;

use humhub\modules\file\libs\ImageHelper;
use Imagine\Image\Box;
use Imagine\Image\ManipulatorInterface;
use yii\imagine\Image;
use yii\web\UploadedFile;

/**
 * ProfileBannerImage is responsible for the profile banner images.
 *
 * This class handles all tasks related to profile images.
 * Will used for Space or User Profiles.
 *
 * Prefixes:
 *  "" = Resized profile image
 *  "_org" = Orginal uploaded file
 *
 * @since 0.5
 * @author Luke
 */
class ProfileBannerImage extends ProfileImage
{

    /**
     * @var Integer width of the Image (default: 1134)
     */
    protected $width = 1248;

    /**
     * @var Integer height of the Image (default: 192)
     */
    protected $height = 552;

    /**
     * @var String folder name inside the uploads directory
     */
    protected $folder_images = 'profile_image/banner';


    /**
     * Constructor of Profile Image
     *
     * UserId is optional, if not given the current user will used
     *
     * @param string $guid
     * @param string $defaultImage
     */
    public function __construct($guid, $defaultImage = 'default_banner')
    {
        parent::__construct($guid, $defaultImage);
    }

    /**
     * Sets a new profile image by given temp file
     *
     * @param \yii\web\UploadedFile $file
     * @throws \yii\base\Exception
     */
    public function setNew($file)
    {
        if ($file instanceof UploadedFile) {
            $file = $file->tempName;
        }

        $this->delete();

        // Make sure original file is max. 800 width
        $image = Image::getImagine()->open($file);
        ImageHelper::fixJpegOrientation($image, $file);
        if ($image->getSize()->getWidth() > 2000) {
            $image->resize($image->getSize()->widen(2000));
        }
        $image->save($this->getPath('_org'), ['format' => 'jpg']);

        // Create version
        $image->thumbnail(new Box($this->width, $this->height), ManipulatorInterface::THUMBNAIL_OUTBOUND)
            ->save($this->getPath(''));
    }

    /**
     * @inheritDoc
     */
    public function render($width = 32, $cfg = [])
    {
        if(is_int($width)) {
            $width .= 'px';
        }

        Html::addCssStyle($cfg, ['width' => $width]);
        return Html::img($this->getUrl(),$cfg);
    }
}
```

This change of the height and width helps already to enable us inserting and resizing images that are 192px or as height as 552px. Depending on the CSS those images then appear either stretched or normal or squeezed. But all images that had been resized smaller then 552 will always appear NORMAL and the CSS takes the height of the image as in CSS it is set to max-height 552px.


This means already right now if ONLY in core that number would be changed from 192px to 552px and the width from 1134px to 1248px the problem would be solved. Even better if you would change also the setting in CSS from height 192px to max-height 552px.

Both changes need ZERO programmers knowhow actually but unfortunately both need to be done in core files!

The CSS change is as follows:

```
.panel-profile .panel-profile-header .img-profile-header-background {
	width:100%;
	max-height:192px;
}
```

needs to be changed to 
```
.panel-profile .panel-profile-header .img-profile-header-background {
	width:100%;
	max-height:552px;
}
```
- - - 

and that problem is solved.

Images that had previously been set or displayed with 192px height will still be displayed as 192px height because they are smaller then 552px in height.

**Comment by luke-** [comment]
Currently we do not want to change the default banner size in the standard theme. 

The new sizes would result in a new banner image ratio, which mean that newly cropped banners would no longer fit correctly into the default banner image size.

**Comment by lisandi** [comment]
No that is not the case as we use that setting in many sites and the images that have been originally 192 are still like that and those bigger are bigger. The problem is much more vice versa as when you have images that are bigger then 192 but you insert them in a site where the core had not been modified they will be squeezed to the 192 format due to the css settings. You can test it actually out. The only problem with the CSS is that even you would change the css settings in your theme you won't be able to actually create a bigger image because of the wrong and static fixed settings in protected/humhub/libs/ProfileBannerImage.php. If that setting in that file would allow bigger cropping all would be fine and eoending only on the CSS value given by the themes.
![Screen Shot 2023-04-26 at 3 59 11 PM](https://user-images.githubusercontent.com/1982011/234525879-13c77c62-925b-4998-823b-16043f62a1eb.png)

This means yu can still leave your height in standard humhub Theme at 192px and people can resize it to be fitting to 192 because that frame can also be made smaller in height. And it looks so much better
![Screen Shot 2023-04-26 at 4 00 04 PM](https://user-images.githubusercontent.com/1982011/234525916-74f9bade-ed28-4f5a-aeb9-6788afec8970.png)
![Screen Shot 2023-04-26 at 4 01 24 PM](https://user-images.githubusercontent.com/1982011/234525919-dee50fd3-86b7-49ab-898e-623c4a11f3d3.png)

Anyway if you won't change it in core how could it be changed via a module that overwrites that value - i.e. a modified Clean Theme. we tried it but it isn't working.

**Comment by luke-** [comment]
We are also planning to add a full-width header option here in the Enterprise theme as well. 
For this we will have to revise the banner handling. However, we cannot change ratios in advance now.
