### ISSUE TITLE
Cannot oEmbed Facebook Posts or Videos

### ISSUE THREAD

**Issue by damianperera** [humhub/humhub#1450]
Post and Video Url's from Facebook are not getting embedded in HumHub.

URL Prefix: _www.facebook.com_
Endpoint Url: _https://www.facebook.com/plugins/post/oembed.json/?url=%url%_

Endpoint Url for both **posts** and **videos** can be found at https://developers.facebook.com/docs/plugins/oembed-endpoints

![screen shot 2016-01-31 at 6 46 59 pm](https://cloud.githubusercontent.com/assets/15967502/12702306/43c312aa-c84b-11e5-8ba4-866e125e2093.png)

**Comment by MBlondin** [comment]
I am getting the same thing.  Just gave that a try

**Comment by absynth47215** [comment]
@buddh4 This issue was, in fact, never actually tackled. It's a simple issue and can be easily fixed, but I don't know the "correct" way to do it in HumHub's coding guidelines.
Facebook expects a valid user agent from any client which requests JSON embed codes, and HumHub sends "-". This is on a default install on an otherwise empty Ubuntu 18.04 VM.

I have added a user agent in protected/humhub/libs/UrlOembedHttpClient.php::fetchUrl() like this:
`curl_setopt($curl, CURLOPT_USERAGENT,"curl/7.64.0");` and Facebook oembed codes started working. 

I think this should be made a configurable option in the main config.

**Comment by ArchBlood** [comment]
I just added this little snippet like this, should work and keep things somewhat clean :man_shrugging:

```php
        // CURLOPT_USERAGENT support
        if ($curl) {
            curl_setopt($curl, CURLOPT_USERAGENT, "curl/7.69.1");

        }
```
The main issue I have is that Facebook has two options `post` & `video` while HumHub only has the ability of adding one per oEmbed option which kind of works against it, I'd rather an optional secondary entry being possible.

**Comment by gabrielfigueroa** [comment]
Does this fix still work with the new FB API changes to oEmbed and the token requirement?
