### ISSUE TITLE
Enhance translation files

### ISSUE THREAD

**Issue by TheZoker** [humhub/humhub#1693]
Why do you have such a strange translation system?

I mean I have to look into like 100 different files to translate it into my language?
Why don't you use the GNU gettext method: https://en.wikipedia.org/wiki/Gettext

Or manage the translation in one big file (if you need to change a string, you can always search for that string in the file). Now I have to search through 100 files...

**Comment by buddha87** [comment]
Don't know what you mean with strange ;) it's Yii's built in translation system, there is no need to introduce any external dependencies, which bypasses humhubs basic framework. Since humhub is a modular system it's not a good idea to just dump all translations in one heavy file. The translation should not be done by hand anyways, since they will be overwritten after an update. We have an translation community for this purpose.

**Comment by cebe** [comment]
btw, Yii does support gettext format if you want to use that instead of php arrays. http://www.yiiframework.com/doc-2.0/yii-i18n-gettextmessagesource.html
