### ISSUE TITLE
Make directory module optional

### ISSUE THREAD

**Issue by andystrobel** [humhub/humhub#171]

**Comment by WASasquatch** [comment]
Open-Source Lightweight Directory Access Protocol or LDAP, is not a enterprise feature in the least. It's just a method...

**Comment by scrobbleme** [comment]
Sure, the protocol is open, but to offer direct support (especially for user integration) through the application is typically a thing, what companies would pay for and the average user just doesn't need it.

**Comment by WASasquatch** [comment]
I think that's where you are missing the point of LDAP. LDAP is uppose to take over all SSL related user handling. It's just a new protocol. Almost all modern software being actively developed offer LDAP support because it is part of PHP now, and it would be "old school" and "lacking ingenuity" if they didn't keep to standards in user management and security....

I have yet to see a company offer a "paid" LDAP system for their open source software, cause they would be pushed into the ground by people that specialize in security via exploits, ddosing, and back doors.

**Comment by scrobbleme** [comment]
Maybe we are just talking about different things ;)
----
Okay, just to be sure. Even if PHP can handle LDAP connections, it can't provide a suitable UI and logic for example to synchronize HumHubs internal user directory with the companies AD/LDAP-enabled user directory. This is what I meen and think the "directoy module" does and not implementing some standards on your own.

This is typically a use case where open source applications can do some money. Providing support for this as so called "enterprise" features.

**Comment by WASasquatch** [comment]
That's only if you use a companies LDAP.....  You can install your own server as I have.

**Comment by buddh4** [comment]
Can be deactivated by Module configuration configuration.
