### ISSUE TITLE
Question: Where "beginBody" is located/calls to

### ISSUE THREAD

**Issue by Censtudios** [humhub/humhub#1765]
Hey, I noticed that this call in main.php

`<?php $this->beginBody() ?>`

Is the one that includes all the javascript files from /assets, /js and /resources folders.

I was wondering where I can find this piece of code. I want to bring all of my javascript files into 1 file to speed up the loading of my site. As of now there are 28 individual .js files being loaded seperately, which kinda slows down the site.

I can comment that code and manually include all the files into 1 file, but then if I install a new module or whatnot it will get screwed up.

Another question:

Is the ?v=1462798733 really important?

**Comment by buddha87** [comment]
The asset timestamp prevents browser caching problems after updates. 

In v1.2 we'll try to combine some ressources where possible. I do not recommend implement a custom merge of the dependencies since you'll have to keep the dependencies and the loading order up to date and you'll have to bypass humhubs current assetmanagment. Furthermore some modules require specific libraries which are loaded after page load.

**Comment by Censtudios** [comment]
Nice, because it literally slows down the site atleast 2-3x. The load time right now is about 5 to 7 seconds, but when I use RocketLoader from cloudflare, which combines the .js files the load time is 1.5-2 seconds. If only RocketLoader didn't bug out some of the scripts I would be using it, but I can't so I wanted to do it manually.

**Comment by Censtudios** [comment]
Not just that, it's also for parallelizing downloads across multiple hostnames. All the .js files are loaded from 1 hostname. I want to change it so that let's say all the .js files from /assets are loaded from cdn1.domain.com and all the .js files from /js from cdn2.domain.com etc etc
