### ISSUE TITLE
Follow button shows error

### ISSUE THREAD

**Issue by pateln54** [humhub/humhub#1774]
I have installed latest stable release on xampp localhost, ubuntu 15.04, everything works fine and thank you very much for such a great product. But, I found a bug, when I go to user profile and click on follow button, it shows blank page with message 'Invalid method!', please check. Path for this on my local machine is something like : http://localhost/humhub101/index.php?r=user%2Fprofile%2Ffollow&uguid=b2b862b4-7f08-4694-a958-7e6ec12e7061

**Comment by buddha87** [comment]
Hi, I can't reproduce this, do you use a custom theme ?

**Comment by xensor** [comment]
i am getting this error as well. it says invalid method! when i do this. i do not know if its something with the site or what. its a fresh install of the latest theme.

http://www.pokefansnews.cf/index.php

**Comment by KitsuneSolar** [comment]
Maybe https://github.com/humhub/humhub/issues/1731 ?

**Comment by buddha87** [comment]
Perhaps clear your cache. Check if the following file in your installation https://github.com/humhub/humhub/blob/master/resources/user/followButton.js and check if this file is loaded correctly.

**Comment by Lercher** [comment]
Had the same issue. In my case the reason was the AdBlock extension of my Chrome with enabled Antisocial filterlist. It blocks the loading of the humhub script followbutton.js as described in #1731 and hence the error message because of a missing script.

I propose to change the error message 'Invalid method!' to something like 'Invalid method! - Please check that you have configured an exception for this site in your browser's AdBlock or similar advertisement management browser extension. Then reload this page and try again.'.

**Comment by buddh4** [comment]
this won't be the case in v1.2 since the followButton,js will be removed.
