### ISSUE TITLE
Viele fehlende Übersetzungen in deutsche.

### ISSUE THREAD

**Issue by wumix** [humhub/humhub#1860]
Humhub ist nur zu 45% übersetzt ins deutsche.

Benachrichtigungen und das Profil sind nur ein Beispiel. 

Wo kann man selbst weiter übersetzen?

**Comment by 001101** [comment]
Fist you should write in English on github

Second I agree, but would say it is about 90%, but i am having big issues to find all suitable translations, cause they are mixed up in different areas, also the modules are very bad translated, mostly not.

Would be very helpful for further translations that we get a guide how and where to find translations...

**Comment by buddha87** [comment]
The best way to contribute translations is over: http://translate.humhub.org/

**Comment by 001101** [comment]
I have already registered, but what about all the modules out there? Would be very nais if we could also translate 3rd party Extensions and of course official modules through the hub. Maybe just a space for modules with link or simple upload and a mod can register them if they are fine.

Also I don't understand how I can translate foreign language in the system, I have set to Russian for example in Usersettings, but still get german translations, is it because of the usersting in browser?

The language selector is also not much clear, because foreign members can't see which languages are available, would be nicer, if the dropdown is set up with international language code in front of the original name.
