### ISSUE TITLE
Allow Table Prefix

### ISSUE THREAD

**Issue by wutong** [humhub/humhub#187]
user should add table prefix option

**Comment by thewhiterabbit** [comment]
Since I have been working on this at my fork (local), I will post in here about this subject rather than post in the  "Do not use reserved SQL keywords as table names" #1424 issue.

Where I'm at on this issue:
I have changed all iterations of table_name with {{%table_name}}.
I am currently debugging.

**Comment by buddha87** [comment]
As luke suggested in #1424 perhaps it would be better to rename all potential conflicting tables as the like table since most of the tables are by default prefixed with the module id and should not conflict with any db engine.

**Comment by thewhiterabbit** [comment]
@buddha87, I think you may not be grasping what I am trying to get across. Luke's suggestion has nothing to do with the need for a unified table prefix for all HumHub tables, to differentiate them from user contributed modules, and other frameworks installed on the same database. Hence, I moved to this issue. :)

In my particular usage case, I require that the HumHub be compliant with certain standards, and best practices. This is a standards issue, industry standards, that's why I'm implementing it.

Do you have any questions? Is there something you have misunderstood that I can explain better?

**Comment by luke-** [comment]
@thewhiterabbit There is already a convention that all thirdparty or contributed modules should prefix their tablenames with "moduleId_tableName". https://www.humhub.org/docs/guide-dev-db.html#conventions

IMHO it's not a best practice or even standard to put multiple applications/frameworks into the same database using prefixed tablenames. Maybe it's a cheap solution if your hosting provider limits your databases.

Anyway I've no problem with adding an option for that - but it may require a lot of adjustments.

**Comment by thewhiterabbit** [comment]
@luke- When I was referring to industry standard, I strictly meant allowing table prefixes for an obscurity layer. I do have plenty of web resources to accommodate another database, but others might not.

Having too much data in the same base could create bottlenecks, but that's a marginal concern for most HumHub implementations. I'm willing to help build the best solution possible.

Obviously I'm not familiar with Yii, and TBH I'm lagging on learning the Yii framework. A few hundred replace actions and my "solution" generated this error...
```

 PHP Fatal Error – yii\base\ErrorException
Class 'yii\authclient\BaseClient' not found

    1. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/humhub/modules/user/authclient/BaseClient.php at line 18
    9101112131415161718192021222324252627

    namespace humhub\modules\user\authclient;
     
    /**
     * Extended BaseClient with additional events
     *
     * @since 1.1
     * @author luke
     */
    class BaseClient extends \yii\authclient\BaseClient
    {
     
        /**
         * @event Event an event raised on update user data.
         * @see AuthClientHelpers::updateUser()
         */
        const EVENT_UPDATE_USER = 'update';
     
        /**
         * @event Event an event raised on create user.

    2. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/BaseYii.php at line 20 – yii\BaseYii::autoload()
    3. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/BaseYii.php at line 20 – spl_autoload_call()
    4. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/BaseYii.php at line 288 – unknown()
    5. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/BaseYii.php at line 26 – yii\BaseYii::autoload()
    6. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/BaseYii.php at line 26 – spl_autoload_call()
    7. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/BaseYii.php at line 288 – unknown()
    10. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/humhub/modules/admin/widgets/PrerequisitesList.php at line 37 – humhub\libs\SelfTest::getResults()
    31323334353637383940414243

         * Check there is an error
         * 
         * @return boolean
         */
        public static function hasError()
        {
            foreach (SelfTest::getResults() as $check) {
                if ($check['state'] == 'ERROR') {
                    return true;
                }
            }
     
            return false;

    11. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/humhub/modules/installer/controllers/SetupController.php at line 41 – humhub\modules\admin\widgets\PrerequisitesList::hasError()
    35363738394041424344454647

         * Libary
         *
         * (Step 2)
         */
        public function actionPrerequisites()
        {
            return $this->render('prerequisites', ['hasError' => PrerequisitesList::hasError()]);
        }
     
        /**
         * Database action is responsible for all database related stuff.
         * Checking given database settings, writing them into a config file.
         *

    12. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – humhub\modules\installer\controllers\SetupController::actionPrerequisites()
    13. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array:{/home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/InlineAction.php:55}()
    14. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams()
    15. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction()
    16. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction()
    17. in /home/m1chaelkent/public_html/cannacle.com/streams/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest()
    18. in /home/m1chaelkent/public_html/cannacle.com/streams/index.php at line 25 – yii\base\Application::run()
    19202122232425

        require(__DIR__ . '/protected/humhub/config/web.php'),
        (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
        require(__DIR__ . '/protected/config/common.php'),
        require(__DIR__ . '/protected/config/web.php')
    );
     
    (new humhub\components\Application($config))->run();

```
My branch has the code that generated the above error. Maybe we could exchange ideas, and you could briefly school me on the Yii, so I could implement a proper solution and make a pull request?

Hats off to you and the HumHub team for the best open source social engine I've come across thus far. That's why I want to help, if I can. I see something I like and I want to help. :)

**Comment by luke-** [comment]
@thewhiterabbit Your error seems related to a missing dependecy. Try running "composer update". 
Hope that solves your problem...
