### ISSUE TITLE
How to edit second topbar navigation?

### ISSUE THREAD

**Issue by primantok** [humhub/humhub#1876]
Hi all,

How to edit (add / remove) second top bar item?
(Please see image for detail ilustration what I want to do)

Thanks.

![topbar](https://s31.postimg.org/yebag5qwr/topbar.png)

**Comment by cebe** [comment]
what do you want to add there? the custom pages module for example allows you to add items in that list.

**Comment by primantok** [comment]
@cebe, sorry I missed to upload another image.

What really I want to do is moving sidebar menu item from "directory layout" permanently to topbar. So user can visit space listing, member listing & user stream directly without visiting directory page.

Thanks for your help.


![sidebar]
(https://s32.postimg.org/aip3xn3md/dir.png)

**Comment by 001101** [comment]
Just link them with Custom Pages, no effort worth for code looking.

**Comment by buddh4** [comment]
Just install the custom pages module and create Link based Custom Page within your admin section.

In order to remove the navigation and change the layout you'll have to create your own [Theme](http://docs.humhub.org/theme-README.html), if you require further help, consider asking the [community](https://community.humhub.com/s/theming-appearance/)

**Comment by BDSM-Master** [comment]
Or instead of making people jump through very unnecessary hoops, you can just tell is where to make the changes. Prime example I have no need for calendar or messages to be on that menu bar and would like to remove them.

**Comment by buddh4** [comment]
Currently there is no single location for editing those navigations, since they are appended within an event handler like [this](https://github.com/humhub/humhub-modules-calendar/blob/master/Events.php#L20). Editing such core or module files directly is not recommended, since they probably will be overwritten when updating.

There are many ways of hiding/adding navigation items as for example:

- Javascript
- Custom Pages Module (only adding)
- CSS
- Custom Module
- Overwrite views by means of a custom theme
- etc.

This depends on your skillset and preferences...
In the future a configuration would be thinkable for managing those menus.

Also, if you expect any support in the future show some more respect.

**Comment by BDSM-Master** [comment]
The problem is that what I want to hide/ remove such as calendar and messages do not show up in custom pages or custom modules. So if the only way is to edit core files, then so be it. So if you know how to hide/remove calendar and. Was ages from the menu bar only, it would be greatly appreciated.

**Comment by buddh4** [comment]
Add the following code into `Administration -> Settings -> Statistics`

```
<script>
$(document).on('humhub:ready', function() {
     $('#top-menu-nav').find('.fa-calendar').closest('li').remove();
});
</script>
```

Its not the cleanest way, but should be ok until there is a configuration available.

**Comment by BDSM-Master** [comment]
Let you know how it works. Thanks.

**Comment by buddh4** [comment]
To also remove the message icon replace the line with

`$('#top-menu-nav').find('.fa-calendar, .fa-envelope').closest('li').remove();`

Think the message icon will be removed in an upcoming message module version anyways.

**Comment by BDSM-Master** [comment]
@buddh4  That did not work. Any other ideas?

**Comment by Mimanolis** [comment]
Regardless of this question being ~7yo, If I'm allowed to hijack the issue and ask, is there a similar way to edit the names of the shortcuts in the topbar?

**Comment by Mimanolis** [comment]
> To change the navigation titles you can use: https://docs.humhub.org/docs/admin/translations#overwrite-translation-messages

Followed the guidelines in https://docs.humhub.org/docs/admin/translations/ but nothing changes

Created a folder with the language ISO in protected/config/messages to preserve the core files
write down the translation according to the format <;php .. => etc
named the file UserModule.custom.php

No change

**Comment by felixhahnweilheim** [comment]
It shouldn't be UserModule.custom.php but e.g. UserModule.base.php
