### ISSUE TITLE
How to remove "directory" button or block this page

### ISSUE THREAD

**Issue by lArcade** [humhub/humhub#2057]
I want to remove the "directory" button and not show the members of my community. But, I prefer block this page: http://xxxxx.xx/index.php?r=directory%2Fdirectory%2Fmembers

How I can do it?

Sorry for my bad English

**Comment by StellarisAgency** [comment]
in 'protected/humhub/modules/directory/controllers/DirectoryController.php' change lige 70.
this : `return $this->redirect(['members']);` into this : `return $this->redirect(['spaces']);`

And in 'protected/humhub/modules/directory/widgets/Menu.php' comment or delete the 'members' item:
` $this->addItem(array(
            'label' => Yii::t('DirectoryModule.views_directory_layout', 'Members'),
            'group' => 'directory',
            'url' => Url::to(['/directory/directory/members']),
            'sortOrder' => 200,
            'isActive' => (Yii::$app->controller->action->id == "members"),
        ));`

But know that this manipulation just hide the members section, the directory/members page can still be reaching by the direct url !!

**Comment by boppy** [comment]
My approach was to use my theme to hide it:

1. Create the following file inside your theme directory: `views/directory/directory/_layout.php`
2. Paste that into the file (or change it  the way you want; original file at `protected/humhub/modules/directory/views/directory/_layout.php`):
```php
<?php
use humhub\modules\directory\widgets\Menu;
use humhub\modules\directory\widgets\Sidebar;

\humhub\assets\JqueryKnobAsset::register($this);

// == THESE LINES DIFFER ==========================
if(!Yii::$app->user->isAdmin()){
    header('Location: /');
    exit;
}
// == END =========================================
?>

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <?= Menu::widget(); ?>
        </div>
        <div class="col-md-7">
            <?= $content; ?>
        </div>
        <div class="col-md-3">
            <?= Sidebar::widget(); ?>
        </div>
    </div>
</div>
```
3. Insert the following CSS to your `less/theme.less`-File:
```css
li.directory,
li>a.directory {
  display: none !important;
}
```
4. Recompile your less with `lessc -x themes/**THEME_NAME_HERE**/less/build.less themes/**THEME_NAME_HERE**/css/theme.css`

Steps (1) and (2) make it impossible for non-admin to see somthing even if they are able to enter the page in any way. Steps (3) and (4) make the menu entries disappear (keep in mind: They are stil shipped to the users but not shown). You should not limit the selector to `li.directory` because in the dropdown menu (mobile layout) the class is added to the `<a>` not the `<li>` - I have choosen this selector hoping not to match any other element w/ that class (perhapt a folder in a file manager).

An admin can still call and see the directory if accessing the url directly.

**Comment by jasdevmoun** [comment]
I am using Humhub version 1.4.0-beta.1

In this version you can go to Administration ---> Users ----> Groups  and then allow or Deny Directory access to any of the user groups.

I hope it helps!

**Comment by DrGreenCodeWizard** [comment]
> I am using Humhub version 1.4.0-beta.1
> 
> In this version you can go to Administration ---> Users ----> Groups and then allow or Deny Directory access to any of the user groups.
> 
> **No need to edit the code or theme's code**
> 
> I hope it helps!



Can't find this setting option in Version: 1.8.1

Can someone help?

**Comment by ArchBlood** [comment]
You can disable or disallow guest access in your common.php file with these parameters
https://github.com/humhub/humhub/blob/26d7e2667a9317057abe335a056ac8e8f4d675fb/protected/humhub/modules/directory/Module.php#L44-L52

To disable this by user group you have to go into the User Group permissions, if you don't see this then it could be an issue with your theme
![Screenshot_1](https://user-images.githubusercontent.com/35392110/112768254-3092a180-8fe9-11eb-956a-5bedfb52c6e0.png)

**Comment by DrGreenCodeWizard** [comment]
Hi ArchBlood, thx for the quick replay, but can I set up directory access for guests anyhow?
