### ISSUE TITLE
Improve page-load performance

### ISSUE THREAD

**Issue by coliff** [humhub/humhub#2098]
I'm very interested in helping Humhub improve performance, page load times. I'd like to see all the JavaScripts which are loaded be minified and the images losslessly optimised.

On this page (https://community.humhub.com/user/auth/login) there are many JavaScript files which are unminified and it makes the filesizes almost twice the size. It'd be great if these were minified and would save about 90 KB.
REF: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcommunity.humhub.com%2Fuser%2Fauth%2Flogin%23

There are also many PNG which could be losslessly optimised to save space and SVG files which could be losslessly minified. Should I open pull requests to improve these issues?

**Comment by buddha87** [comment]
In v1.2 all core script and css files will be served as one minified file if you run in production mode, But you  could check the image optimization if this will boost the performance.

**Comment by 001101** [comment]
My HumHub with only Nginx, Opcode and Cloudflare is blazing fast on a VPS with 2 vCores.

**Comment by gigabytedevelopers** [comment]
Please Buddha, in which file are you guys planning to include the commands(functions and variables) that would serve all the javascript files in a single minified file when running in production mode in version 1.2 release? Because I have gone so far in 1.1 and wouldn't like to perform a full upgrade to 1.2 when its released because I fear to encounter problems, it would be nice if I can just manually edit the files in the current 1.1 to go gain some features available for 1.2 without changing the entire environment (this manual method is known as patch).

**Comment by gigabytedevelopers** [comment]
@buddha87 . 
Please Buddha, in which file are you guys planning to include the commands(functions and variables) that would serve all the javascript files in a single minified file when running in production mode in version 1.2 release? Because I have gone so far in 1.1 and wouldn't like to perform a full upgrade to 1.2 when its released because I fear to encounter problems, it would be nice if I can just manually edit the files in the current 1.1 to go gain some features available for 1.2 without changing the entire environment (this manual method is known as patch).

**Comment by buddha87** [comment]
Did you modify some of the core js files, since v1.2 includes an js rewrite, you would have to merge your changes to the new js api?

Here is the current part of the asset build doc, but its fare from complete.

https://github.com/humhub/humhub/blob/v1.2-dev/protected/humhub/docs/guide/dev-build.md#assets

The asset build for production will compress all css/js assets included in 

https://github.com/humhub/humhub/blob/v1.2-dev/protected/humhub/assets/AppAsset.php

Here you can check the current state of the js api. Since the api is modular, it should be easier to overwrite certain logic without modifieng the core files.

https://github.com/humhub/humhub/tree/v1.2-dev/js/humhub

**Comment by gigabytedevelopers** [comment]
@buddha87. Thanks, I think I changed some core javascript files and that's why I fear for errors after a full upgrade to version 1.2, but after a had a good look at the links you provided, I decided to ask a few questions which are: 1. After the release of 1.2, does this mean that I can run this command -> yii asset humhub/config/assets.php humhub/config/assets-prod.php on my current version of humhub and still get all my javascript files to be minified for production use? 

Please guide me through because right now, I a little bit confused. Least I forget, what exactly will be the core changes, features, and fixes that will be available in 1.2 which are not or which may vary from the current 1.1? 

Thanks!

**Comment by buddha87** [comment]
The yii asset command will minify and combine all assets of the [AppAsset](https://github.com/humhub/humhub/blob/v1.2-dev/protected/humhub/assets/AppAsset.php) file e.g. bootstrap, jquery, some jquery plugins and the new humhub core api, but you do not have to call it unless you change the core files which is not recommended, since you'll probably have the same problem with each update.

Almost all old js logic will be/is transfered to the new js module system.
We've tried to design the modules as flexible as possible, so you can overwrite exported functions or ui components. Furthermore we've removed inline code blocks where possible. 

Here are some of the changes in v1.2:

- JS Rewrite (e.g. new Userpicker/Spacepicker/Upload-component, new Statusbar for user feedback, Modal handling, new gallery/, ..
- GUI/Usability improvemetns
- Enhanced theming, so you do not have to copy the whole .less file anymore and can just overwrite what you need.
- Fixed some usability issues
- Optional Pjax support for a single page application (only reload content)
- New Group Permissions for managing admin sections
- Better testability / module tests / test coverage
- Performance improvements (asset management/content handling/pjax/...)
- Introduction of realtime updates (not yet implemented)

We'll provide a migration guide for theme developers and module/core developers.

**Comment by gigabytedevelopers** [comment]
@buddha87. Wow!! This is indeed so cool. Cooler than the current 1.1.
U talked about a new gallery, does this contain an album that holds all the images that has been uploaded by a user to the network? 
If I should overwrite the new js files that controls Userpicker, Spacepicker, Upload component, Modal handling and the so called new Statusbar for user feedback; with the current one on 1.1, would it cause problems? Maybe because of the addition of new variables and functions? 
Would the pjax option make humhub function on non-javascript users/browsers? 
Thanks once again!

**Comment by buddha87** [comment]
There will be also a new gallery module but I was talking about the gallery framework, we switched to this gallery: https://blueimp.github.io/Gallery/

You cannot just overwrite the new files with the old files, if you want to use the new functionality you'll have to follow the migration guide and migrate your views. Some alignments are optional and some are mandatory.

**Comment by martinbeek** [comment]
Does anyone have experience / advice for using cloudflare w. humhub, focussing on caching and page rules? All advice is much appreciated!
