### ISSUE TITLE
iOS App in work?

### ISSUE THREAD

**Issue by petrk94** [humhub/humhub#2183]
Hello,
I would like to know whether a iOS App is in development?
I found already an Android App here: https://play.google.com/store/apps/details?id=ch.tink.humhub

Any informations?

**Comment by Felli** [comment]
@petrk94 at the moment both iOS & Android apps are on the To-Do list, that app is not an official one, it's best to read the [Roadmap](https://community.humhub.com/s/96d933cd-e5a9-4314-8f8f-564f2dd81cf6/wiki/page/view?title=Roadmap) for this, or the [Module Roadmap](https://community.humhub.com/s/a620fd6b-425b-4591-b0d4-47d22f2f8edd/wiki/page/view?title=Roadmap) for modules roadmap. :+1:

**Comment by petrk94** [comment]
@Felli Thanks for your information, but the mobile Apps are unsorted, has that a reason?

**Comment by Felli** [comment]
They just haven't sorted it in a version release as of yet, it's one of the most requested things as of right now, but overall Core development & bugfixes are more important before a mobile app can be created, need a stable core environment before the thoughts of any mobile apps.

**Comment by boreys** [comment]
Any update on mobile app? it's kind of a big deal

**Comment by Felli** [comment]
@boreys should be sometime after `HumHub v1.3` release I would think, but I can't give any ETA on a date/time both apps will be released.

**Comment by kngatai** [comment]
Hi is there any update on the iOS App?

The network we are trying to target are more interested in using a phone app.

Regards

**Comment by Felli** [comment]
HumHub is planning on a PWA solution at this time.

**Comment by pablodgavilan** [comment]
Is there an ETA for PWA with Humhub? That would really make a difference to increase user adoption.

**Comment by Felli** [comment]
The last time it was posted about in the community site it was planned somewhere after v1.4 this could have changed as of right now but I can not give an exact ETA as plans always change with development.

**Comment by luke-** [comment]
@pablodgavilan Unfortunately, there is no safe ETA yet. We hope to support a first PWA support with the 1.4.

**Comment by jabo59** [comment]
v1.4 is now available. What is the current state regarding the IOS app?

**Comment by Darkknight33** [comment]
This topic is 3 years old. If it were a priority for them, it'd be done already. 

Respectfully, projects like these need a different mindset when you are considering using them. I think you should evaluate the project for what it can do you today, not what it _might_ do in the next version. As it stands, they don't have mobile apps, don't seem to plan on specific apps, and want to use the browser as the main interface. 

If you want a network like this with dedicated apps, you should probably look elsewhere.

**Comment by nomatica** [comment]
Lack of an app is a problem several projects like this have.  It is hard to find any software like this with an app. 

> 
> 
> This topic is 3 years old. If it were a priority for them, it'd be done already.
> 
> Respectfully, projects like these need a different mindset when you are considering using them. I think you should evaluate the project for what it can do for you today, not what it _might_ do in the next version. As it stands, they don't have mobile apps, don't seem to plan on specific apps, and want to use the browser as the main interface.
> 
> If you want a network like this with dedicated apps, you should probably look elsewhere.

Lack of an app is a problem several projects like this have.  It is hard to find any software like this with an app.

**Comment by buddh4** [comment]
There are several problems regading a native apps as:

- HumHub is modular, so you could only provide a subset of features within a native app e.g. only core features, no custom module features.
- HumHub is themable, and the app should somehow match that theme (which would not be impossible but need to be considered)
- Notification backend: when providing a single app for all networks, we'd need to provide a central notification backend. There are existing solutions available, but nontheless this would be a non trivial system to integrate and maintain
- Instead of providing a single app for all networks, there could be an app template, which are not that welcome in marketplaces especially in apples marketplace as far as i know.
- We'll have to maintain at least one additional frontend (or three in case of a real native app).
- A simple webview based app is inferior to a PWA, the only real reason to implement it would be iOS notifications.
-...

We've enhanced the mobile view and added PWA features to HumHub v.1.4 and we'll continue enhancing the usability and performance on mobile devices. This enables the usage of all features within a HumHub installation and notifications (unfortunately iOS does not support web push notifications yet).

In my opinion PWA's are perfect for the use case of HumHub, they are simple to install, no need for maintaining different frontends and they provide most of the features you'd expect from an app. Yes, the usability may lack, but enhancing the mobile usability of the PWA is way cheaper than building and maintaining a native app with the advantage, that the mobile browser frontend of the network is enhanced simultaniously.

In the future special apps like a HumHub task manager or calendar would be thinkable, and could be implemented either as PWA or native app.

**Comment by Khanboch** [comment]
any updates on this?

**Comment by Khanboch** [comment]
> Hello, I would like to know whether a iOS App is in development? I found already an Android App here: https://play.google.com/store/apps/details?id=ch.tink.humhub
> 
> Any informations?

ANy updates on this?

**Comment by ArchBlood** [comment]
> > Hello, I would like to know whether a iOS App is in development? I found already an Android App here: https://play.google.com/store/apps/details?id=ch.tink.humhub
> > 
> > Any informations?
> 
> ANy updates on this?

https://github.com/humhub/app

**Comment by wahshibinharb** [comment]
fatal erör

**Comment by dreua** [comment]
Android app is here: https://play.google.com/store/apps/details?id=com.humhub.app
iOS app seems to be not here. No idea if it is going to ever be a thing.

Regarding PWAs as a solution for iOS: Apple plans to ban them in the EU and they say it'd be due to EU legislation. I believe they should be very well capable of allowing PWAs without compromising security but banning them is just what's best for their profit and they don't care about the users and developers. Maybe we can pressure Apple to change their plans if enough people care/write/talk about this.

**Comment by marc-farre** [comment]
@dreua the project for the app is here: https://github.com/humhub/app
iOS app is currently in progress.
Apple makes it difficult to send it to their store, but HumHub team is working on it!

**Comment by wahshibinharb** [comment]
I admit that Apple is a little detail-oriented when it comes to apps, but I don't think it should take this long just to publish an app?

**Comment by dreua** [comment]
> @dreua the project for the app is here: https://github.com/humhub/app

Huh I didn't see the iOS directory there yesterday. Maybe I was blinded by the meaningless Readme file and the completely empty repo description ;)

**Comment by marc-farre** [comment]
![image](https://github.com/humhub/humhub/assets/23310825/e9abde14-6e9a-47bd-a581-3761791f9678)

**Comment by dreua** [comment]
I literally meant that I didn't see it, it was there of course. Sorry for causing confusion.

**Comment by marc-farre** [comment]
> I literally meant that I didn't see it, it was there of course. Sorry for causing confusion.

Yes, it was clear to me, but I wanted to add the screenshot to this feed so others can see where it is, and to show @wahshibinharb that work is on progress about iOs (last commit 3 days ago).

**Comment by samuk** [comment]
Any updates on when this might be in the app store @luke-

**Comment by luke-** [comment]
@samuk We will try again when further features have been implemented. Unfortunately, I can't give any more precise timeframes.

**Comment by ilMagnifico** [comment]
Bump

**Comment by marc-farre** [comment]
iOS app URL: https://apps.apple.com/hr/app/humhub/id6446092274
