### ISSUE TITLE
Google Drive Module

### ISSUE THREAD

**Issue by stellarmagnet** [humhub/humhub#2199]
Hello there!

We are a new team using humhub. We want to develop a google drive module. Wondering if anyone is already working on this and wants a collaborator. We are also new to module development and can use some more pointers than what is in the documentation. Are there any tips listed somewhere?

Thanks,
Yalda

**Comment by WebCrew** [comment]
The only thing you can do so far is to use other modules as a example, or to read the HumHub documentation and to use the HumHub community. 

As far as I know the documentation becomes a update with more advanced informations. 

There is also a not 100% finished but useable "Demo Module" for HumHub here at GitHub with lots of explanations etc. 

For my opinion you can try to use the HumHub **DropBox Module as a good example** and starting point because it is similar to a GooleDrive Module. I hope it will help you - I wish you good luck and much success :+1:

**Comment by buddh4** [comment]
Hi, you could join our community: http://community.humhub.com/ the developer community isn't that big yet, but I hope this will change soon. We are currently working on enhancing the documentation for the upcoming version.

**Comment by JanMarvinChrist** [comment]
@petrk94 you? :)
