### ISSUE TITLE
Bug: open invite to space link in new window

### ISSUE THREAD

**Issue by randomboygh** [humhub/humhub#2211]
Right click on "Invite" button and open it in new tab in any Space have opened a window without styles. For example: https://community.humhub.com/s/feature-requests/space/membership/invite

**Comment by Felli** [comment]
Hmm... Devs should add in right click disabled, the same thing happens with the mail module, tho it opens to a about:blank in Chrome and Firefox when it should just redirect to the message.

**Comment by randomboygh** [comment]
No, it's wrong way I think. So if I disable JS, I can't open this page anymore?
And if devs disabled right click, I clicked middle button and get the same page.

**Comment by Felli** [comment]
Oh no, I meant disabling the ability of right clicking on the invite button(s) alone, disabling JS alone won't fix this, but I'm sure that the devs will find away of doing this so that the button(s) will still work. :smiley:

**Comment by randomboygh** [comment]
To my mind devs can make choise like it made on login/singup and other modal windows, which have single page for each

**Comment by buddh4** [comment]
Yes those are old links with a data-target="#globalModal" most of them were or will be replaced replaced in v1.2. Also this can be prevented by using buttons instead of links. Thanks for reporting. Note that the whole frontend won't work without Javascript, since the frotnend is based upon Html5 and Javascript. Without Javascript not even the Modals can be loaded, no Ajax calls etc...
