### ISSUE TITLE
Testing 1.2.0-beta1

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#2245]
> Compressed & combined CSS/Javascript assets

Can't activate this, is there an option to enable this?

**Comment by blendsoft** [comment]
grunt build
undefined
Running "concat:dist" (concat) task

Running "uglify:build" (uglify) task
File js/dist/humhub.all.min.js created: 0 B → 0 B
>> 1 file created.

Running "uglify:assets" (uglify) task
Warning: Cannot read property 'indexOf' of undefined Use --force to continue.

Aborted due to warnings.
grunt less
undefined
Running "less:dev" (less) task
>> Destination themes/HumHub/css/less/theme.css not written because no source files were found.

Done.

**Comment by buddh4** [comment]
The combined assets are automatically used if you run your installation in production mode. In production the all-*.js and all-*.css file is used. The documentation will follow. Sorry the grunt tasks are a bit outdated for building the assets you'll have to follow this: https://github.com/humhub/humhub/blob/master/protected/humhub/docs/guide/developer/core-build-assets.md I think we'll create a grunt task for this soon.
