### ISSUE TITLE
Database compatibility HH 1.0.1 vs 1.0.2

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#2258]
Hi, after try everything trying to update HH to 1.0.2 I used a bit of brute force to install it. I changed the name of my root folder and I created a new installation in new folder with original root name. I installed it directly to my 1.0.1 database and finally I replaced all files to my original HH.
The principal problem is that some database tables doesn't exist.

I try to import my old database to the new database but also they are not compatible. Even for simple entries as Users and credentials.

Welle, here is the problem. I can't update from 1.0.1 to 1.0.2 and I can't import my database to new one.

Have I to stay forever in HH 1.0.1?
Pass to 1.0.2 loosing all mu users and content?

**Comment by jeremiahtenbrink** [comment]
By installing HH that way, it sounds to me like HH is missing migrations that need to be run in order for the new database schema to be correct. Why are you updating HH in this manner?

**Comment by eddiepiazza** [comment]
because when I try to update by normal mode using the updater I am getting this error:
![image](https://cloud.githubusercontent.com/assets/8577866/22863541/0fda8658-f13a-11e6-8c00-acff62b111d1.png)

I am also recieving a lot of new errors into my logs and after restore my last backup I discovered that I can´t edit a post in my own Space. More I try to fix the system more errors and bugs I am getting.

I would like to install a fresh HH with last version and import all content from my old one. But phpmyadmin is sending me errors because of tables. The database structure changed and tables cannot merge.

**Comment by eddiepiazza** [comment]
As you see the button edit disappeared from posts but is available for comments:
![image](https://cloud.githubusercontent.com/assets/8577866/22863553/5791de24-f13a-11e6-960a-2d00f3807cf2.png)

This is one of some bugs I am getting after put my fingers in the system.

**Comment by eddiepiazza** [comment]
Here you can see an example of tables between both versions: I get error importing for all database so is being really difficult to fix all.

HH 1.0.2
INSERT INTO `content` (`id`, `guid`, `object_model`, `object_id`, `visibility`, `**pinned**`, `archived`, `created_at`, `created_by`, `updated_at`, `updated_by`, `contentcontainer_id`, `stream_sort_date`, `stream_channel`) VALUES

HH 1.0.1
INSERT INTO `content` (`id`, `guid`, `object_model`, `object_id`, `visibility`, `**sticked**`, `archived`, `created_at`, `created_by`, `updated_at`, `updated_by`, `contentcontainer_id`) VALUES

**Comment by jeremiahtenbrink** [comment]
I sure hope you saved you database before you tried to update humhub.
Because if you didn't update you database schema and data. I don't think
there is anything you can do. Try to restore your database back to the
backup you hopefully did before you updated.

On Feb 12, 2017 8:50 AM, "eddiepiazza" <notifications@github.com> wrote:

Here you can see an example of tables between both versions: I get error
importing for all database so is being really difficult to fix all.

HH 1.0.2
INSERT INTO content (id, guid, object_model, object_id, visibility,
**pinned**, archived, created_at, created_by, updated_at, updated_by,
contentcontainer_id, stream_sort_date, stream_channel) VALUES

HH 1.0.1
INSERT INTO content (id, guid, object_model, object_id, visibility,
**sticked**, archived, created_at, created_by, updated_at, updated_by,
contentcontainer_id) VALUES

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/humhub/humhub/issues/2258#issuecomment-279227218>, or mute
the thread

**Comment by eddiepiazza** [comment]
Sorry but I think you didn t understood the problem. My database is working with my HH 1.0.1. I made backup of all.

Just I try to get last HH version by two ways.
First by brute force overwriting files and database with new HH installation.
Second by creating new clean installation of HH 1.0.2 and importing all data from old database.

No one worked.
I need a solution to not loose all my users, their configs, posts, all my custom pages and files having a new clean HH installation. Or fixing my actual HH 1.0,1 to pass to 1.0.2

**Comment by jeremiahtenbrink** [comment]
Oh ok. Well good. I'm glad you still have all your data. Then this problem
can be solved. Give me time to look at the two different vs of humhub to
see what's going on with the migrations. It would be beneficial if you
happen to know what the difference is in the database schema.

**Comment by jeremiahtenbrink** [comment]
I just looked at the difference between the two insert statements. There have been additions to the table and I think one has changed. However I am not seeing the vs 1.02. Where are you finding this humhub vs at?

**Comment by eddiepiazza** [comment]
Well seems there are differences in all database because when I try to import old one into new one I get errors for all.
This example I sent you is one of few differences. At the same time, I am updating my HH since almost one year what means that maybe my base system is not compatible with new one.
Here the challenge is more to install new clean version and import all important data. I have not enough knowledge to do it...

**Comment by jeremiahtenbrink** [comment]
I don't understand where you are finding vs 1.0.2 I can't do anything to
help you till I know exactly what the migration files look like.

**Comment by eddiepiazza** [comment]
If you provide me an email I can send you 2 databases, my HH 1.0.1 and a clean one 1.0.2 for compare

**Comment by jeremiahtenbrink** [comment]
A clean version of 1.02 code to look at and then your database from schema
from 1.01. Specifically the migration folder. Is it your mail that's
getting messed up or just the wall posts. If you can't pin point then I'll
need all the 1.02 code. Because I can't locate the code for 1.02.

On Feb 12, 2017 12:05 PM, "eddiepiazza" <notifications@github.com> wrote:

If you provide me an email I can send you 2 databases, my HH 1.0.1 and a
clean one 1.0.2 for compare

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/humhub/humhub/issues/2258#issuecomment-279240162>, or mute
the thread

**Comment by jeremiahtenbrink** [comment]
Jeremiahtenbrink@gmail.com

**Comment by eddiepiazza** [comment]
I sent you by mail both databases.
Thank you

**Comment by jeremiahtenbrink** [comment]
I told you I would also need the core code from vs 1.0.2 which is where the
error will be located. I can't help you I'm sorry.

**Comment by eddiepiazza** [comment]
Ok sorry, could you please provide me the source of this code you need? Is it in a specific file?
