### ISSUE TITLE
“Hide file info (name, size) for images on wall” in Advanced settings -> Files has lost its function in 1.2 beta 1+2

### ISSUE THREAD

**Issue by Twilek-de** [humhub/humhub#2302]
“Hide file info (name, size) for images on wall” in Advanced settings -> Files has lost its function in 1.2 beta 1+2. The name and size of images are shown wether it is activated or not.

**Comment by gigabytedevelopers** [comment]
Ya. Same problem here, I noticed it myself too

On Feb 26, 2017 09:05, "Twilek-de" <notifications@github.com> wrote:

“Hide file info (name, size) for images on wall” in Advanced settings ->
Files has lost its function in 1.2 beta 1+2. The name and size of images
are shown wether it is activated or not.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/humhub/humhub/issues/2302>, or mute the thread
