### ISSUE TITLE
Special Characters break Mentions

### ISSUE THREAD

**Issue by Felli** [humhub/humhub#2348]
From what I've seen in [this post](https://community.humhub.com/content/perma?id=97445). Adding a special character like `()` will break the mention and give the user ID.
![](http://image.prntscr.com/image/f655b5189974476e8258bce4d489e7d5.png)

**Comment by tomtomsen** [comment]
I think the problem comes from the the regular expression 
```regex 
\@\-([us])([\w\-]*?)($|[\.,:;\'"!\?\s])
``` 
in [RichText.php:164](https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/RichText.php#L164)

first it checks for the "@-u" at the beginning
then it searches for an **optional**(?) string (containing word characters and -)
and checks if the string ends with differnent characters (like ., ,, ;)

in your case the last part of the regex should also contain the ")" character.

wouldnt it be a better solution to improve the regex in such a way, that
* the second part isnt optional (make the ```([\w\-]*?)``` required. like: ```([\w\-]+)```)
* improve it even more to something like ```(\w{8}\-\w{4}\-\w{4}\-\w{4}\-\w{12})```

Probably the regex of [UUID:66](https://github.com/humhub/humhub/blob/master/protected/humhub/libs/UUID.php#L66) could be extracted to a method an be reused in RichText?

i could try to make a pull-request, if you like

**Comment by buddh4** [comment]
@tomtomsen a pull request would be gread.
