### ISSUE TITLE
cfiles module breaks design

### ISSUE THREAD

**Issue by martinbeek** [humhub/humhub#2446]
latest version april 2017.

If i add a number of imagefiles to a file directory, a preview is given of only one file (sometimes more, but as separate files), that don't fit on the stream.

Adding the following CSS in my theme.css solves the problem:
```
.content .pull-left a img.animated.fadeIn {   
    width: 100%;
    height: auto;
}

```
![schermafbeelding 2017-04-03 om 19 03 40](https://cloud.githubusercontent.com/assets/6781157/24621098/9e4caa46-18a0-11e7-83da-6dc9826c3f64.PNG)

See picture.

**Comment by buddh4** [comment]
Thanks for the note, but again, the wrong repository ;) https://github.com/humhub/humhub-modules-cfiles

**Comment by martinbeek** [comment]
Again?

**Comment by acs-ferreira** [comment]
@buddh4 it would be great if issues on modules repositories were addressed ;)
They're not... :(

**Comment by Felli** [comment]
It could be possible to add this in a line on the `CONTRIBUTING.md`?

**Comment by martinbeek** [comment]
@buddh4  There are thousands of repositories on Github, so new users as i need some guidance from time to time. 
@acs-ferreira I'm not doing this on purpose; if only i knew of the existence of the repo, i'd have posted it there. 
I'm just a failry new humhub ánd github user, so my sincere apologies for being a dumbass.

**Comment by buddh4** [comment]
@martinbeek No problem, just a recommendation. It's just easier to filter for us.
@acs-ferreira Since the v1.2 isn't that time consuming anymore, we'll focus more on the modules, so if your issue is missing in the modules repository the chances are that we overlook it. So in the future please search for the module respoistory first. Note that only free modules have a public github repo.

**Comment by acs-ferreira** [comment]
Yes sure, i understand.

But some modules have PRs since 2016, non merged, but bug fixing. ;)
