### ISSUE TITLE
Anyone Attempted To Integrate HumHub with an existing site?

### ISSUE THREAD

**Issue by chodges** [humhub/humhub#2491]
The subject pretty much says it all.  I have an existing site (CRM) written in Yii2 and I'd love to able to get integrate Humhub into it.  Unfortunately HumHub seems like an all-or nothing deal.  I really want to be about add it as a component of my existing site.

Anyone ever done that and if so any recommendations?

Thanks!

**Comment by Felli** [comment]
Which CRM are you using?

**Comment by chodges** [comment]
Oh its a custom one I built in Yii2

**Comment by Felli** [comment]
Hmm... I would suggest looking at both the normal [Docs](http://docs.humhub.org/dev-README.html) & Enterprise Edition [Docs](http://docs.humhub.org/ee-README.html)

**Comment by buddh4** [comment]
What do you want to integrate, just the stream or content? The thing is, currently humhub is rather designed to integrate other software than the other way around. Unfortunately there is not rest api or something yet.

**Comment by chodges** [comment]
Ideally I want to be pull the main UI of humhub into my exiting project and have it appear as a module with my application.   

If I absolutely had to integrate my code into HumHub I could but it would be quite a bit of effort and I'd have to refactor a ton of code which I can't afford to do.

**Comment by buddh4** [comment]
The problem is that humhub has its own module system, marketplace, aligned yii components, bootstrapping, installation process, dependencies, configuration, asset management etc. so its not just a single module its a platform itself. Perhaps you could operate both applications seperately and use single sign on and/or a rest interface + custom humhub theme. (As mentioned before the rest interface has to be implemented first).
