### ISSUE TITLE
Cronjob under Windows disables users

### ISSUE THREAD

**Issue by V3R4DE** [humhub/humhub#2570]
Hello, 
i am using Windows Server with IIS on it. To execute the daily and hourly jobs, i created an .Ink to the yii.bat with the parameter cron/hourly for example and execute it. 

If i execute these .Ink, all users on humhub got disabled and i must login with the local admin to enable the users manually.

Why this happened?

Thank you for your answer!

**Comment by V3R4DE** [comment]
No idea why this happened?

**Comment by buddh4** [comment]
Are you using ldap?

**Comment by V3R4DE** [comment]
yes, we do.

**Comment by dschoty** [comment]
We have the same issue with ldap. If a User try to login with his e-mail-address and not his ldap username, after the next cronjob task this account is disabled. Sometimes this account is shown as local not as ldap.

Our Workaround:
Find the objectGUID for the user from AD/Ldap-Server and change in the Humhub Table User the guid value.
Talk to out users how to login with ldap account. (Only Username is required.)

**Comment by githubjeka** [comment]
On work my case is:
If users from ldap haven't email field or Attribute `E-Mail` is wrong in admin-ldap-options-panel after cronjob this users will be disabled.

**Comment by luke-** [comment]
The hourly cronjob automatically disables (or create) users which are not found using the "UserFilter".

Seems you have some problem in this LDAP query.

**Comment by githubjeka** [comment]
For my case everything suits me :feelsgood:

**Comment by V3R4DE** [comment]
i looked at the log and saw, that there was an error with an attribute (field type was number but required text). Now i fixed that. So that caused these error?

**Comment by V3R4DE** [comment]
damn..with correct attributes it also disables all users. Any other ideas? I think the ldap query is correct. Is this a problem of version 1.1.2?

**Comment by V3R4DE** [comment]
some suggestiones?

**Comment by luke-** [comment]
What is the number of users displayed in the LDAP configuration page (Administration -> Users -> Settings -> LDAP)?

**Comment by V3R4DE** [comment]
The message in LDAP configuration is "Status: OK! (0 Users)", so i think there is the reason.

My LDAP configuration looks like:

Hostname: server1 server2
Port: 389
Encryption: None
Username: cn=X,ou=Admins,ou=Users,ou=X,dc=X,dc=local
Password: X
Basis DN: ou=X,dc=X,dc=local
Login Filter: sAMAccountName=%s
User Filter: cn=AppGroup,ou=x,ou=Groups,ou=X,dc=X,dc=local
User Attribute: sAMAccountName

Thank you for your help!

**Comment by V3R4DE** [comment]
i found the error. The error was the missing "memberOf" part on the userfilter.

Cron works now, but there are changes done on a user in LDAP (another input on an attribut) but the changes are not refreshing in the humhub user profile.

**Comment by Buliwyfa** [comment]
Sorry to ask... but why use a link?

Since you are using a batch file already why not something like this:

Please note:
- I have added a lot of debugging so it will be easier to play with it.
- My public web folder is called 'public' (not 'www', or 'wwwroot')
- I place the batch file under a folder called cronjobs (but not always, some installation cannot create the folder)
----------------------------------------------------------------
`
cls
@ echo off

REM find current dir (current_dir)
REM --------------------------------------------------------
for %%* in (.) do set current_dir=%%~nx*


REM if current_dir = cronjobs => go 1 dir/folder down
REM --------------------------------------------------------
if "%current_dir%" == "cronjobs" CD ..



REM get Yii bath realtive to current path
REM --------------------------------------------------------
SET yii_path="%CD%\public\protected\"

REM echo.
REM echo.
REM echo current_dir = "%current_dir%"
REM echo.
REM echo yii_path = %yii_path%
REM echo.
REM echo.


CD /D %yii_path%
"C:\PHP\php-7.1.x-nts-Win32-VC14-x64\php-win.exe" yii cron/daily

`
----------------------------------------------------------------


I am asking to learn, so any tips, options or explanations will be great ;)


Thanks
