### ISSUE TITLE
Username length < 4

### ISSUE THREAD

**Issue by nico-herbig** [humhub/humhub#2572]
Why must be the length of the username at least 4 letters? We would like to use HumHub at our university but there are LDAP users which usernames are less than 4 letters, e. g. 2 letters.

Reference #1491

**Comment by Felli** [comment]
Changing
`[['username'], 'string', 'max' => 50, 'min' => Yii::$app->getModule('user')->minimumUsernameLength],`
to
`[['username'], 'string', 'max' => 50, 'min' => X],`
should be possible? `X` represents the minimum of the username that you are wanting to use [line 93](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/User.php#L93). As for why it is 4 over any other number? I would guess this is because 4 is the default fallback method.

**Comment by nico-herbig** [comment]
Thanks for your reply. In the near future, is there any option to make this value configurable over the website? Otherwise I need to override this file on every update.

Thanks

**Comment by acs-ferreira** [comment]
Just override that file permanently and it will not be override by updates.
See documentation to do this.

**Comment by nico-herbig** [comment]
@Felli and @acs-ferreira: Thanks for your hints. Now, it is working fine.

If others have the same question like me, here is my solution. 
I have added the following lines to _/protected/config/common.php_.

```
<?php

return [
    'modules' => [
	'user' => [
	    'minimumUsernameLength' => 2
	]
    ]
];
```
