### ISSUE TITLE
Allowing voices in comments, posts, emails, by a microphone

### ISSUE THREAD

**Issue by leopaula** [humhub/humhub#2590]
Voices could be inserted among texts to make the interactions more dynamical.

https://community.humhub.com/content/perma?id=107330

**Comment by gigabytedevelopersinc** [comment]
Sounds like a great idea to me!

**Comment by Felli** [comment]
I'm not really seeing any use this could do for a social media kit, possibly for a chat yes, or even integrating this into the [Mail Module](https://github.com/humhub/humhub-modules-mail) but overall doesn't seem like something that is needed...

**Comment by gigabytedevelopersinc** [comment]
Ok.. Now the point is simplified. I have to agree with Sarah, this feature
would be better if implemented in the mail module, but most preferably in a
chat because I really don't fancy the mail module. A chat with calling
feature (both audio and video) would be a lot more better. I seriously
don't know why this chat feature is taking so long for humhub to add, from
my research, cometchat can be a lot more efficient (except you guys want to
code yours from scratch)!

**Comment by Felli** [comment]
The issue with cometchat is that it is it's own software, sure a module can be created to connect the two, but the underlining problem still remains. Also to addon to this, cometchat is pretty resource heavy as mentioned before in a number of topics related to the discussion of cometchat and integrating it into HumHub, it's a nice idea, but I also don't see this being integrated, and not for free mind you. Building from scratch is never a bad thing, just means development is always in motion! :wink:

**Comment by gigabytedevelopersinc** [comment]
Sure! Building from scratch isn't a bad idea at all! But development can be
too tasking. Anyways, I except a chat feature to be ready on humhub by
version 1.3.0. Hope that's possible?

**Comment by leopaula** [comment]
Could be at least an optional for someone find that useful for a social media.

**Comment by gigabytedevelopersinc** [comment]
Of course! A chat feature for calls (both audio and video) with real-time
updates for messages is considered a very very important feature for a
social media!

**Comment by luke-** [comment]
@funkycram Thats very nice! A PR would be cool!
