### ISSUE TITLE
Make reference for content easier.

### ISSUE THREAD

**Issue by leopaula** [humhub/humhub#2610]
I think we should be able to search content by just typing the id number (108614 from https://community.humhub.com/content/perma?id=108614, for example) in the search box. It’s easier for references.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/7053.

I tried to add the column `content_fulltext.content_id` to the search match fields list, but it creates an error `Illegal mix of collations for operation 'match'`, as I got it all fields should have same collation, but the `content_fulltext.content_id` is INT. It is why I have appended it to the field `content_fulltext.contents`.

I have tested dirvers ZendLucance and Solr, they search a content by id because they already index it.
