### ISSUE TITLE
Remove index.php from url and keep only number

### ISSUE THREAD

**Issue by byndstd** [humhub/humhub#2622]
hello
my url actuel is show like that
http://mysiteexample.com/index.php?r=space%2Fspace&sguid=ec859ff5-1a0e-4e9e-b046-a605138c06f8
is it possible to make the url like example
http://mysiteexample.com/page=1a0e-4e9e-b046-a605138c06f8 
or the post id instead the numbers
 I tried with .htaccess but i faild to do that

Thank you

**Comment by buddh4** [comment]
http://docs.humhub.org/admin-installation-configuration.html#url-rewriting-optional

**Comment by byndstd** [comment]
Thank you Thank you Thank you Thank you Thank you Thank you Thank you

**Comment by harshitjawla** [comment]
Hey. This page does not exist now.
Please help me. I want my links to be customised such that my space links become like http://example.com/s/space_name
I have managed to get the links like http://example.com/index.php/s/space_name

Also Please help me so that user links would be generated as http://example.com/username OR http://example.com/u/username
As of now, I could get user links like:
http://example.com/index.php/u/username
