### ISSUE TITLE
Receive notifications for new content by default as a space setting

### ISSUE THREAD

**Issue by Clindbergh** [humhub/humhub#2652]
Currently members of a space have to explicitly change the space setting to receive notifications for new content (opt-in). Instead I suggest that users receive notifications for new content by default and have an option to not receive notifications for a particular space (opt-out). Ideally administrators of spaces could decide what the default behavior for a particular space is, that is new members receive notifications for new content by default or they do not receive notifications for new content by default.

**Comment by buddh4** [comment]
Unfortunately this currently would lead to performance issues in bigger communities, since we have to create a notification entry for each space member, if you have spaces with hundreds or thousands members this would be a performance bottleneck. In v1.2 we introduced a queuing to be able to handle such task asynchronously in the future, but currently there is no real asynchrone queue handling implemented.

**Comment by luke-** [comment]
Implemented in 1.3+ for administrators
