### ISSUE TITLE
A module broke my page.

### ISSUE THREAD

**Issue by xSynthx** [humhub/humhub#2729]
Link to module: https://github.com/GreenVolume/humhub-discordapp-module
I installed the discordapp module, and this is basically what happened:

I am using humhub version 1.2.2 and upon install of this module, my humhub just constantly shows a page that says "An internal server error occurred." I tried deleting the folder from the modules folder, and it still says ^ I cant go to my admin panel, or nothing.
I changed the correct file, but I feel like I might have changed the wrong part. You should make the 1st step more detailed, as in the file it says
```php
<iframe src="<?php Url::to(['https://discordapp.com/widget?id=', 'id' => Url::to($this->context->route)]); ?>">
    <?php $this->render($view); ?>
</iframe>
```
Are we supposed to put our id after the `widget?id=idhere` or where it says `'id'`?
I put it after the `widget?id=` the first time, and thats when the error occurred, I then put the id where it says `'id'` and it didnt fix the error.

Does someone know how I can fix this, and get my page back?

**Comment by xSynthx** [comment]
I trusted this one as it had something about @Felli making a commit.

**Comment by buddh4** [comment]
Its not an official module, please open an issue in the modules repo if no already done.

**Comment by xSynthx** [comment]
@buddh4 I just need a way to remove it, and make my page work again. I did open one on the repo.

**Comment by buddh4** [comment]
You should never just delete a module folder, since installed modules are still registered in the `module_enabled` table.

You can remove modules either in your admin interface or by running:

`php yii module/remove discordapp`

If this does not work try to remove the module_enabled query and delte all related tables of this module (if there are any)

**Comment by xSynthx** [comment]
@buddh4 Like I said, I cant even visit my admin interface. Thank you, the command fixed the issue.

**Comment by Felli** [comment]
Go into your database and remove `discordapp` from `module_enabled` manually if you don't have access or the knowledge to use command lines.

**Comment by acs-ferreira** [comment]
@buddh4 IMO, a template for issues should be created (at issue submission time) to state that Github should be used for **HumHub Core issues/bugs only**, other issues/questions/configuration/module related, should be asked on their respective repo _(if existent)_ or https://community.humhub.com

Otherwise, we take our time providing basic/hosting support here :)

**Comment by buddh4** [comment]
@acs-ferreira Yeah, I recently thought of this too, perhaps we should just use the one from yii with some additional infos ;)
