### ISSUE TITLE
Move Documentation into separate Github Repository

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub#3002]
I would like to submit the idea about create a Wiki about Humhub here in GitHub Wiki.

This would treat aspects like real administration (How to create a Space, How to change space Security settings, How to...) and this could be a real User/Admin Manual community driven, not only the basics that we can find at http://docs.humhub.org/

One example : https://github.com/firehol/netdata/wiki

Let me know if this is something interesting or not.
Cc @luke- @buddh4

**Comment by LThecross** [comment]
Hello, I find it's a good idea and I'm not against helping.
As extra topics, I would see:
- How to make the humhub instance secured (TLS, CSP...)
- Some tools to help the administration of an instance (Goaccess, Rsync...)
- Example of system requirements, to help users to choose the right VPS.
- Capitalisation of the questions found in the community website. Because I guess there are a lot of questions that are often raised and that have the same root cause.

**Comment by funkycram** [comment]
Great idea !

**Comment by buddh4** [comment]
Yes a real user/admin guide would be great, but why not adding it to the [official documentation](http://docs.humhub.org/), which is also part of the humhub project?

**Comment by danielkesselberg** [comment]
@buddh4 howto contribute to docs.humhub? i dont see them here on github :-(

**Comment by funkycram** [comment]
I think it's here : https://github.com/humhub/humhub/tree/master/protected/humhub/docs/guide

**Comment by buddh4** [comment]
https://github.com/humhub/documentation
