### ISSUE TITLE
User delete don't work

### ISSUE THREAD

**Issue by DeltaLima** [humhub/humhub#3218]
### What steps will reproduce the problem?
Create a User as Admin in the Admin Backend.
Login as created user.
Relogin as Admin, try to delte the user in the admin backend.

Message comes up "User deletion process queued." -> Nothing happens.
 
### What is the expected result?
User get deleted
### What do you get instead?
Only the message "User deletion process queued."
### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3-dev
| PHP version      | 7.0 - debian stretch repo
| Operating system | debian 9.0 64bit

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.
> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

no related errors in log

**Comment by buddh4** [comment]
There was a problem for the soft deletion, which was fixed by https://github.com/humhub/humhub/commit/4372da76ee53cfe0dc9d3d0ae80807e5c6adb6f4#diff-b7cd12c3a3221e1174d1361fa0d988cc

In case you are not using the latest master make sure your [queue](http://docs.humhub.org/beta/admin-installation-configuration.html#cronjobs-and-asynchronous-job-processing-v13) is processed.

**Comment by DeltaLima** [comment]
Thanks a lot! The Hint with the queue to the beta documentation made the trick! It's working now! :)
