### ISSUE TITLE
private setting for users profile wall, and space wall

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#327]
Make the privacy setting in user profile wall, and space wall. Who can write on your wall? like a facebook... But now, any user can post messages on the wall & space wall... The best solution is to add a configuration, who can write on the wall space & profile wall, friends? all users? or anyone...

**Comment by jakeyjdavis** [comment]
+1

**Comment by JeXawoW** [comment]
+1

**Comment by IceSweets** [comment]
+1

**Comment by mkaptein172** [comment]
I agree, I'd replace 'Following someone' with 'making friends'; this way, when 2 people are 'friends', they 'follow' each other. I think this will be less confusing from a potential user's point of view. Another thing, is to include the module 'Mail' (because private messaging is essential to any social network) but to only make possible for 'Friends' to contact each other (as well as 'notifying members').

**Comment by wannabe21** [comment]
+1

PLUS allow users to set profile fields visible to : anyone, Friends, Only Myself

**Comment by buddha87** [comment]
Is part of 1.1
