### ISSUE TITLE
Hidden Gallery popup

### ISSUE THREAD

**Issue by soappl** [humhub/humhub#3341]
When new user Logs in in to my website instantly gets a pop up with hidden Gallery and is unable to close it?

![44234912_242899639910087_6133733685515517952_n](https://user-images.githubusercontent.com/44270848/47170145-428e9700-d2fd-11e8-9017-e1627e64b000.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.3.4
| PHP version      |  7
| Operating system | Windows 10

**Comment by buddh4** [comment]
Please check for any javascript errors in your browser console, did you recently update your installation or is it a fresh install?

**Comment by Eddy271** [comment]
Hi 
I have the same problem and teh same pop up but when i try to publish a comment or a new publication

It's a fresh installation, i'm a new user of Humhub 

Version PHP 7

HumHub version | 1.3.8

In the console i have this message : 

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Thank You for help me
![humhub](https://user-images.githubusercontent.com/46261217/50547279-73614580-0c37-11e9-94e9-a1ad36ecaa57.PNG)


Eddy

**Comment by Eddy271** [comment]
Hi 

Yes it's a public site, I solved the problem in the settings of Google Chrome but I have the problem with Mozilla on the connection for the url Dashboard only in the console i have this message : 

The use of XMLHttpRequest synchronously on the main thread is deprecated because of its negative impact on the end user's navigation. See http://xhr.spec.whatwg.org/ for more information. all-3f982780da2f34ab3a227208dfd04d48.js: 31: 259
frameLoad

The url is : https://collectifcitoyenuni.com

Thank You

**Comment by GaretSD** [comment]
Hi, 
I'm sorry to re-open this issue as I don't really get why did it get close in the first place.
The Pop-up appear in Firefox only and it shows up right after logging in.

It's a fresh install of Humhub (1.3.12), it's the community version. I have PHP 7.0 and MySQL 5.6.
I'm hosted by OVH, on a shared hosted environnement, on a sub-domain.
Note that it works just fine in a localhost.

Any idea on how to get rid of it?
![screenshot](https://user-images.githubusercontent.com/49170650/55359438-1f822900-54d2-11e9-8295-b65408c4ff45.PNG)

Modifying the Browser settings won't as I want it to work for all my users,

Thanks a lot for your help

**Comment by Jut8** [comment]
Hi All, 
I'm having the same issue on Chrome... anyone know the issue?

Thank you for your help!

**Comment by GaretSD** [comment]
Hi @Jut8 ,
I solved the problem by switching to PHP 5.6, but it seems PHP 7.2 works as well,

Try it and us know how that work !

**Comment by docisit** [comment]
I have the same issue.  I also have a warning about the PWA manifest needs Web_Form set to wide added.  But, the depriecated warning is what worries me.  I see no answer from the above questions.  Did anyone solve this yet.

affectted 
humhub-app.js:1

Refers me to:
https://xhr.spec.whatwg.org/

This must me a function for showing images, or something important.  Or, it would have been answered. But, it worries me.  It is a opening which an attacker can use, to do damage to my visitors.  How can this be fixed?

**Comment by marc-farre** [comment]
@docisit  can you confirm that the domain has an SSL certificate? The URL must start with https://.
Have you made specific CORS settings in the protected/config/web.php file?

**Comment by docisit** [comment]
Yes sir. You can close it here. 
  No sir, I did not make any change. The code is too sophisticated for me to touch. I only follow the instructions that have been given. 
     You guys are awesome and thanks for prompt replies. Humhub should be everyone’s choice for Social Media Communities, for their teams and organizations. Far better than Drupal. Well, it’s good too. But, not set up as well as Humhub. I tried humzilla, as well. And a couple others. Sorry for being long winded.  Again, you can close it here.
