### ISSUE TITLE
[Enhancement] My fast test, and my opinion what to improve

### ISSUE THREAD

**Issue by amaroc** [humhub/humhub#3383]
1. Design - make more cleaner design like VK, even old version vkontakte.ru (like old facebook) (optional).
2. You cant make post just by ENTER, you need click it by mouse. You cant post it even with Shift+Enter. Try how it works on Vk. Need same.
3. I dont see functional of private messages + it would be nice to have some encription on it.
4. Too slow notification, it`s not instant, as i see its need 30-1 min to give notification for user.
5. You can upload  video, but you cant look this video on site.
6. You cant insert just link on image, from internet, it would be like link, but need to appear image. Look how it work in VK.com

Thanks and sorry for my english

**Comment by Felli** [comment]
1. HumHub gives users the option to create their own custom themes with view overwrites.
2. `Tab + Enter` is used in HumHub for Windows users.
3. HumHub has the mail module which is used for private and/or group messages
4. The notifications system has its problems, but as all other software do, some servers can handle the notifications better than others.
5. I'm not sure what you mean about this, HumHub has a built-in video player that plays videos.
6. I'm not exactly sure what you mean by this one, at the moment HumHub supports most Markdown syntax which includes `![](http://domain.com/image.png)`, if you mean pop out images, HumHub has a gallery module that could be used, please provide more information.

> In the future please use the [Feature Request](https://community.humhub.com/s/feature-requests/) space in the [community site](https://community.humhub.com) for personal opinions or general questions. :wink:

**Comment by amaroc** [comment]
> 5. I'm not sure what you mean about this, HumHub has a built-in video player that plays videos.

I tried upload video but it attaches like file, i cant watch video from site.
> 2. `Tab + Enter` is used in HumHub for Windows users.
Why this? Wich big service use it? I think 1%, Enter better, Shift+Enter better. You can give opportunity make new line by Shift Enter, and Enter for publish post.
> 6. I'm not exactly sure what you mean by this one, at the moment HumHub supports most Markdown syntax which includes `![](http://domain.com/image.png)`, if you mean pop out images, HumHub has a gallery module that could be used, please provide more information.
>
I meant that on the VK.com site, you can insert a link to the image in post, from the Internet: http://aa.kom/img.jpg and this link is automatically converted to the image added to the post.

**Comment by Felli** [comment]
HumHub supports oembed posts, so if an image service supports this as well then all you'd have to do is use the right endpoints with the image link, HumHub also has a premium module called [Linkpreview](https://www.humhub.org/en/marketplace/details?id=23) just for reference.

**Comment by buddh4** [comment]
Appreciate your feedback!

1, The design its definetly enhancable especially regarding responsiveness, perhaps have a look at the enterprise theme, perhaps its more appealing. I don't know vkontakte.ru, but from a quick google image searches I can't detect any big ui enhancements (but I assume those images are rather old).

2, `Tab + Enter` is not the recommended way of submitting, it just works for posts because you focus the submit button. The should be included in the richtext, and was discussed before, should not be that hard to implement.

3, Which kind of private do you mean? Private profile posts? When posting private posts "without friendsihp mode enabled" the posts should only be visible by yourself, but with friendship enabled your friends can see private posts.

4, By default notifications are sent out by `queue/run` cron, so it depends how often your cron is running, should definetly be faster than 30 Min if configured correctly. It should also be possible to configure a redis backend, with websocket support, but this is currently in experimental state. Older HumHub versions sent out notifications imediatly, but in order to enable long running and more complex tasks we now use queues.

5, You should be able to upload mp4 and ogg (currently only as post attachment and not within the richtext). But you can embed oembed to the richtext.

6, Don't really understand this point, but you should be able to wrap images into an link in the richtext?

**Comment by Felli** [comment]
@buddh4 I believe he means image link converting to image view on link drop-in or post send. :thinking:
