### ISSUE TITLE
Content Detail View / Single Content View

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3442]
A single entry stream should rather look like a discussion/issue style.

- Default content detail view (Permalink)
- Different layout
- Without "Read More"
- Render all comments
- Perhaps add #3988 content log feature

E.g.:

- [Discourse](https://discuss.prosemirror.net/t/make-only-part-of-a-nodeview-draggable/1145)
- [Github](https://github.com/humhub/humhub/issues/3412)

**Comment by Ace2213** [comment]
I'm not really into the Github UI. It works. It's nothing special. But I'm a big fan of the side timeline in the Discourse UI:

![image](https://user-images.githubusercontent.com/12226710/70049192-e4794d80-15aa-11ea-9ce1-e25a1350d781.png)


But in general their UI is very heavily padded, making it take up too much visual space for every post.

The info bar is the opposite. Extremely crowded and cramped:
![image](https://user-images.githubusercontent.com/12226710/70049304-286c5280-15ab-11ea-910a-6c04786f0a24.png)

The only useful additional information there is the images of the participants/commentors, which can be integrated in a nicer way within the timeline.

In comparison, I prefer the current stream entry layout in these regards, but I would like it if the timeline was brought over and enhanced with user images.

**Comment by luke-** [comment]
+ Without "Read moe"

**Comment by luke-** [comment]
Reddit is also a good example

**Comment by buddh4** [comment]
The question is should we really render all comments or rather an auto scroller comment section like youtube.

**Comment by luke-** [comment]
Rendering all at once is not an option. 

I think the auto scroll is nice, pagination is somehow old style.

**Comment by luke-** [comment]
@yurabakhtin I have already created a PR for this. We should use in this post view, a very high limit of displayed comments and no ReadMore. 

PR: https://github.com/humhub/humhub/pull/5462

**Comment by luke-** [comment]
Related: https://github.com/humhub/humhub/issues/3574

**Comment by yurabakhtin** [comment]
@luke- 

> and no ReadMore.

Commit https://github.com/humhub/humhub/pull/5462/commits/15fdec7c12ddd0bc7b2396767cd8deef3e42926d

> a very high limit of displayed comments

Sorry, not clear what to do here, probably you mean your previous comment:

> Rendering all at once is not an option.
>
> I think the auto scroll is nice, pagination is somehow old style.

As I got it we should implement the loading of next comments portion/page on scroll down like we have on stream view for content records.
Ok, but please note currently we have the input field "Write a new comment..." at the bottom, i.e. on scroll down user will can create a new comment only after scrolling to the last page. so I suggest to move the input field on the top.
However it may be confused for users because currently we sort comments from oldest to newest, now on load page we display 2 latest/newest comments ordered by date ASC, but if we want to load comments on scroll down we should:

- either change comments ordering to `date DESC`, i.e. newest/latest comment will be on top
- or on page loading - display 2 first comments and then on scroll down load newer comments, i.e. users will see the newest comments only on the last page that I think is not good, so I think we should change comments ordering firstly, do you agree?

**Comment by luke-** [comment]
@yurabakhtin 

- Very High Comment Limit: Instead of showing only ~3 comments from the beginning, maybe we should show 20-30 comments. The limit here should be flexibly configurable. (Comment Module Attributes)

- I would not implement auto reload/endless scroll of comments. Just as described before instead of 3 just 25. Maybe when you click on "Comment" it might be possible to jump to the input field. What do you think?

**Comment by yurabakhtin** [comment]
@luke- 

> The limit here should be flexibly configurable. (Comment Module Attributes)

Do you tell about these module attributes https://github.com/humhub/humhub/blob/enh/post-view/protected/humhub/modules/comment/Module.php#L20-L30:

```php
    /**
     * Maximum comments to load at once
     *
     * @var int
     */
    public $commentsBlockLoadSize = 10;

    /**
     * @var int maximum comments to show initially
     */
    public $commentsPreviewMax = 2;
```

If yes, should we just change them right here to new values `25`?
Or should we allow to customize them only from the post view side when we call `StreamEntryWidget::renderStreamEntry($post)`?

---

> - I would not implement auto reload/endless scroll of comments. Just as described before instead of 3 just 25. Maybe when you click on "Comment" it might be possible to jump to the input field. What do you think?

Ok, we don't the scroll feature to load next comments page.
But I don't understand what "Comment" you mean here, where is it? and why we need the jump if we will not implement the page loading on scroll event, so it will be possible to scroll to the new comment input with normal mode without any problem?

**Comment by luke-** [comment]
@yurabakhtin 
- Instead of showing 3 comments directly 25 should only apply to post view page and we to extend this for all `VIEW_CONTEXT_DETAIL`  in several places. e.g. Wiki pages.

- What I mean with "scroll to the new comment input" is related to this issue: https://github.com/humhub/humhub/issues/5417
But leave this as it is for now. We address this issue later...

**Comment by yurabakhtin** [comment]
@luke- 

> - Instead of showing 3 comments directly 25 should only apply to post view page and we to extend this for all `VIEW_CONTEXT_DETAIL` in several places. e.g. Wiki pages.

Commit https://github.com/humhub/humhub/pull/5462/commits/c6bd2168c836ae9c924020e07920b85d9c014c44

> e.g. Wiki pages.

In order to implement this on wiki module side we should modify the code from here https://github.com/humhub/wiki/blob/master/views/page/view.php#L43:

```php
<?= Comments::widget(['object' => $page]); ?>
```

to code like this:

```php
<?= Comments::widget([
    'object' => $page,
    'renderOptions' => new StreamEntryOptions(['viewContext' => WallStreamEntryOptions::VIEW_CONTEXT_DETAIL])
]); ?>
```

**Comment by luke-** [comment]
@yurabakhtin What do you think about adding a variable `$viewMode` directly in the `Comments` widget? That would be a bit easier to set:

e.g. `Comments::widget(['object' => $post, 'viewMode' => Comments::VIEW_MODE_COMPACT]);` or `Comments::widget(['object' => $post, 'viewMode' => Comments::VIEW_MODE_FULL]);`

**Comment by yurabakhtin** [comment]
@luke- Ok, commit https://github.com/humhub/humhub/pull/5462/commits/8b856d28b293f1bddf22cc929eee6b28bd7d6541.
