### ISSUE TITLE
Hide email addresses in spaces

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub#3628]
For large spaces like communities that do not work together, it's unnecessary to have their email addresses exposed in the member list. Even if it's only to the administrators and moderators of the space. After all, any member can create a space.

**Comment by luke-** [comment]
Can you please describe in more detail where email addresses are exposed?

**Comment by luke-** [comment]
Looks like some users will then use their email address as username.

In the upcoming  of HumHub 1.4 the text under the display name (e.g. first name surname) will be better configurable and more uniform.

Otherwise, the current e-mail address should only be displayed in the administration area.

Regarding the directory, such a limitation is currently not supported, e.g. because of the search, user picker & Co. 

However, we are considering a feature in which the user only sees members with whom he is connected (e.g. through spaces).

**Comment by Ace2213** [comment]
That would be great. Through spaces and friendship.

For the time being, is it possible to simply hide the user page in the directory? I mean the front-end access to it.

**Comment by luke-** [comment]
There is currently no option for this. This would only be possible via an own module.
