### ISSUE TITLE
Default oembed styles

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3755]
We should assamble default styles for common oembed in

https://github.com/humhub/humhub/blob/v1.4.0-beta.1/static/less/oembed.less

The problem is that the current default style works for oembeds with iframes as for example youtube, but others as twitter do not require that much padding and look a bit broken.

In 1.4 we can add styles like:

```
.oembed_snippet[data-oembed-provider="twitter.com"] {
    ...
}
```

Since css does not support selectors as "parent with iframe as a child" we my should assamble some styles for common oembed providers, which are broken by the default oembed style.

**Comment by skyfall96** [comment]
good

**Comment by marc-farre** [comment]
Problem reported here too for Tweeter: https://community.humhub.com/content/perma?id=271258

Cause:
![image](https://github.com/humhub/humhub/assets/23310825/aadcb33b-9edb-453e-a88f-e1172d24876a)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/6581.

The issue was there because before this change https://github.com/humhub/humhub/pull/5510/files#diff-92626c7134955d75fc3b3f576a367e9b63de9eb93608aaa8edcb34a933558a2aR365 oembed wrapper had a html like this `<div data-oembed-provider="twitter.com">` and the CSS worked well for twitter posts.
But then after the change it became as `<div data-oembed-provider="https://publish.twitter.com/oembed?url=%url%&maxwidth=450">`, that's wrong, no need to keep the data there.

I have fixed to keep there only provider name like `<div data-oembed-provider="Twitter">`.
However a rendered html is stored in db table `url_oembed`, so it is why we should have CSS for old cached as `[data-oembed-provider*="twitter.com"]` and for new `[data-oembed-provider="Twitter"]`.
