### ISSUE TITLE
SAML support

### ISSUE THREAD

**Issue by kbabioch** [humhub/humhub#3776]
### Is your feature request related to a problem? Please describe.

For professional / enterprise environments single sign-on capabilities are a must-have feature. In a lot of environments SAML is the prevalent standard (vs. OpenID Connect), so having this feature is important for deployments in large-scale organizations.

### Describe the solution you'd like

From some initial research, there seem to be at least two options:

- [yii2-saml](https://github.com/asasmoyo/yii2-saml), which is a ready-to-use for yii2
- Use [SimpleSAMLphp](https://simplesamlphp.org/) as library

This feature needs also a proper administration interface (IdP metadata, certificates, etc. pp.) and options for key rollovers.

**Comment by ArchBlood** [comment]
At the moment HumHub's enterprise edition already supports JWT and adding SAML wouldn't be that hard, so I could see this as another module idea.

**Comment by buddh4** [comment]
https://www.humhub.com/de/marketplace/saml-sso/

**Comment by lisandi** [comment]
Only available for Professional edition which is a real drawback to promote HumHub as i.e. applications like WordPress, Moodle, Mahara etc provide Saml support already and many customers can't afford simply 99Euro/monthand much more in bigger communities only because they would need SAML. This fact is actually helping to make the gap between the rich and the poor even bigger which is a pity, so I suggest to consider to make SAML authentication available in the Community edition and reaching out to many more potential than professional clients which started with the community edition and than need custom developments etc would be a better move - OR we would need to develop based on yii2-saml and using like wp and others the already mentioned SimpleSAMLphp to more or less "reinvent" an already existing feature of humhub, which than even would have to be available for all users of the app according to AGPL. It simply does not make sense to reinvent! Without it humhub in its community edition could not be used without an own programmed or that bought SAML with the following apps and more:

https://wordpress.org/plugins/miniorange-saml-20-single-sign-on/
https://moodle.org/plugins/auth_saml2
https://wiki.mahara.org/wiki/Plugins/Auth/Saml
https://github.com/marketplace/actions/get-saml-identity-action
https://support.google.com/a/answer/6087519?hl=en
https://github.com/lawrencepit/ruby-saml-idp
https://github.com/asasmoyo/yii2-saml
..
etc in other words it is sad that the fact that this very popular authentication method which on the other hand is implemented pretty simple via the mentioned already existing yii2-saml is not a core part of the community edition. Please consider to make an impact by releasing it for the community edition. Thanks

**Comment by ArchBlood** [comment]
> Only available for Professional edition which is a real drawback to promote HumHub as i.e. applications like WordPress, Moodle, Mahara etc provide Saml support already and many customers can't afford simply 99Euro/monthand much more in bigger communities only because they would need SAML. This fact is actually helping to make the gap between the rich and the poor even bigger which is a pity, so I suggest to consider to make SAML authentication available in the Community edition and reaching out to many more potential than professional clients which started with the community edition and than need custom developments etc would be a better move - OR we would need to develop based on yii2-saml and using like wp and others the already mentioned SimpleSAMLphp to more or less "reinvent" an already existing feature of humhub, which than even would have to be available for all users of the app according to AGPL. It simply does not make sense to reinvent! Without it humhub in its community edition could not be used without an own programmed or that bought SAML with the following apps and more:
> 
> https://wordpress.org/plugins/miniorange-saml-20-single-sign-on/
> https://moodle.org/plugins/auth_saml2
> https://wiki.mahara.org/wiki/Plugins/Auth/Saml
> https://github.com/marketplace/actions/get-saml-identity-action
> https://support.google.com/a/answer/6087519?hl=en
> https://github.com/lawrencepit/ruby-saml-idp
> https://github.com/asasmoyo/yii2-saml
> ..
> etc in other words it is sad that the fact that this very popular authentication method which on the other hand is implemented pretty simple via the mentioned already existing yii2-saml is not a core part of the community edition. Please consider to make an impact by releasing it for the community edition. Thanks

I can agree and disagree with you, SAML is a good opportunity for growth for those seeking federated networking and SaaS solutions, but I can't say that it should be given freely, currently, those using HumHub's hosting platform "free" or "paid" have access to using this module and many other "paid" modules for free, overall the SAML solution by HumHub promotes rather well from a business standpoint even for 99€ it's rather cheap compared to many other platforms out there that force you to pay separate charges

The only other solution to your problem would be hiring someone to build you a single module which would probably still cost you an arm and a leg for, much more than an already hosted platform + all modules with said plan, of course, you could also try self-hosted but it would be smarter to just host with HumHub in this regard

**Comment by lisandi** [comment]
@ArchBlood We are a web agency which could do that development actually in-house, so that would not be a problem at all and as it has to be AGPL it than would be available probably afterwards for everybody who has access to our sites. The same actually applies to stuff like categories or translation manager which are already modules in yii and mostly their functionality and spec is not clearly specified - so it is not clear if it would even fit the needs here. If there are really new modules which don't exist in yii and which would really enhance the framework too your argumentation would be right. The point is that we develop applications for organizations - mostly communities and schools which simply can't afford such prices - we are not located in a rich country with high salaries nor do we have or the organizations have high income ourselves - actually right now most of them suffer because of the travel restrictions. When you say it is cheap 99 Euro I totally disagree as with all the above mentioned platforms it is entirely free. It simply does not make sense to reinvent wheels but if that is the only way we simply have to go that way. 95% of the module is already ready to use and provided by the yii2 framework and simpleSAML.php and there are already other auth modules available for humhub as an orientation. It simply does not make sense to hide stuff which actually could bring way more customers when it would be simply available and more and more people would start using humhub as their base. The fact that SAML as a major auth method is missing - actually only available for 99 Euro (if you have only 50 users!!!) makes argumenting to use HumHub much more difficult as all other applications communicate already via SAML - unfortunately one school alone here has already more than 5000 - 6000  students and we have several of those here alone on the island(Province)- as mentioned it sums up in "users" and financial areas which are complete unaffordable for those schools and providers i.e. government institutions. Besides that they rather use their own local developers if they really like the app and create clones in more or less no time - and I guess that is not the purpose. Your argumentation is only valid ie. Germany where schools have big budgets and are way smaller than ours here. And I know that the need actually is also there for Germany by the way - simply check out all those clubs and churches and ... and they haven't got the budgets either but have fast much more than only 50 users. I would really overthink that strategy to block the success of HumHub worldwide by not providing stuff which actually already exists in yii2 framework and what can very easily be integrated to HumHub SAML, Translation Manager, Categories, SEO and much more - it simply does not make sense to reinvent wheels but if that is the only way well that they for sure will get reinvented. Sad but true.
A SAML Module could be like the forum a one time fee - as there are simply no big changes in coming years in such a module and the same applies to the others I mentioned already. i.e. 20 USD for SAML 40 USD for the Translation manager and 30 USD for the categories for spaces and users would be amounts people would simply buy the apps rather then reinventing wheels but for any higher prices and especially monthly prices they would for sure go the in-house or "Asian" way let's say it like that and reinvent theirs and perhaps than even sell that for those prices to finance their development.

**Comment by luke-** [comment]
@lisandi We are aware of the situation regarding the SAML module. We may change this in the future, but there are no concrete plans yet.
