### ISSUE TITLE
Run travis tests with active url rewriting

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#3824]
Run travis tests with active url-rewriting, since it is more error prone.

**Comment by yurabakhtin** [comment]
@luke- I have found a solution to enable the active url rewriting for acceptance tests in commit https://github.com/humhub/humhub/pull/5159/commits/714b87fdb6457ff25748e5c680f370e674a97cd4

In previous version URLs on acceptance tests were like `/index-test.php?r=dashboard/dashboard`, but not URLs are like `/dashboard` which are processed by `.htaccess` file.
Please review I decided to use a condition `strpos($_SERVER['HTTP_SEC_CH_UA'], 'Chromium') !== false)` as flag that is a test run. Locally almost all tests work for me, however we need to check all tests and fix URLs like this my commit https://github.com/humhub/humhub/pull/5159/commits/95e65f708f1b640ffcc748ed309948be9fd4a4aa, but on github testing https://github.com/humhub/humhub/runs/3017081217?check_suite_focus=true all acceptance tests are broken, I guess because there is not file `.htaccess`, do you know how to create it there, maybe it should be created by `.github/workflows/php-test.yml` or somehow manually?

**Comment by yurabakhtin** [comment]
@luke- I asked above:

> do you know how to create it there, maybe it should be created by `.github/workflows/php-test.yml` or somehow manually?

I added the command `cp .htaccess.dist .htaccess` https://github.com/humhub/humhub/pull/5159/commits/55c580484627e7f80abd0142699c99223641d442 but it(https://github.com/humhub/humhub/runs/3017623695?check_suite_focus=true#step:13:2) didn't help to run acceptance tests.

**Comment by luke-** [comment]
@yurabakhtin  I think a ".htaccess" should not be used in the tests, because not always a web server (and also Apache) is used & running.  Normally all automated tests should using the PHP BuildIn Webserver which doesn't support "htaccess" files.
https://stackoverflow.com/questions/27381520/php-built-in-server-and-htaccess-mod-rewrites

We may somehow integrate the router script from SO into the "index-test.php".

What do you think?

**Comment by luke-** [comment]
@yurabakhtin I just tried it too and the ".htaccess" is not used on my machine.

However, according to documentation, the built-in PHP web server has similar behavior as the ".htaccess". 

"If a URI request does not specify a file, then either index.php or index.html in the given directory are returned. If neither file exists, the lookup for index.php and index.html will be continued in the parent directory and so on until one is found or the document root has been reached. If an index.php or index.html is found, it is returned and $_SERVER['PATH_INFO'] is set to the trailing part of the URI. Otherwise a 404 response code is returned." https://www.php.net/manual/en/features.commandline.webserver.php

For us, the ideal behavior would be to specify "index-test.php" instead of "index.php". But at first view this is not possible and you can only specify a full router script, which then takes over all requests.

**Comment by yurabakhtin** [comment]
@luke- Thank you for the advice about the specifying "index-test.php" instead of "index.php", I applied this here https://github.com/humhub/humhub/pull/5159/commits/1ba8329e6dd8f8a151f9d44826826972f046a5d1#diff-acf3e0c6c881e3230ee20ea7499891845048d94362e17e496f06dafa7757f110R111 and now all core acceptance tests works correctly, so we can merge the PR https://github.com/humhub/humhub/pull/5159. Probably some tests of external modules will be broken but we can fix them later.

**Comment by luke-** [comment]
@yurabakhtin ok great. can you now add some url related tests here? https://github.com/humhub/humhub/pull/5152/files/46bc773f521027def31accbfc961a850f6f34f49..5f157243e88e837cf97d0693f112e44334a1a231

Thanks!

**Comment by yurabakhtin** [comment]
@luke- Please note we should update doc page here https://docs.humhub.org/docs/develop/testing#run-acceptance-tests to new `php -S localhost:8080 index-test.php`, also I forgot to update the line `https://github.com/humhub/humhub/blob/develop/Gruntfile.js#L39` and fixed this now in new PR https://github.com/humhub/humhub/pull/5161.

**Comment by yurabakhtin** [comment]
@luke- 

> can you now add some url related tests here?

Commit https://github.com/humhub/humhub/pull/5152/commits/aac7e2a26f05b58a1d2afa3ec39cffb26970ac5e.

**Comment by yurabakhtin** [comment]
@luke- I wrote above:

> Probably some tests of external modules will be broken but we can fix them later.

Now I see all acceptance tests on `develop` branch are broken for example here https://github.com/humhub/wiki/runs/3030102286?check_suite_focus=true. It is because we should update the command "Run test server" to `php --server 127.0.0.1:8080 index-test.php` in files `php-test.yml` of all external modules, but problem in that we need this only for tests run on `develop` branch, but for `master` branch we should keep current command without ` index-test.php`, but I don't know how to configure the yml file to separate the command depending on branch, so probably we should test external modules only on single branch while `master` is not synced with `develop`.

**Comment by luke-** [comment]
@yurabakhtin Hmm, good question how we can handle such situations best. I see following possibilties:

- Make the commit (if only concerning tests) directly in the `Master` & `Develop` branch and directly adjust the module files asap.

- Disable fail-fast option https://github.com/humhub/wiki/pull/191/checks?check_run_id=3030887772

- Somehow allow the "Develop" Branch to fail OR create different Workflow Tests for Master / Develop Branch 

What do you think?

**Comment by yurabakhtin** [comment]
@luke- Please review my solution in PR https://github.com/humhub/wiki/pull/192

If you don't like to see two steps with same name "Run test server" I can try to use a way from here https://github.community/t/if-else-in-github-workflow/139460/2, for our case it maybe like this:

```
- name: Run test server
  run: |
    if ${{ matrix.humhub-ref == 'develop' }} then
      php --server 127.0.0.1:8080 index-test.php &>/tmp/phpserver.log &
    else
      php --server 127.0.0.1:8080 &>/tmp/phpserver.log &
    fi
```

or

```
- name: Run test server
  run: php --server 127.0.0.1:8080 ${{ matrix.humhub-ref == 'develop' && 'index-test.php' || ''}} &>/tmp/phpserver.log &
```

I didn't try the 2 ways so we should check it in order to be sure.

**Comment by luke-** [comment]
@yurabakhtin It is planned to merge the Develop Branch to Master in about a week. Then we need to revert all the module changes again or?

Cool would be a solution where the change is automatically detected.

E.g. (Untested Example)
```
if cat /humhubcore/.github/workflows/php-test.yml | grep -q ":8080 index-test.php"
    // New way
else
   // old way
fi
```

**Comment by yurabakhtin** [comment]
@luke- Yes, your solution is better and works well https://github.com/humhub/wiki/runs/3045244787?check_suite_focus=true#step:22:2.
Should I do this fix for all modules now?

**Comment by luke-** [comment]
@yurabakhtin Yes, would be great if you can add this to all modules. A small comment about the If condition would be quite good, that it is only temporary.

**Comment by yurabakhtin** [comment]
@luke- 

> A small comment about the If condition would be quite good, that it is only temporary.

Commit https://github.com/humhub/wiki/pull/192/commits/8b4c962066c4d996dcbc58984c840e8af467b0d0

**Comment by yurabakhtin** [comment]
@luke- 

> Yes, would be great if you can add this to all modules.

- https://github.com/humhub-contrib/birthday/pull/30
- ...

**Comment by luke-** [comment]
@yurabakhtin Maybe the page will help. Would be cool if we could somehow trigger a re-run tests for all modules.
Unfortunately, the page can only display public modules. 

https://community.humhub.com/s/contribution-core-development/wiki/page/view?title=Module+Test+Overview

**Comment by luke-** [comment]
@yurabakhtin can you please take a look into these tests:
https://github.com/humhub/custom-pages/runs/3056091585?check_suite_focus=true

**Comment by yurabakhtin** [comment]
@luke- 

> can you please take a look into these tests:
https://github.com/humhub/custom-pages/runs/3056091585?check_suite_focus=true

Fixed in PR https://github.com/humhub/custom-pages/pull/190

**Comment by yurabakhtin** [comment]
@luke- I create new file `php-test.yml` in PR https://github.com/humhub/humhub-modules-external-users/pull/9, but tests are not executed there, do you know why?

**Comment by yurabakhtin** [comment]
@luke- I updated all modules with tests, full list is here https://github.com/humhub/humhub/issues/3824#issuecomment-878904489, but I cannot fix a functional test of the latest module in the list yet.

**Comment by luke-** [comment]
@yurabakhtin Awesome, thank you for the good work!
