### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by marlonbjj** [humhub/humhub#3861]
What is this warning?
`Deleted inconsistent notification with id 40408. Invalid base model found for notification
`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4
| PHP version      |  7.4

**Comment by luke-** [comment]
It looks like there are still notifications in the database from a module which no longer exists (e.g. uninstalled).

However, I have added more details to the error message. 
With the next version and should the errors occur more often we will be able to debug it better.

But otherwise the warning should have no further effect.
