### ISSUE TITLE
Show a message if a user tries to see a private content in a space where he is not member

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#3980]
### Is your feature request related to a problem? Please describe.

Create public space.
In this space, create a private content.
Tag a **non** member of this space or send him the permalink of this private content.

The user, as he is not member of this space, when he goes to the link, ha as a blank stream :
![image](https://user-images.githubusercontent.com/23310825/78879788-adcdab00-7a54-11ea-8d13-33626c3551ce.png)

### Describe the solution you'd like

Add a message explaining why he cannot see the content and what he can do (ask space membership, ...).

**Comment by buddh4** [comment]
Perhaps, just intercept the single entry stream request and redirect to 403 error page in such cases maybe with specific a message in a first version? I hope we'll rework the single entry view as suggested in https://github.com/humhub/humhub/issues/3442 where we'll have a dedicated view/controller to handle such cases.

Another solution would be to return a dummy stream entry with an info message.

**Comment by luke-** [comment]
On Facebook I have sometimes seen such a dummy (Content not found or no permission) timeline entry.

**Comment by acheype** [comment]
> On Facebook I have sometimes seen such a dummy (Content not found or no permission) timeline entry.

Yes, on the FB timeline, it's often when you don't have access to the post (per exemple, a share of a private group post).

Concerning this issue, I can confirm users don't understand when they arrive to a blank screen as above, and they don't see the top right button.
A fix could be to display a message like "You can't see this content because you don't have access to this space". Then, as the case may be :

- offer to join the space and show the appropriate button below
- offer to apply to join the space and show the appropriate button below
- offer nothing more

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/4370 Could be also handled by the About Message (e.g. using Alert)

**Comment by funkycram** [comment]
If https://github.com/humhub/humhub/issues/4370 fixes this issues it can be closed
