### ISSUE TITLE
Force Password Change

### ISSUE THREAD

**Issue by Ockenheimer** [humhub/humhub#3996]
### Is your feature request related to a problem? Please describe.

When adding new users, you are able to set a password. These pw are active and given to the user. 
The user itself dont have to change the password. 
When setting up Humhub in a company without LDAP (we are using humhub as a social network in a kindergarden), we have to add mayn users and must provide each an easy to remember but unique password.

### Describe the solution you'd like
When adding a user, it would help to mark the password as deprecated, so that the user is forced to change the password on the first login.

### Describe alternatives you've considered
the alternative would be, to generate passwords via a pw-manager, which is not provided in our environment. Setting up all users with the same password without changing it, would be a huge security-problem.

**Comment by yurabakhtin** [comment]
@luke- Please confirm it should be implemented like this scheme:

<img width="1151" alt="force_password" src="https://user-images.githubusercontent.com/6995524/97959179-d4bc4780-1dbf-11eb-86a3-60d97f1b04d2.png">

> We should add a flag maybe in the "contentcontainer_settings" of the user.

I see the db table `contentcontainer_setting` contains settings per module and per some container, as I understand there we can keep some custom settings per User from the module `user`, right?
If yes, do you mean to store there new flag for the checkbox "[√] Force to change this password on first log in" instead of extend db tables like `user` or `user_password`?

**Comment by luke-** [comment]
@yurabakhtin Yes, but I would use this layout: (When Guest Access is disabled at: Administration -> User -> Settings -> Allow limited access for non-authenticated users (guests)")

![image](https://user-images.githubusercontent.com/4736168/97967230-3c24c800-1dbd-11eb-8b30-591c9cac94d2.png)

Regarding Settings something like:

```php
/** @var Module $module */
$module = Yii::$app->getModule('user');
$module->settings->user()->set('mustChangePassword', true);
```

**Comment by yurabakhtin** [comment]
@luke- Please review the PR https://github.com/humhub/humhub/pull/4602.
<img width="951" alt="test_force_pwd" src="https://user-images.githubusercontent.com/6995524/98273488-620bc180-1fa3-11eb-95df-8f7bbf213ecf.png">
