### ISSUE TITLE
Remember richtext state (backup)

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4133]
We should cache the richtext content to prevent loosing the content e.g. when accidentaly closing the tab or leaving the page. For this we need a way to identify the richtext context, for example:

- Create new Post
- Create new Comment on content xy
- Edit content xy
- Mail message in message group xy

We could facilitate the current richtext `context.id`.

**Comment by yurabakhtin** [comment]
@luke- Should we store the content in sessions or in database?

- Sessions: the content will be lost after closing browser, i.e. it will works only for closing tab.
- Database: we could store it per current user e.g. in the table `contentcontainer_setting`, but then we don't have this feature for anonymous users, and probably it is ok, because I don't know where they may post some data. But this way will increase the database.

What way do you prefer?

**Comment by luke-** [comment]
@yurabakhtin I would just store it in the browser locale storage? We could then add a flag in the Richtext Editor JS (saveStatebyId=true/false).

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5242, how it works:

- Each 3 seconds(`AbstractRichTextEditor::backupInterval = 3`) a content is backuped by AJAX request in Sessions; the AJAX request is called only when content was really changed.
- It works only for editors with specified ID, like this `RichTextField::widget(['id' => 'contentForm_message'...`, because if ID is not defined then it is generated randomly on each page reloading, so we cannot know ID on previous page.
- It works only for new creating objects, i.e. a backuped content is restored only for forms with empty content, because I am not sure how it will be correct if we will display a restored content if user expects to see an actual content. I think it may be implemented with one of these solutions:
  - Add new menu option "Edit lost content" right under "Edit"
  - Add a small button/link under content with text like "Restore lost content"

The menu option or button/link will appears only when content was really backuped.
I think the small button/link under content will looks better then increasing menu, do you agree?

**Comment by luke-** [comment]
@yurabakhtin Is there a reason why we don't save it to the browser's LocalStroage via javascript? That sounds somehow more elegant to me.

**Comment by yurabakhtin** [comment]
@luke- Ok, I have redone this in commit https://github.com/humhub/humhub/pull/5242/commits/e1a6954d749b0dac6b8152855da8fead296671f2.

**Comment by luke-** [comment]
@yurabakhtin Looks good! What is needed to enable the feature e.g. in the comment field or is that already by default?

**Comment by ArchBlood** [comment]
> @yurabakhtin Looks good! What is needed to enable the feature e.g. in the comment field or is that already by default?

I think it should be enabled by default to be honest with a similar dropdown as the `Dashboard` and other functions from the Basic Settings

**Comment by luke-** [comment]
@ArchBlood I have seen something with random IDs. if that is so, a default saving at least with random IDs is unfortunately not possible.

**Comment by ArchBlood** [comment]
> @ArchBlood I have seen something with random IDs. if that is so, a default saving at least with random IDs is unfortunately not possible.

Hmm, could token-generated and stored as JSON options not be possible? I think it should do in such cases then classify a time when the JSON is deleted or updated, although I don't think it would be possible in custom modules that use the RichText editor without a deeper integration 🤔

**Comment by yurabakhtin** [comment]
@luke- 

> What is needed to enable the feature e.g. in the comment field or is that already by default?

It is enabled by default. But it works only for textareas with defined id as I wrote above in the comment https://github.com/humhub/humhub/issues/4133#issuecomment-898416694.

**Comment by luke-** [comment]
@yurabakhtin  Ok thanks I see, was just a little confused about the comment in the PR code, now I got it :-)

Can you please add that with the backup, that an ID must be set, somewhere in the class header doc comment? It is otherwise later difficult to find out what is needed here.

**Comment by yurabakhtin** [comment]
@luke- I added a doc comment in the commit https://github.com/humhub/humhub/pull/5242/commits/cc5426dc436160d4243a7357c6ae467a7fd0240e.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
