### ISSUE TITLE
Remove or increase pinned post limit

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4194]
Currently you can only pin up to two post per space. This limit was introduced due to the old stream logic and to prevent polluting the stream with pinned posts. Since mainly space admins or moderators are allowed to pin posts, the amount of pinned posts should be up to them.

We should either remove the limit or at least increase the pinned post limit e.g. up to 20.

**Comment by ArchBlood** [comment]
Should make this configurable by profile owner or space admin/moderator would be a lot easier to implement than just remove/increase pinned limit.

**Comment by buddh4** [comment]
I think a space level configuration is probably a bit too much for such a specific setting. As far as I know there are not many complains about the current logic. Removing the limit or adding a module class level configuration would be sufficient. Its rather confusing if we allow spaces to have different rules/validations like this.

**Comment by ArchBlood** [comment]
Good point, although on the note of space pins vs profile pins, I myself would like to be able to limit a profile to let's say 1 pin but a space to 3 or 4 this should be possible which would keep some of the logic and enhancing what's already there to differentiate the two, with the current logic it's very limited and making it configurable with the current logic would make all pins X amount instead of setting one for one and one for the other. :thinking:

**Comment by buddh4** [comment]
You are right, the limit should definetly be active on user profile level.
