### ISSUE TITLE
More failsave module loading when reading module config

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4242]
We should use [include](https://www.php.net/manual/en/function.include.php) instead of using `require` for better error handling when loading invalid module configuration files.

**Comment by yurabakhtin** [comment]
@luke- I have changed this in 3 places - PR https://github.com/humhub/humhub/pull/5196.

**Comment by luke-** [comment]
@yurabakhtin Thank you!

Have you tried different error scenarios here? 

Does it have any other differences/effects the modification between require and include?

**Comment by yurabakhtin** [comment]
@luke- I didn't find any differences/effects in these places where I changed `require` to `include`, I think because before call `require '.../module_folder/config.php';` we check the file `config.php` exists in the folder, the code is here https://github.com/humhub/humhub/blob/master/protected/humhub/components/bootstrap/ModuleAutoLoader.php#L120.

As we can read from the PHP doc https://www.php.net/manual/en/function.include.php if the file is not found then:

- `include` generates `E_WARNING`
- `require` generates `E_ERROR`

So I agree to get warnings instead of errors for case when module is invalid by some unknown reason.

**Comment by luke-** [comment]
@yurabakhtin Can we somehow catch such warnings and write them to the log?

  Additionally, can we somehow catch errors in the "config.php"?

e.g. if a class is not found or syntax errors?

**Comment by yurabakhtin** [comment]
@luke- I think the code https://github.com/humhub/humhub/blob/enh/4242-more-failsave-module-loading/protected/humhub/components/bootstrap/ModuleAutoLoader.php#L75-L86 already catches all errors in log.

**Comment by luke-** [comment]
@yurabakhtin Ok, you're right in my tests it's catches all errors. Thank you!
