### ISSUE TITLE
Space chooser not updated after following a space

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4281]
After following a new space the space should be immediately be added to the space chooser

**Comment by yurabakhtin** [comment]
@luke- @buddh4 PR https://github.com/humhub/humhub/pull/4815

Please note here https://github.com/humhub/humhub-modules-enterprise-theme/issues/5#issue-666429343 was reported "*but left-navigation does not change the list. We must go logout and return.*", but really we just need to refresh a page, probably they have a browser caching I think, so the fix was done only for JS side.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/pull/4815/commits/4d8324fff4361018a7f5a29108e6bfc39829b529
