### ISSUE TITLE
Implement Member since virtual profile field

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4283]

**Comment by luke-** [comment]
+ Last Login?

**Comment by buddh4** [comment]
Yeah would also be nice

**Comment by luke-** [comment]
Some more info:

- Admins can add individual profile fields at: Administration -> User -> Profiles 
- The profile fields can have different types (e.g. text / date)
- Virtual profile field types, are read only and providing some fixed info e.g. E-Mail of user (from user table)

Example of a virtual profile field:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/fieldtype/UserEmail.php

We should add to more virtual fields:

- Member since
- Last login

Which optionally can be used by the admins.

**Comment by Carl2213** [comment]
Facebook displays the age of the profile to group admins when the person is added to a group. It's obviously not very effective for new networks, but can be a useful anti-spam technique to consider.

**Comment by MasterHans** [comment]
@luke- 
I created classes with names:

- UserLastLogin.php
- UserMemberSince.php

Added inside user/models/fieldtype/BaseType.php this:

```
            UserMemberSince::class => Yii::t('UserModule.profile', 'User member since'),
            UserLastLogin::class => Yii::t('UserModule.profile', 'User last login'),

```


Now admins could add these virtual fields to _Administration - profiles_ by pressing **"Add new field"** button set parameters for the field and pick up the field type - **"User member since"** or **"User last login"**, select Profile Field Category as "General". It successfully appears in **profiles tab**.
![virtual_fields](https://user-images.githubusercontent.com/17376109/94919508-43566e80-04bd-11eb-9ec6-8143e2f8f395.png)




But when admin saves the new field "User member since", it did not appear in the **user tab** of the user profile.
The created previously **UserEmail** virtual field did not show up as well.
![virtual_fields_general](https://user-images.githubusercontent.com/17376109/94919795-b7911200-04bd-11eb-9792-0012347c5ebf.png)

**Comment by luke-** [comment]
@MasterHans Do you just want to commit a PR marked as a draft? Then we can clarify details or problems there.

**Comment by MasterHans** [comment]
@luke- Done

> @MasterHans Do you just want to commit a PR marked as a draft? Then we can clarify details or problems there.

**Comment by luke-** [comment]
I'll close this issue, since we have a PR

**Comment by Carl2213** [comment]
The name of this field is confusing. In spaces, it can be confused with "member of this space since"

Maybe "Account creation date" would be a better name.
