### ISSUE TITLE
Sign Up Email Token Still Usable after account creation

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#4315]
### What steps will reproduce the problem?
Go to Login/Sign up page and create a new account, once you get the email start the account creation process, once you've finished go back to the email and click it again and the token is still usable to create new accounts, in addition if you deny the account then go back to the email you can still use the same token as well which shouldn't be possible!

### What is the expected result?
This token show expire on first use

### What do you get instead?
The token is still usable

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Only tested for v1.6.x
| PHP version      |  7.2, 7.3, 7.4
| Operating system | CloudLinux

**Comment by xdCL** [comment]
I thought I was unfortunately the only person who noticed it, I had to actually disable the creation of accounts and give myself the job of manufacturing them one by one :(

**Comment by luke-** [comment]
Hmm, I can't reproduce that. On our community site, I'll be redirected to the login page if I click the "Sign up" button in the registration e-mail.

The token should actually only prove the validity of the e-mail address and only one registration per e-mail address should be possible.  

Since the issue may be security relevant, please send a short e-mail to hello@humhub.com.

Thanks!
