### ISSUE TITLE
Make Space Members sidebar optional

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4347]
We should add a possibility to hide the `Space members` widget.

For default or larger Spaces where all members are members anyway, this box makes no sense.
The option could implemented as Checkbox in the Space settings. 

The only problem is the missing display of the administrators or moderators. 

It may also be possible to find a way to disable join/leave activities for such large spaces.

**Comment by Carl2213** [comment]
I've asked for this previously, but for all widgets. Including user profile ones like Friends, Member of Spaces, etc. Make their visibility controllable via security settings, along with the option to hide them completely on a per-user and per-space basis.

To address the administrator and moderator problem you mentioned, maybe a widget can be created just for them that appears if the members widget is disabled?

**Comment by buddh4** [comment]
Yeah, space admins should be able to overwrite the visibility and order of sidebar snippets. The only problem I see is how do we make sure to find all sidebar snippets since some snippets will only be added under certain conditions. The tasks sidebar for example is only added if there are tasks available. Perhaps we should not exclude such snippets, but rather add a `condition` configuration to `BaseStack` and `Menu` classes.

**Comment by Carl2213** [comment]
I see this more as a privacy issue, regarding sidebar widgets that reveal information that users/space admins may not want to reveal or control the visibility of.

I think what @buddh4 is referring to is a separate issue.

**Comment by buddh4** [comment]
For me it doesn't matter why a space admin (or profile user) wants to hide a snippet. Either he just does not want a snippet for cosmetic reasons, or he has privacy concerns or he just wants to change the order of snippets. As far as I understood my suggested is very similar to your suggestion, a container level snippet configuration in which a space admin (or profile user) can manage the visiblity and sort order of snippets.

**Comment by Carl2213** [comment]
Your suggestion is more over-arching and would solve the privacy issue as well.

My current workaround has been to disable the widgets by default (globally via views) and re-add them as modules with visibility configured via permissions. But since there's so many of them (4 for Users: Friends, Member of Spaces, Followers, Followed by - and 2 for Spaces: Members, Followers) in addition to other sidebar widgets, I ran into a different issue. Having to split the module menu into two sections: Modules (features/functionality) and Widgets.

I have not been successful in fully implementing this yet.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/4370
