### ISSUE TITLE
Advanced search : fields (checkboxes) dont appear in advanced search section

### ISSUE THREAD

**Issue by devFNO** [humhub/humhub#4349]
### What steps will reproduce the problem?
create a profile field of type checkboxes (boolean)
assign this field with profilefield-visible, profilefield-show_at_registration, profilefield-editable, and field-profilefield-searchable

### What is the expected result?
in the search page , advanced sections, can check the checkbox to search all profiles with this checkbox on.

### What do you get instead?
nothing appear
no possibilities to search with this criteria.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.4
| PHP version      |  7.2
| Operating system | linux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
If a profile field is marked as searchable, only its content is included in the search index. Currently there is no further functionality here.

In the Advanced Search Option it is unfortunately not that nice to include user specific options, because the search mainly searches content but also Space.

But we planned to add something like that in the directory user section.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/4157
