### ISSUE TITLE
Changed Space Homepage breaks Member Invites

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4354]
### What steps will reproduce the problem?

For a private Space, no member invitations are possible if the Space start page has been changed to the Tasks module, for example.

If an invited users clicks on the Invite notification, the user is redirected to the tasks modul and gets a "permission denied" page.

### What is the expected result?

On a private space, make sure non-members are not redirect to the configured start page.

or 

Use full space start page url in the invite notification.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | master
| PHP version      | 
| Operating system |

**Comment by fae7em** [comment]
This problem is for both public and private spaces and I think it’s more about the Guest Homepage Url which set in space setting. 
The options of the dropdown menu for it, are gathered from the left side menu which can be stream, tasks, or any other enabled modules. There is no guarantee that all these modules handle guest users (like the Tasks module which doesn't). So currently this setting parameter can have useless values. In this case, it causes permission denied for invited users but in any other usage of it, there is the same problem again.
Isn’t it better to use the default space Homepage Url and direct guests and non-member users to this page and just ignore the configured Guest Homepage URL? If so, what’s the usage of the Guest Homepage URL, If we can’t use it for guests and non-member users?

**Comment by buddh4** [comment]
I aggree the stream should be used as fallback. But all modules should support some kind of guest view if possible.

**Comment by ArchBlood** [comment]
> I aggree the stream should be used as fallback. But all modules should support some kind of guest view if possible.

Sadly @GreenMeteor can't do much for guest views so we rather block the viewpoints for the most part so that it encourages guests to login/sign up to view our work :thinking:  

### Example
This just removes it from view for `isGuest` as those that know Yii2
```php
        if (Yii::$app->user->isGuest) {
            return;
        }
```
So another alternative is more than welcomed

**Comment by fae7em** [comment]
Actually it's not just about guest users, it's also about space non-member users. 
I think it's a good thing that all modules support the guest's view, but there is no guarantee for it now.
Since "Guest Homepage Url" in the setting is just used here and it's not useful even here, maybe it's better to remove this parameter setting and just use the stream default page.

**Comment by Carl2213** [comment]
Maybe all spaces should have a "welcome" page for new members? This would show group info, description, members, etc (whatever the space admins configure) with the choice to accept or decline the invite. Then once they accept they can start seeing the configured homepage.

**Comment by ArchBlood** [comment]
> Maybe all spaces should have a "welcome" page for new members? This would show group info, description, members, etc (whatever the space admins configure) with the choice to accept or decline the invite. Then once they accept they can start seeing the configured homepage.

Although I like this idea, it would be more view files that would have to be created, I think an alternative to this would be a dialog model, we wouldn't have much trouble configuring this and it wouldn't force more loading on the user and the admin/owner of the spaces  could easily configure it from the space settings :thinking:

**Comment by Carl2213** [comment]
I like this idea because it provides more information for the user before joining the group. Like how Facebook groups, for example, give you an overview before joining. That helps you make a more informed decision.

It can also include group rules, which I wanted to have included in the question that is asked to new users, but this would be a better alternative that solves many issues at once.

**Comment by luke-** [comment]
Wouldn't it solve the issue if we implement the `getUrl()` method in the class below and always return a direct URL to the space `stream action` (accessible by no members&guests in case of invite) and not the selected homepage (if configured)? 
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/space/notifications/Invite.php

Overwrite: https://github.com/humhub/humhub/blob/master/protected/humhub/components/SocialActivity.php#L248

---

There are many useful use cases for a indivdiual guest homepage (start page for non members), e.g. using the custom pages module and create a Welcome Page. In the case of Private Spaces we can of course disable or hide the `Guest Homepage` option.

Unfortunately we can't filter out the unsupported modules in the select box for the Guest Homepage, but I don't see a solution here at the moment.

Thanks also for the other interesting ideas, but we should create a separate issue for this.  Here however then a more detailed proposal would be helpful.

**Comment by fae7em** [comment]
We can overwrite getUrl() in Invite.php, also we can change the actionIndex() in spaceController, and if a user is not a member of the group just redirect it to achtionHome() that already support non-member users, instead of configured Homepage Url.

https://github.com/humhub/humhub/blob/923c71474a5cec7f90bd48f0b126c69449c6a303/protected/humhub/modules/space/controllers/SpaceController.php#L76-L81

This currently solves the problem. Then we can create another issue for customizing this page or create another page for non-member users and let the space admin customize it in the setting.

**Comment by luke-** [comment]
I don't fully understand the advantage of modifing the SpaceController instead of the Invite.php?

If we adjust the SpaceController, I would suggest to always use the actionHome in case the user is not a member **and** the Space is not public.

**Comment by fae7em** [comment]
There are two issues here, 1. what should be displayed to the invited users after clicking on the notification. 2. generally what should be displayed to non-member users who visit the space.
It's not about doing just one of these. We can modify Invite.php and set a specific URL for it (anything, a new page or homePage or ...), **and** modify SpaceController for general issue.

**Comment by luke-** [comment]
Please excuse me if I do not fully understand the problem :-)

1.) is clear --> ``stream page``  to avoid problems with modules
2.) Non-members should start either on the ``stream page`` or, if set, on the configured guest homepage. 
- For Private Spaces this Guest Homepage setting can be ignored, since non-members should not have access to it anyway.  (Except during invite process)

**Comment by Carl2213** [comment]
Here's an example of what I mean (and what I believe fae7em also means with point #2):
![image](https://user-images.githubusercontent.com/69092633/93019838-f2371700-f5af-11ea-8fb4-d04cdc6f1b7f.png)

Obviously in Humhub's case it would be a lot simpler. Just the Space description, attributes (visibility, etc), admins, member count. But it would still provide useful info to non-members, and provides a safe (and useful) landing zone for invited users.

For private spaces, I think this would be a much better approach than configuring a guest homepage since guests can't see whatever is configured.

**Comment by luke-** [comment]
Ok got, I would appreciate such an "About" page as well.

And if I now understand it correctly, it would be also a good target for the Invite Notification too. Especially because the stream is empty in much cases anyway. 

I will create an extra issue for this, where we can discuss details.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/4370
