### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4356]
TBD

**Comment by buddh4** [comment]
https://github.com/php/php-src/blob/master/UPGRADING#L20

**Comment by luke-** [comment]
Oh, that's quite a couple of points. 

We should also make sure that we have a max. PHP version in the documentation, in case there are incompatiblities.

**Comment by buddh4** [comment]
- [ ]  Removed ability to call non-static methods statically.
    Thus `is_callable` will fail when checking for a non-static method with a
    classname (must check with an object instance).
- [ ] Removed `create_function()`. Anonymous functions may be used instead.

**Comment by buddh4** [comment]
- https://github.com/Codeception/Codeception/issues/5993

**Comment by buddh4** [comment]
@luke- can you have a look those functions w
FILE: /mnt/e/codebase/humhub/develop/protected/humhub/modules/ldap/components/ZendLdap.php
---------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
---------------------------------------------------------------------------------------------------------------------
 87 | WARNING | Function ldap_control_paged_result() is deprecated since PHP 7.4; Use ldap_search() instead
 98 | WARNING | Function ldap_control_paged_result_response() is deprecated since PHP 7.4; Use ldap_search() instead
---------------------------------------------------------------------------------------------------------------------

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/issues/4465

**Comment by luke-** [comment]
@buddh4 Yes, thank you. I collect the LDAP points there.
