### ISSUE TITLE
Create Space Information / About page

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4370]
### Is your feature request related to a problem? Please describe.

Some information of a Space is hard to find and sometimes not easy to retrieve. 
In addition, Private Spaces need an entry point for invited members, currently the stream page is used in this case which is always empty.

### Describe the solution you'd like

Add a page called "Information" or "About" in the Wheel Menu(?) of each Space which shows:

- Title & Description
- Owner, Admin and Moderators
- Add a "Contact" link if Mail Modul is enabled to all Admins(?) "Contact Admin"
- Show Meta Information (Visibility, Security, Created At, ...) 

### Describe alternatives you've considered

- Rework header section and add more details
-  Add additional snippets

**Comment by fae7em** [comment]
- Have sidebars displayed on this page? 
- Does this page itself appear in the menus? if so, in space menu or header or ...?

**Comment by buddh4** [comment]
- Your own role (and perhaps even permissions) in this space

**Comment by luke-** [comment]
I do not think we need a sidebar, but this depends a bit on how we organize the displayed information.

I would suggest this "wheel" navigation:
![image](https://user-images.githubusercontent.com/4736168/93087700-38b47080-f699-11ea-9d6a-1f566494c5cc.png)

@buddh4 Good point with the role! I think the permissions will probably be too much and confusing.

**Comment by buddh4** [comment]
I think an overview of what I'am allowed to do in a space would be nice, in terms of troubleshooting, transparency and perhaps in the future for features like gamification.

**Comment by fae7em** [comment]
I think the wheel navigation is more about modifying sth about space and it's not a place for a page that just gives some information.
What about putting it on top of the Space menu?

**Comment by ArchBlood** [comment]
To be honest when looking over the idea, the About menu should be displayed in view just like it is for profile that's a given, should also remove the description from the header altogether and just rely on the About section for information, sidebars should be optional depending on space configurations :thinking:

When dealing with private spaces you wouldn't (shouldn't) be able to see them in the first place so I don't really see the need to worry too much about them, limited privacy though is a different story, I believe that if there is limited privacy to a space (e.g can view About section but not posts) then the stream menu option shouldn't display at all and you wouldn't be able to see exact members other than owner/admins just information like a subtotal of members and posts made without any models or quick action linking to such objects :man_shrugging:

**Comment by luke-** [comment]
As third potion: we could possibly also show an info symbol next to the gear symbol. 

But if necessary we can still make the position configurable. This also depends a little bit on network types. In a small network, this is often not needed as much as in a larger open network.

Maybe something for: https://github.com/humhub/humhub/issues/3913

**Comment by buddh4** [comment]
One advantage of the space menu entry would be:

 - Unify Space and User Profile, Spaces should be as similar to user profile as possible ideally with an profile page, about page, etc.
 - The single stream entry in the space menu (default) looks a bit lost. Why do you need a menu with only one entry. With an about page, the space would look a bit more lively.
 - You immediatley see where you are since the menu entry is activated.

**Comment by Carl2213** [comment]
I think it would make more sense in the Space Menu, to remain consistent with User Profiles.

For private spaces, it would be less for visitors and more of a landing space for invites, and an info page for members as well to check for admins or group rules.

I agree the description/sub-title can be removed from the header for a cleaner look.

**Comment by Carl2213** [comment]
Reposting Facebook screenshot here for reference/ideas.

![image](https://user-images.githubusercontent.com/69092633/93094501-5f15e400-f678-11ea-964d-dc9bc53d2143.png)

**Comment by luke-** [comment]
Ok, then we can simply add it as the last item in the SpaceMenu. And then we'll see how the feedback is.

**Comment by luke-** [comment]
If we assign a very high Sort Order such as 99999, it should always appear at the bottom.

**Comment by ArchBlood** [comment]
I myself am not that good at placing information when it comes to HumHub but I've gotten a somewhat functioning example going on of what this should look like in a sort of way :thinking: 

![Screenshot_1](https://user-images.githubusercontent.com/35392110/93153692-d6c32d80-f6cf-11ea-9d25-e436c34200ca.png)
 > Getting space information is somewhat harder because I don't have much experience dealing with space modifications :sweat_smile:

**Comment by fae7em** [comment]
About the sidebar menu in About page:

In Public spaces : 
- users can see the complete sidebar menus. (consist of stream, about, modules, ...)
- guests can see a limited sidebar menu (consist of the stream (because of the public streams) and about)

In private spaces : 
- users can see the complete sidebar menus. (consist of stream, about, modules, ...)
- guests don't see any sidebar menu. (because it's useless for them, they don't have any permission for its item)

**Comment by luke-** [comment]
@fae7em good point!

Regarding the description:

I would maybe add a new short description field (~max. 100 characters) which can be used in the header and also in the directory, search, etc. 
The existing Description field could become a Markdown field WYSIWYM and only be used on the new About page.

**Comment by ArchBlood** [comment]
> About the sidebar menu in About page:
> 
> In Public spaces :
> 
> * users can see the complete sidebar menus. (consist of stream, about, modules, ...)
> * guests can see a limited sidebar menu (consist of the stream (because of the public streams) and about)
> 
> In private spaces :
> 
> * users can see the complete sidebar menus. (consist of stream, about, modules, ...)
> * guests don't see any sidebar menu. (because it's useless for them, they don't have any permission for its item)

I like the idea behind this, although I don't really see a need for a sidebar at all if you're not a member of the space, so taking this into account sidebars would be useless in general for an About section, just compile everything into a grid/row combination where you'll have About `{name}` ( e.g `{name}` = Space name) and right under it the space description would be in a row view, while information like space members (e.g owner/admins/moderators etc.) are displayed in a grid view beside the row in it's own column, similar to how the Custom Pages module can do, adding widgets here will just complicate and clutter something that should be simple and informational, this is why I completely removed the option in the setup that I provided, granted I signed the waver so HumHub can do what they want with the code given I don't mind :thinking:

**Comment by fae7em** [comment]
Also a question about the header menu:

Should guests see members of private spaces?

<img width="1241" alt="Screenshot 2020-09-15 at 11 41 56" src="https://user-images.githubusercontent.com/66942918/93194811-cac78200-f748-11ea-9384-432dac57f1b4.png">


If they don't have permission to see members of private space, we should also disable this button (also maybe followers part)

**Comment by fae7em** [comment]
> > About the sidebar menu in About page:
> > In Public spaces :
> > 
> > * users can see the complete sidebar menus. (consist of stream, about, modules, ...)
> > * guests can see a limited sidebar menu (consist of the stream (because of the public streams) and about)
> > 
> > In private spaces :
> > 
> > * users can see the complete sidebar menus. (consist of stream, about, modules, ...)
> > * guests don't see any sidebar menu. (because it's useless for them, they don't have any permission for its item)
> 
> I like the idea behind this, although I don't really see a need for a sidebar at all if you're not a member of the space, so taking this into account sidebars would be useless in general for an About section, just compile everything into a grid/row combination where you'll have About `{name}` ( e.g `{name}` = Space name) and right under it the space description would be in a row view, while information like space members (e.g owner/admins/moderators etc.) are displayed in a grid view beside the row in it's own column, similar to how the Custom Pages module can do, adding widgets here will just complicate and clutter something that should be simple and informational, this is why I completely removed the option in the setup that I provided, granted I signed the waver so HumHub can do what they want with the code given I don't mind 🤔

Actually, you are kind of right, and as I said in private spaces for guests there is no sidebar because it's useless for them. But for public spaces, there is a concept as public streams which seem is provided for members and non-members. so if we completely removed the sidebar for guests, they can't even see these streams and if they don't see them, this concept will be useless.

**Comment by ArchBlood** [comment]
> Actually, you are kind of right, and as I said in private spaces for guests there is no sidebar because it's useless for them. But for public spaces, there is a concept as public streams which seem is provided for members and non-members. so if we completely removed the sidebar for guests, they can't even see these streams and if they don't see them, this concept will be useless.
> 
> (Of course, if I understood this concept correctly)

In this case I will gladly hand over the rest of the work to you as I have no more to offer on this topic than the already provided code :sweat_smile:

**Comment by luke-** [comment]
@fae7em I would leave the header as it is for now and maybe add a check here later in my own PR. 
But good point, we should also consider this!

**Comment by fae7em** [comment]
> If we assign a very high Sort Order such as 99999, it should always appear at the bottom.

Actually, `getSortedEntries() `function in Menu uses humhub\libs\Sort class. In this class, if an item has no `sortOrder` attribute, it uses `PHP_INT_MAX` as its `sortOrder`. and since modules are added to the menu by module events, if a module doesn't specify the `sortOrder` (like cfile module), its sortOrder would be `PHP_INT_MAX`.

We can put about after stream, to be like users profile menu, and/or we can modify this Sort class in another issue to support the possibility of determining the last items as well as the first items.

https://github.com/humhub/humhub/blob/c1765aaff6d257dc999279a610f07c772465e689/protected/humhub/libs/Sort.php#L31-L42

**Comment by Carl2213** [comment]
What Buddh4 said here is great:
> I think an overview of what I'am allowed to do in a space would be nice

For members of the space, they can use the About page to view their own permissions in that space.

@fae7em regarding the header counter privacy issue, it also applies to profiles (friends, followers, etc) which is beyond the scope of this issue. My workaround has been to disable the on-click function globally and try to re-add the functionality of viewing members/friends/followers as an optional sidebar widget that is managed by a CanView permission.

**Comment by Carl2213** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/69092633/93234302-8214c680-f752-11ea-9532-05395293af6d.png)

**Comment by fae7em** [comment]
The content is good, but maybe we should work on its appearance more. :)

**Comment by luke-** [comment]
@Carl2213 Thanks for the suggestion, I will discuss this with our designer.

**Comment by luke-** [comment]
Below is a summary of the possible information that we can put on an "About" page. 
Maybe we start here with a simpler version and extend it later...

Did I missed something?


## Basic Information

- Space Title
- Space Description (multiline, markdown)
- Space Image (?)
- Created at | Created By

## Members

show as images?
Separated by roles?

- Owner
- Admins
- Moderators
- Members

Show max 50? members then -> show more link

## Misc 

- Available Topics (?)
- Space Color (?)
- Enabled Modules (?)
- "Contact admins" link (Open Mail Modul Modal if available)


## Security Settings

Not sure this section is really required, maybe simplified as badge

- Space Visibility 
- New Content Default Visibility
- Join Policy


## Membership Infos

Not sure this is really required. Maybe add this at later stage

- Your current role: Guest | Member
- Permissions, List of active permissions
- Member since


## Statistics

Not sure this is really required. Maybe add this at later stage.
Added by statistic modul?

**Comment by luke-** [comment]
@fae7em @buddh4  Regading of the SortOrder & `PHP_MAX_INT` problem,  we should change the behaviour and create a new & better documented apprach.  

e.g. Maximum Sort Order: 10000
Default: 5000

In the last major version we also added a form field widget to specify sort order:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/ui/form/widgets/SortOrderField.php#L48

If we change this in the humhub Sort the effects should be small, at most a few moved entries/widgets.

**Comment by ArchBlood** [comment]
> ## Basic Information
> * Space Title
> * Space Description (multiline, markdown)
> * Space Image (?)
> * Created at | Created By
For an example in my markup I just used About {name} which translated into the Space name, simple and easily translatable :thinking: 
> ## Misc
> * Available Topics (?)
> * Space Color (?)
> * Enabled Modules (?)
> * "Contact admins" link (Open Mail Modul Modal if available)
I don't think enabled modules should be displayed would make things more complex than needed plus depending on space permissions it wouldn't really matter

> ## Security Settings
> Not sure this section is really required, maybe simplified as badge
> 
> * Space Visibility
> * New Content Default Visibility
> * Join Policy
By default Space settings should be completely configurable by space owner/admin, visibility as a whole is already implemented through the permissions set (#4376 proves this), New Content Default Visibility don't really see a need for this on a About section because you're only viewing information about the space itself not the content :thinking:

**Comment by fae7em** [comment]
As @ArchBlood said, I don't also think enabled modules and New Content Default Visibility is really needed, they just make it complicated.

**Comment by buddh4** [comment]
Regarding `Contact admins" link (Open Mail Modul Modal if available)` we should think about how we integrate the mail module, the core definetly should not be aware of the the existence of the mail module. Perhaps we could make use of a base stack widget and other modules are able to inject rows into the about section. Another integration example would be `Report this space`. Or custom page injections.

**Comment by Carl2213** [comment]
Re: Luke's summary:

I don't think the space title and image are necessary because they're already visible in the header.

Members should be optional, if visible at all. I think the member count (in the header) is sufficient. Imo it's only useful to show owner, admins and moderators in the about page. The space members widget can be redesigned for this purpose.

Owner can be shown as the creator of the space and the admins/mods can be shown separately.

I don't think it's necessary to link the mail module. Linking the admin's profile is enough.

Enabled modules I don't think is necessary, since they're already visible in the Space Menu.

New Content Default Visibility can be included in the same section as Space Visibility. As in my sketch above.

Re: "Report this space". I think this would be a useful extension of the report module in general, also for user profiles.

**Comment by buddh4** [comment]
"Report Space" and "Report User" should probably rather be placed in the gear dropdown menu (which is currently missing on user profiles) since its easier to find as within the about section.

**Comment by Carl2213** [comment]
Facebook and other networks have a new feature called "Group profile", which is the person's "profile" within a group.

When you click on a person's name in a group, instead of going to their real profile, you instead go to their group profile. Which contains info pertaining to their participation in the group. Their role, badges, posts, contribution statistics, etc.

For more user-specific info like role and permissions, perhaps it would be better to show them in a person's space profile instead of using the general Space info/about page.

Humhub currently only supports showing a user's posts in a space using stream filters. A more thorough implementation would make it possible to delete/archive all posts from a specific user with one click, for example when removing them. A Space profile would also make it possible to add space-specific badges in the future, like Facebook does.

**Comment by luke-** [comment]
Attached the draft by @orangiene 

![image](https://user-images.githubusercontent.com/4736168/94414091-331c5780-017c-11eb-8783-2e812d495a50.png)

**Comment by Carl2213** [comment]
How do the "contact" buttons work when there's multiple admins/mods? Does it message all of them?

Also, I suggest making it configurable by the space owner to show the owner in the about page. Some owners might find it undesirable.

**Comment by luke-** [comment]
@Carl2213 We skip the contact links in the first versoin.

**Comment by funkycram** [comment]
Great work !
Small bug in https://community.humhub.com/s/announcements/space/space/about
The "Member since:" date is wrong:
![image](https://user-images.githubusercontent.com/23310825/96241842-00a79280-0fa3-11eb-8d0a-7e777bec1daa.png)

Future enhancement idea : add in this "about" page the list of the last members sorted by space membership  date and showing the date of membership ("members since"). Because today only admins can see this membership date in `/manage/member`, but if moderator want to say "hello" to new the members of this week for example, he cannot know who they are.

**Comment by buddh4** [comment]
@funkycram please open an bug report regarding the date issue (I could not recreate it yet). And also a feature request for your suggestion.

**Comment by funkycram** [comment]
https://github.com/humhub/humhub/issues/4542
https://github.com/humhub/humhub/issues/4543
