### ISSUE TITLE
Remove cacert.pem from distribution

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#4458]
### What steps will reproduce the problem?
Install HumHub on CentOS 8, go to Administration -> Modules -> Browse online.

### What is the expected result?
See some installable modules

### What do you get instead?
No modules are shown.
The integrated logging shows errors: `Could not parse HumHub API response! Curl error: #7 - `

### Additional info
May be related to https://github.com/humhub/humhub/issues/1299, but fixes described there don't work.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.3
| PHP version      | PHP 7.2.24
| Operating system | CentOS8

### My workaround
Disable shipped cacert.pem, i.e. comment this line:
https://github.com/humhub/humhub/blob/bea8d5a785e8b19e5da4c50c3daf711a5e444d68/protected/humhub/libs/CURLHelper.php#L33

Can someone tell my why HumHub ships it's own cacert.pem in the first place and if there are any negative side effects to be expected from my workaround?

**Comment by luke-** [comment]
Good point, I think we can safely remove this.

**Comment by luke-** [comment]
@yurabakhtin Can you take a look here? Also because of possible problems.

**Comment by yurabakhtin** [comment]
@luke- 

> Can you take a look here? Also because of possible problems.

I couldn't reproduce the error with the file `cacert.pem` on MacOS (I don't have CentOS for testing).

1) But if I change the curl option to not existing file like `CURLOPT_CAINFO => Yii::getAlias('@humhub/config/cacert_not_found.pem')`, then I could get the same text "No modules found!" instead of expected "browse online" modules and error in log:

```
2020-10-12 11:21:51 [::1][1][-][error][application] Could not parse HumHub API response! Curl error: #77 - error setting certificate verify locations:
  CAfile: .../protected/humhub/config/cacert_not_found.pem
  CApath: none
    in /.../protected/humhub/modules/admin/libs/HumHubAPI.php:44
    in /.../protected/humhub/modules/marketplace/components/OnlineModuleManager.php:207
    in /.../protected/humhub/modules/marketplace/controllers/PurchaseController.php:70
2020-10-12 11:21:51 [::1][1][-][info][application] $_GET = [
    'r' => 'marketplace/purchase'
    '_pjax' => '#layout-content'
    '_' => '1602490868756'
]
```

2) If I remove the option `CURLOPT_CAINFO => Yii::getAlias('@humhub/config/cacert.pem')` completely then I can see all "browse online" modules without restriction and errors in log.

> I think we can safely remove this.

Please check my PR https://github.com/humhub/humhub/pull/4471/files, where I removed the file `cacert.pem` and the curl option `CURLOPT_CAINFO`.
