### ISSUE TITLE
Timezone issues in posts, messages, and comments

### ISSUE THREAD

**Issue by akbansa** [humhub/humhub#4477]
### What steps will reproduce the problem?
- Install a HumHub setup on the UTC timezone server and MySql timezone is the same as SYSTEM.
- Now set Asia/Kolkata via administration settings (I logged into another user account, it shows Asia/Kolkata). But it shows about 6 hours ago on those posts.

### What is the expected result?
Ideally, you should get the current time for the posts which is basically my timezone.

### What do you get instead?
- I am seeing a difference of 5-6 hours in all times on posts, messages, comments.
- Also, when I post a message to someone it shows **Jan 1, 1970** as the message time.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.6.4
| PHP version      | 7.3
| Operating system | Ubuntu

`No logs in logging!`

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by buddh4** [comment]
Your HumHub timezone needs to be the same as your server/mysql timezone.

**Comment by olantrust** [comment]
> Currently, all dates in the db are expected to be in server timezone and there is no translation from server to app timezone. Unfortunately this is not very flexible.

Is this something that is an underlying yii issue, or something that Humhub can address in future?

**Comment by buddh4** [comment]
Its not a yii issue, its our current implementation which is hard to change at least for existing installations. [This](https://www.moesif.com/blog/technical/timestamp/manage-datetime-timestamp-timezones-in-api/) article suggests persisting all dates in UTC, which would maybe solve this issue since we are not dependent on server timezone. In HumHub 1.7 the user timezone should be determined while registration, which should solve at least a part of the problem. 

Maybe we should open a new issue addressing the problem and the downsides of the current implementation.

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/issues/4546
