### ISSUE TITLE
GDPR-related features

### ISSUE THREAD

**Issue by SocioHub-FID** [humhub/humhub#4551]
#3632 # Problem Desciption

In our team we figured out that HumHub has serious GDPR-related problems for us: Short version is: we as admins have far too many chances to access private data. Also users cannot download their data.

### Suggested Solutions

We suggest:
- options to encyrpt database (already mentioned here: https://github.com/humhub/humhub/issues/3412)
- options to deactivate impersonation
- options to deactivate csv-download of all user details for admin
- options to deactivate make it possible for users to download individual user data

Did you get any feedback from other users?

Best,
Your SocioHub-Team 

PS: Thank you for HumHub! 👍

**Comment by ArchBlood** [comment]
I would also like to pin this here as well for future reference

https://github.com/humhub-contrib/legal/issues/13

**Comment by buddh4** [comment]
- You mainly refering to private content on a profile and probably messages? 
- On private spaces, shouldn't admins be able to make sure no illegal content is shared?
- Wouldn't it be enough to define data usage and processing in privacy section of the legal module?
- Instead of removing or deactivation by configuration of the impersonate feature, perhaps we could also think of a grant access for admin process for troubleshooting and a access log

Here are some infos regarding [GDPR encryption](https://gdpr-info.eu/issues/encryption/) and encryption of personal data, which is not required, but can prevent data breaches.

**Comment by ArchBlood** [comment]
> - Wouldn't it be enough to define data usage and processing in the privacy section of the legal module?

I would like to agree with this but sadly not all people go straight to the Privacy Policy or Terms just because it's linked, they normally just click the box and ignore the rest, it's best to give a simplified version in view while also showing a "Learn more..." option, this in my opinion would be better use :thinking:

**Comment by buddh4** [comment]
@ArchBlood but you have to accept to the terms when using the legal module?

**Comment by ArchBlood** [comment]
> @ArchBlood but you have to accept to the terms when using the legal module?

This is true, but this doesn't mean that the Terms or Privacy Policy link are viewed, normally the user just clicks the checkbox to finish registration, my opinion it would be nice to have some kind of validation that the link was checked, but that would seem like it would be rather hard to implement :thinking:

**Comment by buddh4** [comment]
![grafik](https://user-images.githubusercontent.com/9800854/96739201-d3524e80-13bf-11eb-8457-6d1fbd064c60.png)

If you accept this without reading it its your own fault.

**Comment by ArchBlood** [comment]
> ![grafik](https://user-images.githubusercontent.com/9800854/96739201-d3524e80-13bf-11eb-8457-6d1fbd064c60.png)
> 
> If you accept this without reading it its your own fault.

I completely agree with you there, although with how lawsuits are now a days, claims of ignorance is still a thing 😅

**Comment by spoorun** [comment]
See  #4916
For the download button part of this

**Comment by funkycram** [comment]
> See #4916 For the download button part of this

Moved to https://github.com/humhub-contrib/legal/issues/20

**Comment by luke-** [comment]
We should create individual issues per feature request if needed. Feel free to create!
Most issues should be (already) covered by the "legal tools" module.
Some points like "disable Impersonate" are already possible via the configuration.
