### ISSUE TITLE
Composer V2 compatiblity

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4559]
### Is your feature request related to a problem? Please describe.

Check compatibility with composer v2.

**Comment by luke-** [comment]
https://twitter.com/packagist/status/1319945203797708800

**Comment by yurabakhtin** [comment]
@luke- I tested for me it works without errors:

<img width="1958" alt="composer_1_vs_2" src="https://user-images.githubusercontent.com/6995524/97081627-4a7c2280-160c-11eb-952f-8b07aa958535.png">

but please note if php has no `ldap` extension then site cannot work, but composer doesn't display any error during install.
I remember on previous versions of composer I couldn't run `composer install` without errors, but now I cannot reproduce this, I tested composer versions `1.10.14`, `1.10.15`, `1.10.16`, `2.0.0`, all they run install process without errors, but only if I do install by `2.0.0` then I cannot use site, so to make site works I need either use php with ldap(in my case php7.2.22 instead of php7.3.9), or use composer < 2 version, or run `composer install --ignore-platform-reqs`

<img width="877" alt="no_ldap_ext" src="https://user-images.githubusercontent.com/6995524/97081889-29b4cc80-160e-11eb-9c14-4da678445788.png">

**Comment by ArchBlood** [comment]
This is probably due to the install process expecting that LDAP's PHP extension is installed, doesn't mean that the package has to be enabled though, as for the reason, it's required by [laminas/laminas-ldap](https://github.com/laminas/laminas-ldap/blob/2.11.x/composer.json#L25) which will cause this error :thinking:

**Comment by ArchBlood** [comment]
My suggestion would be updating the docs to show required installed PHP extensions but optional to enable

**Comment by yurabakhtin** [comment]
@ArchBlood Just for info if someone will have same issue with installing `laminas/laminas-ldap`:

- I use macos with MAMP,
- so I can have 2 different php versions at same time:
- first php is a system php of macos which is called from command line,
- second php is a server php of MAMP which is used to work with sites.

I can switch between php versions and on system macos and on server MAMP:
- my php 7.2.22 is installed with LDAP extension, but php 7.3.9 - withOUT it,
- when **system** php is used --with-ldap (ver7.2.22) then composer(any version) can install without errors, as on my screenshots above,
- when **system** php is used withOUT ldap (ver7.3.9) then composer(any version) cannot install and stop with error like this:
<img width="906" alt="check_composer_without_php_ldap" src="https://user-images.githubusercontent.com/6995524/97094074-0d3e8180-165a-11eb-8e81-029e902809ca.png">

- but if even composer installed files successfully because **system** php was with LDAP extension, then site will not work if **server** php is used without LDAP as expected.

---

To avoid such issue of error `Composer detected issues in your platform: Your Composer dependencies require the following PHP extensions to be installed: ldap` on site side:
- system and server php must be same, ideally php --with-ldap,
- if composer is stopped on error like `laminas/laminas-ldap 2.10.3 requires ext-ldap * -> it is missing from your system. Install or enable PHP's Idap extension.` then we can run it with param `--ignore-platform-reqs`, and then site will works well too, but I think some modules will be broken, but I don't know which.

**Comment by ArchBlood** [comment]
If used then wouldn't Yii2 framework package be ignored?

- If not then everything should be fine
- If yes then not only the module's but core functions would be broken and the whole platform would be rendered useless :thinking:

**Comment by luke-** [comment]
@yurabakhtin This means that if we create the HumHub packages for the website/updater (ofc with LDAP enabled) on the build server, but later there is no LDAP available on the target system, there is a error by Composer?

If I understand this correctly, this platform check is new in v2 (at least at runtime of the application). Can we deactivate it e.g. with this?  https://php.watch/articles/composer-platform-check

Because HumHub has its own check without fatal error message at least for LDAP.

**Comment by yurabakhtin** [comment]
@luke- Yes, you are absolutely right.

> This means that if we create the HumHub packages for the website/updater (ofc with LDAP enabled) on the build server, but later there is no LDAP available on the target system, there is a error by Composer?

Yes, the error is generated by composer file `/protected/vendor/composer/platform_check.php`:

```
<?php

// platform_check.php @generated by Composer

$issues = array();

if (!(PHP_VERSION_ID >= 70100)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 7.1.0". You are running ' . PHP_VERSION  .  '.';
}

$missingExtensions = array();
extension_loaded('ctype') || $missingExtensions[] = 'ctype';
extension_loaded('curl') || $missingExtensions[] = 'curl';
extension_loaded('dom') || $missingExtensions[] = 'dom';
extension_loaded('exif') || $missingExtensions[] = 'exif';
extension_loaded('fileinfo') || $missingExtensions[] = 'fileinfo';
extension_loaded('gd') || $missingExtensions[] = 'gd';
extension_loaded('iconv') || $missingExtensions[] = 'iconv';
extension_loaded('json') || $missingExtensions[] = 'json';
extension_loaded('ldap') || $missingExtensions[] = 'ldap';
extension_loaded('libxml') || $missingExtensions[] = 'libxml';
extension_loaded('mbstring') || $missingExtensions[] = 'mbstring';
extension_loaded('openssl') || $missingExtensions[] = 'openssl';
extension_loaded('phar') || $missingExtensions[] = 'phar';
extension_loaded('simplexml') || $missingExtensions[] = 'simplexml';
extension_loaded('tokenizer') || $missingExtensions[] = 'tokenizer';
extension_loaded('xml') || $missingExtensions[] = 'xml';
extension_loaded('xmlreader') || $missingExtensions[] = 'xmlreader';
extension_loaded('xmlwriter') || $missingExtensions[] = 'xmlwriter';
extension_loaded('zip') || $missingExtensions[] = 'zip';
extension_loaded('zlib') || $missingExtensions[] = 'zlib';

if ($missingExtensions) {
    $issues[] = 'Your Composer dependencies require the following PHP extensions to be installed: ' . implode(', ', $missingExtensions);
}

if ($issues) {
    echo 'Composer detected issues in your platform:' . "\n\n" . implode("\n", $issues);
    exit(104);
}
```

I tested by comment the line `extension_loaded('ldap') || $missingExtensions[] = 'ldap';` and site can work without error.

> If I understand this correctly, this platform check is new in v2 (at least at runtime of the application). Can we deactivate it e.g. with this? https://php.watch/articles/composer-platform-check

Yes, I tested: v1 doesn't create this file and I can use site even if php has no ldap extension, only v2 creates this file.
We can add `"platform-check": false` in config of the file `composer.json` as it is described there, in this case v2 doesn't create the file `/protected/vendor/composer/platform_check.php` at all.

Should I add this new config option `platform-check`?

**Comment by luke-** [comment]
@yurabakhtin Yes, we have something similar to the platform check with our requirement checker anyway. Are you creating a PR for it?

**Comment by yurabakhtin** [comment]
@luke- I did this in PR https://github.com/humhub/humhub/pull/4580
