### ISSUE TITLE
Prevent double module registration

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4569]
If the same module is found in two seperate moduleAutoloadPaths or a moduleAutoloadPath contains two different folders with the same module, the module configuration is loaded twice and event handler are registered twice. Instead the `ModuleManager` should prevent registering module duplicates and log an error. Furthermore it should not allow the registration of two different modules with the same id.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4804

**Comment by Mouflin-Guillaume** [comment]
Hey,
Ok but how can I override existing module with my moduleAutoloadPath ?
Example : enterprise module is in folder humhub protected and in my folder development I also have enterprise module to override code. 
I override serveral modules cores like comment, post, content, mail in my moduleAutoloadPath. How do this now ?
Now with this update, it's not possible and my project no longer works

**Comment by luke-** [comment]
@yurabakhtin Any idea how we can allow such use cases? maybe an option to disable the new behavior or a custom rewrite map.

**Comment by yurabakhtin** [comment]
@luke- Do you think we should allow to keep two and more modules with same id?
Here https://docs.humhub.org/docs/develop/modules#configphp I see:

- `id` - **Unique** module ID (required)`

**Comment by luke-** [comment]
@yurabakhtin  As a quick idea, we could introduce a variable here https://github.com/humhub/humhub/blob/master/protected/humhub/components/ModuleManager.php#L82
, e.g. overrideModulePath with an array as index the module ID and as value the path.

If there is an entry here, the given module path is always used.

**Comment by yurabakhtin** [comment]
@luke- The file `/protected/humhub/components/ModuleManager.php` is a core file and I don't understand why we should add there some array because not clear where the array will be filled.

Ok, as I got it we should allow to side developers to keep in system several modules with same id and only one module should be used as the latest version, i.e. example:

- core module `protected/humhub/modules/comment` exists with id = `comment`
- someone wants to override the module by own module from the path `protected/modules/nice-comments` but it has same id = `comment` in the file `protected/modules/nice-comments/config.php`

Currently after the fix possible to keep works only one of the modules, because the second module with same id is restricted.

I could suggest a solution:

- Allow new optional param in the modules file `config.php` like `'priority' => 1`, if it is not defined then `0` by default
- So here https://github.com/humhub/humhub/pull/4804/files#diff-a201fcb66f328a30a64fa095e7d69ed8c2fd94bdda7bd06a6b84fcbdc32691ceR77-R83 we will modify the code and only module with top priority will be used.
 
Example:

- custom module `bad-comments` with `priority` == 2
- core module `comments` with not defined `priority` (`priority` == 0)
- custom module `well-comments` with `priority` == 3
- custom module `nice-comments` with `priority` == 1

The script result: only the module `well-comments` with highest priority 3 will be used and all other will be ignored.

Do you agree to implement this?

**Comment by luke-** [comment]
@yurabakhtin The Array could be filled using the configration file (protected/config/common.php) e.g.

```
return [
    'components' => [
        'moduleManager' => [
            'overwriteModuleBasePath' => [
                'comment' => '/var/www/foo'
            ]
        ]
    ]
];
```
Can you check my approach again? The possibility with the priority is also ok, but I think a bit too much for this rare special case. I am open to both variants. Your choice :-)

**Comment by yurabakhtin** [comment]
@luke- I have implemented your approach in PR https://github.com/humhub/humhub/pull/4952.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
@Mouflin-Guillaume Can you please test this PR? Would this solves your problem?

**Comment by yurabakhtin** [comment]
@luke- It seems @Mouflin-Guillaume doesn't want the changes from the PR https://github.com/humhub/humhub/pull/4804 at all. Probably we should create a general setting like "[√] Prevent double module registration with same id." enabled by default.

@Mouflin-Guillaume Why don't you use a new unique module id for your customized module `xxx\modules\enterprise`?

**Comment by luke-** [comment]
@yurabakhtin Yes, a setting to disable the new Double Module Registration could be a solution. Here a flag in ModuleManager would be sufficient?

I don't know if this way of overwriting modules classes is so the proper way. 

There is also a ClassMap to overwrite particial classes:
https://github.com/humhub/humhub/blob/master/protected/humhub/config/common.php#L18
