### ISSUE TITLE
AccountTopMenu: Dynamic "Administration" item 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4695]
### Is your feature request related to a problem? Please describe.

Hardcoded List of Permissions to show the "Administration" menu entry in AccountTopMenu.

### Describe the solution you'd like

Make the display of the "Administration" menu entry dependent on entries visible to the user in the "AdminMenu".

See original discussion here: https://github.com/humhub/humhub-modules-custom-pages/issues/57

### Describe alternatives you've considered

?

**Comment by luke-** [comment]
We should add this change here: https://docs.humhub.org/docs/develop/modules-migrate

**Comment by buddh4** [comment]
Hmm we had a similar solution in 1.3.0 not sure why we chagned it: https://github.com/humhub/humhub/blob/v1.3.0/protected/humhub/modules/admin/widgets/AdminMenu.php

**Comment by luke-** [comment]
That is interesting.

Currently, for example, the ThemeBuilder module does not check the visibility of its MenuEntry.  
We must then identify and fix such modules. But there should not be many.

**Comment by yurabakhtin** [comment]
@luke- 

> Currently, for example, the ThemeBuilder module does not check the visibility of its MenuEntry.
We must then identify and fix such modules. But there should not be many.

I fixed the admin menu visibility in MR https://git.humhub.org/modules/theme-builder/-/merge_requests/2

**Comment by yurabakhtin** [comment]
@luke-

- `external_calendar\Events->onAdminMenuInit()` exists without check permission but really this event is not initialized in `config.php`, so I think the even method can be deleted completely.
- `translationManager\Events->onAdminMenuInit()` uses a condition `!Yii::$app->user->isAdmin()` but controller uses check permission by `ManageModules`, i.e. even if user cannot see the admin menu item but has the perm `ManageModules` then he can open the page by URL /translation-manager/admin. So I think the wrong condition(`isAdmin`) should be replaced by `user->can(ManageModules::class)`.

I tested only my locally installed modules:

- birthday
- devtools
- external-calendar
- gallery
- 2fa
- calendar
- cfiles
- custom-pages
- mail
- polls
- rest
- wiki
- linklist
- tasks
- theme-builder
- translation-manager

Please confirm if I should check all other modules.

**Comment by yurabakhtin** [comment]
@buddh4 The method was created here https://github.com/humhub/humhub/commit/8f42e6151ec346241260d81934030a9c06915a24#diff-2d721231af23913f620138abf74a37259ee98c8600806df3b038e06c84fff228R128-R138 and then changed to the static array here https://github.com/humhub/humhub/commit/4d0036f9917307e7bc0f73f243cc882705567fcc#diff-2d721231af23913f620138abf74a37259ee98c8600806df3b038e06c84fff228R123, maybe you will recall why it was modified.

**Comment by luke-** [comment]
@yurabakhtin Looks good, thanks! Can you please also check our Marketplace for modules, especially those that are not provided by us? https://www.humhub.com/en/marketplace

Otherwise we can attempt to change the code back again from my side.

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please also check our Marketplace for modules, especially those that are not provided by us? https://www.humhub.com/en/marketplace

ok, I will update the list below:

- translation-manager: https://git.humhub.org/professional/translation-manager/-/merge_requests/7

**Comment by luke-** [comment]
@yurabakhtin I also think it would be a good idea to make the default visibility dependent on the `ManageModules` permission.  @buddh4 What do you think?

@yurabakhtin Can you post an example code for the change in the weather module here as comment?

@ArchBlood Can you customize the GreenMeteor modules here? There will be a change to the AdminMenu visibility in 1.8+.

**Comment by yurabakhtin** [comment]
> Can you post an example code for the change in the weather module here as comment?

To make the menu item visible for users with permission `ManageModules`:

Here https://github.com/GreenMeteor/humhub-weather-module/blob/master/Events.php#L15 before `$event->sender->addItem([` the following code should be added:

```
        if (!Yii::$app->user->can(ManageModules::class)) {
            return;
        }
```

and add new param/option `'isVisible' => true,` into the array here `$event->sender->addItem([ ... ])`.

**Comment by buddh4** [comment]
Just for the info: The  `addItem` is deprecated since 1.4 the `addEntry` function should be used instead. We should note that module developers need to add a permission or system admin check when adding entries to the admin menu in the AdminMenu class and ideally in development docs.

**Comment by ArchBlood** [comment]
> @ArchBlood Can you customize the GreenMeteor modules here? There will be a change to the AdminMenu visibility in 1.8+.

I'll inform our GitLab team and update our GitHub repos as soon as we can to reflect the changes


> Just for the info: The `addItem` is deprecated since 1.4 the `addEntry` function should be used instead

I understand, just a side note, some of @GreenMeteor modules haven't been updated for 1.4 as of yet, this is why it doesn't reflect the change from `addItem` to `addEntry`, at the moment we're working in two man groups so some of these updates will come in slower than others due to priority development, and with current new modules being developed this sadly hasn't been much of a priority for us as of yet but we'll try our best to push for a minimum version requirement of 1.5 while making some changes when we can, as some of the modules also still have to be updated due to pjax loading issues as well :thinking:

**Comment by luke-** [comment]
> ... AdminMenu class and ideally in development docs. I think otherwise this is and will be a common error.

Good point!
 
@yurabakhtin Can you please add a warning in the AdminMenu Class description?

**Comment by yurabakhtin** [comment]
@luke- @buddh4 PR https://github.com/humhub/humhub/pull/4708

**Comment by luke-** [comment]
@yurabakhtin Thanks, you can also customize the modules directly from us i.e. humhub & humhub-contrib. If I have understood it correctly, @GreenMeteor then takes care of its modules directly.

**Comment by ArchBlood** [comment]
Alright here's another update due to these changes for the future update of v1.8

#### List of modules to update/ have been updated
- [x] [Weather Module](https://github.com/GreenMeteor/humhub-weather-module)
- [x] [Ko-fi Module](https://github.com/GreenMeteor/humhub-ko_fi-module)
- [ ] [Patreon Module](https://github.com/GreenMeteor/humhub-patreon-module)
- [x] [Discordapp](https://github.com/GreenMeteor/humhub-discordapp-module)
- [x] [Codebox Module](https://github.com/GreenMeteor/humhub-codebox-module)
- [ ] [AdSense Module](https://github.com/GreenMeteor/humhub-adsense-module)
- [ ] [Steam Module](https://github.com/GreenMeteor/humhub-steam-module)
- [ ] [Freshdesk Module](https://github.com/GreenMeteor/humhub-freshdesk-module)
- [ ] [ChatWee Module](https://github.com/GreenMeteor/humhub-chatwee-module)
- [ ] [Itch.io Module](https://github.com/GreenMeteor/humhub-itchio-module)
- [ ] [Gamejolt Module](https://github.com/GreenMeteor/humhub-gamejolt-module)
- [ ] [Spotify Module](https://github.com/GreenMeteor/humhub-spotify-module)
- [ ] Premium Discord Module
- [ ] Premium Weather Module

Also I'd like to make this known, the following modules are no longer supported have have been archived and will no longer get updates, and have been marked in the marketplace to reflect this as well
#### List of deprecated module
- [x] [Pinterest Module](https://github.com/GreenMeteor/humhub-pinterest-module)
- [x] [Tidio Module](https://github.com/GreenMeteor/humhub-tidio-module)
- [x] [Twitch TV Module](https://github.com/GreenMeteor/humhub-twitchtv-module)

> Note: These changes have been done on their GitHub/GitLab repos but not in the marketplace as of yet!
