### ISSUE TITLE
LikeLink also when no CanLike permission  

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4743]
### What steps will reproduce the problem?

Set `CanLike` permission to `Deny` on Space or Profile level. 

### What is the expected result?

No Like link or some deny indicator.

### What do you get instead?

Not clickable like link.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | master/develop

Should be fixed in `master` branch.

**Comment by yurabakhtin** [comment]
@luke- I have fixed this in PR https://github.com/humhub/humhub/pull/4745 for `develop` branch. Yes, you wrote "Should be fixed in `master` branch." but is it normal to do fix only in `master` branch?
I am a bit confused and need more clear instructions, how to do fixes right into `master` because I think if we do such fixes only in `master` then they may be overridden on release of new version from `develop` branch, or am I wrong?

**Comment by luke-** [comment]
@yurabakhtin We regularly merge all commits from the `master` branch into the `develop` branch. This means that the `develop` branch also receives this PR, even it's not the base branch.

**Comment by yurabakhtin** [comment]
@luke- Ah, then I get it, because before I thought you do otherwise, ok I will fix the PR to `master` base.

**Comment by luke-** [comment]
Thanks!
