### ISSUE TITLE
Username Characters

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4781]
Replace username character blacklist (see https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/models/User.php#L151)
with a whitelist.

- Make sure e-mails as username are still working
- Regexp filter should be attribute in the user Module class to allow regexp changes via configuration
- create some test
- make sure/test that existing users are not affected

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/3617

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4783:

- new regexp allows:
  - all letters from all languages,
  - digits,
  - chars: `_-@#$%^&*()[]{}+=<>:;,.?!|~"'\`
- "create some test": https://github.com/humhub/humhub/pull/4783/files#diff-87c8acb8b359862f0c41ef37b74526e4635b4bb2eff2a922e9a7d7bbb7c23a84R24-R27
- "make sure/test that existing users are not affected": if you mean only demo users from fixtures then it works because they have only letters in usernames, but we should care about all old users with not allowed chars like slash `/` then such users will continue work but they and admin can use only new allowed chars on next manual updating their usernames.

**Comment by yurabakhtin** [comment]
@luke- You can find failed tests here https://github.com/humhub/humhub/runs/1721564331?check_suite_focus=true#step:21:307 but it is because this PR still use `develop` version without a fix from PR where the tests were fixed https://github.com/humhub/humhub/actions/runs/493488879.
