### ISSUE TITLE
Labels of form fields generated by HForm are not displayed correctly

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#4793]
The labels of form fields generated by `humhub\compat\HForm` do not seem to be displayed correctly. 

**As a result, the labels are not translated.**

For example, the edit screen for a text type profile field looks like this

![screencapture-hayhub-net-admin-user-profile-edit-field-1590608525716](https://user-images.githubusercontent.com/38252517/105530135-b749aa80-5d2a-11eb-9ed0-4e7d5ad4bf00.png)

The definition is below, but the label set by `Yii:t()` and the label on the screen are different.

https://github.com/humhub/humhub/blob/2432654028a593d8b8b5fd8c7f2edeb06ce2d0bc/protected/humhub/modules/user/models/fieldtype/Text.php#L87-L137

I have not investigated the label display for non-text fields.

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7.2
| PHP version      | 7.4
| Operating system |

**Comment by yurabakhtin** [comment]
@luke- Fixed in commit https://github.com/humhub/humhub/pull/4800.

Please note I fixed similar issue in PR https://github.com/humhub/humhub/pull/4799/files, but current issue was a bit different, however I think we should fix all places related to the PR https://github.com/humhub/humhub/pull/4799 because I find many `public function getFormDefinition($definition = [])` in different classes like `Text`, `TextArea`, `CheckboxList` and etc. but they all don't merge `$definition` as I fixed here https://github.com/humhub/humhub/pull/4799/files#diff-f0dddc2afb07bab05bf804dea03a3f7e2ce5c6b2a244e7e772af4b9a8412eae6R51. Currently I don't find problems in the classes but if some class will be extended in future like we had for `class CountrySelect extends Select` then it will not work as was for `CountrySelect`.

**Comment by luke-** [comment]
Thanks!
Ok, but there are no current cases? The HForm is outdated anyway and should be refactored in the near future.
