### ISSUE TITLE
Dev branch migration error for migration m201130_073907_default_permissions

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4806]
When running migrations on dev branch I get the following:

**Specified key was too long; max key length is 767 bytes**

*** applying m201130_073907_default_permissions
    > create table contentcontainer_default_permission ... done (time: 0.022s)
    > add primary key contentcontainer_default_permission_pk on contentcontainer_default_permission (permission_id,group_id,module_id,contentcontainer_class) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1071 **Specified key was too long; max key length is 767 bytes**
The SQL being executed was: ALTER TABLE `contentcontainer_default_permission` ADD CONSTRAINT `contentcontainer_default_permission_pk` PRIMARY KEY (`permission_id`, `group_id`, `module_id`, `contentcontainer_class`) (/mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException()
#1 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute()
#2 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/db/Migration.php(437): yii\db\Command->execute()
#3 /mnt/e/codebase/humhub/develop/protected/humhub/modules/content/migrations/m201130_073907_default_permissions.php(24): yii\db\Migration->addPrimaryKey()
#4 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/db/Migration.php(114): m201130_073907_default_permissions->safeUp()
#5 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(727): yii\db\Migration->up()
#6 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp()
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp()
#8 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#10 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction()
#11 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#12 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#13 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#14 /mnt/e/codebase/humhub/develop/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#15 /mnt/e/codebase/humhub/develop/protected/yii(29): yii\base\Application->run()
#16 {main}
*** failed to apply m201130_073907_default_permissions (time: 0.046s)

**Comment by buddh4** [comment]
No wonder with this primary key: https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/migrations/m201130_073907_default_permissions.php#L24

**Comment by luke-** [comment]
The problem here is rather this column. 
https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/migrations/m201130_073907_default_permissions.php#L18

I think if we set it to the length of 60 (also used in the ContentContainer table).

This then gives a string length of 310. 
But I'm not sure if we have to multiply this by 4 or by 2.

**Comment by buddh4** [comment]
Is there any advantage of using such a primary key instead of just an id?

**Comment by luke-** [comment]
@yurabakhtin  Can you take a look here, please? For me, it doesn't matter if it's solved via ID or Combined PK, but we have to take into consideration the 767 length restriction.

**Comment by yurabakhtin** [comment]
@luke- 

> Is there any advantage of using such a primary key instead of just an id?

I just did this like table `contentcontainer_permission` where PK is:

- permission_id varchar(150)
- contentcontainer_id int(11)
- group_id varchar(50)
- module_id varchar(50)

The table has the same format InnoDB + utfmb4 as I did for `contentcontainer_default_permission`, so here we have PK length = (150 + 11 + 50 + 50) * 4 = 261 * 4 = 1044, so it is more 767 as well.
Max length for utfmb4 is 191, because 767 / 4 = 191,75.
Max length for ut8 is 255, because 767 / 3 = 255,67.
So I am wondering how it worked on `contentcontainer_permission` before.
My MySQL version is `5.7.26` and it seems it allows up to 3072 as documented here https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix.

> I think if we set it to the length of 60 (also used in the ContentContainer table).

Yes, indeed my error that I used old/first version of the column `contentcontainer::class` because in next migration it was changed to `char(60) NOT NULL`.
But if even I will decrease that from 255 to 60 we will get length (150 + 60 + 50 + 50) * 4 = 1240.

> For me, it doesn't matter if it's solved via ID or Combined PK, but we have to take into consideration the 767 length restriction.

I am not sure we should use addition ID for primary key because we still need to keep unique index for `(permission_id, contentcontainer_class, group_id, module_id)` which have same restriction.

But we can restrict the length of the PK as I did here https://github.com/humhub/humhub/compare/develop...fix/4806-pk-contentcontainer_default_permission?expand=1#diff-5af1f1f7a07d3c5d076b692cecdb92229280c1c994323544248ed1920df7c3d6R24-R25
Do you agree this?
If yes, then we should do same for PK in the table `contentcontainer_permission`.

**Comment by luke-** [comment]
BTW: I just saw that we actually require MySQL 5.7+ as a minimum version. https://docs.humhub.org/docs/admin/requirements#database
@buddh4 Are you using MySQL 5.6?

Anyway, it is still good to close this potential error for now.

@yurabakhtin I like your solution, is it reliable? What happens if the keys are still longer? Are there conflicts then?

**Comment by buddh4** [comment]
I use `10.1.45-MariaDB-0+deb9u1`

**Comment by yurabakhtin** [comment]
@luke-

> I like your solution, is it reliable? What happens if the keys are still longer? Are there conflicts then?

I have done complete testing and I understood that we should not calculate the key restriction as length of all column, we should restrict only columns more than 191 chars.

I did all tests with a disabled setting `innodb_large_prefix = 0` in MySQL config because it was enabled by default. (I will keep this disabled on my local server in order to catch such error in future).

<img width="2374" alt="test_keys" src="https://user-images.githubusercontent.com/6995524/106296304-8acdeb00-6262-11eb-8e55-4e3e95e9ae54.png">

As you can see after change the column to `char(60)` we don't need the restriction, so I reverted that here https://github.com/humhub/humhub/pull/4807/commits/7e1b191bdb1af832c47ebb1710017255db0252ec

To be sure please review this test:
<img width="1090" alt="test_bytes_per_column" src="https://user-images.githubusercontent.com/6995524/106296478-c8cb0f00-6262-11eb-81af-1a1fcfae0464.png">

So we should do the restriction only for columns with length > 191 (for utf8mb4).

Now I can say: yes the PR https://github.com/humhub/humhub/pull/4807 is reliable.
Really this was my bad that I used a not last version for the `contentcontainer_class`.

**Comment by luke-** [comment]
@yurabakhtin Thank you I have also tested it again with MySQL 5.6 and the PR fixes the problem.

Nevertheless, I will increase the Maria DB minimum version to 10.2.
