### ISSUE TITLE
Add setting table indexes

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4825]
### What steps will reproduce the problem?

Such duplicates should not be possible. Please also check `contentcontainer_setting` here and create index(es) if necessary.

Target Branch: Develop 

![image](https://user-images.githubusercontent.com/4736168/106755502-7f960900-662e-11eb-8674-ef285f4f066e.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/4832.

> Please also check `contentcontainer_setting` here and create index(es) if necessary.

There is a coorect index with unique property:
<img width="982" alt="table_contentcontainer_setting" src="https://user-images.githubusercontent.com/6995524/106857124-a3119000-66d0-11eb-89b2-368798a11edf.png">

> Target Branch: Develop

Sorry, I did the PR for `master`, should I redo the PR only for `develop`? But really `master` has the problem too, it is why I did this there.

---

Not related issue, but I tested the setting `enableProfilePermissions` from your screenshot and it works well only with enabled pretty urls.
I mean the checkbox "Enable individual profile permissions" on the page Administration -> Users -> Settings -> Profile Permissions.
Here https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/admin/views/user-permissions/default.php#L46:

```php
'data-action-url' => ['/admin/user-permissions/switch-individual-profile-permissions'],
```

should be fixed to:

```php
'data-action-url' => Url:to(['/admin/user-permissions/switch-individual-profile-permissions']),
```

**Comment by luke-** [comment]
@yurabakhtin Master is ok for this fix. The other issue is fixed here: https://github.com/humhub/humhub/commit/bd9f90b5bca638e5d235aaf9e43db6f95f329e10 thanks for the hint!
