### ISSUE TITLE
1.8: Default Permissions some Modules missing

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4828]
### What steps will reproduce the problem?
Install and activate Wiki Module
Go to space / user default permission settings,

### What is the expected result?

See Wiki permissions

### What do you get instead?

No Wiki Permissions

![image](https://user-images.githubusercontent.com/4736168/106762552-3b0e6b80-6636-11eb-9acb-b4b93ad0a813.png)

### Additional info

Some other module permissions appear

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/4833.

I detected the default permissions were hidden only for modules that are deactivated by default:
<img width="854" alt="check_perms" src="https://user-images.githubusercontent.com/6995524/106870274-f7713b80-66e1-11eb-8eb2-53d9d7cfcfee.png">

Also after investigation I find some modules (extended from `ContentContainerModule`) define permissions in the method `getContainerPermissions()` and those modules had the problem like this https://github.com/humhub/humhub-modules-wiki/commit/6f2e9db1, but some modules define permission in the method `getPermissions()` like this https://github.com/humhub/humhub-modules-cfiles/blob/master/Module.php#L61-L71.
Here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentContainerModule.php#L184-L195 the method `ContentContainerModule->getContainerPermissions()` is called only for Activated modules.

It seems the modification like this https://github.com/humhub/humhub-modules-wiki/commit/6f2e9db1 should be done for all modules extended from `ContentContainerModule` instead of current `getPermissions()` with conditions `if ($contentContainer instanceof Space)` or `if ($contentContainer !== null)` inside. But I didn't investigate/test this deeply, let me know if I should, thanks.

**Comment by yurabakhtin** [comment]
In additional to above the method `ContentContainerModule->getContainerPermissions()` https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentContainerModule.php#L205 should be `public` and not `protected` I think.

**Comment by luke-** [comment]
Okay, this is a little confusing here. I think its worth to refactor/cleanup here a little bit.

As a long-term plan, following method signatures would be nice. 

```php
$globalPermissions = Module::getPermissions()    # Remove `contentContainer` in some later major version (try to avoid use)
$ccPermissions = ContentContainerModule::getContentContainerPermissions($contentContainer);

# Helper
$ccPermissions = ContentContainerModule::getEnabledContentContainerPermissions($contentContainer);
```

So it should be good to migrate all  modules to use "getContentContainerPermissions" if possible and make this method public.

Currently I see two cases which may cause problems here:

- E.g. the "Like" module (core module) actually adds a `ContentContainerPermission`, but does not inherit from `ContentContainerModule`. We need to change the base module class here. But the module should be still core and not visible in them Modules section. https://github.com/humhub/humhub/blob/master/protected/humhub/modules/like/Module.php#L47-L51

- Mail Module: https://github.com/humhub/humhub-modules-mail/blob/master/Module.php#L66-L76

@buddh4 Do you see any other problems here?

**Comment by luke-** [comment]
@yurabakhtin To solve the recent problem, I would simply take out the **Is enabled** check in the `ContentContainerModule::getPermission`. The method is only called by the `PermissionManager` anyway - so the impact is rather clear. The check itself can then be done directly by the `PermissionManager` or in a new method in the `ContentContainerModule`.

**Comment by buddh4** [comment]
Its protected in order to not bypass https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentContainerModule.php#L184 Here are some other calls of this method:

![grafik](https://user-images.githubusercontent.com/9800854/106921322-3320fb00-670c-11eb-8aa9-3b988a50856d.png)

**Comment by yurabakhtin** [comment]
@luke- @buddh4 Please review my fix and comment here https://github.com/humhub/humhub/pull/4833#issuecomment-773828448

**Comment by yurabakhtin** [comment]
@luke- 

> To solve the recent problem, I would simply take out the **Is enabled** check in the `ContentContainerModule::getPermissions`.

Do you want to add new param like `$checkEnabled = true` to the method `ContentContainerModule::getPermissions()`:

```php
public function getPermissions($contentContainer = null, $checkEnabled = true)
{
    if ($contentContainer && (!$checkEnabled || $contentContainer->moduleManager->isEnabled($this->id))) {
        return $this->getContainerPermissions($contentContainer);
    }
...
```

I think we can use this solution only after when all modules extended from `ContentContainerModule` will be updated to use only `getContainerPermissions()` instead of `getPermissions()` because currently as I wrote here https://github.com/humhub/humhub/pull/4833#issuecomment-773828448 some container modules still use `getPermissions()` so their permissions from the not proper method `getPermissions()` will be skipped and we will not them e.g. in the default permissions list.
I think currently we should keep the solution https://github.com/humhub/humhub/pull/4833/commits/fe5838273e9b9e0dc58070c5eff953bdece29d92#diff-3ebc21df74e6cf05d89de34d4e59c1492ae1182da2cc03fe232e6235775c46ceR33-R37 because it gets permissions and from `getContainerPermissions()` and from `getPermissions()`(if module was not use the expected method `getContainerPermissions()`).

**Comment by buddh4** [comment]
Wouldn't it be enough to make ``getContainerPermissions()` public? I'd prefer this over the new parameter. Both solution would introduce breaking change, but the new parameter would be way more problematic in terms of migrating modules. The behavior of both functions should be documented properly.

**Comment by luke-** [comment]
Ok, so for 1.8 we will just make the method Public and include a workaround for modules that have not yet been migrated: 
https://github.com/humhub/humhub/pull/4833/files#diff-3634c090cf95aea01f8986dca83fa4721c2f44685893c63d683de1550ffc02f2

**Comment by yurabakhtin** [comment]
@buddh4 

> Wouldn't it be enough to make `getContainerPermissions()` public?

It was enough only to solve the error "Unknown Method ... `getContainerPermissions()`" from here https://github.com/humhub/humhub/pull/4833. I described it here https://github.com/humhub/humhub/pull/4833#issuecomment-773828448.
