### ISSUE TITLE
1.8: Selftext - Database Min Version not correctly detected

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4835]
### What steps will reproduce the problem?

use debian

### What is the expected result?

Everything ok, MariaDB 10.3x

### What do you get instead?

![image](https://user-images.githubusercontent.com/4736168/106907869-00243a80-66ff-11eb-89ba-9366876a6501.png)

**Comment by yurabakhtin** [comment]
@luke- Yes, very strange why "Database driver - **MySQL**" and "MySQL - Version - 5.5.5-10.3.27-**MariaDB**-0+deb10u1".
My tests were here https://github.com/humhub/humhub/issues/4818#issuecomment-772536166.

The "Database driver" is detected by `Yii::$app->getDb()->getDriverName()` - https://github.com/humhub/humhub/blob/develop/protected/humhub/libs/SelfTest.php#L562.
I don't know why the server has here `mysql` instead of `mariadb`.

The version is detected by `Yii::$app->getDb()->getServerVersion()` - https://github.com/humhub/humhub/blob/develop/protected/humhub/libs/SelfTest.php#L584.
It looks like the server has either some strange DB config or some version of mysql-5.5.5+mariadb-10.3.27, I don't know how it is possible.
I just can suggest to write an additional script to parse the complex version with algorithm like:

- if version has a format like `/^d+\.d+\.d+$/` => use it.
- else try to find driver name("mysql" or "mariadb") inside the version string,
  - also find all versions from the string, to get a result array like `['5.5.5', '10.3.27']`,
  - if at least one version is more than required then OK, otherwise WARNING.

But of course we cannot be sure to know all possible values of the db versions, we just can guess it may be like:

- "MySQL" + `5.x.x`
- "MySQL" + `5.x.x-10.x.x-MariaDB-x`
- "MariaDB" + `5.x.x-10.x.x-MariaDB-x`
- "MariaDB" + `10.x.x`
- etc.

Do you think we need to implement such parser by the suggested algo above?

What I found related to the strange version:
- http://cenn.cl/moodle/admin/index.php?lang=en&agreelicense=1 - too have the database version `mysql (5.5.5-10.3.27-MariaDB-0+deb10u1)`
- https://moodle.org/mod/forum/discuss.php?d=414845 - wrongly identifies MariaDB version
- https://downloads.mariadb.org/mariadb/+releases/ - all mariadb versions

**Comment by luke-** [comment]
@yurabakhtin This unfortunately seems to be a Debian specific weirdness, but since this is our preferred Linux distribution, we should at least not show a warning here.  

So I would go with the proposed approach and write an additional script. But it doesn't have to be anything complex here. The following cases are sufficient:
- regular version
- debian double version
- just drop warning: could not determine db version

**Comment by yurabakhtin** [comment]
@luke- Ok, PR https://github.com/humhub/humhub/pull/4842:

<img width="858" alt="mariadb" src="https://user-images.githubusercontent.com/6995524/107046948-4a2d1f00-67d8-11eb-9a85-f62b486fc354.png">

<img width="859" alt="mysql" src="https://user-images.githubusercontent.com/6995524/107046959-4c8f7900-67d8-11eb-9ebb-dc17f6e733af.png">
