### ISSUE TITLE
1.8: Notification Filter misplaced

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4841]
![image](https://user-images.githubusercontent.com/4736168/107040485-90c24f80-67bf-11eb-90c5-fb6487e1eefc.png)

**Comment by buddh4** [comment]
The `margin-bottom: 0;` seems to be the problem, not sure when and why it was introduced:
![grafik](https://user-images.githubusercontent.com/9800854/107042893-88b7df00-67c2-11eb-96d4-b0c7c77adfe3.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4846
<img width="1152" alt="fixed" src="https://user-images.githubusercontent.com/6995524/107057820-e5c48c80-67e4-11eb-8cbf-53644bf9dd4d.png">

**Comment by buddh4** [comment]
@yurabakhtin did you investigate when this was introduced? Just to make sure this is not an issue anywhere else.

**Comment by luke-** [comment]
@MasterHans  Seems it was introduced with https://github.com/humhub/humhub/commit/2cddf6b8babe257ec9228f53ed1db6c77d110e48 and related to the `/admin/pending-registrations` feature. Please make sure that such CSS/LESS changes are always as precise as possible to avoid such effects. 

Can you fix that?

**Comment by buddh4** [comment]
Same with https://github.com/humhub/humhub/commit/2cddf6b8babe257ec9228f53ed1db6c77d110e48#diff-cee91cfe4da6d567cb8e4101eb29e760ed346def1c9b1de8e2d9472e4b1a2fffR122 is there a reason this was added?

**Comment by yurabakhtin** [comment]
@buddh4 

> did you investigate when this was introduced?

I didn't find when it was introduced but I found where the `checkboxList()` works well and compared the differences there:

<img width="1487" alt="differences" src="https://user-images.githubusercontent.com/6995524/107176146-9e562000-69df-11eb-9aeb-34e757203ac6.png">

What differences between `yii\widgets\ActiveForm` and `yii\bootstrap\ActiveForm`:

- `yii\widgets\ActiveForm` uses same template for all fields:
  - `public $template = "{label}\n{input}\n{list}\n{error}";` - `protected/vendor/yiisoft/yii2/widgets/ActiveField.php`
 
- `yii\bootstrap\ActiveForm` uses custom template for checkbox:
  - `public $inlineCheckboxListTemplate = "{label}\n{beginWrapper}\n{input}\n{error}\n{endWrapper}\n{hint}";` - `protected/vendor/yiisoft/yii2-bootstrap/src/ActiveField.php` and please see there method on the line 243:

```php
public function checkboxList($items, $options = [])
{
...
    return '<div class="checkbox">' . Html::checkbox($name, $checked, $options) . '</div>';
}
```

so here the wrapper `<div class="checkbox">` is added and then we have JS script which adds class `regular-checkbox-container` to the parent with class `checkbox` https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.ui.form.elements.js#L71-L75:

```js
// Check if the standard bootstrap container <div> exists
if ($input.parent().parent().attr('class') === "checkbox") {
    $input.parent().parent().addClass('regular-checkbox-container')
            .append('<div class="regular-checkbox-clear"></div>');
}
```

I.e. if we use `yii\widgets\ActiveForm` we don't have the parent element with `checkbox` and this JS doesn't work there.
Also we have this style `.checkbox{margin-top:5px !important;` in the file https://github.com/humhub/humhub/blob/master/themes/HumHub/css/theme.css
It seems the style `label{margin-bottom: 0;}` was created in order to remove this from `label` inside `.checkbox`, but also you can find on my screenshot `.radio label, .checkbox label {margin-bottom: 0;}` from `form.less`.
However if we will remove the `label{margin-bottom: 0;}` from `theme.css` we will get an additional space 5px index all field titles like "Activites" because they have a html like this `<label class="control-label">Activities</label>`.

It is why I decided to don't touch css files and fix only the view file to use the same templates where it works well.

I see 50 places where the `use yii\widgets\ActiveForm;` is used, probably we should check all them for same issues.

**Comment by MasterHans** [comment]
Hi, guys
1) Looks like I have made mistake in the issue number during my commits.
I worked with #4225 and mistakenly typed #4525:
![image](https://user-images.githubusercontent.com/17376109/107558717-30327880-6bec-11eb-8dfa-23b14f7f01cd.png)

I am sorry for that...

@buddh4 the reason was in here
I tried to fix the checkboxes position and "export" button size
![image](https://user-images.githubusercontent.com/17376109/107558990-843d5d00-6bec-11eb-93ef-aae258eb20df.png)

**Comment by MasterHans** [comment]
> @MasterHans Seems it was introduced with [2cddf6b](https://github.com/humhub/humhub/commit/2cddf6b8babe257ec9228f53ed1db6c77d110e48) and related to the `/admin/pending-registrations` feature. Please make sure that such CSS/LESS changes are always as precise as possible to avoid such effects.
> 
> Can you fix that?

I'll make it precise.

**Comment by MasterHans** [comment]
> The `margin-bottom: 0;` seems to be the problem, not sure when and why it was introduced:
> ![grafik](https://user-images.githubusercontent.com/9800854/107042893-88b7df00-67c2-11eb-96d4-b0c7c77adfe3.png)

my fault fixing sorry

**Comment by MasterHans** [comment]
> @MasterHans Seems it was introduced with [2cddf6b](https://github.com/humhub/humhub/commit/2cddf6b8babe257ec9228f53ed1db6c77d110e48) and related to the `/admin/pending-registrations` feature. Please make sure that such CSS/LESS changes are always as precise as possible to avoid such effects.
> 
> Can you fix that?

Done!

**Comment by luke-** [comment]
@MasterHans Please see my PR comment.
