### ISSUE TITLE
Reply Notifications share same message as first reply

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub#4857]
### What steps will reproduce the problem?
Comment on any post then reply to the comment twice and have someone like both replies to your comment and you'll get 2 notifications with the same text from the first reply

### What is the expected result?
When someone likes a reply or multiple replies it should be the exact text not a copy of the first reply

### What do you get instead?
![Screenshot_1](https://user-images.githubusercontent.com/35392110/107129588-6db59f80-6894-11eb-8db7-2e3443cc7736.png)

### Additional info
This is very confusing and could cause users to think that the notifications are being spammed by someone

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8-beta.1
| PHP version      | 7.3
| Operating system | CloudLinux

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look? Sounds similar to this: https://github.com/humhub/humhub/commit/17e514355ce34572fd36b5c2fd885421c0f18951

**Comment by yurabakhtin** [comment]
@luke- Yes, this but is related to the commit from issue https://github.com/humhub/humhub/issues/4869, as I wrote there it would be better to fix main function `BaseRichTextConverter::buildCacheKeyForContent()`. I have done this in new PR https://github.com/humhub/humhub/pull/4882 because as we see it was not enough to fix the single case in the previous PR.

---

Not related to this issue but please see what error IDE shows me:
<img width="1281" alt="abstract_func_call" src="https://user-images.githubusercontent.com/6995524/108039291-f5e23480-704c-11eb-92b4-471d9cbfbf96.png">
Probably the code `return parent::renderAbsy($blocks);` never calls but I think it should replaced with `return ''`, do you agree?

**Comment by luke-** [comment]
@yurabakhtin Please see my PR comments. I also get the warning about `renderAbsy`. Can you please fix that too? I think either we remove the `parent::renderAbsy` or implement an empty function in the parent.

**Comment by yurabakhtin** [comment]
@luke- 

> I also get the warning about renderAbsy. Can you please fix that too?

Commit https://github.com/humhub/humhub/pull/4882/commits/ccad96646c51cd4f3db7aa873faed352a5afeafd

**Comment by buddh4** [comment]
The error by PHPStorm seems to be a false positive. If we do not return `parent::rendarAbsy` nothing will be rendered at all.

**Comment by yurabakhtin** [comment]
@buddh4 ok, if you are sure this is only PHPStorm issue then I can revert that, please confirm.

**Comment by buddh4** [comment]
Yes, if the `renderAbsy` would be broken, the whole render process would not work since its responsible for rendering all blocks.

**Comment by buddh4** [comment]
Maybe related to https://youtrack.jetbrains.com/issue/WI-56893
