### ISSUE TITLE
Comment Notification E-Mail 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4869]
### What steps will reproduce the problem?

Receive a notification about a comment

### What is the expected result?

See the comment and the original text. 

### What do you get instead?

See comment twice.
![image](https://user-images.githubusercontent.com/4736168/107632558-edfa4d00-6c66-11eb-8987-21eba50b6368.png)

May introduced which RichText parser enhancements.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4870:

<img width="1245" alt="test_email_content" src="https://user-images.githubusercontent.com/6995524/107736195-8bf72180-6d12-11eb-8c03-1b9755e0095c.png">

The problem was in the cached content with same key for Comment and for Post because there(https://github.com/humhub/humhub/blob/fix/4869-cached-comment-notification-content/protected/humhub/modules/content/widgets/richtext/converter/BaseRichTextConverter.php#L170-L174) same value id is used, probably there we should use a code like `$content->id` instead of current `$content->content->id`, but currently I fixed only the single case to make the key unique, you can see the debug for more details:

<img width="1703" alt="debug_cached_mail_content" src="https://user-images.githubusercontent.com/6995524/107736446-1b9cd000-6d13-11eb-80f4-0b5c87cbf20d.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks, for the fix. 
@buddh4 As you are currently working on it, you might want to move the fix a little deeper into the API (if necessary).
