### ISSUE TITLE
1.8: JS Warning "Required non-init module: space.chooser"

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#4895]
1.8 - Following console warning appears on dashboard

![image](https://user-images.githubusercontent.com/4736168/108491869-bc0b6b00-72a4-11eb-9f12-4682fae426e8.png)

**Comment by buddh4** [comment]
Maybe due to: https://github.com/humhub/humhub/commit/09cdaf37cfa5f2229cfa31e015868f13de6b6c67#diff-61c9f24e66ac43241ce6de95866f87727072cf58f1cb5f05eaaa15c7b391d407R10 I assume the chooser asset is loaded after the `humhub.content.container.js` so its not available here.

We need to replace [those](https://github.com/humhub/humhub/commit/09cdaf37cfa5f2229cfa31e015868f13de6b6c67#diff-61c9f24e66ac43241ce6de95866f87727072cf58f1cb5f05eaaa15c7b391d407R32) lines with 

```
require('space.chooser').SpaceChooser.instance($('#space-menu-dropdown')).removeItem(response.space);
```

**Comment by buddh4** [comment]
The asset order is defined by: https://github.com/humhub/humhub/blob/master/protected/humhub/assets/CoreBundleAsset.php

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/4900

**Comment by buddh4** [comment]
@luke- @yurabakhtin we need to test this in the community as well as enterprise theme

**Comment by luke-** [comment]
@buddh4 The commit worked fine with both themes except for the warning. Or do you mean the Require?

**Comment by buddh4** [comment]
If you tested on ee theme its fine.
