### ISSUE TITLE
Add codemirror asset

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub#4902]
Codemirror is already used in some modules e.g. custom pages. We should add a core [codemirror](https://codemirror.net/6/) Assetbundle.

**Comment by yurabakhtin** [comment]
@luke- As I understood we just need to copy the JS library `CodeMirror` from the external module `custom_page` into the core. I have done this in PR https://github.com/humhub/humhub/pull/4965, please check I selected a proper place in the module `content`.

**Comment by luke-** [comment]
@yurabakhtin Yes. The https://github.com/humhub/humhub/tree/master/protected/humhub/modules/ui/form `ui/form` module should be a good place for this.

**Comment by yurabakhtin** [comment]
@luke- Ok, thanks, I have moved the files - https://github.com/humhub/humhub/pull/4965/commits/a0b8e02095790a93b3b86166c92c4c950db0624a.

**Comment by luke-** [comment]
@yurabakhtin Would it be possible to include CodeMirror as a composer asset?

**Comment by yurabakhtin** [comment]
@luke- I am not sure what exact codemirror library we should use from composer:

```
npm-asset/codemirror
npm-asset/codemirror-graphql
npm-asset/codemirror-minified
npm-asset/codemirror-formatting
npm-asset/codemirror-advanceddialog
npm-asset/codemirror-asciidoc
npm-asset/codemirror-highlight
npm-asset/codemirror-spell-checker
npm-asset/codemirror-node
npm-asset/codemirror-jsx
npm-asset/codemirror-cirru
npm-asset/codemirror-movie
npm-asset/codemirror-inlet
npm-asset/codemirror-plus
npm-asset/codemirror-esnext
npm-asset/codemirror-inject
npm-asset/codemirror-widgets
npm-asset/codemirror-console
npm-asset/codemirror-persist
npm-asset/codemirror-hashare
npm-asset/codemirror-activine
npm-asset/codemirror-infusion
npm-asset/codemirror-textlint
npm-asset/codemirror-sql
npm-asset/codemirror-requirebin
npm-asset/codemirror-javascript
npm-asset/codemirror-no-newlines
npm-asset/codemirror-spellckecker
npm-asset/codemirror-grammar-mode
npm-asset/codemirror-github-light
npm-asset/codemirror-highlight-node
npm-asset/codemirror-liquid-multiplex
npm-asset/codemirror-composition-mod
npm-asset/codemirror-typewriter-scrolling
npm-asset/codemirror-mode-jsonnet
npm-asset/codemirror-extension
npm-asset/codemirror-sane
npm-asset/codemirror-binding
npm-asset/codemirror-github-dark
npm-asset/codemirror-colorpicker
npm-asset/codemirror-addon-lint-fix
npm-asset/codemirror-one-dark-theme
npm-asset/codemirror-http
npm-asset/codemirror-mode-jq
npm-asset/codemirror-cubic-bezier
npm-asset/codemirror-mode-dust
npm-asset/codemirror-mode-apex
npm-asset/codemirror-mode-eve
npm-asset/codemirror-markdown-list-autoindent
npm-asset/codemirror-addon-search-korean
npm-asset/codemirror-spell-checker-inkdrop
npm-asset/codemirror-helpers
npm-asset/codemirror-lint-eslint
npm-asset/codemirror-atom-modes
npm-asset/codemirror-palettehints
npm-asset/codemirror-emmet
npm-asset/codemirror-iced-coffee-script
npm-asset/codemirror-revisedsearch
npm-asset/codemirror-guide
npm-asset/codemirror-contrib
npm-asset/codemirror-typo
npm-asset/codemirror-examples
npm-asset/codemirror-mongodb
npm-asset/codemirror-bps
npm-asset/codemirror-console-ui
npm-asset/codemirror-mathml
npm-asset/codemirror-rholang
npm-asset/codemirror-rtl
npm-asset/codemirror-nsis
npm-asset/codemirror-ambiance-plugin
npm-asset/codemirror-abap
npm-asset/codemirror-embed
npm-asset/codemirror-boethius
npm-asset/codemirror-react
npm-asset/codemirror-mode-elixir
npm-asset/codemirror-addon-infotip
npm-asset/codemirror-binder
npm-asset/codemirror-wikidata
npm-asset/codemirror-jiahe
npm-asset/codemirror-ot
npm-asset/codemirror-6
npm-asset/codemirror-6-prerelease
npm-asset/codemirror-addon-toggle-comment
npm-asset/codemirror-md
npm-asset/codemirror-6-experiments
npm-asset/codemirror-theme-ubuntu
npm-asset/codemirror-editor
npm-asset/codemirror-mode-stata
npm-asset/codemirror-one-light-theme
npm-asset/codemirror-sdk
npm-asset/codemirror-blocks
npm-asset/codemirror-syntax-themes
npm-asset/codemirror-zh
npm-asset/codemirror-frontmatters
npm-asset/codemirror-solidity
npm-asset/codemirror-mode-chapel
npm-asset/codemirror-mode-zenscript
npm-asset/codemirror-textmate
npm-asset/codemirror-nunjucks
npm-asset/codemirror-record
npm-asset/codemirror-program
npm-asset/codemirror--next
npm-asset/codemirror-theme-github
npm-asset/codemirror-spell-checker-extended
npm-asset/codemirror-rego
npm-asset/codemirror-wzk
npm-asset/codemirror-mode-icu
npm-asset/codemirror-dlx
npm-asset/codemirror-latex-hint
npm-asset/codemirror-template-mode
npm-asset/codemirror-mode-promql
npm-asset/codemirror-promql
npm-asset/codemirror-bpl
npm-asset/codemirror-js-mixed
npm-asset/codemirror-minimap
npm-asset/codemirror-xmlmixed-mode
npm-asset/codemirror-form-customize
npm-asset/codemirror-tal
npm-asset/codemirror-show-hint-addon-options
npm-asset/codemirror-show-hint
npm-asset/codemirror-show-hint-options
npm-asset/codemirror--panel
npm-asset/codemirror--state
npm-asset/codemirror--view
npm-asset/codemirror--text
npm-asset/codemirror--rangeset
npm-asset/codemirror--gutter
npm-asset/codemirror--matchbrackets
npm-asset/codemirror--language
npm-asset/codemirror--collab
npm-asset/codemirror--search
npm-asset/codemirror--lint
npm-asset/codemirror--tooltip
npm-asset/codemirror--theme-one-dark
npm-asset/codemirror--highlight
npm-asset/codemirror-mode-apache
npm-asset/codemirror--comment
npm-asset/codemirror--closebrackets
npm-asset/codemirror--autocomplete
npm-asset/codemirror--commands
npm-asset/codemirror--history
npm-asset/codemirror--lang-css
npm-asset/codemirror--lang-html
npm-asset/codemirror--lang-javascript
npm-asset/codemirror-languageserver
```

I have tried to install the first `npm-asset/codemirror` but it is not same as we have in the folder https://github.com/humhub/humhub/tree/enh/4902-add-codemirror-asset/protected/humhub/modules/ui/form/resources/codemirror.

**Comment by luke-** [comment]
I think the normal "codemirror" should be ok.  It would be good to have also a Richtext FormField widget for it.
To use it in the core as well (for testing purposes) we can use the FormFieldWidget here.

![image](https://user-images.githubusercontent.com/4736168/111655123-accaff00-8809-11eb-922d-5fc6101dda6e.png)

**Comment by yurabakhtin** [comment]
@luke- Ok, I have implemented to use composer package `npm-asset/codemirror` in commit https://github.com/humhub/humhub/pull/4965/commits/cc7f23988464f2522800957c5db582ddca5c5dd8:

<img width="857" alt="codemirror" src="https://user-images.githubusercontent.com/6995524/113134663-c583dd80-9229-11eb-939c-d4912022cc94.png">

In order to use this we should register asset as `humhub\modules\ui\form\assets\CodeMirrorAssetBundle::register($this);` and attribute `data-codemirror` as `$form->textArea($model, 'optionName', ['data-codemirror' => 'text/html'])`.
Maybe we should implement some new method `$form->textArea(...)->codemirror($mode = 'text/html')`.

**Comment by luke-** [comment]
@yurabakhtin Ok cool.  Would nice to have a `humhub\modules\ui\form\widgets\CodeMirrorInputWidget` which automatically registers the asset. (Similar to the RichtextEditor Input)

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub/pull/4965/commits/e7ce9f3648e1e063f0b5db85ae3b29474fba2a99 for `humhub\modules\ui\form\widgets\CodeMirrorInputWidget`.

**Comment by luke-** [comment]
@yurabakhtin Thanks, can you please check the tests and if anything is green we can merge that! Can you please also take a look into modules which may using CodeMirror standalone (e.g. CustomPages)? Also a point to the dev documentation would be great.

**Comment by yurabakhtin** [comment]
@luke- 

> can you please check the tests and if anything is green we can merge that!

I see tests are broken here https://github.com/humhub/humhub/runs/2247736458?check_suite_focus=true but I don't understand why it happens, it looks like problems are in uglify new js files because there are errors:

- `Error: Unable to compress JavaScript files into '/home/runner/work/humhub/humhub/protected/humhub/config/../../../static/js/humhub-bundle.js'.`
- `JS_Parse_Error.get (eval at <anonymous> (/home/runner/work/humhub/humhub/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)`
- `at /home/runner/work/humhub/humhub/node_modules/grunt-contrib-uglify/tasks/uglify.js:150:17`

I have reviewed the files but cannot find what can be wring there.
Probably it is related to https://github.com/humhub/humhub/pull/4965/files#diff-7b55bf05455d0713b162b43b698dce9bc7f2fde5527a77054831cddfd51c7b6aR26 because I added `js/humhub/humhub.ui.codemirror.js` to the bundle `CoreExtensionAsset`. Do you have an idea how it can be fixed or what we should declare?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you please also take a look into modules which may using CodeMirror standalone (e.g. CustomPages)?

I find this only in the module "Custom Pages" and I have implemented changes to use codemirror from the new core composer - PR https://github.com/humhub/humhub-modules-custom-pages/pull/179

> Also a point to the dev documentation would be great.

I don't understand what and where I should write in dev doc files, please explain, thanks.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

- Regarding the docs: A small note that "CodeMirror" is now directly bundled with HumHub should be suffient
https://github.com/humhub/documentation/blob/develop/docs/develop/modules-migrate.md#migrate-from-18-to-19

- Tests: I've upgraded grunt-uglify which seems to solve the problem: https://github.com/humhub/humhub/pull/4965/commits/889298242b41856ac0e4ae5924915950cd135a42

Now there is a new problem: https://github.com/humhub/humhub/runs/2280214650?check_suite_focus=true#step:21:1326

**Comment by yurabakhtin** [comment]
@luke- Doc updated - https://github.com/humhub/documentation/commit/7fd76117047796c35a24fb91f00aaa081c0f331a

> Tests: I've upgraded grunt-uglify which seems to solve the problem: 8892982 Now there is a new problem: https://github.com/humhub/humhub/runs/2280214650?check_suite_focus=true#step:21:1326

I cannot reproduce this:
<img width="529" alt="tests_web" src="https://user-images.githubusercontent.com/6995524/113819694-5571dc00-9782-11eb-86a2-0d26a735041f.png">

but on debugging I see that CodeMirror is not applied to the textarea, it seems `CoreExtensionAsset` is not loaded on tests so the file `js/humhub/humhub.ui.codemirror.js` https://github.com/humhub/humhub/commit/cc7f23988464f2522800957c5db582ddca5c5dd8#diff-7b55bf05455d0713b162b43b698dce9bc7f2fde5527a77054831cddfd51c7b6aR26 is not loaded and doesn't initalize CodeMirror for the textarea, but even if it is not initialized the test should works because there is a testing of simple js `alert()` function.

**Comment by luke-** [comment]
@yurabakhtin When I run the tests locally, I also get the errors. When I open a screenshot Artifact, CodeMirror is loaded correctly here.  
![web acceptance NonceCest testStatistic fail](https://user-images.githubusercontent.com/4736168/114188958-f363d300-9949-11eb-835c-4e28304e3ab1.png)

**Comment by yurabakhtin** [comment]
@luke- I use debug in order to stop the testing process to see what really we have on the page:

<img width="1202" alt="test_mode" src="https://user-images.githubusercontent.com/6995524/114213535-bf010e80-996b-11eb-9f77-eea30f6afd99.png">

I can see the initialized CodeMirror only on normal browser mode, however the tests on my machine work without errors as I displayed above:

<img width="1242" alt="browser_mode" src="https://user-images.githubusercontent.com/6995524/114213593-d6d89280-996b-11eb-91bd-9bdf432122a8.png">
