### ISSUE TITLE
Error! Update

### ISSUE THREAD

**Issue by andrewua85** [humhub/humhub#4930]
Error!

{"status":"ok"}Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away The SQL being executed was: SELECT `id` FROM `user_http_session` WHERE `id`='d2f59123d7940fc603cdf9c274490272'' in /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/db/Schema.php:677 Stack trace: #0 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'SELECT `id` FRO...') #1 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT `id` FRO...') #2 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/db/Command.php(427): yii\db\Command->queryInternal('fetchColumn', 0) #3 /home/u31843/post.losper.net/protected/humhub/modules/user/components/Session.php(61): yii\db\Command->queryScalar() #4 [internal function]: humhub\modules\user\components\Session->writeSession('d2f59123d7940fc...', '__flash|a:0:{}_...') #5 /home/u31843/post.losper.net/protected/vendor/yiisoft/yii2/web/DbSession.php(151): session_write_close() #6 [internal function]: yii\web\DbSession->close() #7 {main}

http://prntscr.com/108woht

**Comment by ArchBlood** [comment]
Clear your cache then try again

**Comment by andrewua85** [comment]
> Clear your cache then try again

Seriously? )) I have caching is disabled.

**Comment by marc-farre** [comment]
@luke- This issue still occurs: https://community.humhub.com/comment/perma?id=49303
And it has been reported several times:
- https://github.com/humhub/humhub/issues/2242
- https://github.com/humhub/humhub/issues/2633
- https://community.humhub.com/content/search?keyword=%222006%20MySQL%20server%20has%20gone%20away%20The%20SQL%22%20user_http_session&page=1&orderBy=score (15 posts)

Maybe there is something to be done?
Or at least displaying a warning explaining what should be done on the server before updating?

**Comment by luke-** [comment]
Unfortunately, it rather indicates a problem with the database and there is little we can do on the HumHub side.
https://matomo.org/faq/troubleshooting/faq_183/

Don't think it's related to the HumHub Update

**Comment by marc-farre** [comment]
@luke- As it seems to be always related to the `user_http_session`, isn't it because sometimes it becomes too large compared to the SQL server capacities? On some HumHub instances, I can see a huge amount of rows in it.

Perhaps we could detect this frequent error (or warn if the table is too large) and suggest purging this table (except for the current user), indicating that it will disconnect everyone?

Alternatively:
- Optimize this SQL query: https://github.com/humhub/humhub/blob/17a6190648b945adb4d10e3db9f676c20b9b2963/protected/humhub/modules/user/components/Session.php#L78-L82
- Find a solution to reduce the size of the `user_http_session` table (deleting old unused rows?)

**Comment by luke-** [comment]
Would be interesting to know how many rows the affected installation has. Maybe it's related to a cleanup issue
