### ISSUE TITLE
Right arrow not working in some cases in richtext editor

### ISSUE THREAD

**Issue by spoorun** [humhub/humhub#4950]
**Steps to reproduce**

Create a post
Write a phrase in bold
Press 'Enter' for a new line (not Shift+Enter)
Write a further phrase in regular text
Attempt to navigate with the cursor using arrow keys - from the end of the line in bold to the beginning of the line in regular text

**Expected:**

The right arrow key will move from the end of the emboldened text line to the beginning of the regular text line

**Currently:**

The right arrow key does not do anything. The cursor will move left or down but not right.

**Comment by ArchBlood** [comment]
If the text is highlighted `<` key is used as a back button currently I'm seeing issues with `>` key not reinstating the bold text if highlighted, this is tested in v1.8.0 :thinking:

As for the original issue, this is probably due to the rich text editor not having the ability to turn itself off, should work just fine in normal markdown syntax where `**Text**` is used for bold, and to be honest this is pretty normal behavior for a rich text editor because you're treating the first line as a bold text or the end of the line as a bold text so I'm not really seeing much of an issue here, `Shift + Enter` just creates a non-breaking line where as `Enter` just creates a breaking line :thinking:

This happens in all of the markdown syntax used in the editor to be honest
![Screenshot_1](https://user-images.githubusercontent.com/35392110/110220804-1f48f000-7e96-11eb-9dec-9cae8cec523f.png)

**Comment by spoorun** [comment]
> If the text is highlighted `<` key is used as a back button currently I'm seeing issues with `>` key not reinstating the bold text if highlighted, this is tested in v1.8.0 thinking
> 
> As for the original issue, this is probably due to the rich text editor not having the ability to turn itself off, should work just fine in normal markdown syntax where `**Text**` is used for bold, and to be honest this is pretty normal behavior for a rich text editor because you're treating the first line as a bold text or the end of the line as a bold text so I'm not really seeing much of an issue here, `Shift + Enter` just creates a non-breaking line where as `Enter` just creates a breaking line thinking
> 
> This happens in all of the markdown syntax used in the editor to be honest
> ![Screenshot_1](https://user-images.githubusercontent.com/35392110/110220804-1f48f000-7e96-11eb-9dec-9cae8cec523f.png)

Thanks for this.

I'm not sure my original post was clear enough thought.

The forward arrow key works in all scenarios with rich text formatting, to navigate around the text, as tit should be.

When the right arrow is used to try and navigate from the end of a line of formatted text to the beginning of another line (separated by a line brake), the right arrow does not work, it does nothing.

When the right arrow is used to try and navigate from the end of a line of unformatted text to the beginning of a another line of text (formatted or not), the right arrow works correctly.

This does not appear to be a general richtext issue:

I've texted the behaviour on:
https://prosemirror.net/
https://ckeditor.com/ckeditor-5/demo/

Both work correctly and do not display this behaviour, so it's a specific bug in Humhub implementation (since I believe Humhub is using prosemirror?)

**Comment by ArchBlood** [comment]
The only way that I can reproduce this issue is when typing out the text/paragraph then making it into a markdown syntax (i.e. bold or etc.), but `>` is the only key that shows issues when a line break is applied after the text/paragraph, using `<`, &#709;, `^` key works as normal :thinking:

**Comment by ArchBlood** [comment]
On the plus side adding a space or more text to the first line will enable you to continue as you need

**Comment by spoorun** [comment]
Moved to humhub-prosemirror repository:

https://github.com/humhub/humhub-prosemirror/issues/50
