### ISSUE TITLE
users dont get added to standard group 

### ISSUE THREAD

**Issue by stockh0lm** [humhub/humhub#5022]
This is humhum 1.8.1, on a mariadb.

New Users are not added automatically to the standard group. instead they remain groupless. the cronjobs are running every minute.

https://community.humhub.com/s/general-discussion/?contentId=239656
This issue was discussed and verified in the humhub community.

my config of the standard group:
https://community.humhub.com/s/general-discussion/?contentId=239656

### What is the expected result?
Users should be added to standard group after cron jobs are run

### What do you get instead?
Users remain groupless

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8.1
| PHP version      |  7.4
| Operating system | gentoo

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

no loged error is related

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5033.

Yes, there was bug when system setting `[√] Show group selection at registration` is enabled but the default group has no enabled setting `[ ] Show At Registration` and no other groups with the enabled setting `[√] Show At Registration`.

**Comment by luke-** [comment]
@yurabakhtin thanks!
