### ISSUE TITLE
Invite space member by "Group" or "User Topic"

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#5055]
### Is your feature request related to a problem? Please describe.
I tried to invite many members to my new space, but I miss.

### Describe the solution you'd like
If I had be able to select the invite members by group or user topic, I may have invited correct members.

### Describe alternatives you've considered
How about adding selector on the Member Invite dialog?

**Comment by luke-** [comment]
Currently you can only:  add default Spaces to Groups in the Group Administration.

**Comment by tomofu74** [comment]
But that is Administrative function, not for space owner...
The new space Owner ( Creator, discussion starter ) want to invite someone...

**Comment by ArchBlood** [comment]
I myself do not need such a feature, as there are some drawbacks to think of when implementing this as a feature
- How many users are in said Group, this could cause a few issues because of background Cron Jobs running, you also have to think that some servers only allow X amount of jobs to run in a given X amount of time.
- This should not be separated from Administrative permissions as this would give any person who has the ability to create a space the ability to also invite a whole Group which would then also cause the above point.

If such a feature were added it would have to be limited in a lot of areas to prevent issues that would cause timeouts as well as resource eating by background jobs running

**Comment by tomofu74** [comment]
I see.  I give it up and figure out how to group by tags or Administrator's group operation.
