### ISSUE TITLE
Prerequisites: Increase PHP Min version to 7.3

### ISSUE THREAD

**Issue by dreua** [humhub/humhub#5128]
### Is your feature request related to a problem? Please describe.
"Note: HumHub version 1.9+ requires PHP 7.3 or higher!" *(from [the lastest beta release note](https://github.com/humhub/humhub/releases/tag/v1.9.0-beta.1))*

The server I'm maintaining, however, runs happily on PHP 7.2 (CentOS 8) and other PHP versions can only be installed through 3rd party sources which I like to avoid for security and stability reasons. 

### Describe the solution you'd like
Downgrade the PHP requirement to "7.2 or higher". (7.2.24 would be the exact version on CentOS 8.)

### Describe alternatives you've considered
1. Make 1.8 a "Long term supported" (LTS) version. (Okayish but my client might miss the newest features.)
1. Install PHP from a third party repository. (Again, I'd like to avoid those on my servers.)
1. Install it all in some Docker environment. (Possible but costly and a bit annoying as the server runs currently perfectly without docker. Is there an official docker image / guide?)
1. Describe which features break with PHP 7.2, maybe we won't miss them that much.

**Comment by dreua** [comment]
Btw, you also need to update the help string in the prerequisites check: "PHP - Version - 7.2.24 (Hint: Minimum Version 7.1)"
And I might have a similar issue with the newly needed PCNTL extension, which is not mentioned in the release note but in the prerequisites check.

**Comment by luke-** [comment]
@dreua Unfortunately, we have to raise the minimum PHP version because we want to use recent versions of some base libraries/frameworks. As we have to keep our software stack state-of-the-art, this is unfortunately a necessary step.

Of course we still offer updates for critical bugs for the 1.8 version.

Otherwise, I would recommend to consider updating PHP if  somehow possible. 
https://www.php.net/eol

Since our official documentation is based on Debian, perhaps it would be a consideration to wait for Debian 11 and then migrate?

@yurabakhtin Can you please check the minimum PHP Version warning. PHP 7.3 should be minimum.

**Comment by dreua** [comment]
Thanks, I wasn't aware that 7.2 is already eol, time for Centos to upgrade then, or migrating to Debian as per your suggestion. leaving this open for the prerequisites info string, otherwise it may be closed.

**Comment by luke-** [comment]
@dreua Thanks!

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5131

**Comment by luke-** [comment]
@yurabakhtin please see my remarks

**Comment by yurabakhtin** [comment]
@luke- answered here https://github.com/humhub/humhub/pull/5131#discussion_r653610165.
