### ISSUE TITLE
Image links shown in notifications and activities

### ISSUE THREAD

**Issue by mopawa** [humhub/humhub#5129]
### Is your feature request related to a problem? Please describe.
When an image is embedded in a post, the full image link is visible in notifications and activities.  
![humhub](https://user-images.githubusercontent.com/4270199/122303925-5df93800-ced2-11eb-968d-93512e2986bf.jpg)
  
### Describe the solution you'd like
Strip links from posts in notifications and activities  
  
### Describe alternatives you've considered

N/A

**Comment by ArchBlood** [comment]
As an alternative, I suggest that an icon is displayed in the Latest activities widget instead of a link, this will help everyone know that an image is present and not just some link, of course, this can also be done in notifications as well.

The only thing is how would this be done for external images as well as internal images

**Comment by luke-** [comment]
Which version are you using. In Humhub v1.9+ we show [Image] instead.

@yurabakhtin Can you confirm this?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you confirm this?

Yes, develop:
<img width="280" alt="develop_image" src="https://user-images.githubusercontent.com/6995524/122403628-2ef0ce00-cf87-11eb-94e3-565e92123a5f.png">

master:
<img width="953" alt="master_image" src="https://user-images.githubusercontent.com/6995524/122404204-b3435100-cf87-11eb-8f53-219e45061320.png">

**Comment by mopawa** [comment]
@luke- I'm on 1.8.2

**Comment by luke-** [comment]
Ok, after we have improved the behaviour here with v1.9+, I would close the ticket.

Otherwise, please write here gain!
