### ISSUE TITLE
UserPickerField - Instant display of users

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5170]
### Is your feature request related to a problem? Please describe.

When typing the @ sign in a post or comment, it would be nice to directly see a list of possible and relevant users.

### Describe the solution you'd like

For example, in a post, this could be a list of the last 10 members active in the Space/ContentContainer.

For a comment, this could be e.g. the followers of the content. (The creator, other commenters, Liking Users).

**Comment by yurabakhtin** [comment]
@luke- Do you mean the already existing feature:

<img width="666" alt="sign" src="https://user-images.githubusercontent.com/6995524/126488898-acd10b31-284a-4237-b703-8e609ca07d81.png">

If yes, is what you want, or should it modified somehow?

**Comment by luke-** [comment]
The idea is to get rid of the "Please type at least 2 character" message and directly show options. 
As example see how it works on  Github.

![image](https://user-images.githubusercontent.com/4736168/126518811-5dda6671-c42e-4473-b296-4bebf4a5042e.png)

**Comment by yurabakhtin** [comment]
@luke- We can quickly to decrease the 2 characters to `1` here https://github.com/humhub/humhub/blob/master/protected/humhub/widgets/CoreJsConfig.php#L110, but we cannot configure there to `0`.
But if we want to display a users list right after `@` I think we should modify the external plugin, probably here https://github.com/humhub/humhub-prosemirror/blob/master/src/editor/core/plugins/mention/provider.js, can I modify this library in order to allow `minInput  == 0`?

**Comment by luke-** [comment]
@yurabakhtin The intention is not to reduce the characters for the search but to suggest/show relevant users directly without searching.

Yes, you can also edit & modify the library.

**Comment by yurabakhtin** [comment]
@luke- Ok, I have modified the library in PR https://github.com/humhub/humhub-prosemirror/pull/63, after it will be merged we can merge core PR https://github.com/humhub/humhub/pull/5243.

**Comment by luke-** [comment]
@yurabakhtin Thanks looks good so far.

Can we please reduce the list to max. 6 entries. (Would be great if this value can be overwritten using config file).
![image](https://user-images.githubusercontent.com/4736168/131505748-a9dd531e-36d5-45f7-a191-eeab55e0526b.png)

- For Posts in Spaces: It would be good if we could always display the last 6 active Space members (space_membership.last_visit - db index?).
 - For comments: Initially display max. 6 users who are following the Content (follow table).

**Comment by yurabakhtin** [comment]
@luke- Please note currently the mentioning URL doesn't contain data like current Space, Post, Comment, so there we just search between All Users and Spaces. I have ordered Users by `user.last_login`, this column doesn't have db index and `space_membership.last_visit` doesn't have db index too. Should I find a solution to send different mentioning URL depending on where it is called, i.e. send additional data of current Space, Post etc.?

In the commit https://github.com/humhub/humhub/pull/5243/commits/9e41335f929cfe1648a4a64a606f937426053be6 I just limited the Users results to 6, also if less 6 users are found then the list will be filled with rest Spaces in order to have 6 records totally.

> (Would be great if this value can be overwritten using config file).

Could you please tell me an example where I should put the config var? Thanks.

**Comment by luke-** [comment]
@yurabakhtin Yes, would be great if you could use somehow different mentioning urls OR add context (space. content) to the mentioning URL.

e.g. https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/Module.php#L140
You could add here a `mentioningSearchBoxResultLimit=6`

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub/pull/5243/commits/d97ac811183503fa4cd75740bca3b0aa036e5876:

> Yes, would be great if you could use somehow different mentioning urls OR add context (space. content) to the mentioning URL.

I have done this by implementing 2 new separate actions `/search/mentioning/post-space-members` and `/search/mentioning/comment-content-followers` specially for Post and Comment forms, in all other cases we still use the previous action `/search/mentioning/index`.

Please note all these 3 actions firstly do the searching Users and then if found results less 6(`mentioningSearchBoxResultLimit`) records then we append the results with Spaces up to 6, if you think we should keep this way only on old `/search/mentioning/index` let me know, but I think we should keep this because some users may be confused if they used the mention feature to find Spaces.

**Comment by luke-** [comment]
@yurabakhtin Please see my PR review.  

Thanks for the hint about the Spaces. Let's keep it that way for now.

**Comment by yurabakhtin** [comment]
@luke- I have done new changes in commit https://github.com/humhub/humhub/pull/5243/commits/98f9b48dfd66ac6b69d9a87f3465a51a73477f7e for your PR review, but please read my answers there.

**Comment by luke-** [comment]
@yurabakhtin thanks!
