### ISSUE TITLE
People / Spaces: Endless Scrolling

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5188]
### Is your feature request related to a problem? Please describe.

Instead of showing a "Load more" button, automatically load more entries.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5211.

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by dantefromhell** [comment]
From recent research it is shown that endless scroll is one of the more toxic UI patterns. Wired has a nice article on it
https://www.wired.com/story/stop-doomscrolling/

I suspect different people will have a different opinion, mine is to construct a community in which toxic UI patterns are not used.

But as others will disagree, I wonder if endless scroll could be made an option instead of generally enabled? Possibly a per-user choice with a global default?
