### ISSUE TITLE
Separate view document button

### ISSUE THREAD

**Issue by spoorun** [humhub/humhub#5216]
**Currently:**

When has onlyoffice installed and one selects a file a dialogue window opens offering a choice of 
'Download | Edit Document'
The Download button has a dropdown offering a further option of 'View document'

If one opens a document which one has no edit rights over, one sees:
'Download'
With a dropdown offering a further option of 'View document'

This hides the View functionality.

**Proposed:**

View functionality should be exposed.
Always offer a separate View button for a file, if viewing is possible.

**Comment by luke-** [comment]
FYI: I moved the issue away from the CFiles module since the "File Dialog" comes from the HumHub Core.
![image](https://user-images.githubusercontent.com/4736168/127673546-2bcb264d-db99-4713-a988-bef9d7de198f.png)

Related: https://github.com/humhub/humhub/tree/master/protected/humhub/modules/file/handler

Currently, there is mainly OnlyOffice for editing and viewing files. More file handlers would be good of course, I have created an issue here: https://github.com/humhub/cfiles/issues/122

**Comment by yurabakhtin** [comment]
@luke- Please note the button (Download/View) were built by handlers `FileHandlerCollection::TYPE_VIEW` and `FileHandlerCollection::TYPE_EXPORT`. The **core** download button was displayed by type `TYPE_VIEW` and the **onlyoffice** button "View document" is also displayed by the same type `TYPE_VIEW`. So in order to split them I decided to change the download button to type `TYPE_EXPORT`, see PR https://github.com/humhub/humhub/pull/5225.

If we need to rename the button "View document" to "Open" we should merge my PR https://github.com/yurabakhtin/onlyoffice-humhub/pull/1, but please note it is forked from external https://github.com/ONLYOFFICE/onlyoffice-humhub.

**Comment by luke-** [comment]
@yurabakhtin Good solution. We can adjust the OO button later if necessary. Is there anything against the current labeling? 

![image](https://user-images.githubusercontent.com/4736168/128029659-495af8e0-2b89-445a-90ac-4f9e4cb50de3.png)

**Comment by yurabakhtin** [comment]
@luke- 

> Is there anything against the current labeling?

Nothing.
