### ISSUE TITLE
Admin People Settings cannot be saved

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5301]
![image](https://user-images.githubusercontent.com/4736168/134316094-57d3ebc9-6d08-4e20-acb9-826347334d62.png)

**Comment by yurabakhtin** [comment]
@luke- Yes, really when "Default Sorting" == "Default" then the field "Prioritised User Group" should be required.

I.e. we should either use "Last login" as default value for the field "Default Sorting" instead of current value "Default" or we should set default value e.g. to "Administrator" for the field "Prioritised User Group".
I think we can do this because the group "Administrator" cannot be deleted, right?
Or is it not good to list administrator on top by default there?

**Comment by luke-** [comment]
@yurabakhtin I would prefer if initially the "Default Sorting" is simply set to "Last login". 

Alternatively, we can enable "Default" as you suggested and set the Prioritized Default Group to "Administrators" as suggested.

I am open for both :-)

**Comment by yurabakhtin** [comment]
@luke- I too prefer the "Last login" by default because it doesn't require additional checking that the selected group exists and also the sorting way was used in previous versions before the people settings were implemented.
PR https://github.com/humhub/humhub/pull/5305.
