### ISSUE TITLE
mobile navigation: width detection problem (first navigation point)

### ISSUE THREAD

**Issue by orangiene** [humhub/humhub#5340]
The script, which combines the navigation items to the super-item "Menu" especially in the mobile display, does not calculate the available space correctly. Mostly 1-2 menu items have more space, but they are not displayed, because they are placed in the menu item "Menu".  (The problem occurs mostly in the German version. (after a reload))

![WhatsApp Image 2021-10-11 at 14 33 16 (1)](https://user-images.githubusercontent.com/62644500/136790796-09677b80-9e4a-42ad-bba4-66f9da506db1.jpeg)

![WhatsApp Image 2021-10-11 at 14 33 16 (2)](https://user-images.githubusercontent.com/62644500/136790812-442a3fa7-25a4-4143-9ef7-86d987391aaf.jpeg)

![WhatsApp Image 2021-10-11 at 14 33 16](https://user-images.githubusercontent.com/62644500/136790981-53dfbe5f-d0dc-4a1d-961d-bcc60031e003.jpeg)

**Comment by luke-** [comment]
@Soundwave2142 Here is an example. Somehow there often seems to be space left for a menu item. 

![image](https://user-images.githubusercontent.com/4736168/137631048-167fa9dd-6eef-4f27-93f1-aa16e9168bcc.png)

**Comment by Soundwave2142** [comment]
@luke- @orangiene 
I can see the problem from your example, however I can not repeat it. Menu item for me only created when all items together are too wide to be displayed (more noticeable on German version as German words generally has more letters), and ALL of the items then moved to menu item at the same time. I can not repeat behavior where you can see "ubersicht" item and menu item, because for me it always either all items either menu item. 

I have attached the video recording of what I see. Please describe in details how to repeat the problem.

https://user-images.githubusercontent.com/39148595/142765296-9753b663-5763-45eb-b660-331dc14a3f39.mp4

The only problem I can see is that script doesn't recalculate items after pjax. which creates this problem you see on attached screnshots.
![image](https://user-images.githubusercontent.com/39148595/142764793-69c93045-a1a8-46ca-8a16-c41762a6a4be.png)
![image](https://user-images.githubusercontent.com/39148595/142764852-969fa4a0-01a6-4ebe-8dae-27e2198e65c3.png)

All other seems like a proper behavior? If not let me know.

**Comment by luke-** [comment]
@Soundwave2142 See my recoding here. You can also add some further navigation entries using the custom pages module.

https://user-images.githubusercontent.com/4736168/143058836-542f215c-3a1a-4aff-a28d-587bd501d3f1.mp4

To me it looks like there is a fixed spacing at the beginning which is much too high in most cases.
