### ISSUE TITLE
Display password rules in form field hint

### ISSUE THREAD

**Issue by timaschew** [humhub/humhub#5423]
I have 5 password rules, but the user will see only one at a time/fail. It's really annoying if you need 5 attempts find out all the rules.

Example:
```
'passwordStrength' => [
                '/[a-z]/' => 'Das Passwort muss mindestens einen kleinen Buchstaben enthalten.',
                '/[A-Z]/' => 'Das Passwort muss mindestens einen großen Buchstaben enthalten.',
                '/[0-9]/' => 'Das Passwort muss mindestens eine Zahl enthalten.',
                '/[\W]/' => 'Das Passwort muss mindestens ein Sonderzeichen enthalten.',
                '/^.{10,}$/' => 'Das Passwort muss mindestens 10 Zeichen lang sein.'
            ]
```

### Is your feature request related to a problem? Please describe.
Bad UX when using more than one password rule

### Describe the solution you'd like
Display all rules if the password does not match at least one of the rules.  
Ideally the rules which are not matching are shown red, the others green.

### Describe alternatives you've considered
Show all rules at any time in a pop-up or so.

**Comment by marc-farre** [comment]
It would require adding Attribute Hints for:
- `humhub\modules\user\models\forms\Login::$password`
- `humhub\modules\user\models\Password::$newPassword`

But we cannot directly use the rules from the User `Module::getPasswordStrength()`, because if there are many rules (e.g. https://docs.humhub.org/docs/admin/security/#password-strength-configuration), the hint would be too long and messy.

I suggest adding a new attribute to the User `Module` class. E.g. `Module::$passwordHint` [here](https://github.com/humhub/humhub/blob/1636be6ea95697ea80c49184143b66762159f04d/protected/humhub/modules/user/Module.php#L129).
It would be null, but the value could be added from the configuration file.

In the `Login` and `Password` classes, we would use it only if not null and allow translations this way:

```php
    public function attributeHints()
    {
        return $module->passwordHint ? [
            'newPassword' => Yii::t('UserModule.base', $module->passwordHint),
        ] : [];
    }
```

What could be added:
If `$module->passwordHint` is empty AND `Module::getPasswordStrength()` has only one array element, we display the message.
This way, when no custom configuration is added, we would display [this](https://github.com/humhub/humhub/blob/1636be6ea95697ea80c49184143b66762159f04d/protected/humhub/modules/user/Module.php#L269-L269):
> Password needs to be at least 5 characters long.


@luke- what do you think? Would you accept such a PR?

**Comment by luke-** [comment]
@marc-farre Sounds like a good interim solution.

In the long run, we should develop a new password field with strength indiciator.

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/7272
