### ISSUE TITLE
Guide is stopped when clicking on disabled `Next` button

### ISSUE THREAD

**Issue by timaschew** [humhub/humhub#5434]
### What steps will reproduce the problem?
Start the interactive guide/tour and go to the end of one. The button `Next` is disabled but if you click there the guide is stopped. Same happens if you press on the keyboard the `right arrow` key.

### What is the expected result?
Since a click outside of the guide/tour box is not doing anything (not closing the box, not stopping the guide) the disabled button and the right arrow key should have the same behavior.

Alternatively the `Next` button could start the next guide, for that use case it would make sense to rename it from `Next` to `Continue` or something like that. It means it the button shows `Next` for the next step and `Continue` to load the next guide.

### What do you get instead?
The guide box is closed and the guide is stopped. The user is redirected to the dashboard.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.2
| PHP version      |  Try Out instance
| Operating system | Try Out instance

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5452: I could only hide the disabled buttons, but the press event on the key `right arrow` still works as before, it executes the same event as button "End guide" does, because it is coded inside the external bootstrap library and we cannot modify the code here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/tour/resources/js/bootstrap-tourist.js#L2123.

<img width="286" alt="hidden_buttons" src="https://user-images.githubusercontent.com/6995524/144181614-fa299955-720a-4180-a599-6890571b8bf8.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks for the fix! This should be sufficient!
