### ISSUE TITLE
Isn't the translation file corrupted?

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#5480]
humhub\protected\humhub\modules\admin\messages\el\base.php L:54

https://github.com/humhub/humhub/blob/9441680ea372741a212741bfb70df4725bc8b04a/protected/humhub/modules/admin/messages/el/base.php#L1-L59
| Q                | A
| ---------------- | ---
| HumHub version   | 1.10.0 - 1.10.3

**Comment by yurabakhtin** [comment]
@luke- The bug was created here https://github.com/humhub/humhub/commit/7997963#diff-cd058b06d1908fcafaecead6eaa9ad02120009b3a2746a4a0ef304c190b83b56R54. I don't know how it was created either manually or there is a bug of the command, but if I run `php yii message/extract-module admin` I cannot reproduce this, see what I have after run the command https://github.com/humhub/humhub/pull/5481/files#diff-cd058b06d1908fcafaecead6eaa9ad02120009b3a2746a4a0ef304c190b83b56R52 .

**Comment by luke-** [comment]
@yurabakhtin Ok, maybe there was a problem with our translation tool here.

Can you please correct only the syntax error in the PR and not recreate the files? Otherwise there will be too many conflicts when we use our translation tool.

**Comment by yurabakhtin** [comment]
@luke- Ok, I have reverted the changes and keep only in the single file https://github.com/humhub/humhub/pull/5481/files.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
