### ISSUE TITLE
Check PHP 8.1 Support

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5552]
Yii is already updated to 2.0.45 
- See tests: https://github.com/humhub/humhub/actions/runs/1833164829

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5561 - fixed errors for PHP 8.1 only what I found on web version, but tests are broken, because I cannot find a solution yet here:

<img width="922" alt="test_error_upload_file" src="https://user-images.githubusercontent.com/6995524/153889371-3bd4d2c7-a5bb-4576-af50-0aa48d02f3c4.png">

I just find that code `\yii\helpers\BaseFileHelper::getMimeType($file, $magicFile = null, $checkExtension = true)` line 166:

```php
if (PHP_VERSION_ID >= 80100) {
    return static::getMimeTypeByExtension($file, $magicFile);
}
```

and here result is `null` because the uploaded file has a name like `/Applications/MAMP/tmp/php/phpXcqG6X` without expected extension `.jpg`.
I will try to find a solution later.

**Comment by yurabakhtin** [comment]
@luke- I still cannot find a solution, but all uploading forms are broken currently on php 8.1:

<img width="869" alt="logo_upload_bug" src="https://user-images.githubusercontent.com/6995524/154020325-11b43ce6-94eb-4cf1-b965-0bcc7dd73033.png">

I guess yii developers fixed some issue here https://github.com/yiisoft/yii2/commit/1271bc419ffaa2ac0e4db7d2eabea349ac5e4ace#diff-a24265ff97a3e4b91fb816aaf401c9d8f80a837bdf23ccfb9576263f15151ed6R165-R167 by the added code:

```php
if (PHP_VERSION_ID >= 80100) {
    return static::getMimeTypeByExtension($file, $magicFile);
}
```

but I cannot understand why uploading is broken at all.
I think they added the code because a return result of the function `finfo_open()` was changed from `resource` to `finfo` as described here https://www.php.net/manual/en/function.finfo-open.php#refsect1-function.finfo-open-changelog.
I.e. they added the code in order to don't run below code on PHP >= 8.1 versions:

```php
$info = finfo_open(FILEINFO_MIME_TYPE, $magicFile);

if ($info) {
    $result = finfo_file($info, $file);
    finfo_close($info);

    if ($result !== false) {
        return $result;
    }
}
```

I am not sure how the code `return static::getMimeTypeByExtension($file, $magicFile);` can return string like `image/jpeg` when `$file` is `/Applications/MAMP/tmp/php/phpXcqG6X` has no extension.

If rewrite the code for php 8.1 version:

```php
$info = finfo_open(FILEINFO_MIME_TYPE, $magicFile);

if ($info instanceof \finfo) {
    $result = $info->file($file);

    if ($result !== false) {
        return $result;
    }
}
```

it will returns expected `image/jpeg` as it worked for PHP < 8.1, but then I got another bug, that I have same if I disable `checkExtensionByMimeType` on rules side:

<img width="1403" alt="bug_upload" src="https://user-images.githubusercontent.com/6995524/154023128-c308e5b9-a84f-41e8-9c51-4362cb46dc5a.png">

and here I stopped because I don't understand why the error appears: `During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of Imagine\Image\Metadata\MetadataBag::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /www/humhub/humhub/protected/vendor/imagine/imagine/src/Image/Metadata/MetadataBag.php:70`
because for me it looks all compatible:

<img width="707" alt="compatible_issue" src="https://user-images.githubusercontent.com/6995524/154023915-c5dc665d-ce32-47fb-8732-e906704381d5.png">

Could you please try to upload any file on your side with php 8.1, maybe these bugs only on my php version?
Thanks.

**Comment by yurabakhtin** [comment]
@luke- All above tests I did on php 8.1.0, but right now I installed 8.1.1 and it has the same issues.
PHP < 8.1.0 has no such bugs.

**Comment by luke-** [comment]
@yurabakhtin See here: https://github.com/yiisoft/yii2/issues/19243

**Comment by yurabakhtin** [comment]
@luke- I don't find there a solution for our case. As I understand there was problem in wrong rule with `.` instead of correct `,` (`'extensions' => "jpg,jpeg,png.gif"`), but we have correct rules like `'extensions' => 'png, jpg, jpeg'`.

They did a fix and here https://github.com/yiisoft/yii2/pull/19246/files#diff-a24265ff97a3e4b91fb816aaf401c9d8f80a837bdf23ccfb9576263f15151ed6L165-L167 the code was deleted, so in next version 2.0.46 it will be deleted:

```php
if (PHP_VERSION_ID >= 80100) {
    return static::getMimeTypeByExtension($file, $magicFile);
}
```

but if I deleted this code on my side then I have the same error when I use the option `'checkExtensionByMimeType' => false` for a file rule: 

<img width="1234" alt="fatal_error" src="https://user-images.githubusercontent.com/6995524/154907199-12dea3c4-414b-4293-b07c-2c5ae38732a0.png">

So I am not sure their fix solved current issue even in yii 2.0.46 for php >= 8.1.

**Comment by luke-** [comment]
@yurabakhtin I've tested with `composer require --dev yiisoft/yii2:dev-master` and on my system with PHP 8.1.3 the uploads seems to work.

Can you please retry?

**Comment by yurabakhtin** [comment]
@luke- After run `composer require --dev yiisoft/yii2:dev-master` the file validator issue is fixed, but I still get the error:

`During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of Imagine\Image\Metadata\MetadataBag::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /humhub/protected/vendor/imagine/imagine/src/Image/Metadata/MetadataBag.php:70`

Then I go to the file `/vendor/imagine/imagine/src/Image/Metadata/MetadataBag.php` and modified that as described in the error message, i.e. `public function offsetExists($offset)` => `public function offsetExists($offset): bool`, so totally I modified the file in 6 places:

<img width="1148" alt="MetadataBag_errors" src="https://user-images.githubusercontent.com/6995524/154942518-5e1853b2-ca8f-4d9f-a5d5-43c4d6f0123a.png">

and after these fixes I can upload **images** on my side, note if upload **not image** file then no such errors.

I think the file https://github.com/php-imagine/Imagine/blob/develop/src/Image/Metadata/MetadataBag.php should be updated for php version >= 8.1.
