### ISSUE TITLE
Prevent space creation 

### ISSUE THREAD

**Issue by max2020** [humhub/humhub#558]
Is it possible to forbid the creation of spaces for users ?

**Comment by acinelli** [comment]
In admin settings, use or create a default user group.  Within group, you can set members not allowed to create public / private spaces.  Then in "authentication", set the default user group to this group.

**Comment by prateekvarma** [comment]
@tcinelli , so the new users will still be able to create new groups?
Is there a way that only an admin can add groups (or spaces), and not a user?
Thanks.

**Comment by Felli** [comment]
As @tcinelli mentioned, in `Adminisation > User Settings > Groups > Default group > Permissions` you can change the settings for this.

**Comment by anjanikumartsvs** [comment]
> @tcinelli , so the new users will still be able to create new space?
> Is there a way that only an admin can add spaces), and not a user?
> Thanks.

All the said options here work fine . But ,Yes there is a way to achieve your goal by modifying code.. 
Modify the below condition from 'spaceChooser.php' from below path (to test some options)
<humhub>\protected\humhub\modules\space\widgets\views\

<?php if($canCreateSpace) : ?> to  <?php if(Yii::$app->user->isAdmin() && ($canCreateSpace)) : ?>

Then it is visible only to admins in 'My Spaces'. Anyways , since admin can create space from Administration Menu, if you want to remove this option from My Spaces for all, remove this condition and associated html code in that <li>...</li>...
It's risk while upgrading to new version, but if you take proper care by versioning, this is fine..
Let me know how it works...

Thanks,
AnjaniKumar
