### ISSUE TITLE
Searching by keywords in a space

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#5584]
Related to https://github.com/humhub/humhub/issues/4298 and https://github.com/humhub/humhub/issues/1358

### Is your feature request related to a problem? Please describe.

Today (Humhub 1.10) it is possible to search by keywords in a space, but the process is not easy.
You need to search for a keyword in the global search field, click on "Advanced search settings" and add a space.

This is not intuitive: users who wish to search for a keyword in a space click on "Filter" on the stream:
![image](https://user-images.githubusercontent.com/23310825/156574093-df150dee-b501-4595-824c-b9598e5e03d8.png)

### Describe the solution you'd like

Adding a search field in the space's filter block:
![image](https://user-images.githubusercontent.com/23310825/156574829-5f5d3f62-6f4d-472a-a6cf-a223545ca729.png)

**Comment by lisandi** [comment]
Not only the search for keywords is missing but also an option to define other categories. Right now you have only the chance to define one category but especially in bigger projects, it would be necessary to have a combination of categories available. i.e. Show all spaces in [category] Forums in [Language] German and located in [Austria]
That would make just as an example 3 lists of categories one for the actual category, another that defines the Language as in many countries you need to foster Forums in different languages i.e. right now in Ukraine with so many refugees coming to specific countries and therefore we need also the last one [locations]. Additional for all those subcategories would be very helpful.

1. Forums for Children, Forums for Adults, Forums for Refugees, and others for those who Help 
2. Languages - i.e. German, German-Suisse, German Austria, etc. 
3. Location - Country, Province, City, Region

Some of those search functionalities are actually available for people and could be ported to spaces.

This functionality is necessary because besides having keywords (you can enter right now not even a combination of them) it is necessary to have an easier way instead of having to open space and then searching for one that contains a certain keyword and then clicking on that keyword to list all spaces that contain that keyword.

**Comment by luke-** [comment]
I'm closing the issue for now because of the new search. Maybe it would make sense to open a more specific issue e.g. ‘Add Search in Filter Panel’, if required.
