### ISSUE TITLE
Check Content/Comment Creation On Demand

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5602]
We need to create a way to check the permission to create contributions (e.g. posts/comments) via Events on demand.

The Event (the check if it is allowed or not) should only take place after clicking into the text field. Possibly, the test should also be repeated at an interval during writing, should something change during writing. This is necessary to ensure performance during potentially costly checks.

Ideally, the Event also contains a text attribute with the text content and a reference to the content_id.

If the event is `isValid=false` and contains an `errorMessage`, the TextField should be grayed out to the user and the error message should be displayed. 

Some modules and audits are thinkable here: 

- The user may write only a certain number of contributions in a period of time
- Spam Check (using the content text field)
- Muted user: The user cannot create contribution for a period of time
- ...

**Comment by yurabakhtin** [comment]
@luke- I didn't start to implement this yet because not fully clear so please read my questions:

> The Event (the check if it is allowed or not) should only take place after clicking into the text field. Possibly, the test should also be repeated at an interval during writing, should something change during writing. This is necessary to ensure performance during potentially costly checks.

As I understand we need to bind to JS events "click/focus on the text field" some new ajax action, where we will check if current user can post new content. Also we need probably to repeat the checking at some interval for example send the same check ajax request each 10 seconds, or 1 minute, right? I am afraid such interval requests event each 1 minute may create a server slower unfortunately.

What if run the checking action only once on load the text field on php/server side, and also we can check the same on post the content before saving.

> Ideally, the Event also contains a text attribute with the text content and a reference to the content_id.

Ok for text content, but I think on a creating time the `content_id` is unknown yet, also the table `comment` has no `content_id`, but yes we can get it from parent object.

> If the event is `isValid=false` and contains an `errorMessage`, the TextField should be grayed out to the user and the error message should be displayed.

"grayed" - do you mean just to change the background color, or also to make it disabled? I think we should not disable it, for that case to allow user to fix spam words in content, right?
The error message should be displayed as hint tooltip or as red text under field?

> Some modules and audits are thinkable here:

Should I start to implement at least one such event processor? I think yes, because it will be easier to implement the new event trigger.

**Comment by yurabakhtin** [comment]
@luke- 

> What do you mean? You mean directly implement a sample check?

Yes, I think it would be good if we will implement at least one(from these 3 what you provided) case, where the new trigger event is used. Or do you prefer just add new triggers and keep them not used, so they will be used only in future by some external(not core) modules?

**Comment by yurabakhtin** [comment]
@luke- 

> Yes, let's to this in the first version. Of course, we have to check again when we actually save.

What if instead of implementing new event trigger we will use core event with config like:

```php
[Post::class, Post::EVENT_BEFORE_VALIDATE, [Events::class, 'onPostValidate']],
```

so it will works like this:

```php
    public static function onPostValidate($event)
    {
        /* @var Post $post */
        $post = $event->sender;

        if (strlen($post->message) > 255) {
            $post->addError('message', 'Message is very long!');
            $event->isValid = false;
        }
    }
```

![test_event_before_validate](https://user-images.githubusercontent.com/6995524/161729893-449d22d8-def4-4f12-bd39-9650a943907b.png)

Or do you wanted some another UI?

**Comment by yurabakhtin** [comment]
@luke-

>Wouldn't there be an error right at the beginning, "Must not be empty?"

Sorry, not clear what you mean here.

In my sample code I used the event `EVENT_BEFORE_VALIDATE`, it is called before start to check fields by rules, i.e. if the event does `$event->isValid => false` then other rules will not be applied.
Also after executing of all model's rule validators we can use event `EVENT_AFTER_VALIDATE`.

The code is written in the class `yii\base\Model`:

```php
public function validate($attributeNames = null, $clearErrors = true)
{
    if (!$this->beforeValidate()) { // <= here EVENT_BEFORE_VALIDATE
        return false;
    }

    # Rules of the current Model/ActiveRecord is executed here...

    $this->afterValidate(); // <= EVENT_AFTER_VALIDATE

    return !$this->hasErrors();
}
```

**Comment by luke-** [comment]
> @luke-
> 
> > Wouldn't there be an error right at the beginning, "Must not be empty?"
> 
> Sorry, not clear what you mean here.
> 
No empty posts/comments are allowed. There should be a validation rule for this.

If we now start a validation when clicking into the comment/post field, it should always return an error. (Cannot be empty)
We need then something like an "allowEmpty" for the Ajax Validation.

Otherwise I think your approach is good, if possible we should stick to `ActiveForm::enableAjaxValidation` if possible.

**Comment by yurabakhtin** [comment]
@luke- Please see my test with for the "allowEmpty":

![test_empty_content](https://user-images.githubusercontent.com/6995524/161968102-376d7ffe-dcb5-4273-ae23-1b1720bc914d.png)

---

For the post create form we don't use `ActiveForm`, there is a code:

```php
Html::beginForm($submitUrl, 'POST', ['data-ui-addition' => 'acknowledgeForm']);
```

Here we cannot use the `enableAjaxValidation`.

**Comment by luke-** [comment]
@yurabakhtin Ok that sounds good!

So do I understand it correctly that we can just use the existing BEFORE_VALIDATE/AFTER_VALIDATE events.

And we just add a AJAX check  in the frontend/UI on focus and before send?

**Comment by yurabakhtin** [comment]
@luke- 

> So do I understand it correctly that we can just use the existing BEFORE_VALIDATE/AFTER_VALIDATE events.

Yes.

> And we just add a AJAX check in the frontend/UI on focus and before send?

No, ajax/client checking doesn't work on the create new post form, because there is no `ActiveForm`.
However on the edit post form we have the `ActiveForm`, but there is no effect even when I added options `'enableClientValidation' => true` and `'enableAjaxValidation' => true`.

Should I find a solution to enable ajax/client checking for the create/edit post forms?

**Comment by luke-** [comment]
> @luke-
> 
> > So do I understand it correctly that we can just use the existing BEFORE_VALIDATE/AFTER_VALIDATE events.
> 
> Yes.

Thats perfect.

> 
> > And we just add a AJAX check in the frontend/UI on focus and before send?
> 
> No, ajax/client checking doesn't work on the create new post form, because there is no `ActiveForm`. However on the edit post form we have the `ActiveForm`, but there is no effect even when I added options `'enableClientValidation' => true` and `'enableAjaxValidation' => true`.

Somehow we have to implement an Ajax Logic, because the event should be triggered after the click.

Of course it would be best to use Yii2 components/logic if possible. But if this is not possible, we can implement our own AJAX logic.

> Should I find a solution to enable ajax/client checking for the create/edit post forms?

**Comment by yurabakhtin** [comment]
@luke- 

> Somehow we have to implement an Ajax Logic, because the event should be triggered after the click.
>
> Of course it would be best to use Yii2 components/logic if possible. But if this is not possible, we can implement our own AJAX logic.

My previous code from the comment https://github.com/humhub/humhub/issues/5602#issuecomment-1088507864 doesn't on client side validation, it works only after submit form.
In order to do validation on client side we should use a code like from PR https://github.com/humhub/humhub/pull/5645, but it works only with simple fields.
The client side validation doesn't work for widget `RichTextField` even if we define rules right in the ActiveRecord without event trigger. I think firstly we should change the widget `RichTextField` somehow in order to make client validation working if we need it. Should I find a solution for this?

**Comment by yurabakhtin** [comment]
@luke- Yii2 validators don't have possibility to check field on focus event. It has only options: `validateOnChange`, `validateOnBlur`, `validateOnType` - https://www.yiiframework.com/doc/guide/2.0/en/input-validation#ajax-validation.
So I decided to implement new separate option `focusUrl` for the RichTextEditor here https://github.com/humhub/humhub/pull/5645/commits/395917537cbfabb61e6950286ba09a60b3691e51:

- The new option `focusUrl` can be defined from external module event like here https://github.com/humhub/humhub/pull/5645/commits/395917537cbfabb61e6950286ba09a60b3691e51#diff-1e416e0a1f88b590076f8b7df0b48f82a8d45e46ab1d6afeb9f1932488bab58aR69
- new rule also can be added from external module event like here https://github.com/humhub/humhub/pull/5645/commits/395917537cbfabb61e6950286ba09a60b3691e51#diff-1e416e0a1f88b590076f8b7df0b48f82a8d45e46ab1d6afeb9f1932488bab58aR46
- action for validation can be written in external module like this https://github.com/humhub/humhub/pull/5645/commits/395917537cbfabb61e6950286ba09a60b3691e51#diff-d47476863657fd72e21ff4461f800efee7289a4c8641efa9f3169c65a39da4b6R104

Please check the mechanism, of course it is not ideal yet and probably have some issues, but if it is what is required then we can continue to improve it.

**Comment by luke-** [comment]
@yurabakhtin Hmm, somehow I don't like the solution with the focusURL in the RichTextField.

Can you try a solution with Yii2 onBlur/onChange (i.e. without focus).

Maybe then focus can be triggered manually somehow?

**Comment by yurabakhtin** [comment]
@luke- Ok, I reverted the commit and started validation by AJAX here https://github.com/humhub/humhub/pull/5645/commits/dbd3e9837c71b8ccf9a56bbf723dcc501b94ac85, but it is not completed yet.

**Comment by luke-** [comment]
@yurabakhtin Looks good to me. With this approach we can support ActiveForms and NonActiveForms in the same way or?

**Comment by yurabakhtin** [comment]
@luke- 

> With this approach we can support ActiveForms and NonActiveForms in the same way or?

In the commit above I already did a change here https://github.com/humhub/humhub/commit/dbd3e9837c71b8ccf9a56bbf723dcc501b94ac85#diff-c7a984c2524e612a97175a575de5e73d01058d9c5b6f89e1364a874c9898e06dR45 in order to use `ActiveForms` in all cases because I am not sure it will be possible to apply the event trigger for NonActiveForms.

**Comment by yurabakhtin** [comment]
@luke- Please review the latest changes in the PR https://github.com/humhub/humhub/pull/5645/files and test how it works on create new Post from space wall.

- In order to test how AJAX checking works - just click on the post message field and then focus out, so action defined here https://github.com/humhub/humhub/pull/5645/files#diff-a092d5282f7c97b2fbe215cb8fef23616ec523403b8dab95785eae229e576a73R30 `/post/post/validate-new-post` will be called for verifying.

- This event code https://github.com/humhub/humhub/pull/5645/files#diff-1e416e0a1f88b590076f8b7df0b48f82a8d45e46ab1d6afeb9f1932488bab58aR39-R51 was implemented only for testing and will be deleted if we need this from another external module, or we can modify it if some new core settings will be added for control posting.

- Please note here https://github.com/humhub/humhub/pull/5645/files#diff-a092d5282f7c97b2fbe215cb8fef23616ec523403b8dab95785eae229e576a73R45 I added new param, so we need to update at least one external module `Poll` here https://github.com/humhub/polls/blob/master/widgets/WallCreateForm.php#L21. We need this because now the create form should be `ActiveForm`.

**Comment by yurabakhtin** [comment]
@luke- Yes, the `ActiveForm` ajax checking is used for checking now.

> Can you find a solution for this?

Commit https://github.com/humhub/humhub/pull/5645/commits/e22a2490000ca85e7dd2b73546d0642d5c1de462.
Please note for validation all rules are used, so when message is empty user will see the message "Message cannot be blank." because this rule `[['message'], 'required']` is defined in core model `Post`.

**Comment by luke-** [comment]
@yurabakhtin I like that with all the rules, however we need to skip the Required rule somehow. Can you look here for a solution?
I hope that it will be possible without dirty hacks.

**Comment by yurabakhtin** [comment]
@luke- Please review the commit https://github.com/humhub/humhub/pull/5645/commits/63908a84d9bb0c43d11457f99bc2d959f8026ae5, I hope it doesn't look as hack.

![ajax_vs_submit_empty_post_message](https://user-images.githubusercontent.com/6995524/170515942-3e747608-f11d-40f8-a8c8-7ccd743b454c.png)

**Comment by luke-** [comment]
@yurabakhtin Thank you that is a nice solution! Had no approach of it at my own and wasn't sure how... :-)
Can you please take a look into the Dummy Module task.
