### ISSUE TITLE
How to "include beta updates" in the new module marketplace (Humhub 1.11)?

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#5637]
### Is your feature request related to a problem? Please describe.

Since the new modules' marketplace is released in Humhub 1.11, I do not find anymore the setting allowing to "Include beta updates".

Previously, it was in the `/marketplace/update` page ("Available updates").

**Comment by luke-** [comment]
@yurabakhtin Wasn't there a settings dialog somewhere?

**Comment by yurabakhtin** [comment]
@luke- Old UI:

![old_modules](https://user-images.githubusercontent.com/6995524/163559605-9bdc4af3-bf8a-4ddf-8849-f914d51c2f07.png)

new UI:

![new_modules](https://user-images.githubusercontent.com/6995524/163559601-e96ab530-c9be-497f-8c0d-5d557b301631.png)

We should either add the checkbox somewhere on new UI, or always include beta updates, because currently we use the last stored value in `Yii::$app->getModule('marketplace')->settings->get('includeBetaUpdates')` and user cannot change this value anymore, that is wrong.

**Comment by luke-** [comment]
We can open a lightbox here with a simple form with settings.

For now, just the one checkbox:
- Allow module versions in beta status

![image](https://user-images.githubusercontent.com/4736168/163602698-c21cfd11-5f27-4f24-8e0e-ec86773b865a.png)

Later we can add more Marketplace / Module specific options if necessary.

What do you think?

**Comment by ArchBlood** [comment]
> We can open a lightbox here with a simple form with settings.
> 
> For now, just the one checkbox:
> - Allow module versions in beta status
> 
> ![image](https://user-images.githubusercontent.com/4736168/163602698-c21cfd11-5f27-4f24-8e0e-ec86773b865a.png)
> 
> Later we can add more Marketplace / Module specific options if necessary.
> 
> What do you think?
> 

Would also make sense to add a tooltip for what the cog is used for.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5643:

![module-filter-settings](https://user-images.githubusercontent.com/6995524/163806927-0168f3cb-2e5d-44d4-9d76-ff2e29d4576d.png)

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by funkycram** [comment]
Thanks!
