### ISSUE TITLE
Members modal in space header doesn't work as guest

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/humhub#5657]
### What steps will reproduce the problem?

Enable guest access.
Navigate to a public space as guest (e.g. private mode in browser).
Click on "X Members" (or "X Followers")

### What is the expected result?

Either the field should not be clickable at all.
Or the modal should be displayed and only show the profile pictures and names of public profiles. 

### What do you get instead?

The screen is kind of doubled (tested in Firefox and Chrome):

![Screenshot 2022-04-22 at 19-05-11 Willkommens-Space - Felix Hahn Development](https://user-images.githubusercontent.com/84990763/164765820-46bc608a-2a9f-4004-84bb-696e8078a563.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.11.1
| PHP version      |  8.0
| Operating system | Ubuntu

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

I do not get an error in the log section or in the browser console.

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/humhub/pull/5672.

The bug was created here https://github.com/humhub/humhub/pull/5435/files, please check my PR to be sure it is what required to do in the previous PR #5435, because I am bit confused with the title "Allow non modal links in header counter" and what was done there, it seems the title should be "**Deny** non modal links...".
