### ISSUE TITLE
Allow Admin to sort the Spaces in a custom order.

### ISSUE THREAD

**Issue by miteshprmr34** [humhub/humhub#5668]
Allow Admin to sort the Spaces in a custom order.

**Comment by funkycram** [comment]
@luke- would you accept a PR from me to add a sort attribute to the Space model, working the same way as the profile fields?

![image](https://user-images.githubusercontent.com/23310825/231504041-c83e091d-06c1-4a11-83f9-00d9e9034b83.png)

![image](https://user-images.githubusercontent.com/23310825/231504122-e4a6910a-9775-4641-bed7-bac7df4ea851.png)

Default value would be 100.

On the Space page, I would add an option named "Default" which will sort using the sort number, and for same numbers, by name:
![image](https://user-images.githubusercontent.com/23310825/231505838-7dc91847-d67d-40c0-bb30-b21d2349b9b9.png)

What do you think about it?
Do you anticipate any difficulties or updates of the automatic tests?

**Comment by luke-** [comment]
@funkycram Sounds good for me. Some thoughts on this:

- The SortOrder should only be set by a user with the ManageSpaces permission. Normal Space owners should not be able to rank their own Space higher than others.

- The field should be a "SortOrder" field type and placed in AdvancedSettings.

- I am a bit unsure with the naming of the "Default" sort order. Because usually `By Name` and `Default` would be the same. Also, sorting by size would be useful.

- Of course, it would be good to implement tests for this as well to ensure functionality.

**Comment by funkycram** [comment]
@luke- https://github.com/humhub/humhub/pull/6247

Thanks for your advises.

> I am a bit unsure with the naming of the "Default" sort order.

I haven't found any better name. Have you got a suggestion?

> sorting by size would be useful.

What do you mean about "size"? The number of members?

> implement tests

What type of test would we need?
I didn't find any tests about the `sort_order` field in the User module to have an example.

Thanks!

**Comment by funkycram** [comment]
@luke- Tests fails here: https://github.com/humhub/humhub/actions/runs/4747493377/jobs/8432472868#step:18:1411
It's about this test:
```php
        $space = new Space();
        $space->name = 'Test Space';
        $space->save();
        $this->assertFalse($space->isNewRecord);
```

It looks like if migration adding the `sorter_order` filed hasn't been done in the DB.
