### ISSUE TITLE
Some notifications about a comment redirects to the post instead of the comment

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#5693]
### What steps will reproduce the problem?

1. User 1 creates a post.
2. User 2 comments the post and tags User 2
3. User 2 click on the notification (in the bell's menu)

### What is the expected result?

4. User 2 is redirected to the comment of the post (the should be `&commentId=xxxx` at the end of the URL)

### What do you get instead?

4. User 2 is redirected to the post

### Additional info

This bug doesn't occurs all the time. Sometimes your are correctly redirected to the post.

Discussion: https://community.humhub.com/content/perma?id=255498

| Q                | A
| ---------------- | ---
| HumHub version   | 1.10 and 1.11

**Comment by samuk** [comment]
+1

**Comment by samuk** [comment]
For example, I would expect this URL: https://vive.transitiontogether.org.uk/s/transition-together/?contentId=515&commentId=201 to send me to the comment, rather than the top of the page.

**Comment by yurabakhtin** [comment]
@luke- As I understand from the comment https://community.humhub.com/s/feature-requests/?contentId=255498&commentId=41763 and one next, the problem was in that autoscrolling to selected/marked comments didn't work, so user saw only a page top with post message and not the single comment as expected.
I have done a fix for this in PR https://github.com/humhub/humhub/pull/5698

Also I tested different comment posting ways and reviewed the code and I didn't find a case where the param `&commentId=123` is missed.

**Comment by funkycram** [comment]
Thanks @yurabakhtin 

The fix you've done is great, as it was also a problem.

But the one I describe is different.
See the screenshots below which correspond to the steps described above:

![image](https://user-images.githubusercontent.com/23310825/168245864-2a4fb1e2-f5ef-4a33-81ee-037ae42866b9.png)
![image](https://user-images.githubusercontent.com/23310825/168246016-44977ae4-c3e9-467e-b325-28d69b31d21e.png)
![image](https://user-images.githubusercontent.com/23310825/168247730-43de283b-1b10-4a76-a197-2b0a45bef9a6.png)

**Comment by yurabakhtin** [comment]
@funkycram Thank you for the additional details!
Fixed in the next commit https://github.com/humhub/humhub/pull/5698/commits/620176f1f2a6218c89f851485ece245b23cf7cb3 of the same PR.

**Comment by funkycram** [comment]
Tanks a lot @yurabakhtin !

**Comment by samuk** [comment]
Thanks all :)
