### ISSUE TITLE
Add block button into profil

### ISSUE THREAD

**Issue by antho2305** [humhub/humhub#5751]
### Is your feature request related to a problem? Please describe.
It's complicated to block someone have to go to profil setting > setting -> block user
### Describe the solution you'd like
It would be great to have a button or icon to block user directly from the profil next to "follow" "ask friend" and the possitibily to report the user (without needing a post)
### Describe alternatives you've considered
nothing

**Comment by Raphaa2022** [comment]
I agree!

**Comment by luke-** [comment]
- Add the cog wheel button also to the profile, same as on Spaces e.g.
![image](https://github.com/humhub/humhub/assets/4736168/35f30afd-c6da-448c-95c0-93577e160817)
- Add "Block" feature
- For User admins, add an "Edit" option 
- If "Friendship" + "Follow" is enabled, move "Follow" into the new menu
- 
This menu will probably have further entries in the future, such as a "Report Profile"

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6689:

![user-menu](https://github.com/humhub/humhub/assets/6995524/6528c943-06b2-4546-848d-f140ced017aa)

**Comment by yurabakhtin** [comment]
> Can you please adapt?

@luke- Sorry, but I don't understand what to do.

Please note I used the icon `√` because it was used in previous button and it is still used on the "People" page:

![header-actions](https://github.com/humhub/humhub/assets/6995524/fd5bc2fb-7f3a-4864-93f8-5a045d7f71d1)
![people-card](https://github.com/humhub/humhub/assets/6995524/adb91634-11aa-4600-a9c1-a7bf43b399ef)

but the button "Follow" has no icon:

![follow-header](https://github.com/humhub/humhub/assets/6995524/68fd12ed-796b-4d54-abd5-d379ce7676fb)
![follow](https://github.com/humhub/humhub/assets/6995524/1b089398-21e8-4916-92b4-f1000fd91e7f)

**Comment by Semir1212** [comment]
@luke- @yurabakhtin Text ist fine

Follow button looks off: 

![image](https://github.com/humhub/humhub/assets/38326726/54bd8ebe-cadc-4545-af4d-6c94a134f631)

**Comment by Semir1212** [comment]
@yurabakhtin Just change "Confirm Action" to "Leave Space". Rest is fine.

**Comment by yurabakhtin** [comment]
@Semir1212 @luke- Done in commit https://github.com/humhub/humhub/pull/6689/commits/ded523f8eb504531fd02eca737e1276e3cd5f298:

![space-leave](https://github.com/humhub/humhub/assets/6995524/b575c37d-4237-4d70-8163-600a4ac23125)

![spaces](https://github.com/humhub/humhub/assets/6995524/a8f33ea7-4780-4c38-ba43-09f885957569)

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by Eladnarlea** [comment]
@Semir1212 @luke- We should rename the button text to "Leave" or even better "Leave space". From a UX point of view, it's clearer that way, especially because this is an action that can't simply be undone.

**Comment by luke-** [comment]
![image](https://github.com/humhub/humhub/assets/4736168/0fb8d65b-2847-405a-9486-c89e91c92b19)

Can you please rename the confirm leave space buttton to "Leave".

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6722:

![leave-btn](https://github.com/humhub/humhub/assets/6995524/85915ae8-43fc-4833-bcbd-69242ee1d8b7)

**Comment by Eladnarlea** [comment]
<img width="302" alt="Screenshot 2023-12-14 at 12 06 30 PM" src="https://github.com/humhub/humhub/assets/105652258/4719a7ea-5c64-4492-8abd-cf1f49811f60">

@luke- we should also review the logic regarding the `√ following ` and change it to `X unfollow` to uniform it. Actually this is a mistake in UI/UX Design because it is in the style of a button but it actually functions as a badge. Same for `√ friends ` `X unfriend`

**Comment by luke-** [comment]
@Eladnarlea Hmm, we should  create a separate issue for this.

I actually think it's nice that it says "√ follow" like a badge. I wouldn't like an unfollow button in this overview
