### ISSUE TITLE
Cron Broken: User Query `visible()` uses `getSession()`

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5830]
Regardless of the fact that the testmail can be sent, there are some logged errors. The first one is reducible by rebuilding the search index, the second/third one seems to be the result of the hourly tasks: 
![Bildschirmfoto 2022-08-04 um 08 33 59](https://user-images.githubusercontent.com/60502320/182807756-5353a465-5fec-469f-99d4-884a6ca4eb21.png)

_Originally posted by @smashm in https://github.com/humhub/humhub/issues/5826#issuecomment-1204976026_

**Comment by luke-** [comment]
@yurabakhtin Don't we need some kind of Visiblity Check? e.g. deactivated/semi-deleted users should never appear in search index.

**Comment by yurabakhtin** [comment]
@luke- I could not reproduce the bug by run commands:

```
php yii search/queue-rebuild
php yii queue/run
```

i.e. they are executed without errors and no errors in log.

Also I modified the command `humhub\modules\search\commands\SearchController::actionQueueRebuild` to:

```php
$job = new RebuildIndex();
$job->run;
```

so the command is executed right now without queue waiting, so I saw a result like this:

```
\humhub\humhub\protected>php yii search/queue-rebuild
..................................................................................................................................................................................................
```

i.e. no error too.

Then I decided to remove the `->visible()` as you can find in the PR https://github.com/humhub/humhub/pull/5831, because as I understand the code is executed only from CLI mode so no need to check the visibility relating to current logged in user, or am I wrong?

Probably the but is generated from some external module where the event `ActiveQueryUser::EVENT_CHECK_VISIBILITY` may be  handled, but I don't find such module.

**Comment by yurabakhtin** [comment]
@luke- 

> Don't we need some kind of Visiblity Check? e.g. deactivated/semi-deleted users should never appear in search index.

Ah such users... may be yes, ok I will review the `->visible()` again.

**Comment by yurabakhtin** [comment]
@luke- In the next commit https://github.com/humhub/humhub/pull/5831/commits/65d16e5d8a6a7ef11973218d27f209592f96d57c I added `->active()`, I think it is enough for CLI side.
If I remember in old version the `->visible()` just called `->active()` i.e. it was the same, but in new version the `->visible` was updated so it might creates the bug.

**Comment by smashm** [comment]
@yurabakhtin @luke- 

Added `->active()` manually, seems to work as it should, so that rebuilding the search index now works without errors. :)
