### ISSUE TITLE
Space About Page - Add possibility to show Members/Followers as List

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#5841]
### Is your feature request related to a problem? Please describe.

Especially with the Enterprise Theme it is not possible to open the user lists (members or followers) via the header. So it would be good to create this possibility on the about page.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/4736168/184479353-8b1e68f5-cf24-4ca8-9c19-effb37137039.png)

**Comment by yurabakhtin** [comment]
@luke- If I have understood this correctly:

- Bind a click action for the Headline same as Collapse/Expand does,
- Add new option "Show as List", on click it will looks like this:

![list](https://user-images.githubusercontent.com/6995524/185067225-6323cbae-efc6-49fc-80ab-7e0ce2258805.png)

And the option will be renamed to "Show as Grid" after switching.
Should we store the view mode per current User in cookie, seession or db?

**Comment by luke-** [comment]
@yurabakhtin No, simply open a modal like when click here:
![image](https://user-images.githubusercontent.com/4736168/185172263-6a465a0b-dd7d-4c06-9fb6-455b85eae2bc.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5847:

![members-followers](https://user-images.githubusercontent.com/6995524/185334275-2803f23c-5cdb-4ada-9e72-82d9cdc6fe5a.png)

Please note the new option "Show as List" is displayed by deprecated property `\humhub\widgets\PanelMenu->extraMenus`, because I don't find another property to add option there.
