### ISSUE TITLE
Remove Topic Filter on Dashboard until Global Topic Support

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#5861]
If two users tag their own posts with the same Topic, these topics are duplicated and show separate results in the Dashboard filter, even though they appear to be identical.

For example, I have several posts in a "Video" topic, and another user has done the same thing.  When I type the word "Video" in the Topic textbox of the Dashboard filter, it drops down a list with "Video" listed twice.  Depending on which "Video" I click on, I get either my own posts or the other user's posts, but not both.  And there's no way to tell which is what from the filter selector.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.1

**Comment by luke-** [comment]
Probably the only solution at the moment would be to remove the Topic Filter option on the dashboard.

Clicking on a topic in the dashboard stream also opens the container stream (Profile or Space) instead of filtering directly.

Related: https://github.com/humhub/humhub/issues/3615

**Comment by miqrogroove** [comment]
It's a very minor bug, so removing Topic filters should not be a high priority.  If I may suggest, I would rather see this one fixed first:

#5495

**Comment by ArchBlood** [comment]
@luke- I believe now that the Trending module has been published on @GreenMeteor this issue seems to display more issues, and I can also confirm the duplication of Topics.
![Screenshot_1](https://github.com/humhub/humhub/assets/35392110/4e8bf851-e200-48ff-b3b2-688dbb6ad56c)
![Screenshot_2](https://github.com/humhub/humhub/assets/35392110/586501aa-7017-4d0f-a976-f33ae9b571cf)
![Screenshot_3](https://github.com/humhub/humhub/assets/35392110/305545c1-35e2-4bb7-832f-10fb11c8cabd)
![Screenshot_4](https://github.com/humhub/humhub/assets/35392110/94741695-f400-4a8d-b1fa-caee3d5c4d32)
![Screenshot_5](https://github.com/humhub/humhub/assets/35392110/862fa4ff-bb27-436d-8d5c-cb8d71e23676)

I believe it's only possible because of Select2?

**Comment by marc-farre** [comment]
With 1.17, we now have Global Topics.

**Comment by luke-** [comment]
@marc-farre I'll close this. or speaks anything against?
