### ISSUE TITLE
Replied comments accessed by a notification hide next replies

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub#5956]
### What steps will reproduce the problem?
You need at least 3 users. User A, User B and User C.

1) User A Create a message.
2) User B comment the message.
3) User C reply to this comment.
4) User A reply to this comment.
5) User B reply to this comment.
6) User C reply to this comment.

User A receive a notification for a comment.
When user A click on this notification, it leads to -> step 5.
the User B reply is yellow and there are no other comment displayed after this one.
So your answer may be incomplete as User A hadn't see the comment on step 6.

### What is the expected result?
You should see all the comments.

### What do you get instead?
The comment linked to the notification, and the previous one. Not the next one.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.12.2
| PHP version      |  8.1
| Operating system |

**Comment by Reuns** [comment]
I have this behavior since a version or 2.

The notification I have
![1 Notification](https://user-images.githubusercontent.com/19529531/204847951-338d3a9e-595a-48ae-9816-83e73d4742a6.png)

What I get when I click on the notification
![2 Click on notif](https://user-images.githubusercontent.com/19529531/204847978-f0727074-431f-4f77-8dd9-36f34ca95ad5.png)

What I really have if I use the post/message permalink (not the comment)
![3 - Reality](https://user-images.githubusercontent.com/19529531/204848003-027a6687-fa6f-4005-ad54-555b4c751ee4.png)

**Comment by yurabakhtin** [comment]
@Reuns 

> What I really have if I use the post/message permalink (not the comment)

Do you really see more 2 comments right after page loading?
I see only 2 comments and others can be displayed by click on the link "Show all X comments":

![post_permalink](https://user-images.githubusercontent.com/6995524/205037999-a9bc2a98-103f-4b50-8bcf-bdf882aa957e.png)

---

> What I get when I click on the notification

Yes, by default we display only 2 comments:

![comment_permalink](https://user-images.githubusercontent.com/6995524/205039670-9c62758c-fc56-45ef-a715-319bac6f921d.png)

@luke- Do you think we should display all comments on load a comment permalink page?

**Comment by Reuns** [comment]
That's ok if we don't see the previous comment, but at least, we should see all the new comment that were written after the one in the notification.
More than once I've got disapointed by answering something that was already answered.
And many users still haven't see that their might be more comments waiting ...

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/5981 - I have done to display all newer comments after the current comment:

![display_more_newer_comments](https://user-images.githubusercontent.com/6995524/208381551-453dc512-929b-43c4-9895-5f562e235aad.png)

**Comment by funkycram** [comment]
I think this is much better, as we need to know what's new since the viewed comment before replying. Thanks @yurabakhtin !

**Comment by Reuns** [comment]
So nice ! This is exactly what we needed ! Thank you so much @yurabakhtin.

**Comment by luke-** [comment]
@yurabakhtin What happens if there are a lot of comments, e.g. 1000 and I send a direct link to the first/oldest comment.
Are all other comments including subcomments really loaded and displayed as well?

It would be important that we would have some kind of pagination here as well.

**Comment by Reuns** [comment]
Then you should display x next comment and a button below for the next comment.  (you have to define x, like 5 or 10 comments)
But the button above is useless as people don't understand.

**Comment by yurabakhtin** [comment]
@luke- Yes, it works as you wrote above, we should improve this indeed.

How it works currently:

For example, if we have 25 posted comments:

1) Load a permalink of the 4th comment:

- We see comments from 3rd to 25th, and the 4th is highlighted with yellow background,
- On click by "Show all 25 comments" we see loaded only the 10 latest comments, from 16th to 25th,
- Then on click "Show 10 more comments" => 10 older comments are loaded, so we see from 6th to 25th comments,
- Then on click "Show 5 more comments" => see comments from 1st to 25th.

2) Load a post link:

- See 2 latest comments, from 24th to 25th,
- On click "Show all 25 comments" => 10 latest comments, from 16th to 25th,
- On click "Show 10 more comments" => from 6th to 25th,
- On click "Show 5 more comments" => from 1st to 25th.

---

a. I think the text  "Show all 25 comments" sounds wrong, because really in all cases it loads only the latest/newest 10 comments, so maybe it would be better to rename it to like "Show 10 latest comments".

b. Then if we display the "Show 10 more comments" above the comments, more correct text is "Show 10 previous comments" or "Show 10 older comments".

c. Yes, it is not good to display all 1000+ comments after the currently selected comment as I implemented here, so we should limit the list, for example, with 10 comments, we could display 1 comment before the selected comment and 8 comments after.
  c.1. Also if we have more comments below, we should add new link like "Show 10 next comments" or "Show 10 newer comments", this link will be located under the comments list, so on click the loaded comments will be appended under the list.
  c.2. We still need to keep the current link above the comments list in order to load previous/older comments, but there we need some changes as I described above.

Please tell me what you agree, thanks.

**Comment by luke-** [comment]
@yurabakhtin I'm not sure that I fully understood your plan, but it would like/agree to introduce such new links. Above comments as suggested ("Show X older comments") and below ("Show Y newer comments"). 
When a permalink has been viewed, then show X comments before it and Y comments after it by default. Of course, this must also work for sub-comments.

In the long term, we should also completely refactor the comment section, but this will be a topic in a few later major versions.

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub/pull/5981/commits/4d02e6a0c637eca2bb4a52ed7a92f5165de568d3 - please review how it works now:

![new_show_comments_links](https://user-images.githubusercontent.com/6995524/212684440-a609c834-1517-4ddb-968e-0bd49b1f3ca0.png)

**Comment by luke-** [comment]
Merged in v1.14 branch.
