### ISSUE TITLE
Warning Invalid session auth key attempted

### ISSUE THREAD

**Issue by noman-maken** [humhub/humhub#5965]
The error logs are full of warnings

`Invalid session auth key attempted for user '664' from 103.186.76.178: 4ae01737-a8bc-43a7-bfeb-77956220d759
`

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Version: 1.13.0-beta.2
| PHP version      | Version - 8.1.13

**Comment by luke-** [comment]
With version 1.13 the session auth key changes, so these messages are correct. However, we should try to suppress them.

@yurabakhtin Do you have any idea here?

**Comment by yurabakhtin** [comment]
@luke- I have investigated the code, so the warning is generated in the core of yii2 in the method `yii\web\User->renewAuthStatus()`.
This is a small part of the method:

```php
        if ($identity !== null) {
            $authKey = $session->get($this->authKeyParam);
            if ($authKey !== null && !$identity->validateAuthKey($authKey)) {
                $identity = null;
                $ip = Yii::$app->getRequest()->getUserIP();
                Yii::warning("Invalid session auth key attempted for user '$id' from $ip: $authKey", __METHOD__);
            }
        }
```

I don't find how the line `Yii::warning(...` can be suppressed here, only if we will redeclare the method completely by copying the full code into the new HumHub core method `humhub\modules\user\components\User->renewAuthStatus()` but it is very bad idea because it may works uncorrectly after future update of the yii2 core method `yii\web\User->renewAuthStatus()`.
So it seems we should keep it as is unfortunately.

**Comment by luke-** [comment]
@yurabakhtin What is the message category for this warning? If it's limited to the class/method we could add this here `https://github.com/humhub/humhub/blob/master/protected/humhub/config/common.php#L66`

**Comment by funkycram** [comment]
This user is affected too by the problem: https://community.humhub.com/content/perma?id=264336
