### ISSUE TITLE
Compatibility with pagespeed module

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/humhub#5991]
### Is your feature request related to a problem? Please describe.
I've just installed HumHub on a Plesk webhosting (by Serverstation54). There the pagespeed_module is enabled by default. This leads to a lot of errors in the browser console like
`Uncaught EvalError: call to eval() blocked by CSP` and `Uncaught ReferenceError: humhub is not defined`

And I had problems installing modules from the marketplace. I do not completely understand why but those problems disappeard by solving the problem with the pagespeed_module.

### Possible solutions

1. Add a rule to the .htaccess file that completely turns off the pagespeed_module:
`<IfModule pagespeed_module>
ModPagespeed off
</IfModule>`
2. Add a rule to the .htacces file that disables the combination of javascript (which seems to be the only problem)
`<IfModule pagespeed_module>
ModPagespeedDisableFilters combine_javascript
</IfModule>`

3. Only add a note to the documentation
4. make HumHub fully compatible with pagespeed_module

HumHub: v1.13.0
PHP: 8.0.26

**Comment by ArchBlood** [comment]
Looking into this I don't think that it should be added to the core `.htaccess` due to this being more of a personal issue and is limited to a small number of shared hosting providers, nor to I think that we should comply to another third-party, if someone wishes for such a thing then I believe a module should be created for such a thing.

Moreover, it should be recommended for the person who is running the server to configure their server to their needs, and in this case using for using `pagespeed_module`.
https://www.modpagespeed.com/doc/

The first error message is similar to the following;
https://stackoverflow.com/questions/57426099/call-to-eval-blocked-by-csp-with-selenium-ide

So from searching, your server does not include a `unsafe-eval` in the CSP header which is telling you to include it in your CSP configurations.

For the second error;
Are there any custom scripts being used via module or theme from third-party sites? If so then here are a number of solutions to this error;
http://jquery-howto.blogspot.com/2013/02/referenceerror-jquery-is-not-defined.html

Overall this is more of a personal issue and more generalized to a small amount of server hosting providers.

**Comment by luke-** [comment]
I would also prefer to only include support for default Apache modules in the core `.htaccess` file.
Otherwise it gets too overloaded if we have to include supports for all possible configurations like PageSpeed / Cloudflare etc pp. 

So I prefer option 3. However, I would create a page `PageSpeed` for this Wiki and create notes about it here.
https://staff.humhub.org/s/development/wiki/overview/list-categories

In the official installation documentation I would then refer to the Wiki.

**Comment by felixhahnweilheim** [comment]
Ok, but staff.humhub.org sounds like it is only for staff of the company?
Then it should better be a new Wiki page here? https://community.humhub.com/s/installation-and-setup/wiki/overview/list-categories

I just don't like that it is not public so it is harder to find. But if there is a link from the documentation, then it's ok.

**Comment by luke-** [comment]
@felixhahnweilheim Yes sorry, I corrected the URL.

**Comment by luke-** [comment]
Yes, we should definitely create links from the documentation to the wiki. Maybe we can also make it public in the future.

**Comment by felixhahnweilheim** [comment]
Here is a new Wiki page: https://community.humhub.com/content/perma?id=263054

I hope that's how you meant it.

**Comment by luke-** [comment]
Yes exactly, thank you!

I also added a reference to the community wiki.
