### ISSUE TITLE
Guest Mode: Click on private User Profile results in 404

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6027]
### What steps will reproduce the problem?

![image](https://user-images.githubusercontent.com/4736168/211291241-d88474a6-09ed-4c81-b9b2-de95732561a7.png)

Instead Show same error as for non guest Spaces

![image](https://user-images.githubusercontent.com/4736168/211291368-3e44cf44-01f4-4d85-99b9-c59641029947.png)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- I have compared how it works for Spaces and I am bit confused how it should works, please read what I found:

On init ContentContainerController we find Space or User by guid,
see method `humhub\modules\content\components\ContentContainerController->getContentContainerByGuid($guid)`,
there we filter the records by `->visible()`,
but Space and User have a difference for Guest case:
- Space: `visibility != Space::VISIBILITY_NONE` "Private (Invisible)"
- User: `visibility == User::VISIBILITY_ALL` "Visible for all (also unregistered users)"

I.e. for Guest we list Spaces even with visibility "Public (Registered users only)", so such Spaces are listed in the spaces directory page, but after click on the Space we see the "Login required" page as your screenshot above.

If we will have the same visibility filter for Users as well then we see the same login page, because it is generated by the code https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ContentContainerController.php#L82-L84:

```php
if ($this->contentContainer !== null && $this->contentContainer->controllerBehavior) {
    $this->attachBehavior('containerControllerBehavior', ['class' => $this->contentContainer->controllerBehavior]);
}
```

i.e. the `User->controllerBehavior` is not attached as it works for Space, but the logic to generate the 401 http exception with message "You need to login to view this user profile!" is implemented inside the user controller behavior.

I am thinking how it should works properly:

1. Modify `User->visibility()` to make it like we have for Space, so all not public users (even with visibility "Registered users only") may be listed for guests in some lists, however page "People" is not available for guests.
2. Modify `Space->visibility()` to make it like we have for User, but then all not public spaces will be hidden from the space directory page. Then we should find another solution to throw to loginf page because `ContentContainerController->getContentContainerByGuid($guid)` will returns null and the `controllerBehavior` will not be attached.

**Comment by yurabakhtin** [comment]
@luke- 3\. I think to completely remove the filter `->visible()` from the `ContentContainerController->getContentContainerByGuid($guid)` because it seems it was added by me here https://github.com/humhub/humhub/commit/a471984#diff-d8832f96ac059fb95a2d32b1d600e8c30b00e625f8bc9778a6c6320f1e27a747R161

**Comment by luke-** [comment]
@yurabakhtin Thank you, the PR should solve the problem correctly. 

Can you maybe create a test case for it:
- If GuestMode active and user profile private ==> 401 then Please Login Message

**Comment by yurabakhtin** [comment]
@luke- 

> Can you maybe create a test case for it:
>
> - If GuestMode active and user profile private ==> 401 then Please Login Message

Commit https://github.com/humhub/humhub/pull/6039/commits/ab90cbd36d6303fbea92f0e63ce2e985a1c4ff92, but I don't see tests were executed for the commit, probably they will be run after merge.
