### ISSUE TITLE
Attempt to read property "is_admin_group" on null

### ISSUE THREAD

**Issue by TheFox** [humhub/humhub#6104]
### What steps will reproduce the problem?

1. Browse to users /admin/user/list
2. Edit one user (eg. /admin/user/edit?id=9)
3. In the Groups field add a new name of a group which doesn't exist yet.
4. Error

### What is the expected result?

1. Add a new User Group.
2. Add the edited user to the new created user Group.

### What do you get instead?

```
PHP Warning – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Attempt to read property "is_admin_group" on null

1. in /var/www/html/protected/humhub/modules/admin/models/forms/UserEditForm.php
```

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.2
| PHP version      | 8.1.15
| Operating system | Debian 11

**Comment by yurabakhtin** [comment]
@luke- The bug is fixed in PR https://github.com/humhub/humhub/pull/6105, but do you agree that we should allow to create new group right from the new entered group name on the user edit form side?
I think we should restrict to type there new group name and keep only selecting from existing group, should I fix this as well?

**Comment by luke-** [comment]
@yurabakhtin Yes, we should restrict the group selector to existing groups

**Comment by yurabakhtin** [comment]
@luke- Ok, commit https://github.com/humhub/humhub/pull/6105/commits/aa04688ba9d70a75d5a0b4d4d4b0409ef8317e44.
