### ISSUE TITLE
The Default user idle timeout item is not working properly.

### ISSUE THREAD

**Issue by aris-mirai** [humhub/humhub#6126]
Hello. This is to provide bug information.
The HumHub is not working correctly for the Default user idle timeout item in the Administrative Settings -> User Management -> User Management Settings.
The default user idle timeout times out after 24 minutes, but even if I set that time to be 1 year, the user is still logged out after 24 minutes. What should I do?
Thank you in advance for your investigation.

**Comment by marc-farre** [comment]
@luke- I had this problem when login with an SSO, which I solved adding this parameter to the `protected/config/web.php` file:

```php
return [
    'components' => [
        ...
        'session' => [
            'cookieParams' => [
                'lifetime' => 3600 * 24 * 32,
            ],
            'timeout' => 3600 * 24 * 32, //session expire
        ],
        ...
    ],
];
```

But:
- it depends on the server (sometimes it needs to add it, and sometimes not)
- on the current develop branch (1.16), even without SSO I need to add it

One of the discussions about it: https://community.humhub.com/comment/perma?id=45893

**Comment by luke-** [comment]
@marc-farre Thanks for the information.

Apparently we should also set `Session::$timeout` and `User::$authTimeout` to the same value.

https://www.yiiframework.com/doc/api/2.0/yii-web-user#$authTimeout-detail

Because `Session::$timeout` is loaded by the php.ini setting `session.gc_maxlifetime` and otherwise takes effect before the $authTimeout

This should fixed the issue: https://github.com/humhub/humhub/pull/6818/files

**Comment by marc-farre** [comment]
@luke- Thanks for this quick fix! I'll let you know if it works well in a few days after testing on different instances.

**Comment by marc-farre** [comment]
@luke- it seems to work fine! Tested in different scenarios (SSO, default login, Humhub 1.15 and 1.16).
Thanks!

**Comment by luke-** [comment]
@marc-farre Thanks for testing. I've merged into `master`.
