### ISSUE TITLE
`Group::getAdminGroupId()` returns sometimes `int`, sometimes `string`

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/humhub#6192]
### What steps will reproduce the problem?

1. Make sure, the following setting is deleted:
    ```SQL
    DELETE FROM setting WHERE module_id = 'user' AND name = 'group.adminGroupId';
    ```
    Of course, you can review it first! ;-)
    ```SQL
    SELECT * FROM setting WHERE module_id = 'user' AND name = 'group.adminGroupId';
    ```
2. call [`Group::getAdminGroupId()`](https://github.com/humhub/humhub/blob/bb0d8a5f1f923148ffcd51124511604f8316e003/protected/humhub/modules/user/models/Group.php#L234) and check the type of the result. It will be `int`. As a side-effect, the id is stored in the `settings` table.
3. call [`Group::getAdminGroupId()`](https://github.com/humhub/humhub/blob/bb0d8a5f1f923148ffcd51124511604f8316e003/protected/humhub/modules/user/models/Group.php#L234) again and check the type of the result. It will be `string`, as this time it's been loaded from the `settings` table, rather than the `group` table

It would be good to get a consistent result. IDs would be expected to be of type `int`.

### Possible solutions

A quick fix would be adding `(int)` to the return line would do the job.

``` php
public static function getAdminGroupId()
{
	$adminGroupId = Yii::$app->getModule('user')->settings->get('group.adminGroupId');
	if ($adminGroupId == null) {
		$adminGroupId = self::getAdminGroup()->id;
		Yii::$app->getModule('user')->settings->set('group.adminGroupId', $adminGroupId);
	}
	return (int) $adminGroupId;
}
```
Best, the return type of the function would be `int` too, but that might break backward-compatibility.

Happy to create a PR, if that is appreciated.

### Additional considerations

However, using a setting only makes sense, if there could be multiple admin groups, which in fact does not seem possible (from the front-end, not the database, as there is no setting to make a group an admin group).

As such, it would be enough to simply cache the result, but not also adding it to the settings. Yet, removing this redundant setting would also break backward-compatibilty. However, the setting should be signed deprecate. As it will only be available once the `Group::getAdminGroupId()` was called. Using the the setting to cache the value is overkill and could cause problems in case of ambiguous values. Also, clearing the cache would not reset the setting.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.13.1
| PHP version      | 8.2

**Comment by luke-** [comment]
@martin-rueegg This is indeed not ideal and you are welcome to create a PR for this.

If it is not time critical, I would prefer the  `develop` branch, version `1.15` (July 23) as the base. Here you can also add return types (if no big error potential for core/modules). Please also add your change here `https://docs.humhub.org/docs/develop/modules-migrate` in a new `1.15` section. If the bug is critical you can simply add `(int)`.

In some situations (e.g. Admin Group / Theme Details), we currently use the `SettingsManager` for caching purposes as well, since it also caches and, most importantly, also directly loads a bunch of values and holds them in memory. Of course, it would be good to separate here in the long run and transfer these cases into a new cache system. For now, I have opened an internal issue for this.
