### ISSUE TITLE
Revise email sender

### ISSUE THREAD

**Issue by atdqm** [humhub/humhub#6212]
### Is your feature request related to a problem? Please describe.

When humhub sends a notification following an action taken by a member (e.g. acceptance to join a space, internal message sent,...), in the from field it puts the general email of the site and the person's name:

First name Last name of the member <administrator-email@site.com>
example: John Doe <admin@humhub.org>

E-mail reading software then tends to display only "First Name Last Name" (not the email) and the recipient replies to the e-mail thinking he is replying to the person but he is replying to the site administrator

### Describe the solution you'd like

I suggest adding an option in the settings

/admin/setting/mailing-server

which proposes not to use the members' names

![image](https://user-images.githubusercontent.com/112695767/228771190-314f42e2-c41b-4724-a135-6c995911d6ad.png)

and to test it here ?

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/targets/MailTarget.php#L70

### Describe alternatives you've considered
I'm open to other ideas

**Comment by funkycram** [comment]
@luke- would you like a PR for this idea?

**Comment by luke-** [comment]
@funkycram I would rather improve the default behavior instead of introducing a new option for this. We would probably also need to adjust the subject lines if we remove information from the sender name.

To start this it would be good to have an overview of the current subject lines & sender names. Based on this, we could start to improve the subject lines & sender name.

**Comment by funkycram** [comment]
Because `MailTarget` sets the "From name" to the originator each time it's available ([see here](https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/targets/MailTarget.php#L70)), the list of affected notification classes should be:

- Content: (ContentCreated)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/notifications/ContentCreated.php#L64-L64]
- Content: (ContentDeleted)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/notifications/ContentDeleted.php]
- Comment: (NewComment)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/comment/notifications/NewComment.php#L84-L84]
- Comment: (CommentDeleted)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/comment/notifications/CommentDeleted.php]
- Friedship: (Request)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/friendship/notifications/Request.php#L57-L57]
- Friedship: (RequestApproved)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/friendship/notifications/RequestApproved.php#L57-L57]
- Friedship: (RequestDeclined)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/friendship/notifications/RequestDeclined.php#L59-L59]
- Like: (NewLike)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/like/notifications/NewLike.php#L54-L54]
- Space: (InviteAccepted)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/notifications/InviteAccepted.php#L46-L46]
- Space: (InviteDeclined)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/notifications/InviteDeclined.php#L51-L51]
- Space: (InviteRevoked)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/notifications/InviteRevoked.php#L54-L54]
- Space: (ApprovalRequest)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/notifications/ApprovalRequest.php#L65-L65]
- Space: (ApprovalRequestAccepted)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/notifications/ApprovalRequestAccepted.php#L44-L44]
- Space: (ApprovalRequestDeclined)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/notifications/ApprovalRequestDeclined.php#L44-L44]
- Space: (UserAddedNotification)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/notifications/UserAddedNotification.php#L40-L40]
- Space: (ChangedRolesMembership)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/space/notifications/ChangedRolesMembership.php#L42-L42]
- User: (Followed)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/user/notifications/Followed.php#L57-L57]
- User: (Mentioned)[https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/user/notifications/Mentioned.php#L68-L68]

External modules:
- Calendar: (Invited)[https://github.com/humhub/calendar/blob/master/notifications/Invited.php#L47-L47]
- Calendar: (ForceAdd)[https://github.com/humhub/calendar/blob/master/notifications/ForceAdd.php#L61-L61]
- Calendar: (Remind)[https://github.com/humhub/calendar/blob/master/notifications/Remind.php#L79-L79]
- Calendar: (CanceledEvent)[https://github.com/humhub/calendar/blob/master/notifications/CanceledEvent.php#L65-L65]
- Calendar: (ReopenedEvent)[https://github.com/humhub/calendar/blob/master/notifications/ReopenedEvent.php#L65-L65]
- Calendar: (EventUpdated)[https://github.com/humhub/calendar/blob/master/notifications/EventUpdated.php#L65-L65]

**Comment by luke-** [comment]
@funkycram It looks like the originator user is usually in the subject again anyway. So  we can remove him from the quite easily?

**Comment by funkycram** [comment]
@luke- yes, I think it's okay.
PR: https://github.com/humhub/humhub/pull/6227

**Comment by luke-** [comment]
@funkycram Thanks for the PR!
