### ISSUE TITLE
Does not allow beta versions of modules, but beta versions are candidates for installation

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#6275]
I have newly installed HumHub v1.14.0. 

I have disabled beta installation in the module management settings, but the beta version of the Wiki module(1.9.0-beta.1) is loaded.

Why are beta versions of modules eligible for installation?

![2023-04-29_21h51_50](https://user-images.githubusercontent.com/38252517/235306587-2da045e7-31db-4cf9-a08d-50ece707e52f.png)

![2023-04-29_21h52_16](https://user-images.githubusercontent.com/38252517/235306608-2493c426-ceb8-45e3-9e90-999715af5697.png)

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.0
| PHP version      | 8.1
| Operating system |linux

**Comment by yurabakhtin** [comment]
@luke- I could not reproduce this, because in all cases I see only version `1.9.0`:

![wiki_version](https://github.com/humhub/humhub/assets/6995524/d886c2d6-e001-4fde-acb5-1daeb556b3b8)

At least from Administration side it wroks correctly because I debugged the code:

```php
$this->_modules = HumHubAPI::request('v1/modules/list', [
    'includeBetaVersions' => (boolean)$module->settings->get('includeBetaUpdates')
]);
```

and the param `includeBetaVersions` is passed correctly.

Also I have reviewed a code on the API side and it looks correctly.
Probably at the time when the bug was detected the module "Wiki" had the beta version `1.9.0-beta.1` as approved version by mistake. Could you please review this version for the "Wiki" module to be sure it is not approved? Thanks.

**Comment by luke-** [comment]
@sakurafarm Can you still reproduce this?

**Comment by sakurafarm** [comment]
@luke - Currently, this issue does not occur. Thank you for investigating.
