### ISSUE TITLE
Publishing draft requires reload

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#6291]
HH 1.14

Currently a reload of the page or editing/saving is required in order for the option to publish a draft is required.

**Comment by yurabakhtin** [comment]
@Semir1212 @luke- I confirm we have this bug and I already reported today it here https://github.com/humhub/humhub/pull/6288#issuecomment-1534583425, and I fixed it in the line https://github.com/humhub/humhub/commit/01b7385dfaa51de8034b9a37d6a777600d94ab1d#diff-2c7f5125956ea366a36488ba4ce215cb860de73c049764d95def6ef8cfafd9b0R23, so it would be good to implement new method `Content->hasState(Content::STATE_PUBLISHED)` as I suggested there in order to avoid such bug in future.

**Comment by luke-** [comment]
@yurabakhtin Ok, thanks. Can you please also add this # Nr. into the related PR Changelog.
