### ISSUE TITLE
wrong date on scheduled element 

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub#6337]
### What steps will reproduce the problem?
Create a poll and scheduled it for the day after at 8h00.

### What is the expected result?
The day after, your poll is available at 8h00 and appears on top of the dashboard.

### What do you get instead?
The poll is available at the creation time and is far away in the dashboard.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.1
| PHP version      |  8.1
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@luke- I have reviwed the PR, merged `master` branch and rebased this PR to the `master` branch. For me it looks correctly.

> We may also need some new DB indizies

I see the indexes were added here https://github.com/humhub/humhub/pull/5315/files#diff-9564608c9a0fae3806457392a6c26c51e02e5812ed40ec29f3d850b49f21937dR15-R16 for columns `created_at` and `stream_sort_date`(this column is used instead of `updated_at`).

I think the PR https://github.com/humhub/humhub/pull/5315 can be merged and then we could implement the updating `created_at` on content publishing action.

**Comment by luke-** [comment]
@yurabakhtin I would like to merge this PR into 1.15 - so the bug cannot be fixed in v.14

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look into the test from #5315?

**Comment by luke-** [comment]
@yurabakhtin Thanks. I've merged the PR into `next` branch, which will become `v.16` and `develop` after stable release. Can you also fix the `created_at` on publish?

**Comment by yurabakhtin** [comment]
> Can you also fix the `created_at` on publish?

@luke- PR https://github.com/humhub/humhub/pull/6525.
