### ISSUE TITLE
Poll creation doubles the answers

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub#6344]
### What steps will reproduce the problem?
Create a new Poll with 3 answer (actually it doesn't matter how many)
### What is the expected result?
Have a poll with 3 possible answer
### What do you get instead?
Have a poll with 6 possible answer
### Additional info
Issue on Mobile and Desktop
https://github.com/humhub/humhub/assets/19529531/8b5f5271-9885-4c67-9447-76256f583111

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.1
| Module version      |  Polls 1.3.0
| PHP version      |  8.1
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
@luke- I can confirm this is an issue with HumHub v1.14.2 and Poll v1.3.0

### Space Polls
![Screenshot_1](https://github.com/humhub/humhub/assets/35392110/353d17d5-68af-470b-8095-c3d15019d8cd)

### User Polls
![Screenshot_3](https://github.com/humhub/humhub/assets/35392110/678e289b-07f0-4428-a842-f9d6bbc1aaf1)

I also noticed that when the Poll is created the title field isn't cleared after saved?

**Comment by yurabakhtin** [comment]
@Reuns @ArchBlood Thanks for the report!

@luke- Fixed in PR https://github.com/humhub/polls/pull/123.
I think this bug appeared after I implemented new method `ContentActiveRecord->afterStateChange()` that is called in `Content->afterSave()`, so `ContentActiveRecord->afterSave()` is called twice, maybe in future we should implement better solution to don't call it twice.
I mean this code https://github.com/humhub/humhub/commit/6d65da3#diff-b3de8a7bb84547e2de7081f31795f491fb051a7df7042d02d991041ee0235a51R245-R247 should be called once, probably we need some flag-variable to avoid this.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the fix.

Can we maybe just do an `updateAttributes` in the `afterStateChange`?

**Comment by yurabakhtin** [comment]
@luke- I have fixed it in core PR https://github.com/humhub/humhub/pull/6359 in order to avoid similar issue in other modules.
