### ISSUE TITLE
Improve accessibility for 'List pending registrations' button

### ISSUE THREAD

**Issue by dantefromhell** [humhub/humhub#6346]
Proposal: Move the `List pending registrations` button to the top of the `User administration` page.

### Is your feature request related to a problem? Please describe.
The `List pending registrations` button in the `Users` Administration menu is located on the bottom of the list of accounts. Depending on the amount of registered users this list can be fairly long, which makes it harder to find and/ or access the button.

### Describe the solution you'd like
I did a quick mock-up by copy & pasting the button around in my Browsers DOM tree (limited HTML skills) to get a feeling for the visual of my proposal.
![image](https://github.com/humhub/humhub/assets/90508808/767aa1d2-fe65-4042-9778-7972b9f5a4f4)

IMO it makes sense to have a "bar" with the most frequent actions regarding user management located towards the top of the page.

### Describe alternatives you've considered
n/a

**Comment by funkycram** [comment]
It also could be in an additional new tab, as it's a separated page.

**Comment by dantefromhell** [comment]
@funkycram 
As in adding a new tab after `People` or adding a another tab bar similar to the one in `User` -> `Profiles` section?

![image](https://github.com/humhub/humhub/assets/90508808/348e32cb-2e9d-4980-a1d8-ff64606e825e)

**Comment by ArchBlood** [comment]
> It also could be in an additional new tab, as it's a separated page.

Speaking from a UI point of view I disagree with adding more tabs 100%, the last thing a user wants is multiple scrollbars on mobile view, currently the admin section needs a complete rework when it comes to this.

Me personally I'd like it so that on mobile view it would use a collapsible menu with dropdown options for their respected sections.

For the list of pending registrations, I like this approach as it is in a good placement and once the pending registrations are handled the button disappears.

Another option would be adding this to the dropdown filter under a "Pending" label.

**Comment by dantefromhell** [comment]
> once the pending registrations are handled the button disappears.

I love the idea of greying out the button if there are no pending invites. Or even adding the number of pending invites to the button text

**Comment by dantefromhell** [comment]
Sounds good to me - adding the button to expandable/ scrollable elements definitely makes more sense than creating another one.
