### ISSUE TITLE
In command line, LogoImage::getUrl() returns 3 times the base URL

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub#6386]
### What steps will reproduce the problem?

In a console controller, create this code:
```
echo LogoImage::getUrl();
```

### What is the expected result?

`https://my.humhub.com/assets/logo/600x80.png?v=1685222378`

### What do you get instead?

`https://my.humhub.comhttps://my.humhub.comhttps://my.humhub.com/assets/logo/600x80.png?v=1685222378`

| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.2
| PHP version      | 8.2

**Comment by funkycram** [comment]
I have the same problem with `Url::home(true);`. Here the base URL is displayed twice only.

**Comment by yurabakhtin** [comment]
@funkycram I found one solution in PR https://github.com/humhub/humhub/pull/6414, it works now like this:

- `LogoImage::getUrl()` => `http://humhub.yb/assets/logo/600x80.png?v=1688387891`
- `Url::home(true)` => `http://humhub.yb/dashboard`

but I am not sure it will not break some other code, so we need to wait at least the tests will be executed on github side, and yes I think it would be better to make it for next version `1.15` in order to fix errors there if we will detect them.

**Comment by luke-** [comment]
@yurabakhtin Thanks
@funkycram Can you please check?

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
@luke- tested, works fine.
