### ISSUE TITLE
SelfTest throws an error if a views exists in the DB

### ISSUE THREAD

**Issue by sakurafarm** [humhub/humhub#6585]
### What steps will reproduce the problem?
1. Run the HumHub in debug mode
2. Create some view in the DB
3. `ACP` -> `Informaition` -> `Prerequisites`
### What is the expected result?
Prerequisites must be displayed
### What do you get instead?
![2023-09-22_18h40_58](https://github.com/humhub/humhub/assets/38252517/4c6821d1-e33b-4537-9fd4-aedf021812e2)
### Additional info
I am developing a module with tables and views in DB. I would appreciate it if it could be fixed so that the error does not occur even when it has views.
| Q                | A
| ---------------- | ---
| HumHub version   | 1.14.4
| DB | MariaDB 10.9.3
| PHP version      | 8.1
| Operating system | Windows11

**Comment by ArchBlood** [comment]
Error reporting seems to be enabled which will show this warning, seems to me that a view is broken which is causing the issue, otherwise I've not ran into the issue on a fresh install. If line 700 throws this then there's a view path that breaks the collations check, which would mean that it could also break on line 706 for engine check. :thinking:

**Comment by ArchBlood** [comment]
A simple fix would be to add `?? ''` after `$recommendedCollation` and `$recommendedEngine`.
