### ISSUE TITLE
Images are not resized in mail $content

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/humhub#6639]
HH1.15 beta. (I dont know if this issue was already existing in previous versions)
When you add an image in a post, and when it is larger than the post container, HH will resize it. So far so good.
But **image is not resized in the notification email**.
Example here under:
**In post**
![image](https://github.com/humhub/humhub/assets/91057837/7c8b52e8-74e5-42b7-80a3-280bedb40d02)

**In email**
![image](https://github.com/humhub/humhub/assets/91057837/69efffb0-1401-40db-861d-b6d0b392904d)

**Comment by ArchBlood** [comment]
> @Gilbertdelyon What email client do you use? I guess some email clients may ignore styles from `<style>`. For me it works like this:
> 
> ![email](https://user-images.githubusercontent.com/6995524/279996239-5445e478-e31d-4ecf-ad10-320f61114200.png)
> 
> We did it here https://github.com/humhub/humhub/pull/5041/files#diff-64dbf955de454317993eed2a2754a54164ba9c37e95fd949e158d689dc752727R61.

This is probably because of `max-width`, the container is probably smaller than the width of the image which will cause such issues.

**Comment by ArchBlood** [comment]
> @Gilbertdelyon What email client do you use? I guess some email clients may ignore styles from `<style>`. For me it works like this:
> 
> ![email](https://user-images.githubusercontent.com/6995524/279996239-5445e478-e31d-4ecf-ad10-320f61114200.png)
> 
> We did it here https://github.com/humhub/humhub/pull/5041/files#diff-64dbf955de454317993eed2a2754a54164ba9c37e95fd949e158d689dc752727R61.

This is probably because of `max-width`, the container is probably smaller than the width of the image which will cause such issues.

**Comment by Gilbertdelyon** [comment]
I am using **gmail** (web mail) and also **Thunderbird**. Same behaviour in both.

You are right, issue is from the client side. **It works in Yahoo web mail**
Any chance to make it mork in any client?

**Comment by yurabakhtin** [comment]
@Gilbertdelyon Thank you for the info!

@luke- What I have found:

- https://stackoverflow.com/questions/35481108/styles-not-working-in-gmail/35481223#35481223 - "UPDATE 2018
GMAIL now and from a while ago has been supporting embedded CSS, so you can use CSS inside tag `<style>` in `head`, it even allow/supports the use of media queries."
- https://support.google.com/mail/thread/4763501?hl=en&msgid=4787293 - "Also having the same problem.  And gmail's own help on using styles no longer works either: https://developers.google.com/gmail/design/css Neither example on that page displays correctly in gmail in a web browser."

If believe the doc https://developers.google.com/gmail/design/css then "Most CSS selectors, attributes, and media-queries are supported." but it doesn't work for many users.
I have found the email message in my inbox recevied 1 month ago and checked it:

![gmail-styles](https://github.com/humhub/humhub/assets/6995524/895801d3-db61-4663-8889-49ab08dc4990)

As I understand only single solution is to use inline style per each html element, of course we could implement a parser to append automatically all styles from `<style>` to each html element, but I am not sure we need this now, probably we just need to fix it only for image by search-replace `<img ...>` into `<img ... style="max-width:100%">`

What do you think?

**Comment by luke-** [comment]
Wouldn't it be possible to create the `img` element differently in the `RichTextToEmailHtmlConverter`parser with an additional inline style?
https://community.humhub.com/s/contribution-core-development/wiki/Richtext#converter-classes

If there are other problems in future, we can further optimize this converter?

**Comment by yurabakhtin** [comment]
> If there are other problems in future, we can further optimize this converter?

@luke- I have tried to implement a quick solution by 
- replacing a result of the method `RichTextToEmailHtmlConverter::renderPlainImage()` with `str_replace('<img ', '<img style="max-width:100%" ', $theMethodResult)`, 
- and with adding `img.style` to the property `RichTextToHtmlConverter::$htmlAllowedAttributes`,
 
but HtmlPurifier removes the `max-width:100%` completely because as I understand percent units are not allowed https://stackoverflow.com/a/77141710. I.e. style like `width:100px` is not removed but `width:100%` is removed after the parser.

**Comment by Gilbertdelyon** [comment]
My humble 2 cents, just an idea
In html.php layout I notice that  `<?= $content ?>` has this parent element  
```
<!-- start container 600 -->
                    <table width="600"
```
So, why not to simply add `style="max-width:600px"` attribute to the image element?
Let's make a simple test:
Let's modify html.php layout as follows:
**Before modification:**
```
            <!-- START EMAIL CONTENT -->
            <?= $content ?>
            <!-- END EMAIL CONTENT -->
```
**After modification**
```
            <!-- START EMAIL CONTENT -->
            <?= $content ?>
            <!-- END EMAIL CONTENT -->
            
            <!-- TEST image-->
            <tr>
                <td height="10">
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" class="fix-box" style="font-family: 'Open Sans', Arial, Tahoma, Helvetica, sans-serif;">
                    <table width="600" style="background-color: <?= $defaultBackground ?>; border-radius: 4px; color:#555555;font-size:13px; line-height:22px;" class="full-width">
                        <tr>
                          <div>
                             This image is not in the $content variable. It has inline style ="max-width:600px;
                             <img src="image source" style ="max-width:600px;">
                          </div>                             
                        </tr>                                                
                    </table>
                </td>
            </tr>
            <!-- END TEST IMAGE -->
```
**It works at least in gmail **
![image](https://github.com/humhub/humhub/assets/91057837/716e13d2-648a-47e1-8464-acb56872810a)

By the way: I noticed another stange behaviour.
large images in $content are
not resized in gmail/chrome/windows/laptop, 
while they are resized in chrome/android/smartphone

**Comment by Gilbertdelyon** [comment]
My humble 2 cents.
I notice that `$content` variable is located in  parent container as follows
```
<!-- start container 600 -->
                    <table width="600"....
                            <table width="560" .....
                                     <td valign="top" align="left" style="padding-right:20px">
                                             <avatar icon width = 50px........
                                     < message content width = 560-50-20=490px

```
it means that in any mail client the image cannot be larger than 510px
so I made a quick test by adding this piece of code in `html.php` layout
```
<!-- TEST image-->
            <tr>
                <td height="10">
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" class="fix-box" style="font-family: 'Open Sans', Arial, Tahoma, Helvetica, sans-serif;">
                    <table width="600" style="background-color: <?= $defaultBackground ?>; border-radius: 4px; color:#555555;font-size:13px; line-height:22px;" class="full-width">
                        <tr>
                          <div>
                             This image is not in the $content variable. It has inline style ="max-width:490px;
                             <img src="https://test-site/index.php?r=file%2Ffile%2Fdownload&guid=122421f6-8f24-42ec-b045-a89fef513897" style ="max-width:490px; margin-left:70px;">
                          </div>                             
                        </tr>                                                
                    </table>
                </td>
            </tr>
            <!-- END TEST IMAGE -->
```
And it works in gmail!

**Comment by Gilbertdelyon** [comment]
@yurabakhtin 
This test was only a fast check, but if you dont find any workaround for the "max-width:100%" that is rejected by gmail it could be at least a temporary way.  A large part of our members is using gmail, so it could help.

BTW, I noticed that in my smartphone/android/gmail  images are correctly resized with native HH email layout. (but I did not take time to inspect if the  "max-width:100%" was removed or not.)

**Comment by luke-** [comment]
@yurabakhtin Thanks for the PR.  I'd like to avoid this slightly more complicated workaround.

Do you see any reason why we need to use the HTMLPurifier here at all?
In general, it should not be possible to inject HTML code via Markdown.

**Comment by yurabakhtin** [comment]
@luke- 

> In general, it should not be possible to inject HTML code via Markdown.

Yes, I confirm, it looks like this.

> Do you see any reason why we need to use the HTMLPurifier here at all?

What I have found:

- `RichTextToEmailHtmlConverter` is extended from `RichTextToHtmlConverter`
- `RichTextToHtmlConverter` has by default `public $purify = true;`
- The using of the HTMLPurifier was implemented here https://github.com/humhub/humhub/pull/4686
- `RichTextToEmailHtmlConverter` was implemented here https://github.com/humhub/humhub/pull/4995

Probably we could set the `$purify` to `false` only for the extended `RichTextToEmailHtmlConverter`.
But even if we will do that then we use the same code of the `preg_replace` what I have implemented in the method `onAfterParse()`, i.e. the same code will be applied in the method `renderPlainImage()`, and new code will not be less complicated.

It would be better if the method `cebe\markdown\inline\LinkTrait::renderImage($block)` has some options param to additional attributes, so we could pass them but the method just build `<img>` tag only by code like this:

```php
		return '<img src="' . htmlspecialchars($block['url'], ENT_COMPAT | ENT_HTML401, 'UTF-8') . '"'
			. ' alt="' . htmlspecialchars($block['text'], ENT_COMPAT | ENT_HTML401 | ENT_SUBSTITUTE, 'UTF-8') . '"'
			. (empty($block['title']) ? '' : ' title="' . htmlspecialchars($block['title'], ENT_COMPAT | ENT_HTML401 | ENT_SUBSTITUTE, 'UTF-8') . '"')
			. ($this->html5 ? '>' : ' />');
```

so I see only the way it to use the search-replace solution, and no big difference between use it for `renderPlainImage()` or for `onAfterParse()`.

Another solution is to copy the code completely from external `cebe\markdown\inline\LinkTrait::renderImage($block)` into humhub method  `renderPlainImage()` with possibility of passing additional options like `renderPlainImage($block, ['style' => 'max-width:100%'])`, i.e. we will forget for using of the `cebe\markdown\inline\LinkTrait::renderImage($block)` completely.
Do you agree this solution instead of the complicated `search-replace` way?

**Comment by luke-** [comment]
@yurabakhtin Thanks for the explanation. Then I would actually stick with your current solution. Or would you prefer create a new `renderImage` method?

Currently in HumHub RichText Editor there are some options for images (Width, Height, ...). Are these not supported by the current parser?

![image](https://github.com/humhub/humhub/assets/4736168/4746fb41-7f57-4d7e-a465-5d1ed74ec047)

**Comment by yurabakhtin** [comment]
@luke- 

> Or would you prefer create a new `renderImage` method?

No, I prefer to use the parent method wthout overriding this in child class, because when parent method will be update then the child method will works with old logic either not correctly or will be broken.

> Currently in HumHub RichText Editor there are some options for images (Width, Height, ...). Are these not supported by the current parser?

My test on `master-v1.15.1` without changes from the PR https://github.com/humhub/humhub/pull/6642:

![test-image-email](https://github.com/humhub/humhub/assets/6995524/ad7af314-5882-4d96-b52a-e75d65ed6c45)

As you can see `width` and `height` are not rendered on email side, because the method `cebe\markdown\inline\LinkTrait::renderImage($block)` doesn't render these attributes at all (see code [here](https://github.com/humhub/humhub/issues/6639#issuecomment-1801414707)).

Also please see on the char `>` in the end of description, as I understand it is a flag to align the image to right, because for left alignment I find there `<` and for center - `><`.

So I think better to have own method to render images on email messages instead of the `LinkTrait::renderImage()` in order to add all required attributes and parse the alignment chars correctly. I can continue this in the same PR, i.e. I will remove the search-replace code, it will be replaced with new attribute `style`, also new attributes `width` and `height` will be added and probably alignment too. Do you agree?

**Comment by luke-** [comment]
@yurabakhtin Yes, sounds good!

**Comment by yurabakhtin** [comment]
@luke- Done in commit https://github.com/humhub/humhub/pull/6642/commits/9d1884b0624ce4157c7dd684d58689dac20c27a7:

![uploaded](https://github.com/humhub/humhub/assets/6995524/09ca7716-a4f8-4326-ba6c-925fc641aa3f)

---

![image-tag](https://github.com/humhub/humhub/assets/6995524/cb88c05d-32e3-4ff0-8688-8a75c8a79268)

Please wait when tests https://github.com/humhub/humhub/actions/runs/6816672370/job/18538509549 will be completed before merging, probably some fixes will be required there.

**Comment by yurabakhtin** [comment]
@luke- I think we should forget to use the attribute `align` because `align=middle` doesn't work as expected, and this attribute is not supported in HTML5:

![align-broken](https://github.com/humhub/humhub/assets/6995524/e5087fdb-efea-4ffa-be93-aec2571cefa4)

I will replace this to `class="center-block"` for `RichTextToHtmlConverter` and to `style="display:block; margin: auto;"` for `RichTextToEmailHtmlConverter`.

**Comment by yurabakhtin** [comment]
@luke- I have added new tests https://github.com/humhub/humhub/pull/6642/commits/1230cda47ef811be55df5f744d759c405d8a2184, locally they work well, after they will be executed here you can merge the PR.
