### ISSUE TITLE
URL in email notification removes the sub-folder of the Base URL (since Humhub 1.15)

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#6653]
### What steps will reproduce the problem?

1. In Administration -> Settings -> Base URL, enter this URL: `https://domain.tld/sub-folder`
2. Send an email notification
3. Check the URL of the "View online" button

### What is the expected result?

The URL should be `https://domain.tld/sub-folder/notification/entry?id=xxx`

### What do you get instead?

This URL `https://domain.tld/notification/entry?id=xxx`

### Additional info

https://community.humhub.com/content/perma?id=272524

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15

**Comment by yurabakhtin** [comment]
@luke- I have fixed the button "View online" in the PR https://github.com/humhub/humhub/pull/6658 but I am not sure it is a good solution because I see other URLs has no an exepected sub-folder in email message.
Please see what I have fixed (green) and what not fixed yet (red):

![email-urls](https://github.com/humhub/humhub/assets/6995524/3de77515-d7f2-49ee-85d7-31ac630763f9)

I tested with Base URL = `http://localhost/humhub` and send email when site is loaded from `http://humhub.yb`.

As you can see I have fixed only several urls by new helper `SafeBaseUrl` which we implemented here https://github.com/humhub/humhub/pull/5993, and there it is used only for link to recovery password from email.
But other links like user profile links or links from Legal module cannot be fixed by using the helper.
I am trying to recall why we decided to move the code to the separate helper `SafeBaseUrl` instead of doing this in the main Url Manager.

Firstly we tried to fix the "password recovery url in email" issue from here https://github.com/humhub/team_tasks/issues/250 in the PR https://github.com/humhub/humhub/pull/5864.
Then additional changes were done in https://github.com/humhub/humhub/pull/5871.
But then all those changes from `protected\humhub\components\UrlManager` were moved to the helpder `SafeBaseUrl` here https://github.com/humhub/humhub/pull/5993 where we decided to apply it only for the single url to recovery password, because original issue was only related to the password recovery url from email.

Probably here https://github.com/humhub/team_tasks/issues/250#issuecomment-1250787601 described why we reverted the code from main Url Manager and decided to use the fix only for several urls like we did for the "password recovery" url.

**Comment by yurabakhtin** [comment]
I have compared the same URLs in email for version `1.14.5`, they all are correct.
I have debugged the method `yii\web\UrlManager` for var `$_SERVER['HTTP_HOST']`:

- `1.14.5` => `humhub.yb`
- `1.15` => undefined

**Comment by luke-** [comment]
@yurabakhtin Hmm, not sure, following behavior should be correct:

- Console: Populate the UrlManager from BaseUrl setting
- Web: Use default Yii2 behavior, when possible. The reason to not use the configured base url here, is that a misconfiguration would make the application unusable.
- Web (Safe): In special rare situations where a spoofed header would, for example, generate an incorrect URL in an e-mail. the `SafeUrlHelper` is used .     

Ideally, we could also refactor such e-mail dispatch (Recover Password, ...) as background queue jobs. To get rid of `SafeUrlHelper`. Maybe something for v16 or v17.

Regarding the current PR, is it really to add now `:8080` to the unit tests url?

**Comment by yurabakhtin** [comment]
@luke- 

> * Console: Populate the UrlManager from BaseUrl setting

Yes, it works this way here - https://github.com/humhub/humhub/pull/6658/files#diff-bd5d7074d6bc27336b5f7df3487759b56f4837d192594afe3d7e2ad772acf03d, you can see there each method is called only for case `if ($this->hasConsoleSettingBaseUrl()) {` i.e. when `Yii::$app->request->isConsoleRequest === true`, for other cases parent method code is called.

> * Web: Use default Yii2 behavior, when possible. The reason to not use the configured base url here, is that a misconfiguration would make the application unusable.

Yes, the default Yii2 behavior is used for not console mode, e.g. here https://github.com/humhub/humhub/pull/6658/files#diff-bd5d7074d6bc27336b5f7df3487759b56f4837d192594afe3d7e2ad772acf03dR65

> * Web (Safe): In special rare situations where a spoofed header would, for example, generate an incorrect URL in an e-mail. the `SafeUrlHelper` is used .

I didn't modify the using for this case in the PR, we still use it here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/user/services/PasswordRecoveryService.php#L62-L65:

```php
'linkPasswordReset' => SafeBaseUrl::to(['/user/password-recovery/reset',
    'token' => $token,
    'guid' => $this->user->guid
], true)
```

I just added one fix there https://github.com/humhub/humhub/pull/6658/files#diff-30b2842e66da3905f0f925dff3566218f199d915a88677c68a1e4e7b0fdf5586R28 because detected a sub-folder was missed for the password recovery url even from Web side.

> Ideally, we could also refactor such e-mail dispatch (Recover Password, ...) as background queue jobs. To get rid of `SafeUrlHelper`. Maybe something for v16 or v17.

Sorry, not clear your idea. Do you want to remove the using of `SafeUrlHelper` for url `/user/password-recovery/reset`?

> Regarding the current PR, is it really to add now `:8080` to the unit tests url?

The unit tests are called from console mode, so the urls are generated now from Base URL which is configured as `http://localhost:8080` for tests, it is why new urls in console have the port `:8080`.

**Comment by luke-** [comment]
Fixed here: https://github.com/humhub/humhub/pull/6673#event-11050786154
