### ISSUE TITLE
Tour: Auto start test issue

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6678]
Seems the `AutoTourCest` sometimes fails, maybe because the first login is not always detected.  

https://github.com/humhub/humhub/blob/master/protected/humhub/modules/tour/Module.php#L40

For the "first login" check, I do not want any additional DB/Settings queries from the `tour` module.
Maybe we could do a check via the AFTER LOGIN event and then set a session variable, which is detected by the tour widget ?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6685 - I have done to use Session from dashboard event side as you suggested, but after activating the test `AutoTourCest` here https://github.com/humhub/humhub/pull/6685/commits/ac3059f18600620505213928fa87293fa9eb35ca it is broken again.
I will review deeply how to fix it.

**Comment by yurabakhtin** [comment]
@luke- I have fixed the auto tour test in the commit https://github.com/humhub/humhub/pull/6685/commits/97710e05b738f1d3cc19e28bc0279287c28fa2bf: as you can see I just set `last_login` to `null`, because it is used now to detect new user after creating/registration.
Before I strarted to use the flag `last_login == null` the condition `updated_by` was used there, it is why the auto test was broken as well because as you can see the user fixtures data has `'updated_by' => '1'` for admin and for several other users.
