### ISSUE TITLE
Self Always Offline in People v1.15

### ISSUE THREAD

**Issue by miqrogroove** [humhub/humhub#6694]
### What steps will reproduce the problem?

When I log in, my online status only appears in the menu bar.  The People page always shows me offline.  I tried changing visibility from Registered Users to Visible All, and there was no improvement.

### What is the expected result?

My own online status should be visible in the People page.

### What do you get instead?

My own online status is missing, which looks broken.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0
| PHP version      | 8.3.0
| Operating system | Ubuntu

**Comment by marc-farre** [comment]
This is intended.
For the current user, we only show the online indicator on the profile image at the right of the top menu.
This is to avoid having green dots everywhere as we already know we are online.
We need to see other users status only.

**Comment by ArchBlood** [comment]
> This is intended and is the way other major social network works.
> For the current user, we only show the online indicator on the profile image at the right of the top menu.
> This is to avoid having green dots everywhere as we already know we are online.
> We need to see other users status only.

I've also noticed this in a way, and it shows an invisible offline indicator, this is because of tooltips, with the current version of the status indicator there is a graphical bug, it shouldn't show anything for the current user, meaning online/offline, this I can reproduce on desktop and mobile.

![Screenshot_20231202-063148.png](https://github.com/humhub/humhub/assets/35392110/26bb3154-7caa-4dda-854e-2073589a0219)

![Screenshot_20231202-063201.png](https://github.com/humhub/humhub/assets/35392110/5a7a650a-c381-49b2-bb8e-b111a8332e62)

**Comment by miqrogroove** [comment]
Confirmed the additional problem from @ArchBlood , when I log into the HumHub community and hover my own avatar, there is a tooltip that says "Offline".  This can be reproduced on the People page as well.  If you hover the mouse in just the right spot, it shows a tooltip that I am "Offline".

@marc-farre I just can't agree that this design would be useful.  If there is no indication anywhere on the site that I am online, then as a user I would have no idea how to determine if anyone else is online.  The single green dot in the corner becomes the noise, not the signal.

**Comment by ArchBlood** [comment]
> @ArchBlood thanks for the info.
> 
> @luke- PR #6695 on master
> 
> @luke- About the behavior of not displaying the online status on our own avatar, except at the top right, I cannot found our conversation about it. If I remember well, you or @Eladnarlea asked me to it this way, as it's the way it's done on other platforms.

I personally don't mind the idea of only showing it in this way, my only issue was the tooltip which is fixed here. 👍🏻

**Comment by luke-** [comment]
@marc-farre Thanks for the fix!

I'm also fine with the current behavior. No need to add own profile images.
@Eladnarlea Any suggestions here?

**Comment by Eladnarlea** [comment]
I took another look at various social platforms. 
First of all, I would like to mention that it is also not a signal if you always see yourself online, in every post and every comment.  This turns the dashboard into a sea of green dots. 

The online status information is the most important thing in messaging. 
When the online status is displayed next to the main navigation point (your personal profile picture and the drop down navigation from where you can access and control almost everything), it is very clear that you are seeing your own status.

However, I agree that we could use the online status signal more often. In fact, it makes sense to display it on your own card for people cards/user overview as well. We should also display it in the "My profile" section next to your profile picture. Likewise in the "Space members" snippet.

I would still prefer not to display the online status for every single comment or post on the dashboard.  Otherwise the interface is completely cluttered with green dots.

**Comment by luke-** [comment]
@Eladnarlea Thank you for your investigation. Would you please  create a new issue with missing online status?

**Comment by Eladnarlea** [comment]
@luke- yes sure it is here: https://github.com/humhub/humhub-internal/issues/131
