### ISSUE TITLE
`develop` tests fail

### ISSUE THREAD

**Issue by martin-rueegg** [humhub/humhub#6714]
For some reasons, the tests fail since the recent merges.

e.g. 
- https://github.com/humhub/humhub/actions/runs/7150405383/job/19473640939?pr=6711
- https://github.com/humhub/humhub/actions/runs/7145740499/job/19462051162?pr=6713

All failing tests have to do with

-  `http://localhost/` vs
-  `http://localhost:8080/`

They are unrelated to the above PRs.

**Comment by luke-** [comment]
Probably related to this commit: 
https://github.com/humhub/humhub/commit/ebe45bacfcaecbbb5f703652f3c8d83bce74a0a9c

**Comment by martin-rueegg** [comment]
It appears that the `AutoTourCest` is [failing](https://github.com/humhub/humhub/actions/runs/7181825119/job/19557011099#step:18:1531) on various PRs on `develop`.

@yurabakhtin, since you re-enabled it in

- #6685

you might find quickly what's the reason?

**Comment by yurabakhtin** [comment]
> @yurabakhtin, since you re-enabled it in
> 
> * [Refactor auto start tour for new user #6685](https://github.com/humhub/humhub/pull/6685)
> 
> you might find quickly what's the reason?

@martin-rueegg Yes, I still could not find how to fix the test, because locally it works without errors, but on github side it has a random effect, e.g. you can find the latest commit in the PR https://github.com/humhub/humhub/pull/6685/commits/dd3c56ad5a455bfd139fa8f561ec64512170a791 and all tests are green there, but after merging they all are red.

@luke- I think we should disable the test again - https://github.com/humhub/humhub/pull/6731.

**Comment by martin-rueegg** [comment]
> > @yurabakhtin, since you re-enabled it in
> > 
> > * [Refactor auto start tour for new user #6685](https://github.com/humhub/humhub/pull/6685)
> > 
> > you might find quickly what's the reason?
> 
> @martin-rueegg Yes, I still could not find how to fix the test, because locally it works without errors, but on github side it has a random effect, e.g. you can find the latest commit in the PR [dd3c56a](https://github.com/humhub/humhub/commit/dd3c56ad5a455bfd139fa8f561ec64512170a791) and all tests are green there, but after merging they all are red.

Oh jeah, I know that situation. Somehow frustrating, isn't it? :-)

> @luke- I think we should disable the test again - #6731.

It would also be great to find a solution for the port in the host address that makes several other tests fail. Again, before the merge all was green.

**Comment by yurabakhtin** [comment]
> Oh jeah, I know that situation. Somehow frustrating, isn't it? :-)

@martin-rueegg yes, indeed :)

> @luke- I think we should disable the test again - #6731.

@luke- I see many errors there, so we cannot merge the PR now yet, I need to review them all.

**Comment by luke-** [comment]
Tests should be green now. Still need to check what's the difference between `master` and `develop`.

**Comment by luke-** [comment]
FYI, on `master` somehow the setting fixtures are not loaded correctly and the fallback (https://github.com/humhub/humhub/blob/master/protected/humhub/components/console/UrlManager.php#L46)  `http://localhost` is used instead of settings `baseUrl` value `http://localhost:8080`.


So I think the current solution with `http://hosthost` is ok. https://github.com/humhub/humhub/commit/f81f901c26dc289fda645920b567fb23d5f549b5  

Maybe in the long run we should also use the configured base URL `http://localhost:8080` for unit tests.
