### ISSUE TITLE
[DEVELOP] Module tests failing due added return type in `ContentContainerModule::disable`

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6754]
Currently many module tests fail, due to added return type here
https://github.com/humhub/humhub/pull/6550/files#diff-3634c090cf95aea01f8986dca83fa4721c2f44685893c63d683de1550ffc02f2R31

e.g.

- https://github.com/humhub/polls/actions/runs/7235129041/job/19712244281
- https://github.com/humhub/tasks/actions/runs/7235123207/job/19712230598
- https://github.com/humhub/cfiles/actions/runs/7235136109/job/19712260460

I would suggest we revert the change.

@martin-rueegg

**Comment by martin-rueegg** [comment]
@luke- thanks for the report

> I would suggest we revert the change.

- done in #6755

**Comment by martin-rueegg** [comment]
Maybe we should introduce a new section to MIGRATE-DEV.md:

```md
## Future type restrictions
```

A list of method return types that will be restricted in (one of the) next release. So devs can already add that return type to their modules and are ready by the time they are enforced by the underlying method. Otherwise, adding return types will never be possible as of course they to affect inheritance.


The problem still exists for class fields, though. There we do not have the ability to enforce the type later (as with function parameters) or earlier (as with function return types). a work-around would be to remove overwriting parameters in child classes and instantiate the values first thing in the constructor instead.

**Comment by luke-** [comment]
Thanks for the quick fix.

Instead of "Future type restrictions", my big hope is, to use Rector rules to optimize the code base here. Ideally, we can gradually add Rector rules, and on some point e.g. Humhub 2.0 enforce them.
