### ISSUE TITLE
Installer: Force Database UTF8 Collation

### ISSUE THREAD

**Issue by dakur** [humhub/humhub#677]
Hi, we are running HumHub on Ubuntu 14.04 and asking for user authentication on LDAP running on Windows 2003 Server. But there is a problem with received information about the user - the lastname, which containts special national characters, is not imported correctly - it shows "kucha?" instead of "kuchař" in HumHub. Is there any possibility to set characters encoding, or something like that?

**Comment by jkuchar** [comment]
I'm @dakur college.

It looks like something more global than just LDAP issue. When I post a text on a wall there is the same issue. 

ěščřžýáíéů becomes ?š??žýáíé?

It looks like wrong character-set in database. There definitely should be utf-8, it there? If not why? Shoudn't it be default in HumHub?

**Comment by dakur** [comment]
Then, maybe it is something wrong on our side. Will check it out.

**Comment by luke-** [comment]
Hmm, no problem here with special chars and ldap.

Are your tables Profile/User set to UTF8?

**Comment by jkuchar** [comment]
We will check this thing more deeply with @dakur next week. Probably there is some bug in installation script. Because it should ensure, that tables are created in utf8 (even if database configuration is whatever)

**Comment by dakur** [comment]
Ok, the problem was, that I did not follow the steps in installation guide about creating database. Instead, I've created user "humhub" and checked the option "create database with the same name as username" in phpMyAdmin. The default collation is "latin1_swedish_ci", so all HumHub tables were set in "latin1_swedish_ci".
BUT should not the HumHub installator check this out and set the right collation?

**Comment by jkuchar** [comment]
Or shouldn't installer stop installation and throw an error?

**Comment by jkuchar** [comment]
@dakur Please, could you update the issue title?

**Comment by cboulanger** [comment]
I just found out about this problem and will need to convert our databases manually... Please address this issue before releasing v1.0!

**Comment by buddh4** [comment]
@luke- this can be closed?

**Comment by jkuchar** [comment]
Still think that this should at least throw an error. So user will not end up in broken state.

**Comment by buddh4** [comment]
Maybe we can add  a prerequisite check for this. What do you think @luke- .

**Comment by luke-** [comment]
@buddh4 Yes, we may can also check table collations/engines in the test.

**Comment by luke-** [comment]
In the setup we have to do this check again separately, because the prerequisite check runs before.

It would also be good to make the port of the database configurable.
https://github.com/humhub/humhub/issues/158

In addition, a checkbox that creates the database directly, if possible, would also be a good thing.

**Comment by buddh4** [comment]
I've opened a seperate issue: https://github.com/humhub/humhub/issues/4818

**Comment by yurabakhtin** [comment]
@luke- I have tested this:

- Created a new DB with collection `latin1_general_ci`
- Run install
- The collation of the DB was converted to `utf8mb4_unicode_ci` and all tables were created with same `utf8mb4_unicode_ci` collection

It works like this because this migration https://github.com/humhub/humhub/commit/4ef22e12ffe30cacb7bacc9cb2e6b24098a11398#diff-f5897f5c0c6fbea496d34d10efdda6c776f533755cf12156b69c76b21366ec7cR8

I have also tested an install without the migration, in such case all tables were created with `latin1_general_ci`, so the sample `ěščřžýáíéů` is stored as `?š??žýáíé`.

**Comment by yurabakhtin** [comment]
> It would also be good to make the port of the database configurable. https://github.com/humhub/humhub/issues/158

Commit https://github.com/humhub/humhub/pull/4822/commits/dd9a7a7b8ba377edb591a06fdaff96c96d0d341b:
<img width="749" alt="port" src="https://user-images.githubusercontent.com/6995524/106720985-21a8f780-6615-11eb-86c8-5e768a229420.png">

**Comment by yurabakhtin** [comment]
> In addition, a checkbox that creates the database directly, if possible, would also be a good thing.

Commit https://github.com/humhub/humhub/pull/4822/commits/89e675ecd4324b23f3efd76fb98d8b2f3ca8bc5a:

<img width="973" alt="test_create_db" src="https://user-images.githubusercontent.com/6995524/106739340-13190b00-662a-11eb-8503-88ae11071c46.png">

**Comment by luke-** [comment]
@yurabakhtin  Looks good. Can you also check the collation?

**Comment by yurabakhtin** [comment]
@luke- 

> Looks good. Can you also check the collation?

Sorry, but I don't understand what collation check you mean here.

If you tell about collation prerequisite check then I implemented this here https://github.com/humhub/humhub/issues/4818.

If you want some additional check during install then I tested the install into DB with wrong collection here https://github.com/humhub/humhub/issues/677#issuecomment-772295510, i.e. if DB has no collection `utf8mb4` then such DB will be converted to `utf8mb4` during install and all tables will be created in the same collation because of migration https://github.com/humhub/humhub/commit/4ef22e12ffe30cacb7bacc9cb2e6b24098a11398#diff-f5897f5c0c6fbea496d34d10efdda6c776f533755cf12156b69c76b21366ec7cR8.

If this is not enough please give me more details where the collation check should be implemented, thanks.

**Comment by luke-** [comment]
Oh, that's right, I hadn't considered the migration. Then that is enough of course. Thanks!
