### ISSUE TITLE
Marketplace - Filtering and module count

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#6791]
HH 1.15.3

The displayed number of installed/not installed modules always stays the same. It should change depending on the selected filter or be removed when a filter is selected:

![image](https://github.com/humhub/humhub/assets/38326726/0717b393-6180-4a2a-89ed-4f23f8f559bf)

In general the numbers seem to be off. The filter "All categories" indicates that there are 95 modules, whereas the view in my test installation shows 22 installed and 62 not installed modules.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/issues/6791.

The number was wrong because the Marketplace displays not all unstalled modules but only which have `latestCompatibleVersion` and not deprecated, also it depends on the setting:

![mp-setting](https://github.com/humhub/humhub/assets/6995524/b6da0cc2-5cb7-468d-8c98-f918bbbfc05f)

I have fixed all these issues.

Also I have detected some modules have no categories at all, so I have added new option "Without category", and I have renamed the first option "All categories" to "All modules" because it really contains modules without category:

![marketplace-categories](https://github.com/humhub/humhub/assets/6995524/5b242978-2a63-4834-925e-b001b172e248)
