### ISSUE TITLE
 Some Emojis not loading

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6801]
See: https://community.humhub.com/u/archblood/?contentId=274473&commentId=47577

**Comment by yurabakhtin** [comment]
@luke- PR  - I have downloaded missed images from here https://www.bootcdn.cn/twemoji/, but I still see some emojis is empty but there I cannot see what image should be downloaded, for example, for the missed images I find a html code like:

```html
<li class="atwho-emoji-entry">
    <img class="emoji" draggable="false" alt="❤️‍🩹" src="/static/img/twemoji/72x72/2764-fe0f-200d-1fa79.png" data-name="mending heart" style="width:16px">
</li>
```

but some rest empty cells I see only this html code:

```html
<li class="atwho-emoji-entry"></li>
```

such empty cells looks like a separator, if it is not normal please let me know to investigate them.

**Comment by luke-** [comment]
@yurabakhtin Can you send me an example picture of missing emojis?


In principle, I would prefer it if we could manage to load this emojis dependency via NPM or Composer.

e.g. via https://www.npmjs.com/package/twemoji

can you check if that would be possible?

**Comment by yurabakhtin** [comment]
> Can you send me an example picture of missing emojis?

@luke- 

![empty-smiles](https://github.com/humhub/humhub/assets/6995524/3a701bfa-29fb-433e-9a45-a561729d3cd3)

**Comment by yurabakhtin** [comment]
> In principle, I would prefer it if we could manage to load this emojis dependency via NPM or Composer.
> 
> e.g. via https://www.npmjs.com/package/twemoji
> 
> can you check if that would be possible?

@luke- Here https://www.npmjs.com/package/twemoji#dom-parsing I see:

```js
img.src;        // https://twemoji.maxcdn.com/v/latest/72x72/2764.png
```

as I understand the package has no images, they should be loaded from `https://twemoji.maxcdn.com/v/latest/`.
I tested to change the config path https://github.com/humhub/humhub/blob/master/protected/humhub/config/common.php#L271-L274:

```php
        'twemoji' => [
            'path' => '@web-static/img/twemoji/',
            'size' => '72x72'
        ],
```

to `'path' => 'https://twemoji.maxcdn.com/v/latest/',` so all images are loaded correctly:

![cdn-source](https://github.com/humhub/humhub/assets/6995524/d74d2c6c-5545-4b01-bf96-fd82806f40dd)

however if I open url like https://twemoji.maxcdn.com/v/latest/72x72/1f389.png I have a redirect to https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/72x72/1f389.png so better to use this url.

Do you agree these external urls, or we need to find a package with contains all latest version images?

**Comment by luke-** [comment]
@yurabakhtin We should find a solution without external URLs.

It might also make sense to research whether we should switch to a more modern libarary than twemoji.
What do you think? Can you check what the current approaches are here?

Perhaps Serh could then implement this.

**Comment by yurabakhtin** [comment]
@luke- I find only this https://www.npmjs.com/package/emojiimages, but it contains images with size 200x200 instead of current 72x72, also the images are different, for example:

- https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/72x72/1f1e6-1f1e9.png

![1f1e6-1f1e9](https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/72x72/1f1e6-1f1e9.png)

- https://github.com/cj1128/emoji-images/blob/master/imgs/1f1e6-1f1e9.png

![1f1e6-1f1e9](https://github.com/cj1128/emoji-images/blob/master/imgs/1f1e6-1f1e9.png?raw=true)

as you see the 200px size has unexpected space around real image:

![space](https://github.com/humhub/humhub/assets/6995524/3ca7b46c-282b-4943-8594-e2b3c68703c7)

**Comment by luke-** [comment]
Hmm. are all files available here?
https://github.com/twitter/twemoji/tree/master/assets/72x72

**Comment by yurabakhtin** [comment]
Yes, but I don't find them here:

![npm-twemoji](https://github.com/humhub/humhub/assets/6995524/0c43f291-0e00-4b3b-a407-9f528bcece8f)

as I understand from here https://github.com/twitter/twemoji?tab=readme-ov-file#download we should use the package https://www.npmjs.com/package/gh-pages in order to download the files.

**Comment by luke-** [comment]
@yurabakhtin I think it's about the git branch: see here: https://github.com/twitter/twemoji/tree/gh-pages

**Comment by luke-** [comment]
Hmmm, ok. Can you extract all needed files from the Github repo?

**Comment by yurabakhtin** [comment]
@luke- What do you mean here by "extract"? Just download them manually or create a script which will downloads them all automatically?

Curently here https://github.com/humhub/humhub/tree/fix/6801-emojis-not-loading/static/img/twemoji/72x72 we already have all required image.

**Comment by luke-** [comment]
@yurabakhtin By extract, I mean download and add it to `static/img`. As already done.

Aren't there any emojis missing?

**Comment by yurabakhtin** [comment]
@luke- 

> Aren't there any emojis missing?

Currently, I don't see any images which cannot be loaded, I added 130 missed images in the first commit https://github.com/humhub/humhub/pull/6802/commits/62b743fc197b8e5a2873c1621b9358598719ef97, but yes we have some empty cells where we don't see what image should loaded there. As I wrote above the empty smiles have version `15.0`, I guess they should be fixed from prosemirror js-plugin side or twemoji should be updated to use v15 smiles.

I have compared what new images can be loaded from reporsitory `twemoji`:
- https://github.com/humhub/humhub/tree/fix/6801-emojis-not-loading/static/img/twemoji/72x72 - 3207 images(including these 130 added in the 1st commit)
- https://github.com/twitter/twemoji/tree/gh-pages/72x72 - 872 images (no new images)
- https://github.com/twitter/twemoji/tree/master/assets/72x72 - 3689 images (482 new images)

I have commited the new 482 images in the 2nd commit https://github.com/humhub/humhub/pull/6802/commits/0746eb6c5d3e2a6a8a9e5f595c6817e347469b06, but it doesn't solve the empty smiles because I guess the twemoji uses only 14 version, for example, `shaking face`(unicode `1FAE8`) is not displayed(it is empty cell) and here https://emojipedia.org/unicode-15.0 we see all the empty smiles are from v15.
