### ISSUE TITLE
add support for openid SSO 

### ISSUE THREAD

**Issue by jvies** [humhub/humhub#6906]
I successfully integrated the Worteks extension for openid (cf https://github.com/Worteks/humhub-auth-oidc) with the latest release (1.15.4), and then successfully connected it with Authelia.

Any chance this extension is officially integrated ?

Best regards

**Comment by jvies** [comment]
I'll give it a try without the Worteks extension.

**Comment by marc-farre** [comment]
@jvies Thanks for sharing.

I've also created an SSO module for Keycloak using OpenId Connect from `yii\authclient\OpenIdConnect`: https://github.com/cuzy-app/humhub-modules-auth-keycloak/blob/master/authclient/Keycloak.php

I had to add this missing dependency: https://github.com/cuzy-app/humhub-modules-auth-keycloak/blob/master/composer.json#L9

So maybe a better approach would be to include this missing dependency in HumHub core and then we can directly use `yii\authclient\OpenIdConnect`.
However, the recommended way of adding SSO to HumHub is to create a module for each SSO provider.

So I'm not sure of the value of your https://github.com/Worteks/humhub-auth-oidc because:
- we already have `yii\authclient\OpenIdConnect`
- it should be a module to make it available on [the Marketplace](https://marketplace.humhub.com/)
- We shouldn't have to add the settings in a configuration file directly on the server (even if it works)

**Comment by marc-farre** [comment]
@jvies Feel free reusing the code of the Keycloak module if it helps.

**Comment by jvies** [comment]
@marc-farre 
I never wrote a Humhub plugin... My last php code was around 2002.

But I can give it a try.

**Comment by jvies** [comment]
OK. I have a first module to be tested here:
https://github.com/jvies/humhub-modules-auth-authelia

I started from the cuzy-app/humhub-modules-auth-keycloak that I cleaned-up and adapted a bit.

I successfully :
- connected an already registered user
- registered a new user in humhub that exists in Authelia

Known limitations :
- I only speak French and English, so I removed all other i8n
- I would like to have users from Authelia automatically approved in Humhub
- I would like to have the Humhub registration form filled-in by the profile from Openid

If you have some free time, it would be great that you review this first draft.


By the way, I did not succeed in using the module yii\authclient\OpenIdConnect only through the configuration.

**Comment by marc-farre** [comment]
@jvies Very well done! And thanks for sharing!

If you think you will maintain the module in the time, it would be nice if you suggest it to HumHub marketplace: https://partner.humhub.com/

I haven't tested the module (because it would take time for me to configure and Authelia server), but after having a look at the code, everything seems perfect!

I think you can close this issue now.

PS: je vois que tu es Toulousain, comme moi ! Si jamais, mon site pero: https://marc.fun/

**Comment by jvies** [comment]
I've proposed my module.

Thanks a lot for your support.

I close the ticket.
