### ISSUE TITLE
v1.16 Search out of viewport on mobile

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub/humhub#6953]
### What steps will reproduce the problem?
Click search icon in community.humhub.com or another instance running 1.16

### What do you get?
![Screenshot_20240418_075254_Chrome.jpg](https://github.com/humhub/humhub/assets/84990763/a83d94e5-33ea-4db2-84e7-af77ed9a38c4)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by yurabakhtin** [comment]
@felixhahnweilheim Thank you for the report. I could reproduce this only on mobile device, but on PC browsers it works well even on device developer mode where I have tried many different sizes of different devices.

@luke- Please try a fix from the PR https://github.com/humhub/humhub/pull/6954, I hope it should helps. I could not repoduce this locally so I have debugged it by USB on my mobile phone, I think the problem was here:

![debug-mobile](https://github.com/humhub/humhub/assets/6995524/48cfdf08-a176-45d5-b594-40be98f5bfd7)

**Comment by felixhahnweilheim** [comment]
Thanks, the PR solves the problem (tested on my instance).
