### ISSUE TITLE
Profile Dropdown - without key syntax - strange behavior 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#6961]
Related: https://github.com/humhub/humhub/issues/6960#issuecomment-2069003708
Directory Loader

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/6965: I don't think we should use a value as key for case when it is not defined, because it may breaks profiles which were stored before. For example, if the options were defined as:

```
Male
Female
Diverse
```

then it works as array with autoincremented keys started with `0`:

```
0 => Male
1 => Female
2 => Diverse
```

so some profiles were strored with `gender = 0` and it worked well except of the People Filter.
The "loading" error was there because of this JS [code](https://github.com/humhub/humhub/pull/6965/files#diff-083f73d6743a73e8bc12820b0b27292b69cba4e4bdf7c2796ea01a6601efb690R273), i.e. the loader is visible there instead of expected title "Male".

The PR fixes the filter issue, it can be merged, but maybe we should either add an additional info in the field hint `One option per line. Key=>Value Format (e.g. yes=>Yes)` or restrict for saving it without keys:

![hint](https://github.com/humhub/humhub/assets/6995524/2ed32734-b541-458d-a354-b5a498fe455f)

**Comment by luke-** [comment]
@yurabakhtin Ok got it, a validator for the field (check for keys) would probably be the cleanest solution. Can you please implement this?

**Comment by yurabakhtin** [comment]
@luke- I have added the validation in the commit https://github.com/humhub/humhub/pull/6965/commits/922b4309c06ed94c6816976e63d50251257e8680:

![validate-select](https://github.com/humhub/humhub/assets/6995524/9b1ed46d-f8ce-40db-9fcc-c30f776a0ed7)

But I have also detected the same hint we have for the profile type "Checkbox List":

![chekcboxlist-hint](https://github.com/humhub/humhub/assets/6995524/23d97069-c234-400f-8d00-5fe6aca1a316)

and this type already uses a Value as Key when it is not defined, the code is [here ](https://github.com/humhub/humhub/blob/fix/6961-profile-filter-dropdown/protected/humhub/modules/user/models/fieldtype/CheckboxList.php#L162).
So here I am a bit confused, because I don't think we should restrict the "Checkbox List" field as I have done for the "Select" field, because such fields were stored in DB with using Values as Keys. Maybe we should update the hint of the "Checkbox List" field to inform the format may be without Keys. Of course better is to keep the same format and same validation for these fields, but in such case we should implement a migration to fix all stored wrong keys.

**Comment by luke-** [comment]
@yurabakhtin I would prefer if we align CheckboxList and SelectList and use the same validation and saved data keys here. Then we could also allow the type to be changed in future.

Would you like to customize the checkboxes and migrate the data?

**Comment by yurabakhtin** [comment]
@luke- 

> Would you like to customize the checkboxes and migrate the data?

Done in the commit https://github.com/humhub/humhub/pull/6965/commits/922b4309c06ed94c6816976e63d50251257e8680.
Options will be fixed by new migration with this way depending on field type:

![checkbox-list](https://github.com/humhub/humhub/assets/6995524/6c9ee181-e1ad-4c95-91cd-550a65014487)

![select-list](https://github.com/humhub/humhub/assets/6995524/10f57f3a-56bc-406e-94ea-6a70bdcf1ce7)

**Comment by luke-** [comment]
@yurabakhtin Thanks, good solution!
