### ISSUE TITLE
Virutal Profile Field Type: Template

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#7056]
Allow the combination of profile fields possible via Twig.

e.g.

"virtual_fullname"  with template "%firstname% %middlename% %lastname%"

**Comment by ArchBlood** [comment]
I've noticed that when it comes to creating templates, these fields are made so that they're only visible but not editable, those that create more advanced twig templates may find that this as well as the 255 character limit too restricting, so I'd like to suggest the following;

- Remove the 255 max limit
- Render both the profile field frontend and in the user settings
- Add ability to edit template fields

**Comment by gevorgmansuryan** [comment]
What it means to edit template field? How it will looks like?

**Comment by ArchBlood** [comment]
> What it means to edit template field? How it will look like?

Say someone creates a template for a custom field that isn't available for use in native HumHub, like a family tree or relationship status, the template should render the template as it does in the about section of a user's profile and editable by the user in their account settings, the current version makes not much sense to me and is very limited in many ways.

**Comment by luke-** [comment]
@ArchBlood I'll close the issue for now. If you have ideas on how we can further improve the feature, please create a separate feature request.
