### ISSUE TITLE
Bulk re-send email invites

### ISSUE THREAD

**Issue by samuk** [humhub/humhub#7068]
### Is your feature request related to a problem? Please describe.

![294pending](https://github.com/humhub/humhub/assets/400875/ff9499fa-b374-42bc-8fab-b9afa9dbb59c)

I have 294 pending invitations in my instance. I'd like to re-send those invites to remind those that have been invited

### Describe the solution you'd like

A button to re-send all 294 invites

### Describe alternatives you've considered

Clicking and scrolling 294 times

**Comment by marc-farre** [comment]
Maybe adding a button with similar behavior to the "Delete All" or "Delete selected rows" button?

![image](https://github.com/humhub/humhub/assets/23310825/e928d3cc-0f7b-452e-9d9f-3e60dd5f90d0)

![image](https://github.com/humhub/humhub/assets/23310825/8d253bba-0d61-4552-900a-e85d9d20809e)

**Comment by samuk** [comment]
Yes that would be great in terms of UX. Is it something we can do locally @marc-farre or does it need to be applied upstream?

**Comment by marc-farre** [comment]
@luke- what do you think about this idea for HumHub core?

I would also move the "Back to user overview" button to the top right of the page to avoid having too many buttons:
![image](https://github.com/humhub/humhub/assets/23310825/767f1df3-5503-4039-93bd-522f6627eb5b)

**Comment by marc-farre** [comment]
> Do we really need the button?

@luke- what do you think about opening pages like this one in a modal box instead?

**Comment by samuk** [comment]
@luke- any thoughts on this one?

**Comment by luke-** [comment]
> > Do we really need the button?
> 
> @luke- what do you think about opening pages like this one in a modal box instead?

@marc-farre Do you mean the "Pending registrations" page? It seems a bit too large for that. Besides, there are also confirm dialogues, which would then be a modal in the modal?

**Comment by marc-farre** [comment]
@luke- yes. I think that admin pages opened via a button should be displayed in a modal box:
![image](https://github.com/humhub/humhub/assets/23310825/4abb4c84-0282-4b39-8309-d81e9ca679d6)

If we use the modal size `large` (https://github.com/humhub/humhub/blob/73fb5aa66cf4cac2d85341f6778fe64ddcb77d17/protected/humhub/widgets/Modal.php#L41-L51) we won't have width issue.

Confirm dialog open in another modal box (`#globalModalConfirm) which has `z-index: 1050;`, so it displays fine on top of the global modal box (`#globalModal`) which has `z-index: 1041;`

However, if you think it's better to keep this page in a plain page, then I think we should keep the "Back to user overview" button. 
Maybe we could rename to "Back to overview" to have the same button as the one on the "Add new user" page:
![image](https://github.com/humhub/humhub/assets/23310825/385ce228-07a4-4888-80f5-79a3d3ec0188)

**Comment by ArchBlood** [comment]
I like the idea of opening in a model box, could also make many things more mobile friendly in the long run, as it stands there are a lot of direct and redirections when it comes to HumHub, this isn't really user friendly or mobile friendly and requires more loading than needed. Simplifying some buttons to work as modals would reduce many issues currently in place.

**Comment by luke-** [comment]
> @luke- yes. I think that admin pages opened via a button should be displayed in a modal box: 

@marc-farre  What do you mean by admin pages?

When it comes to putting some individual views such as "Add User" into a modal, I think it's good.
Other views, such as the user list, I wouldn't want to put in a modal. 

However, we are planning to optimise the page structure and navigation in the future.

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/humhub/pull/7147

Before:
![image](https://github.com/user-attachments/assets/2b84678c-00e2-4827-9655-6b8124c30baa)

After:
![image](https://github.com/user-attachments/assets/a74c69f3-3b90-4fb8-a6c3-42150a433ad1)

There are some new translations to be done.

> When it comes to putting some individual views such as "Add User" into a modal, I think it's good.
> Other views, such as the user list, I wouldn't want to put in a modal.

I agree.

**Comment by luke-** [comment]
@Eladnarlea What do you think about the buttons? Should we adapt them for now and change later?

**Comment by Eladnarlea** [comment]
@marc-farre I have one more question regarding the buttons with indicator `all`: As I understand, with the new design you would not have to select the major check-box anymore, in order to trigger `all-actions` like `delete  all` – `re-send to all` . 

<img width="1048" alt="Screenshot 2024-08-26 at 12 32 12 PM" src="https://github.com/user-attachments/assets/7259db73-4d8e-438d-a010-fd46650d9ff6">

_________________________________

As this would mean, it doesn't follow the logic anymore, I would suggest to style the button differently:
- Make buttons disabled until people have checked the major check-box, or selected several rows. 
- When major checkbox is checked, buttons become active and are clickable afterall

_________________________________

On top of that: 
These action-buttons are related to the list, and therefore should be located underneath the list. Now they are located on top of the list. When admins perform these actions, they usually work their way from top to bottom, and then perform the action. In this scenario they would have to scroll all the way back up to perform the action.

### My quick sketch 
**Note:** Please note that this is neither the correct List and Page, nor the correct icons on the buttons, but the button **positions** could be adapted like this.

The colors of the buttons at the bottom of the list would be disabled and then, when they came into action, would become default style, as they are all of the same level of importance.

<img width="863" alt="Screenshot 2024-08-26 at 12 56 33 PM" src="https://github.com/user-attachments/assets/d3e1bb92-1796-4688-a8b3-bc2d3908bf18">


optionally, we could make the `Delete` Button a `button-danger`

<img width="862" alt="Screenshot 2024-08-26 at 1 01 27 PM" src="https://github.com/user-attachments/assets/9db08242-63e7-48ef-8094-655fcff5a10a">

Pro:
- buttons wouldn't be too cluttered at the top of the list
- easier for mobile

**Comment by marc-farre** [comment]
@Eladnarlea As you can see in my "Before" screenshot, we already had the "Delete All" button.
I think we should keep "All" buttons, because it allows making an action on all users of the list, even if the pagination has more than one page.
Checking the "major check-box" will select all users of the current page only.

This PR only moves the "Back to users overview" button and adds the "Re-send to All" (or "Re-send to selected rows" if some rows are checked) button.

**Comment by Eladnarlea** [comment]
> Checking the "major check-box" will select all users of the current page only.

@marc-farre okay, I understand. I wasn't sure about the correct behaviour as I don't have a page where this scenario exists. I also agree, that your fix is the fastest and easiest one.

### There are two major aspects that I would like to highlight:

1. usability -> buttons which change their names are not really userfriendly. It's always better to design the action itself as clearly as possible so one button would cover every case... 
2. The different  button colors overcrowd the interface. we should at least consider to change the button styles
3. The placement of buttons should be logical to their actions
4. my biggest concern: even if this is only one more button in this case, in the bigger picture we know, that a lot of buttons have been added in the past, therefore every scenario should be viewed carefully :)

**Comment by marc-farre** [comment]
@Eladnarlea 

> 1. usability -> buttons which change their names are not really userfriendly

I agree. It's quite uncommon. However, how should we give the possibility to make an action to all users when users are on multiple pages (e.g., "Delete All")?

> 2. The different button colors overcrowd the interface

Same answer. How to deal with "All" action buttons?
In all HumHub, delete buttons are red.

> 3. The placement of buttons should be logical to their actions

I agree to that we could place them at the bottom of the page.

**Comment by Eladnarlea** [comment]
> I agree. It's quite uncommon. However, how should we give the possibility to make an action to all users when users are on multiple pages (e.g., "Delete All")?

To figure out how to deal with this situation, I have a question to the people using this:
Do you sometimes click the `Major Checkbox` to select the list items on the first page, or not?

Because if this is used seldomly, I would suggest to put a lable next to the `Major Checkbox `clearly stating:   
- [ ] **All**   

, so whenever you click the ckeckbox, all items of the list are selected (how it should be, logically, I guess? Or is this a wrong assumption from my side, @marc-farre?)...

<img width="801" alt="Screenshot 2024-08-27 at 7 55 46 AM" src="https://github.com/user-attachments/assets/71d2c72b-e461-43a0-a4d3-aeccc3f79561">

______________________________

> Same answer. How to deal with "All" action buttons?
> In all HumHub, delete buttons are red.

You are actually partially right, that's why I also added this screen to my previous screenshot, in case the `Delete button` should be `@danger`. 

However, there are some "Delete" `Icon Only Buttons`, that are grey. 

On the other hand, I think this is a matter of UX, because in case we only make the `Delete button` available if the `major checkbox` is selected, then it should not be `@default` style, but `- disabled - @danger-btn` style.

<img width="862" alt="Screenshot 2024-08-26 at 1 01 27 PM" src="https://github.com/user-attachments/assets/0c5e940b-da13-4b0b-95a2-7479086b8e28">

**Comment by marc-farre** [comment]
@Eladnarlea Some screenshots of the "Pending approvals" page of a HumHub instance:
![image](https://github.com/user-attachments/assets/ab48bdbc-0bbf-4346-90e5-4e75375c11fa)
![image](https://github.com/user-attachments/assets/f06c6bcd-1c2b-485e-b9f3-96ed2fa141f0)

Here, the buttons are at the bottom, as you suggested.
And there is no "Email all" (i.e. to 1689 users at once) here. It means, we have to click the "major checkbox" to email 50 users, and repeat the operation 1689/50 = 44 times to email all users, because we have 44 pages with 50 users.

So in this case, the "All" button would be useful. And I think we should have the same system in both pages:
- Pending registrations
- Pending approvals

>  it should not be @default style, but - disabled - @danger-btn style.

I agree. This is how it is on the "Pending approvals" page (see screenshots above).

I'm not quite sure, but perhaps we could add a checkbox like this one?
![image](https://github.com/user-attachments/assets/50c9fdb4-62fb-4562-ade4-a87613b842e6)

**Comment by Eladnarlea** [comment]
@marc-farre just to clarify: This page exists like this already? Or did you modify it to visualise the ideas that we brainstormed?

I think it is a good idea to add the checkbox there. I would probably label it like this:

- [ ] Select all `number`

**Comment by luke-** [comment]
@marc-farre @Eladnarlea Please create an issue for a redesign. But at the moment I can't schedule it.

**Comment by luke-** [comment]
Thanks for the issue. I have merged it.

Then we can close the issue here and you have created a new one for the redesign?

**Comment by marc-farre** [comment]
> Then we can close the issue here and you have created a new one for the redesign?

Yes, in https://github.com/humhub/design-tasks-overall/issues/44
