### ISSUE TITLE
Download Humhub Zip (missing file) ...

### ISSUE THREAD

**Issue by Beduac** [humhub/humhub#708]
Installing Humhub and my database I received the following message, but after hours of searching in those 12.500 files I had transfered to my server I'm sure the file was not included. Hello GITHUB, could you please send me the missing file via email, I'd like to complete my intention.
Kind regards from Germany, Bernd

PHP warning
is_file(): open_basedir restriction in effect. File(/usr/share/php/Zend_Search_Lucene_Search_QueryParser.php) is not within the allowed path(s): (/var/www/web90/htdocs:/var/www/web90/apps:/var/www/web90/priv:/var/www/web90/tmp:/usr/share/pear:/usr/share/php:/tmp)

**Comment by bastrian** [comment]
it means that Humhub cannot access some Files due restrictions. I fixed it on the Windows Server by modifying the open_basedir in php.ini
To help you understanding the error:
"I cannot access /usr/share/php/Zend_Search_Lucene_Search_QueryParser.php because it is not whitelisted in in Open_basedir. What i found is that /var/www/web90/htdocs:/var/www/web90/apps:/var/www/web90/priv:/var/www/web90/tmp:/usr/share/pear:/usr/share/php:/tmp is in the whitelist."

A fix could be if you modify the php.ini and add the missing directory. It would look like this:
/var/www/web90/htdocs:/var/www/web90/apps:/var/www/web90/priv:/var/www/web90/tmp:/usr/share/pear:/usr/share/php:/tmp:/usr/share/php/
