### ISSUE TITLE
Groups - Default permissions/Space creation

### ISSUE THREAD

**Issue by Semir1212** [humhub/humhub#7113]
When a new group is created, it is given the permission to create private/public spaces by default. We should change the default settings so that users do not get this permission by accident. 

Create Private Spaces --> Deny
Create Public Spaces --> Deny

**Comment by luke-** [comment]
Should we allow this for the Default User Group? 
I would say yes, you can always make it more restrictive later on.

**Comment by marc-farre** [comment]
I have often had to deny these default permissions in the config file, so I also think they should be denied by default.
For the Default User Group, I think it's better to deny them too, because:
- When we create a new group, we expect the default permissions to be the same as the User group (it might be confusing to have different default permissions).
- When installing a new HumHub instance, it's logical and safer to reserve Space creation for admins only by default.

Maybe a migration for existing HumHub instances could configure all existing Groups with the existing Space creation permissions?

**Comment by Semir1212** [comment]
I agree with @marc-farre, it should also be denied for the default user group.

**Comment by luke-** [comment]
Ok, we can do it that way too.

For me, the main pro reason was to demonstrate that HumHub can also be freely organised (anyone can create Spaces) without administration.

---

@marc-farre So you mean a migration to manually set the permissions to "Allow" for existing installations?

**Comment by marc-farre** [comment]
> @marc-farre So you mean a migration to manually set the permissions to "Allow" for existing installations?

Yes. But it mustn't apply to the User Group when installing a new HumHub instance...
