### ISSUE TITLE
Improve UX on search popup

### ISSUE THREAD

**Issue by samuk** [humhub/humhub#7148]
### Is your feature request related to a problem? Please describe.

When searching for a term in the (new?) search popup I often need to scroll through many pages of content before finding the users who have that term in their /about content

### Describe the solution you'd like

1) Have an 'advanced search' link at the top of the popup/ modal that opens a full page to return more results

### Describe alternatives you've considered

2) Make the content types collapsible? In my example above if I could click on 'content' and that collapsed all the 'content' results I could more easily find my way to the people

cc @marc-farre

**Comment by ArchBlood** [comment]
See the advanced search module;
https://marketplace.humhub.com/module/advanced-search/description

**Comment by Eladnarlea** [comment]
@samuk are you referring to something like this?

<img width="416" alt="Screenshot 2024-08-01 at 5 49 36 AM" src="https://github.com/user-attachments/assets/1c24d36a-42bd-482c-a36c-72e110c7627a">

**Comment by marc-farre** [comment]
The issues are with the Link Preview module.

1/ When adding a link, the text is not truncated anymore:

![image](https://github.com/user-attachments/assets/bd08c3cc-cd14-467d-a75b-3c6d723f6a90)

2/ We shouldn't display the "Allow content from external source" warning:

![image](https://github.com/user-attachments/assets/b67f6aa0-2172-4b43-89f9-954e4f39dbb0)

**Comment by luke-** [comment]
@yurabakhtin Is the wrong richtext parser perhaps being used here?
I would rather expect a plain output here. This should not contain ‘Translate’, ‘LinkPreview’, etc., should it?

**Comment by samuk** [comment]
> 2/ We shouldn't display the "Allow content from external source" warning:

Shouldn't we? I get that it's ugly from a UX perspective, but if we're taking that seriously we shouldn't leak user IP without consent?

**Comment by marc-farre** [comment]
> > 2/ We shouldn't display the "Allow content from external source" warning:
> 
> Shouldn't we? I get that it's ugly from a UX perspective, but if we're taking that seriously we shouldn't leak user IP without consent?

In search results displayed in the dropdown box, we should display plain text (no preview or external content). So this warning is useless here.

**Comment by yurabakhtin** [comment]
@luke- @marc-farre Currently it works like this on the version `1.16.2 (Unreleased)`:

![render-meta-search](https://github.com/user-attachments/assets/82b6ccd3-79e6-42d6-8d6d-cd18d21af2b6)

![allow-content](https://github.com/user-attachments/assets/e8a6bd38-965b-4cbd-aba1-8c71f8fb2610)

---

- firstly it is rendered by `RichText::output()` in order to remove from text markdown chars like `####`, `---`, `*`
- then all html tags are removed by JS

as I understand we should remove all appended things from modules, so probably we should use `RichTextToPlainTextConverter::process()` instead or create new one to remove all markdown chars, right?

**Comment by yurabakhtin** [comment]
If use `RichTextToPlainTextConverter::process()` instead of `RichText::output()`:

![1](https://github.com/user-attachments/assets/a22e798f-a6a7-4e5b-b283-fcc1ae6b6aa2)

![2](https://github.com/user-attachments/assets/1f06c03a-b535-4fcc-ba1f-96b3be447fc4)

So not all markdown chars are removed.

**Comment by ArchBlood** [comment]
> If use `RichTextToPlainTextConverter::process()` instead of `RichText::output()`:
> 
> ![1](https://private-user-images.githubusercontent.com/6995524/362359141-a22e798f-a6a7-4e5b-b283-fcc1ae6b6aa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjgxNzEsIm5iZiI6MTcyNDg2Nzg3MSwicGF0aCI6Ii82OTk1NTI0LzM2MjM1OTE0MS1hMjJlNzk4Zi1hNmE3LTRlNWItYjI4My1mY2MxYWU2YjZhYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTc1NzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVhNjMxYjlmM2M0ZWY3OWRlYWEwMDhjM2IwMTllZDBiZGU1OTk3Y2RjOWZhMjg0YzI1MzY5MTNlMzE4MjdjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XjWb1k7FrxeGgC9WmJF7j88gKOZRVq4bgOlm_sJYHO0)
> 
> ![2](https://private-user-images.githubusercontent.com/6995524/362359160-1f06c03a-b535-4fcc-ba1f-96b3be447fc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NjgxNzEsIm5iZiI6MTcyNDg2Nzg3MSwicGF0aCI6Ii82OTk1NTI0LzM2MjM1OTE2MC0xZjA2YzAzYS1iNTM1LTRmY2MtYmExZi05NmIzYmU0NDdmYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTc1NzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDEyMzdhOTU4OTZhZjhkOGQ3N2ViMGZkYWJkNzYxOTgwOTU4MzFlZDMyZmYwMmY3OTIwMjE0Njg5NzJkZThjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.St-nd0AbOJOuEzznINn6VrRWCUM0Topk9UeNVARtLYQ)
> 
> So not all markdown chars are removed.

I believe I've mentioned something along the lines of creating a helper class when it comes down to this exact thing;
https://github.com/humhub/humhub-prosemirror/pull/95#issuecomment-2266417530

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub/pull/7193:

- I have decide to use `RichTextToHtmlConverter::process()` and strip tags on the server side,
- also I have done to cut the content to first found word, please how it looks without the cutting:

![before-cut](https://github.com/user-attachments/assets/aea6c395-dca1-4491-89ae-86d8cdba0b9e)
(here the keyword is highliged by js but it is not visible)

It is why I have done to cut the content to first found word with the keyword, but probably we should display one word before the word with searcing keyword, what do you think?
![after-cut](https://github.com/user-attachments/assets/32e7003b-4794-4b8a-a6f7-9851a9e53874)

**Comment by marc-farre** [comment]
@yurabakhtin if `RichTextToPlainTextConverter::process()` keeps markdown syntaxes such as `###`, shouldn't we improve this class to remove them?

Other maybe `RichTextToHtmlConverter` + `strip_tags`?

**Comment by yurabakhtin** [comment]
> if `RichTextToPlainTextConverter::process()` keeps markdown syntaxes such as `###`, shouldn't we improve this class to remove them?

@marc-farre I didn't investigate this deeply why the convertor keep the chars like `###`, probably you are right and such chars should be removed for the convertor because yes it is strange to keep them in plain text.

> Other maybe `RichTextToHtmlConverter` + `strip_tags`?

That is what I have implemented the PR https://github.com/humhub/humhub/pull/7193 [here](https://github.com/humhub/humhub/pull/7193/files#diff-c4cb0fcf397d1272c6dd36f78b88a309cf38639b6947ca4258ca8eccd8d25e93R49-R50).

Do you like how it looks now after changes in the PR? :

![after-cut](https://github.com/user-attachments/assets/9c17fee0-7031-461a-8b18-a2a2d9849b82)

or will it be better to display an additional word before the word with highlighted keyword?

**Comment by marc-farre** [comment]
@yurabakhtin perfect, thanks!

> display an additional word before the word with highlighted keyword?

Yes, I think it would help.

**Comment by yurabakhtin** [comment]
> > display an additional word before the word with highlighted keyword?
> 
> Yes, I think it would help.

@marc-farre I have done this in new PR https://github.com/humhub/humhub/pull/7195 because previous was merged recently.

@luke- Please see how it was before:

![after-cut](https://github.com/user-attachments/assets/529f82f4-522e-4a28-a0ba-7918fad8ac33)

and how it looks after the new PR https://github.com/humhub/humhub/pull/7195:

![1](https://github.com/user-attachments/assets/3f83e1ff-18aa-4e40-bcb9-b5341afed8f5)

other samples:

![2](https://github.com/user-attachments/assets/5d5fd437-37ba-405e-951a-10dd9f9b34ef)
![3](https://github.com/user-attachments/assets/2b82d250-97da-4f91-a700-0c93d812c946)
![4](https://github.com/user-attachments/assets/ee7d3abd-5348-4ac6-ba89-202371e10173)
![5](https://github.com/user-attachments/assets/ba8b43c7-b549-4e80-ab91-9b1d2075bdbc)

**Comment by marc-farre** [comment]
@yurabakhtin looks perfect, thanks!

**Comment by yurabakhtin** [comment]
@luke- 

> but does it mean we no longer show the title the result?

We use the same text from `$this->content->getContentDescription()` as it was before the changes here.
I just improved the removing markdown chars and html from the original text.
Also if the text is so long so the highlighed text is not visible I have done to cut off first part of the text to make the word visible with highlighed keyword.

> However, for hits from the file/wiki module or polls, I think it would be better to see the title/filename.

Each record extended from `ContentActiveRecord` should has defined the method `getContentDescription()` that should return some data, and the data is displayed there.

**Comment by luke-** [comment]
@yurabakhtin Ok, thanks for clarify. Thats fine, so in these modules it is the Filename/Page Title.
