### ISSUE TITLE
"User Display Name Subtitle" shows country code instead of country name

### ISSUE THREAD

**Issue by poVoq** [humhub/humhub#7266]
### What steps will reproduce the problem?
Select "country" as the "User Display Name Subtitle" under the appearance settings.

### What is the expected result?
It should show the country name as a subtitle. For example "Portugal".

### What do you get instead?
It shows "PT" instead.

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.x

**Comment by ArchBlood** [comment]
That is by design.

**Comment by poVoq** [comment]
Maybe it should be labeled as "country code" then?

**Comment by luke-** [comment]
You could use a callback to translate the country code into the name of the country. 

Example of Callbacks:
https://community.humhub.com/s/installation-and-setup/wiki/80/configuration-examples#change-user%E2%80%99s-subtitle

Otherwise, we unfortunately only save the country code in the field as a value. Therefore, it cannot be easily selected as a subdisplay name.
