### ISSUE TITLE
Space permissions not applying right in the User stream

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7351]
### What steps will reproduce the problem?

1. Create 2 spaces: A and B
2. In Space A, for "Members", set "Create comment" and "Can like" permissions to "Deny"
3. With User 1, post in the 2 spaces
4. With User 2, which is a member of the 2 spaces (but not an admin), browser the stream of User 1

### What is the expected result?

User 2 can comment and like the post from Space B, but not the one from Space A

### What do you get instead?

The "Comment" and "Like" links are displayed on both posts, or on none of them.

### Additional info

Full explanation: https://community.humhub.com/s/general-discussion/post/post/view?id=17110

| Q                | A
| ---------------- | ---
| HumHub version   | 1.15.0 to 1.17 develop branch

**Comment by yurabakhtin** [comment]
@marc-farre @luke- Fixed https://github.com/humhub/humhub/pull/7358.

The problem was for the extented permission manager `ContentContainerPermissionManager`, because it has a query as:
`ContentContainerPermission::find()->where(['contentcontainer_id' => $this->contentContainer->contentcontainer_id])`

but the parent `PermissionManager` has it as:
`GroupPermission::find()`,

and also `ContentContainerDefaultPermissionManager`:
 `ContentContainerDefaultPermission::find()->where(['contentcontainer_class' => $this->contentContainerClass])`

It is why they all should be cached with different key.
