### ISSUE TITLE
Allow limited access for non-authenticated users (guests)

### ISSUE THREAD

**Issue by ghost** [humhub/humhub#787]
when open access for guests all site becomes available without welcome page, this is not good idea. It is necessary that the site was only available on the links to specific locations. As twitter, Welcome page + access to special directories, such as profiles, etc.

and another, users should determine in their profile settings to allow access to the profile for guest or not...

https://github.com/humhub/humhub/commit/40ddf7dca94b473c5244a85e3b4995cc2d270145

**Comment by radiolip** [comment]
![capture](https://cloud.githubusercontent.com/assets/9461399/6463310/d10cb088-c1b9-11e4-9c32-7726ddc2ab34.PNG)

![capture7](https://cloud.githubusercontent.com/assets/9461399/6463313/d9a77df4-c1b9-11e4-9b97-f035da3663b5.PNG)

**Comment by luke-** [comment]
You can create a welcome page by module. In future maybe via the custom pages module.

Users can block public profile access via profile settings.

**Comment by radiolip** [comment]
/home/u947813197/public_html/protected/vendors/yii/db/ar/CActiveRecord.php(145)

133      */
134     public function __get($name)
135     {
136         if(isset($this->_attributes[$name]))
137             return $this->_attributes[$name];
138         elseif(isset($this->getMetaData()->columns[$name]))
139             return null;
140         elseif(isset($this->_related[$name]))
141             return $this->_related[$name];
142         elseif(isset($this->getMetaData()->relations[$name]))
143             return $this->getRelated($name);
144         else
145             return parent::__get($name);
146     }
147 
148     /**
149      * PHP setter magic method.
150      * This method is overridden so that AR attributes can be accessed like properties.
151      * @param string $name property name
152      * @param mixed $value property value
153      */
154     public function __set($name,$value)
155     {
156         if($this->setAttribute($name,$value)===false)
157         {

Stack Trace
#0 	
+
 /home/u947813197/public_html/protected/vendors/yii/db/ar/CActiveRecord.php(145): CComponent->__get("visibility")
#1 	
+
 /home/u947813197/public_html/protected/vendors/yii/validators/CNumberValidator.php(78): CActiveRecord->__get("visibility")
#2 	
+
 /home/u947813197/public_html/protected/vendors/yii/validators/CValidator.php(213): CNumberValidator->validateAttribute(User, "visibility")
#3 	
+
 /home/u947813197/public_html/protected/vendors/yii/base/CModel.php(159): CValidator->validate(User, null)
#4 	
+
 /home/u947813197/public_html/protected/vendors/yii/db/ar/CActiveRecord.php(805): CModel->validate(null)
#5 	
–
 /home/u947813197/public_html/protected/modules_core/user/components/UserIdentity.php(139): CActiveRecord->save()

134     private function onSuccessfulAuthenticate($user)
135     {
136         $this->errorCode = self::ERROR_NONE;
137 
138         $user->last_login = new CDbExpression('NOW()');
139         $user->save();
140 
141         $this->_id = $user->id;
142         $this->setState('title', $user->profile->title);
143     }
144 

#6 	
–
 /home/u947813197/public_html/protected/modules_core/user/components/UserIdentity.php(52): UserIdentity->onSuccessfulAuthenticate(User)

47         } elseif ($user->status == User::STATUS_DISABLED) {
48             $this->errorCode = self::ERROR_SUSPENDED;
49         } elseif ($user->status == User::STATUS_NEED_APPROVAL) {
50             $this->errorCode = self::ERROR_NOT_APPROVED;
51         } else {
52             $this->onSuccessfulAuthenticate($user);
53         }
54 
55         return !$this->errorCode;
56     }
57 

#7 	
–
 /home/u947813197/public_html/protected/modules_core/user/forms/AccountLoginForm.php(56): UserIdentity->authenticate()

51     public function authenticate($attribute, $params)
52     {
53         if (!$this->hasErrors()) {
54 
55             $this->_identity = new UserIdentity($this->username, $this->password);
56             if (!$this->_identity->authenticate())
57                 if ($this->_identity->errorCode === UserIdentity::ERROR_NOT_APPROVED) {
58                     $this->addError('username', Yii::t('UserModule.forms_AccountLoginForm', 'Your account has not been activated by our staff yet.'));
59                 } elseif ($this->_identity->errorCode === UserIdentity::ERROR_SUSPENDED) {
60                     $this->addError('username', Yii::t('UserModule.forms_AccountLoginForm', 'Your account is suspended.'));
61                 } else {

#8 	
+
 /home/u947813197/public_html/protected/vendors/yii/validators/CInlineValidator.php(42): AccountLoginForm->authenticate("password", array())
#9 	
+
 /home/u947813197/public_html/protected/vendors/yii/validators/CValidator.php(213): CInlineValidator->validateAttribute(AccountLoginForm, "password")
#10 	
+
 /home/u947813197/public_html/protected/vendors/yii/base/CModel.php(159): CValidator->validate(AccountLoginForm, null)
#11 	
+
 /home/u947813197/public_html/protected/modules_core/user/controllers/AuthController.php(96): CModel->validate()
#12 	
+
 /home/u947813197/public_html/protected/vendors/yii/web/actions/CInlineAction.php(49): AuthController->actionLogin()
#13 	
+
 /home/u947813197/public_html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams(array("r" => "user/auth/login"))
#14 	
+
 /home/u947813197/public_html/protected/vendors/yii/web/CController.php(286): CController->runAction(CInlineAction)
#15 	
+
 /home/u947813197/public_html/protected/vendors/yii/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array())
#16 	
+
 /home/u947813197/public_html/protected/vendors/yii/web/CWebApplication.php(282): CController->run("login")
#17 	
+
 /home/u947813197/public_html/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController("user/auth/login")
#18 	
+
 /home/u947813197/public_html/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest()
#19 	
+
 /home/u947813197/public_html/index.php(39): CApplication->run()

**Comment by 001101** [comment]
any progress??
