### ISSUE TITLE
RTL Version

### ISSUE THREAD

**Issue by sajaddp** [humhub/humhub#871]
Hi,
I today see your script it's very good! :)
if you want i can help you to complete set script for RTL language (ex: Persian, Pashto, Arabic, ...).
Since three years ago i worked on SHARETRONIX and create many plugin for Persian site's.

**Comment by 2012mjm** [comment]
I can help you to complete set script for RTL language ;)

**Comment by buddh4** [comment]
Hi, think this should be done within an own theme? http://docs.humhub.org/theme-README.html

**Comment by Felli** [comment]
I agree it would be just as easy to just create a rtl theme design.

**Comment by rezaervani** [comment]
What about RTL button on prosemirror ? What should we do to get it ?

We don't want to change all theme into RTL version, just add both LTR and RTL Text function to editor.

Thank you,

**Comment by luke-** [comment]
@rezaervani Can you please create an issue here: https://github.com/humhub/humhub-prosemirror/issues

**Comment by ArchBlood** [comment]
@luke- or @buddh4 I'd like to bring a slightly better solution to the table when it comes to RTL, is that alright? The following code should trigger RTL in the case that Arabic language is used, of course if there is another language that also uses RTL then it could be added as well, any thoughts? Reason behind this, I don't think we should force custom theme option because the core code is always changing and will force the theme developer to recompile over each major change

Here's the code that I provide be used
```php
<html <?php if(Yii::$app->language == 'ar')  echo "dir='rtl'"; ?>>
```
