### ISSUE TITLE
Getting "Internal server error" when I click on "Browse online" on "modules"

### ISSUE THREAD

**Issue by mrluisiko99** [humhub/humhub#904]
Error from Errorlog from the server:

2015/04/04 16:06:54 [error] 25485#0: *5517 upstream prematurely closed connection while reading response header from upstream, client: --.--.---.---, server: ---.com, request: "GET /admin/module/listOnline HTTP/1.1", upstream: "https://------:--/admin/module/listOnline", host: "---.com", referrer: "https://---.com/admin/module/list"

**Comment by mrluisiko99** [comment]
Also I'm getting this error when I click on "About" in Administration

**Comment by WASasquatch** [comment]
I have the same issues. Does your server use IPv6?

**Comment by mrluisiko99** [comment]
I can use also IPv6, but now i'm using IPv4...

**Comment by WASasquatch** [comment]
Then IPv6 is taking precedence because it is the newer type. Probably the cause, same with me.

**Comment by luke-** [comment]
Hmm, the HumHub API Server doesn't support IPV6 yet.

I cannot reproduce the problem here, can you try to debug it?

**Comment by WASasquatch** [comment]
All the research I've done says to use raw IPs, that's why I suggest `gethostbyname()` to ensure it's a IP which my server will then recognize as IPv4, and use that protocol. So far I think my system is only being 'tricked' into using IPv4 because of URI strings and other data, otherwise trying IPv6 and crashing. 

I get nothing in Apache/PHP logs, though there was a point I did have some requests not being able to get through to HumHub API but I think that was just maybe things rolling over for updates few days ago??

**Comment by mrluisiko99** [comment]
It is working for me now... I have not done anything :S
