### ISSUE TITLE
Dependency Manager

### ISSUE THREAD

**Issue by rubenCodeforges** [humhub/humhub#957]
Hi im taking now a closer look to your project , perhaps will contribute to it if we choose it as our tools for some of our tasks.

So to the acctual question , why you are not using a dependency manager like composer ?
A git clone that is more the 30mb is preatty heavy , and i know you are using yii , it could be added as a dependency to composer , not ?

**Comment by WASasquatch** [comment]
HumHub I believe relies on specific versions of libraries, which have since updated several times, if not numerous times. 

PHP Modules, in most cases (like open_basedir()) need manual configuration. 

Where does HumHub need Dependency Management when the required libraries are included besides PHP Modules and System Libraries?

**Comment by rubenCodeforges** [comment]
ok ive got your point , thanks for fast response :)
