### ISSUE TITLE
Cron/Queue Execution via HTTP Request (Webcron)

### ISSUE THREAD

**Issue by luke-** [humhub/humhub#98]
Allow running of cronjobs via HTTP.
- Create Controller which can be executed without logged in (API Key?) and calls the cronjobs hourly/daily
- Display URLS at Administration -> Cron Jobs

**Comment by elbotho** [comment]
I think this is important for nearly all users on shared hosting. 
Right now Humhub is not usable for me just because of this. 
I consider adding this myself, but I have no experience with this yii. 
Could so. describe how you would implement this in yii 2.0?

**Comment by ChrDr** [comment]
I would appreciate that very much, too. As for many others this is the only obstacle for me to use humhub.

**Comment by elbotho** [comment]
## Dirty solution

Ok, since this did not happen since 2014 I hacked something for this.
It's as ugly as it could be, because I have zero experience with yii and I'm just posting it here if it to help ppl out that really need this working.

---
In **`AuthController.php`** (🤕  just because it is accessible without login, obviously a real solution should live in it's own module ) add this:
``` php
public function actionDaily1234()
{
$cronc = new \humhub\commands\CronController("cron",$this);
$return = $cronc->actionDaily();
return('daily: '.$return );
}

public function actionHourly1234()
{
$cronc = new \humhub\commands\CronController("cron",$this);
$return = $cronc->actionHourly();
return('hourly: '.$return);
}
```
It's probably a good idea to use random Numbers as function names because those function are not protected at all and can be abused. 🔨 

---
In the **`CronController.php`** comment out alle the `stdout` calls or replace them with your own simple logging system. Something like:
``` php
error_log("Message \n", 3, "./cron.log");
```

Do the same for all occurrences of `$controller->stdout(…)` within `/protected/humhub/modules/` (they should all be in the `Events.php` files

Now you should be able to trigger the cron events from the browser/webcron/wget by accessing:
``` php
'[your domain]index.php?r=user%2Fauth%2Fdaily1234'
'[your domain]index.php?r=user%2Fauth%2Fhourly1234'
```
---
Hope this helps someone!
(and maybe it motivates someone with a basic understanding of yii or humhub to turn this into a clear version worthy of a PR, should be easy as 🍰 .)

**Comment by unclehook** [comment]
@elbotho i'm testing your **dirty solution**, but obtain:
Oooops ... It would seem that you have taken a wrong turn. (Traslated from italian message:  Oooops... Sembrerebbe che tu abbia preso una strada sbagliata. )
Invalid mail update interval!

Is not clear, for me, what is the problem; some ideas?

**Comment by elbotho** [comment]
@unclehook puh, hard to say, don't think I have encountered this. 
Does the error come up when you navigate to `[your domain]index.php?r=user%2Fauth%2Fdaily1234`?

**Comment by unclehook** [comment]
@elbotho Yes, only when i navigate to` [your domain]index.php?r=user%2Fauth%2Fdaily1234` see the attachment
![immagine 1](https://cloud.githubusercontent.com/assets/5794610/23793729/01819bc0-058d-11e7-911c-e1f03ecc800f.png)

**Comment by unclehook** [comment]
@elbotho your _dirty solution_ work if I remove the 1234 from the functions name, in `AuthController.php` and navigate to `[your domain]index.php?r=user%2Fauth%2Fdaily`.

The error is trigger by `MailUpdateSender.php` in `processCron` (line 45>51):
```php
        if (Yii::$app->controller->action->id == 'hourly') {
            $interval = self::INTERVAL_HOURY;
        } elseif (Yii::$app->controller->action->id == 'daily') {
            $interval = self::INTERVAL_DAILY;
        } else {
            throw new \yii\console\Exception(Yii::$app->controller->action->id . ' Invalid mail update interval!');
        }
```

Because your `actionDaily1234` create a controller with `id == daily1234` that is differente from `'hourly'` and `'daily'`, this cause to raise the final exception.

This can help?

I am still not as good and php yii to correct your code without the help of the debugger.

I suppose it is simply corrects this line to create the controller with the correct id:
`$cronc = new \humhub\commands\CronController("cron",$this);`

With my knowledge would change the condition mentioned above by adding `'hourly1234'`  e `'daily1234'`  in '`MailUpdateSender.php`' but it is more dirty,

**Comment by unclehook** [comment]
# Dirty Solution v.2
Based on the [this](https://github.com/humhub/humhub/issues/98#issuecomment-255843995) solution of elbotho, now I'm using the following.
##
In `AuthController.php` add this:
``` php
	/*
		CRONJob from http
	*/
	public function actionDaily()
    {
		if(isset($_GET['pwd'])) 
			$pwd=$_GET['pwd'];
			if ($pwd == '<very_complex_password>') {
				$cronc = new \humhub\commands\CronController("cron",$this);
				$return = $cronc->actionDaily();
			}
		else
			$return = 'Wrong Parameters!';
		return('daily: '.$return );

    }
	


	public function actionHourly()
    {
		if(isset($_GET['pwd'])) 
			$pwd=$_GET['pwd'];
			if ($pwd == '<very_complex_password>') {
				$cronc = new \humhub\commands\CronController("cron",$this);
				$return = $cronc->actionHourly();
			}
		else
			$return = 'Wrong Parameters!';
		return('hourly: '.$return);
    }
``` 
##
[Follow the steps by elbotho](https://github.com/humhub/humhub/issues/98#issuecomment-255843995)
##
Now you should be able to trigger the cron events from the browser/webcron/wget by accessing:

`[your domain]index.php?r=user%2Fauth%2Fdaily&pwd=<very_complex_password>`
`[your domain]index.php?r=user%2Fauth%2Fhourly&pwd=<very_complex_password>`
##
I don't have the knowledge to say the level of security of this solution, but works.
##
Thank you to @elbotho for the inspiration

**Comment by sam11fr** [comment]
Hello,
I add code V2 in AuthController.php and load index.php?r=user%2Fauth%2Fdaily&pwd=<passwod_defind>

and have this error:

2017-09-07 21:47:25 [2.4.216.211][11][aac3e39b472b6257b5a7516ee9be4dab][error][yii\base\ErrorException:1] exception 'yii\base\ErrorException' with message 'Undefined constant 'STDOUT'' in /home/amoilalepy/www/protected/vendor/yiisoft/yii2/console/Controller.php:75
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
2017-09-07 21:47:25 [2.4.216.211][11][aac3e39b472b6257b5a7516ee9be4dab][info][application] $_GET = [
    'r' => 'user/auth/daily'
    'pwd' => 'RunCron'
]

Can you help me ?
Best regards
Sam

**Comment by sam11fr** [comment]
Well seen.
I think I will not use this solution because of the updates that will return the files to the original state.
It is still a very good solution that I keep aside for the moment.
I hope that one day a "maintenance" module is created by a developer.
Thank you very much for the tip.
Very cordially

**Comment by Felli** [comment]
@sam11fr there is a maintenance module that needs to be updated to `v1.2` that I'm sure someone could update at some point.

**Comment by sam11fr** [comment]
It would be fantastic if this module were updated and contains the CRON tasks!
Best regard

**Comment by b90g** [comment]
Still desired, wordpress has it. A lot shared hosting provides offer a webcron (via curl..)

**Comment by ArchBlood** [comment]
> Still desired, wordpress has it. A lot shared hosting provides offer a webcron (via curl..)

Check out the following module

https://github.com/cuzy-app/humhub-modules-cron-daemon
